--- 
title: "Using R for Introduction to Econometrics"
author: "Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      toc:
        collapse: subsection
        scroll_highlight: yes
      download: ["pdf"]
      fontsettings:
        theme: white
        family: sans
        size: 1
    split_by: section
    highlight: tango
    includes:
      in_header: [header_include.html]
      before_body: open_review_block.html
always_allow_html: yes
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: Emwikts1970/URFITE-Bookdown
description: ""
---

# Introduction

#### What this book is (and what it is not) {-}

This book is an interactive script in the style of a reproducible research report. <b>U</b>sing <b>R</b> for <b>I</b>ntroduction to <b>E</b>conometrics (*URFITE*) aims to provide students of economic sciences with a platform-independent e-learning arrangement that seamlessly intertwines theoretical core knowledge and empirical skills in undergraduate econometrics. Thereby, the focus is set on empirical applications with the freely available statistical software package <tt>R</tt>. We leave out tedious derivations and formal proofs. 

*URFITE* is closely aligned on *Introduction to Econometrics* (Stock and Watson, 2014), a standard textbook in introductory econometrics. While the book does very well in motivating theory by real-world applications, we want to take it a step further and would like to enable students not only to learn how results of case studies can be replicated with <tt>R</tt> but also indent to strengthen their ability in using the newly acquired skills in other empirical applications.

However, this book is neither an introduction to <tt>R</tt>, nor is it intended to be a replacement for the textbook let alone a full course in econometrics. 

Throughout the book, interactive <tt>R</tt> programming exercises are used as supplements to code chunks that display how previously discussed techniques can be implemented within <tt>R</tt>. These programming exercises are realized using the [DataCamp light widget](https://github.com/datacamp/datacamp-light) and are backed by an <tt>R</tt>-session which is maintained on DataCamp's servers. The <tt>R</tt> session is initialized by clicking into the widget. This might take a few seconds. You can try that below.

<!--html_preserve-->

<div data-datacamp-exercise data-lang="r">

	<code data-type="pre-exercise-code">
		# This will get executed each time the exercise gets initialized
		b = 6
	</code>
	
	<code data-type="sample-code">
		# Create a variable a, equal to 5


		# Print out a


	</code>
	
	<code data-type="solution">
		# Create a variable a, equal to 5
		a <- 5

		# Print out a
		print(a)
	</code>
	
	<code data-type="sct">
		test_object("a")
		test_function("print")
		success_msg("Great job!")
	</code>
	
	<div data-type="hint">
	Use the assignment operator (<code> <- </code>) to create the variable <code>a</code>.</div>

</div>

<!--/html_preserve-->


