<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Econometrics with R</title>
  <meta name="description" content="<em>Introduction to Econometrics with R</em>">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Econometrics with R" />
  
  
  

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="15-5-estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors.html">
<link rel="next" href="16-atitsr.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!-- datacamp-light-latest -->

<!-- <script async src="https://cdn.datacamp.com/dcl-react.js.gz"></script> -->

<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script> 

<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="MathJax-2.7.2/MathJax.js?config=default"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.oek.wiwi.uni-due.de/en/">Chair of Econometrics @ Uni-DUE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-a-very-short-introduction-to-r-and-rstudio.html"><a href="1-1-a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-pt.html"><a href="2-pt.html"><i class="fa fa-check"></i><b>2</b> Probability Theory</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html"><i class="fa fa-check"></i><b>2.1</b> Random Variables and Probability Distributions</a><ul>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#probability-distributions-of-discrete-random-variables"><i class="fa fa-check"></i>Probability Distributions of Discrete Random Variables</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#bernoulli-trials"><i class="fa fa-check"></i>Bernoulli Trials</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#expected-value-mean-and-variance"><i class="fa fa-check"></i>Expected Value, Mean and Variance</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#probability-distributions-of-continuous-random-variables"><i class="fa fa-check"></i>Probability Distributions of Continuous Random Variables</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#the-chi-squared-distribution"><i class="fa fa-check"></i>The Chi-Squared Distribution</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#thetdist"><i class="fa fa-check"></i>The Student t Distribution</a></li>
<li class="chapter" data-level="" data-path="2-1-random-variables-and-probability-distributions.html"><a href="2-1-random-variables-and-probability-distributions.html#the-f-distribution"><i class="fa fa-check"></i>The F Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-2-RSATDOSA.html"><a href="2-2-RSATDOSA.html"><i class="fa fa-check"></i><b>2.2</b> Random Sampling and the Distribution of Sample Averages</a><ul>
<li class="chapter" data-level="" data-path="2-2-RSATDOSA.html"><a href="2-2-RSATDOSA.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i>Mean and Variance of the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="2-2-RSATDOSA.html"><a href="2-2-RSATDOSA.html#large-sample-approximations-to-sampling-distributions"><i class="fa fa-check"></i>Large Sample Approximations to Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-exercises.html"><a href="2-3-exercises.html"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-arosur.html"><a href="3-arosur.html"><i class="fa fa-check"></i><b>3</b> A Review of Statistics using R</a><ul>
<li class="chapter" data-level="3.1" data-path="3-1-estimation-of-the-population-mean.html"><a href="3-1-estimation-of-the-population-mean.html"><i class="fa fa-check"></i><b>3.1</b> Estimation of the Population Mean</a></li>
<li class="chapter" data-level="3.2" data-path="3-2-potsm.html"><a href="3-2-potsm.html"><i class="fa fa-check"></i><b>3.2</b> Properties of the Sample Mean</a></li>
<li class="chapter" data-level="3.3" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html"><i class="fa fa-check"></i><b>3.3</b> Hypothesis Tests Concerning the Population Mean</a><ul>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#the-p-value"><i class="fa fa-check"></i>The p-Value</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#calculating-the-p-value-when-the-standard-deviation-is-known"><i class="fa fa-check"></i>Calculating the p-Value when the Standard Deviation is Known</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#SVSSDASE"><i class="fa fa-check"></i>Sample Variance, Sample Standard Deviation and Standard Error</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#calculating-the-p-value-when-the-standard-deviation-is-unknown"><i class="fa fa-check"></i>Calculating the p-value When the Standard Deviation is Unknown</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#the-t-statistic"><i class="fa fa-check"></i>The t-statistic</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#hypothesis-testing-with-a-prespecified-significance-level"><i class="fa fa-check"></i>Hypothesis Testing with a Prespecified Significance Level</a></li>
<li class="chapter" data-level="" data-path="3-3-hypothesis-tests-concerning-the-population-mean.html"><a href="3-3-hypothesis-tests-concerning-the-population-mean.html#one-sided-alternatives"><i class="fa fa-check"></i>One-sided Alternatives</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="3-4-confidence-intervals-for-the-population-mean.html"><a href="3-4-confidence-intervals-for-the-population-mean.html"><i class="fa fa-check"></i><b>3.4</b> Confidence Intervals for the Population Mean</a></li>
<li class="chapter" data-level="3.5" data-path="3-5-cmfdp.html"><a href="3-5-cmfdp.html"><i class="fa fa-check"></i><b>3.5</b> Comparing Means from Different Populations</a></li>
<li class="chapter" data-level="3.6" data-path="3-6-aattggoe.html"><a href="3-6-aattggoe.html"><i class="fa fa-check"></i><b>3.6</b> An Application to the Gender Gap of Earnings</a></li>
<li class="chapter" data-level="3.7" data-path="3-7-scatterplots-sample-covariance-and-sample-correlation.html"><a href="3-7-scatterplots-sample-covariance-and-sample-correlation.html"><i class="fa fa-check"></i><b>3.7</b> Scatterplots, Sample Covariance and Sample Correlation</a></li>
<li class="chapter" data-level="3.8" data-path="3-8-exercises-1.html"><a href="3-8-exercises-1.html"><i class="fa fa-check"></i><b>3.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-lrwor.html"><a href="4-lrwor.html"><i class="fa fa-check"></i><b>4</b> Linear Regression with One Regressor</a><ul>
<li class="chapter" data-level="4.1" data-path="4-1-simple-linear-regression.html"><a href="4-1-simple-linear-regression.html"><i class="fa fa-check"></i><b>4.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="4-2-estimating-the-coefficients-of-the-linear-regression-model.html"><a href="4-2-estimating-the-coefficients-of-the-linear-regression-model.html"><i class="fa fa-check"></i><b>4.2</b> Estimating the Coefficients of the Linear Regression Model</a><ul>
<li class="chapter" data-level="" data-path="4-2-estimating-the-coefficients-of-the-linear-regression-model.html"><a href="4-2-estimating-the-coefficients-of-the-linear-regression-model.html#the-ordinary-least-squares-estimator"><i class="fa fa-check"></i>The Ordinary Least Squares Estimator</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-3-measures-of-fit.html"><a href="4-3-measures-of-fit.html"><i class="fa fa-check"></i><b>4.3</b> Measures of Fit</a><ul>
<li class="chapter" data-level="" data-path="4-3-measures-of-fit.html"><a href="4-3-measures-of-fit.html#the-coefficient-of-determination"><i class="fa fa-check"></i>The Coefficient of Determination</a></li>
<li class="chapter" data-level="" data-path="4-3-measures-of-fit.html"><a href="4-3-measures-of-fit.html#the-standard-error-of-the-regression"><i class="fa fa-check"></i>The Standard Error of the Regression</a></li>
<li class="chapter" data-level="" data-path="4-3-measures-of-fit.html"><a href="4-3-measures-of-fit.html#application-to-the-test-score-data"><i class="fa fa-check"></i>Application to the Test Score Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="4-4-tlsa.html"><a href="4-4-tlsa.html"><i class="fa fa-check"></i><b>4.4</b> The Least Squares Assumptions</a><ul>
<li class="chapter" data-level="" data-path="4-4-tlsa.html"><a href="4-4-tlsa.html#assumption-1-the-error-term-has-conditional-mean-of-zero"><i class="fa fa-check"></i>Assumption 1: The Error Term has Conditional Mean of Zero</a></li>
<li class="chapter" data-level="" data-path="4-4-tlsa.html"><a href="4-4-tlsa.html#assumption-2-independently-and-identically-distributed-data"><i class="fa fa-check"></i>Assumption 2: Independently and Identically Distributed Data</a></li>
<li class="chapter" data-level="" data-path="4-4-tlsa.html"><a href="4-4-tlsa.html#assumption-3-large-outliers-are-unlikely"><i class="fa fa-check"></i>Assumption 3: Large Outliers are Unlikely</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="4-5-tsdotoe.html"><a href="4-5-tsdotoe.html"><i class="fa fa-check"></i><b>4.5</b> The Sampling Distribution of the OLS Estimator</a><ul>
<li class="chapter" data-level="" data-path="4-5-tsdotoe.html"><a href="4-5-tsdotoe.html#simulation-study-1"><i class="fa fa-check"></i>Simulation Study 1</a></li>
<li class="chapter" data-level="" data-path="4-5-tsdotoe.html"><a href="4-5-tsdotoe.html#simulation-study-2"><i class="fa fa-check"></i>Simulation Study 2</a></li>
<li class="chapter" data-level="" data-path="4-5-tsdotoe.html"><a href="4-5-tsdotoe.html#simulation-study-3"><i class="fa fa-check"></i>Simulation Study 3</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-6-exercises-2.html"><a href="4-6-exercises-2.html"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-htaciitslrm.html"><a href="5-htaciitslrm.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests and Confidence Intervals in the Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="5.1" data-path="5-1-testing-two-sided-hypotheses-concerning-the-slope-coefficient.html"><a href="5-1-testing-two-sided-hypotheses-concerning-the-slope-coefficient.html"><i class="fa fa-check"></i><b>5.1</b> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</a></li>
<li class="chapter" data-level="5.2" data-path="5-2-cifrc.html"><a href="5-2-cifrc.html"><i class="fa fa-check"></i><b>5.2</b> Confidence Intervals for Regression Coefficients</a><ul>
<li class="chapter" data-level="" data-path="5-2-cifrc.html"><a href="5-2-cifrc.html#simulation-study-confidence-intervals"><i class="fa fa-check"></i>Simulation Study: Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5-3-rwxiabv.html"><a href="5-3-rwxiabv.html"><i class="fa fa-check"></i><b>5.3</b> Regression when X is a Binary Variable</a></li>
<li class="chapter" data-level="5.4" data-path="5-4-hah.html"><a href="5-4-hah.html"><i class="fa fa-check"></i><b>5.4</b> Heteroskedasticity and Homoskedasticity</a><ul>
<li class="chapter" data-level="" data-path="5-4-hah.html"><a href="5-4-hah.html#a-real-world-example-for-heteroskedasticity"><i class="fa fa-check"></i>A Real-World Example for Heteroskedasticity</a></li>
<li class="chapter" data-level="" data-path="5-4-hah.html"><a href="5-4-hah.html#should-we-care-about-heteroskedasticity"><i class="fa fa-check"></i>Should We Care About Heteroskedasticity?</a></li>
<li class="chapter" data-level="" data-path="5-4-hah.html"><a href="5-4-hah.html#computation-of-heteroskedasticity-robust-standard-errors"><i class="fa fa-check"></i>Computation of Heteroskedasticity-Robust Standard Errors</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="5-5-the-gauss-markov-theorem.html"><a href="5-5-the-gauss-markov-theorem.html"><i class="fa fa-check"></i><b>5.5</b> The Gauss-Markov Theorem</a><ul>
<li class="chapter" data-level="" data-path="5-5-the-gauss-markov-theorem.html"><a href="5-5-the-gauss-markov-theorem.html#simulation-study-blue-estimator"><i class="fa fa-check"></i>Simulation Study: BLUE Estimator</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="5-6-using-the-t-statistic-in-regression-when-the-sample-size-is-small.html"><a href="5-6-using-the-t-statistic-in-regression-when-the-sample-size-is-small.html"><i class="fa fa-check"></i><b>5.6</b> Using the t-Statistic in Regression When the Sample Size Is Small</a></li>
<li class="chapter" data-level="5.7" data-path="5-7-exercises-3.html"><a href="5-7-exercises-3.html"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-rmwmr.html"><a href="6-rmwmr.html"><i class="fa fa-check"></i><b>6</b> Regression Models with Multiple Regressors</a><ul>
<li class="chapter" data-level="6.1" data-path="6-1-omitted-variable-bias.html"><a href="6-1-omitted-variable-bias.html"><i class="fa fa-check"></i><b>6.1</b> Omitted Variable Bias</a></li>
<li class="chapter" data-level="6.2" data-path="6-2-tmrm.html"><a href="6-2-tmrm.html"><i class="fa fa-check"></i><b>6.2</b> The Multiple Regression Model</a></li>
<li class="chapter" data-level="6.3" data-path="6-3-mofimr.html"><a href="6-3-mofimr.html"><i class="fa fa-check"></i><b>6.3</b> Measures of Fit in Multiple Regression</a></li>
<li class="chapter" data-level="6.4" data-path="6-4-ols-assumptions-in-multiple-regression.html"><a href="6-4-ols-assumptions-in-multiple-regression.html"><i class="fa fa-check"></i><b>6.4</b> OLS Assumptions in Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="6-4-ols-assumptions-in-multiple-regression.html"><a href="6-4-ols-assumptions-in-multiple-regression.html#multicollinearity"><i class="fa fa-check"></i>Multicollinearity</a></li>
<li class="chapter" data-level="" data-path="6-4-ols-assumptions-in-multiple-regression.html"><a href="6-4-ols-assumptions-in-multiple-regression.html#simulation-study-imperfect-multicollinearity"><i class="fa fa-check"></i>Simulation Study: Imperfect Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="6-5-the-distribution-of-the-ols-estimators-in-multiple-regression.html"><a href="6-5-the-distribution-of-the-ols-estimators-in-multiple-regression.html"><i class="fa fa-check"></i><b>6.5</b> The Distribution of the OLS Estimators in Multiple Regression</a></li>
<li class="chapter" data-level="6.6" data-path="6-6-exercises-4.html"><a href="6-6-exercises-4.html"><i class="fa fa-check"></i><b>6.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-htaciimr.html"><a href="7-htaciimr.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Tests and Confidence Intervals in Multiple Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="7-1-hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html"><a href="7-1-hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Tests and Confidence Intervals for a Single Coefficient</a></li>
<li class="chapter" data-level="7.2" data-path="7-2-an-application-to-test-scores-and-the-student-teacher-ratio.html"><a href="7-2-an-application-to-test-scores-and-the-student-teacher-ratio.html"><i class="fa fa-check"></i><b>7.2</b> An Application to Test Scores and the Student-Teacher Ratio</a><ul>
<li class="chapter" data-level="" data-path="7-2-an-application-to-test-scores-and-the-student-teacher-ratio.html"><a href="7-2-an-application-to-test-scores-and-the-student-teacher-ratio.html#another-augmentation-of-the-model"><i class="fa fa-check"></i>Another Augmentation of the Model</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-3-joint-hypothesis-testing-using-the-f-statistic.html"><a href="7-3-joint-hypothesis-testing-using-the-f-statistic.html"><i class="fa fa-check"></i><b>7.3</b> Joint Hypothesis Testing Using the F-Statistic</a></li>
<li class="chapter" data-level="7.4" data-path="7-4-confidence-sets-for-multiple-coefficients.html"><a href="7-4-confidence-sets-for-multiple-coefficients.html"><i class="fa fa-check"></i><b>7.4</b> Confidence Sets for Multiple Coefficients</a></li>
<li class="chapter" data-level="7.5" data-path="7-5-model-specification-for-multiple-regression.html"><a href="7-5-model-specification-for-multiple-regression.html"><i class="fa fa-check"></i><b>7.5</b> Model Specification for Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="7-5-model-specification-for-multiple-regression.html"><a href="7-5-model-specification-for-multiple-regression.html#model-specification-in-theory-and-in-practice"><i class="fa fa-check"></i>Model Specification in Theory and in Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="7-6-analysis-of-the-test-score-data-set.html"><a href="7-6-analysis-of-the-test-score-data-set.html"><i class="fa fa-check"></i><b>7.6</b> Analysis of the Test Score Data Set</a></li>
<li class="chapter" data-level="7.7" data-path="7-7-exercises-5.html"><a href="7-7-exercises-5.html"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-nrf.html"><a href="8-nrf.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Regression Functions</a><ul>
<li class="chapter" data-level="8.1" data-path="8-1-a-general-strategy-for-modelling-nonlinear-regression-functions.html"><a href="8-1-a-general-strategy-for-modelling-nonlinear-regression-functions.html"><i class="fa fa-check"></i><b>8.1</b> A General Strategy for Modelling Nonlinear Regression Functions</a></li>
<li class="chapter" data-level="8.2" data-path="8-2-nfoasiv.html"><a href="8-2-nfoasiv.html"><i class="fa fa-check"></i><b>8.2</b> Nonlinear Functions of a Single Independent Variable</a><ul>
<li class="chapter" data-level="" data-path="8-2-nfoasiv.html"><a href="8-2-nfoasiv.html#polynomials"><i class="fa fa-check"></i>Polynomials</a></li>
<li class="chapter" data-level="" data-path="8-2-nfoasiv.html"><a href="8-2-nfoasiv.html#logarithms"><i class="fa fa-check"></i>Logarithms</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="8-3-interactions-between-independent-variables.html"><a href="8-3-interactions-between-independent-variables.html"><i class="fa fa-check"></i><b>8.3</b> Interactions Between Independent Variables</a></li>
<li class="chapter" data-level="8.4" data-path="8-4-nonlinear-effects-on-test-scores-of-the-student-teacher-ratio.html"><a href="8-4-nonlinear-effects-on-test-scores-of-the-student-teacher-ratio.html"><i class="fa fa-check"></i><b>8.4</b> Nonlinear Effects on Test Scores of the Student-Teacher Ratio</a></li>
<li class="chapter" data-level="8.5" data-path="8-5-exercises-6.html"><a href="8-5-exercises-6.html"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="9-asbomr.html"><a href="9-asbomr.html"><i class="fa fa-check"></i><b>9</b> Assessing Studies Based on Multiple Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="9-1-internal-and-external-validity.html"><a href="9-1-internal-and-external-validity.html"><i class="fa fa-check"></i><b>9.1</b> Internal and External Validity</a></li>
<li class="chapter" data-level="9.2" data-path="9-2-ttivomra.html"><a href="9-2-ttivomra.html"><i class="fa fa-check"></i><b>9.2</b> Threats to Internal Validity of Multiple Regression Analysis</a></li>
<li class="chapter" data-level="9.3" data-path="9-3-internal-and-external-validity-when-the-regression-is-used-for-forecasting.html"><a href="9-3-internal-and-external-validity-when-the-regression-is-used-for-forecasting.html"><i class="fa fa-check"></i><b>9.3</b> Internal and External Validity when the Regression is Used for Forecasting</a></li>
<li class="chapter" data-level="9.4" data-path="9-4-etsacs.html"><a href="9-4-etsacs.html"><i class="fa fa-check"></i><b>9.4</b> Example: Test Scores and Class Size</a></li>
<li class="chapter" data-level="9.5" data-path="9-5-exercises-7.html"><a href="9-5-exercises-7.html"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="10-rwpd.html"><a href="10-rwpd.html"><i class="fa fa-check"></i><b>10</b> Regression with Panel Data</a><ul>
<li class="chapter" data-level="10.1" data-path="10-1-panel-data.html"><a href="10-1-panel-data.html"><i class="fa fa-check"></i><b>10.1</b> Panel Data</a></li>
<li class="chapter" data-level="10.2" data-path="10-2-PDWTTP.html"><a href="10-2-PDWTTP.html"><i class="fa fa-check"></i><b>10.2</b> Panel Data with Two Time Periods: “Before and After” Comparisons</a></li>
<li class="chapter" data-level="10.3" data-path="10-3-fixed-effects-regression.html"><a href="10-3-fixed-effects-regression.html"><i class="fa fa-check"></i><b>10.3</b> Fixed Effects Regression</a><ul>
<li class="chapter" data-level="" data-path="10-3-fixed-effects-regression.html"><a href="10-3-fixed-effects-regression.html#estimation-and-inference"><i class="fa fa-check"></i>Estimation and Inference</a></li>
<li class="chapter" data-level="" data-path="10-3-fixed-effects-regression.html"><a href="10-3-fixed-effects-regression.html#application-to-traffic-deaths"><i class="fa fa-check"></i>Application to Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="10-4-regression-with-time-fixed-effects.html"><a href="10-4-regression-with-time-fixed-effects.html"><i class="fa fa-check"></i><b>10.4</b> Regression with Time Fixed Effects</a></li>
<li class="chapter" data-level="10.5" data-path="10-5-tferaaseffer.html"><a href="10-5-tferaaseffer.html"><i class="fa fa-check"></i><b>10.5</b> The Fixed Effects Regression Assumptions and Standard Errors for Fixed Effects Regression</a></li>
<li class="chapter" data-level="10.6" data-path="10-6-drunk-driving-laws-and-traffic-deaths.html"><a href="10-6-drunk-driving-laws-and-traffic-deaths.html"><i class="fa fa-check"></i><b>10.6</b> Drunk Driving Laws and Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="11-rwabdv.html"><a href="11-rwabdv.html"><i class="fa fa-check"></i><b>11</b> Regression with a Binary Dependent Variable</a><ul>
<li class="chapter" data-level="11.1" data-path="11-1-binary-dependent-variables-and-the-linear-probability-model.html"><a href="11-1-binary-dependent-variables-and-the-linear-probability-model.html"><i class="fa fa-check"></i><b>11.1</b> Binary Dependent Variables and the Linear Probability Model</a></li>
<li class="chapter" data-level="11.2" data-path="11-2-probit-and-logit-regression.html"><a href="11-2-probit-and-logit-regression.html"><i class="fa fa-check"></i><b>11.2</b> Probit and Logit Regression</a><ul>
<li class="chapter" data-level="" data-path="11-2-probit-and-logit-regression.html"><a href="11-2-probit-and-logit-regression.html#probit-regression"><i class="fa fa-check"></i>Probit Regression</a></li>
<li class="chapter" data-level="" data-path="11-2-probit-and-logit-regression.html"><a href="11-2-probit-and-logit-regression.html#logit-regression"><i class="fa fa-check"></i>Logit Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="11-3-estimation-and-inference-in-the-logit-and-probit-models.html"><a href="11-3-estimation-and-inference-in-the-logit-and-probit-models.html"><i class="fa fa-check"></i><b>11.3</b> Estimation and Inference in the Logit and Probit Models</a></li>
<li class="chapter" data-level="11.4" data-path="11-4-application-to-the-boston-hmda-data.html"><a href="11-4-application-to-the-boston-hmda-data.html"><i class="fa fa-check"></i><b>11.4</b> Application to the Boston HMDA Data</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="12-ivr.html"><a href="12-ivr.html"><i class="fa fa-check"></i><b>12</b> Instrumental Variables Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="12-1-TIVEWASRAASI.html"><a href="12-1-TIVEWASRAASI.html"><i class="fa fa-check"></i><b>12.1</b> The IV Estimator with a Single Regressor and a Single Instrument</a></li>
<li class="chapter" data-level="12.2" data-path="12-2-TGIVRM.html"><a href="12-2-TGIVRM.html"><i class="fa fa-check"></i><b>12.2</b> The General IV Regression Model</a></li>
<li class="chapter" data-level="12.3" data-path="12-3-civ.html"><a href="12-3-civ.html"><i class="fa fa-check"></i><b>12.3</b> Checking Instrument Validity</a></li>
<li class="chapter" data-level="12.4" data-path="12-4-attdfc.html"><a href="12-4-attdfc.html"><i class="fa fa-check"></i><b>12.4</b> Application to the Demand for Cigarettes</a></li>
<li class="chapter" data-level="12.5" data-path="12-5-where-do-valid-instruments-come-from.html"><a href="12-5-where-do-valid-instruments-come-from.html"><i class="fa fa-check"></i><b>12.5</b> Where Do Valid Instruments Come From?</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="13-eaqe.html"><a href="13-eaqe.html"><i class="fa fa-check"></i><b>13</b> Experiments and Quasi-Experiments</a><ul>
<li class="chapter" data-level="13.1" data-path="13-1-potential-outcomes-causal-effects-and-idealized-experiments.html"><a href="13-1-potential-outcomes-causal-effects-and-idealized-experiments.html"><i class="fa fa-check"></i><b>13.1</b> Potential Outcomes, Causal Effects and Idealized Experiments</a></li>
<li class="chapter" data-level="13.2" data-path="13-2-threats-to-validity-of-experiments.html"><a href="13-2-threats-to-validity-of-experiments.html"><i class="fa fa-check"></i><b>13.2</b> Threats to Validity of Experiments</a></li>
<li class="chapter" data-level="13.3" data-path="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html"><a href="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html"><i class="fa fa-check"></i><b>13.3</b> Experimental Estimates of the Effect of Class Size Reductions</a><ul>
<li class="chapter" data-level="" data-path="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html"><a href="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html#experimental-design-and-the-data-set"><i class="fa fa-check"></i>Experimental Design and the Data Set</a></li>
<li class="chapter" data-level="" data-path="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html"><a href="13-3-experimental-estimates-of-the-effect-of-class-size-reductions.html#analysis-of-the-star-data"><i class="fa fa-check"></i>Analysis of the STAR Data</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="13-4-quasi-experiments.html"><a href="13-4-quasi-experiments.html"><i class="fa fa-check"></i><b>13.4</b> Quasi Experiments</a><ul>
<li class="chapter" data-level="" data-path="13-4-quasi-experiments.html"><a href="13-4-quasi-experiments.html#the-differences-in-differences-estimator"><i class="fa fa-check"></i>The Differences-in-Differences Estimator</a></li>
<li class="chapter" data-level="" data-path="13-4-quasi-experiments.html"><a href="13-4-quasi-experiments.html#regression-discontinuity-estimators"><i class="fa fa-check"></i>Regression Discontinuity Estimators</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="14-ittsraf.html"><a href="14-ittsraf.html"><i class="fa fa-check"></i><b>14</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="14.1" data-path="14-1-using-regression-models-for-forecasting.html"><a href="14-1-using-regression-models-for-forecasting.html"><i class="fa fa-check"></i><b>14.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="14.2" data-path="14-2-tsdasc.html"><a href="14-2-tsdasc.html"><i class="fa fa-check"></i><b>14.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="14-2-tsdasc.html"><a href="14-2-tsdasc.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="14-3-autoregressions.html"><a href="14-3-autoregressions.html"><i class="fa fa-check"></i><b>14.3</b> Autoregressions</a><ul>
<li><a href="14-3-autoregressions.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="14-4-cybtmpi.html"><a href="14-4-cybtmpi.html"><i class="fa fa-check"></i><b>14.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="14.5" data-path="14-5-apatadlm.html"><a href="14-5-apatadlm.html"><i class="fa fa-check"></i><b>14.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="14-5-apatadlm.html"><a href="14-5-apatadlm.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="14-6-llsuic.html"><a href="14-6-llsuic.html"><i class="fa fa-check"></i><b>14.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="14.7" data-path="14-7-nit.html"><a href="14-7-nit.html"><i class="fa fa-check"></i><b>14.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="14.8" data-path="14-8-niib.html"><a href="14-8-niib.html"><i class="fa fa-check"></i><b>14.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="14.9" data-path="14-9-can-you-beat-the-market-part-ii.html"><a href="14-9-can-you-beat-the-market-part-ii.html"><i class="fa fa-check"></i><b>14.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="15-eodce.html"><a href="15-eodce.html"><i class="fa fa-check"></i><b>15</b> Estimation of Dynamic Causal Effects</a><ul>
<li class="chapter" data-level="15.1" data-path="15-1-the-orange-juice-data.html"><a href="15-1-the-orange-juice-data.html"><i class="fa fa-check"></i><b>15.1</b> The Orange Juice Data</a></li>
<li class="chapter" data-level="15.2" data-path="15-2-dynamic-causal-effects.html"><a href="15-2-dynamic-causal-effects.html"><i class="fa fa-check"></i><b>15.2</b> Dynamic Causal Effects</a></li>
<li class="chapter" data-level="15.3" data-path="15-3-dynamic-multipliers-and-cumulative-dynamic-multipliers.html"><a href="15-3-dynamic-multipliers-and-cumulative-dynamic-multipliers.html"><i class="fa fa-check"></i><b>15.3</b> Dynamic Multipliers and Cumulative Dynamic Multipliers</a></li>
<li class="chapter" data-level="15.4" data-path="15-4-hac-standard-errors.html"><a href="15-4-hac-standard-errors.html"><i class="fa fa-check"></i><b>15.4</b> HAC Standard Errors</a></li>
<li class="chapter" data-level="15.5" data-path="15-5-estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors.html"><a href="15-5-estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors.html"><i class="fa fa-check"></i><b>15.5</b> Estimation of Dynamic Causal Effects with Strictly Exogeneous Regressors</a></li>
<li class="chapter" data-level="15.6" data-path="15-6-orange-juice-prices-and-cold-weather.html"><a href="15-6-orange-juice-prices-and-cold-weather.html"><i class="fa fa-check"></i><b>15.6</b> Orange Juice Prices and Cold Weather</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="16-atitsr.html"><a href="16-atitsr.html"><i class="fa fa-check"></i><b>16</b> Additional Topics in Time Series Regression</a><ul>
<li class="chapter" data-level="16.1" data-path="16-1-vector-autoregressions.html"><a href="16-1-vector-autoregressions.html"><i class="fa fa-check"></i><b>16.1</b> Vector Autoregressions</a></li>
<li class="chapter" data-level="16.2" data-path="16-2-ooiatdfglsurt.html"><a href="16-2-ooiatdfglsurt.html"><i class="fa fa-check"></i><b>16.2</b> Orders of Integration and the DF-GLS Unit Root Test</a></li>
<li class="chapter" data-level="16.3" data-path="16-3-cointegration.html"><a href="16-3-cointegration.html"><i class="fa fa-check"></i><b>16.3</b> Cointegration</a></li>
<li class="chapter" data-level="16.4" data-path="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html"><a href="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html"><i class="fa fa-check"></i><b>16.4</b> Volatility Clustering and Autoregressive Conditional Heteroskedasticity</a><ul>
<li class="chapter" data-level="" data-path="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html"><a href="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html#arch-and-garch-models"><i class="fa fa-check"></i>ARCH and GARCH Models</a></li>
<li class="chapter" data-level="" data-path="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html"><a href="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html#application-to-stock-price-volatility"><i class="fa fa-check"></i>Application to Stock Price Volatility</a></li>
<li class="chapter" data-level="" data-path="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html"><a href="16-4-volatility-clustering-and-autoregressive-conditional-heteroskedasticity.html#summary-8"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><em>Introduction to Econometrics with R</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="orange-juice-prices-and-cold-weather" class="section level2">
<h2><span class="header-section-number">15.6</span> Orange Juice Prices and Cold Weather</h2>
<p>This section investigates the following two questions using the time series regression methods discussed here:</p>
<ul>
<li><p>How persistent is the effect of a single freeze on orange juice concentrate prices?</p></li>
<li><p>Has the effect been stable over the whole time span?</p></li>
</ul>
<p>We start by estimating dynamic causal effects with a distributed lag model where <span class="math inline">\(\%ChgOJC_t\)</span> is regressed on <span class="math inline">\(FDD_t\)</span> and 18 lags. A second model specification considers a transformation of the the distributed lag model which allows to estimate the 19 cumulative dynamic multipliers using OLS. The third model, adds 11 binary variables (one for each of the months from February to December) to adjust for a possible omitted variable bias arising from correlation of <span class="math inline">\(FDD_t\)</span> and seasons by adding <tt>season(FDD)</tt> to the right hand side of the formula of the second model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate distributed lag models of frozen orange juice price changes</span>
FOJC_mod_DM &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))
FOJC_mod_CM1 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(FDD), <span class="dv">0</span><span class="op">:</span><span class="dv">17</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">18</span>))
FOJC_mod_CM2 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(FDD), <span class="dv">0</span><span class="op">:</span><span class="dv">17</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">season</span>(FDD))</code></pre></div>
<p>The above models include a large number of lags with default labels that correspond to the degree of differencing and the lag orders which makes it somewhat cumbersome to read the output. The regressor labels of a model object may be altered by overriding the attribute <tt>names</tt> of the coefficient section using the function <tt>attr()</tt>. Thus, for better readability we use the lag orders as regressor labels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set lag orders as regressor labels </span>
<span class="kw">attr</span>(FOJC_mod_DM<span class="op">$</span>coefficients, <span class="st">&quot;names&quot;</span>)[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;(Intercept)&quot;</span>, <span class="kw">as.character</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))
<span class="kw">attr</span>(FOJC_mod_CM1<span class="op">$</span>coefficients, <span class="st">&quot;names&quot;</span>)[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;(Intercept)&quot;</span>, <span class="kw">as.character</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))
<span class="kw">attr</span>(FOJC_mod_CM2<span class="op">$</span>coefficients, <span class="st">&quot;names&quot;</span>)[<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>] &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;(Intercept)&quot;</span>, <span class="kw">as.character</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))</code></pre></div>
<p>Next, we compute HAC standard errors standard errors for each model using <tt>NeweyWest()</tt> and gather the results in a list which is then supplied as the argument <tt>se</tt> to the function <tt>stargazer()</tt>, see below. The sample consists of 612 observations:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(FDD)</code></pre></div>
<pre><code>## [1] 612</code></pre>
<p>According to <a href="15-4-hac-standard-errors.html#eq:hactruncrot">(15.6)</a>, the rule of thumb for choosing the HAC standard error truncation parameter <span class="math inline">\(m\)</span>, we choose <span class="math display">\[m = \left\lceil0.75 \cdot 612^{1/3} \right\rceil = \lceil6.37\rceil = 7.\]</span> To check for sensitivity of the standard errors to different choices of the truncation parameter in the model that is used to estimate the cumulative multipliers, we also compute the Newey-West estimator for <span class="math inline">\(m=14\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># gather HAC standard error errors in a list</span>
SEs &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">NeweyWest</span>(FOJC_mod_DM, <span class="dt">lag =</span> <span class="dv">7</span>, <span class="dt">prewhite =</span> F))), 
            <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">NeweyWest</span>(FOJC_mod_CM1, <span class="dt">lag =</span> <span class="dv">7</span>, <span class="dt">prewhite =</span> F))), 
            <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">NeweyWest</span>(FOJC_mod_CM1, <span class="dt">lag =</span> <span class="dv">14</span>, <span class="dt">prewhite =</span> F))),
            <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">NeweyWest</span>(FOJC_mod_CM2, <span class="dt">lag =</span> <span class="dv">7</span>, <span class="dt">prewhite =</span> F))))</code></pre></div>
<p>The results are then used to reproduce the outcomes presented in Table 15.1 of the book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">stargazer</span>(FOJC_mod_DM , FOJC_mod_CM1, FOJC_mod_CM1, FOJC_mod_CM2,
  <span class="dt">title =</span> <span class="st">&quot;Dynamic Effects of a Freezing Degree Day on the Price of Orange Juice&quot;</span>,
  <span class="dt">header =</span> <span class="ot">FALSE</span>, 
  <span class="dt">digits =</span> <span class="dv">3</span>, 
  <span class="dt">column.labels =</span> <span class="kw">c</span>(<span class="st">&quot;Dynamic Multipliers&quot;</span>, <span class="kw">rep</span>(<span class="st">&quot;Dynamic Cumulative Multipliers&quot;</span>, <span class="dv">3</span>)),
  <span class="dt">dep.var.caption  =</span> <span class="st">&quot;Dependent Variable: Monthly Percentage Change in Orange Juice Price&quot;</span>,
  <span class="dt">dep.var.labels.include =</span> <span class="ot">FALSE</span>,
  <span class="dt">covariate.labels =</span> <span class="kw">as.character</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>),
  <span class="dt">omit =</span> <span class="st">&quot;season&quot;</span>,
  <span class="dt">se =</span> SEs,
  <span class="dt">no.space =</span> T,
  <span class="dt">add.lines =</span> <span class="kw">list</span>(<span class="kw">c</span>(<span class="st">&quot;Monthly indicators?&quot;</span>,<span class="st">&quot;no&quot;</span>, <span class="st">&quot;no&quot;</span>, <span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>),
                   <span class="kw">c</span>(<span class="st">&quot;HAC truncation&quot;</span>,<span class="st">&quot;7&quot;</span>, <span class="st">&quot;7&quot;</span>, <span class="st">&quot;14&quot;</span>, <span class="st">&quot;7&quot;</span>)),
  <span class="dt">omit.stat =</span> <span class="kw">c</span>(<span class="st">&quot;rsq&quot;</span>, <span class="st">&quot;f&quot;</span>,<span class="st">&quot;ser&quot;</span>)) </code></pre></div>



<table style="text-align:center"><tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"></td><td colspan="4">Dependent Variable: Monthly Percentage Change in Orange Juice Price</td></tr>
<tr><td></td><td colspan="4" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align:left"></td><td>Dynamic Multipliers</td><td>Dynamic Cumulative Multipliers</td><td>Dynamic Cumulative Multipliers</td><td>Dynamic Cumulative Multipliers</td></tr>
<tr><td style="text-align:left"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">0</td><td>0.508<sup>***</sup></td><td>0.508<sup>***</sup></td><td>0.508<sup>***</sup></td><td>0.524<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.137)</td><td>(0.137)</td><td>(0.139)</td><td>(0.142)</td></tr>
<tr><td style="text-align:left">1</td><td>0.172<sup>**</sup></td><td>0.680<sup>***</sup></td><td>0.680<sup>***</sup></td><td>0.720<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.088)</td><td>(0.134)</td><td>(0.130)</td><td>(0.142)</td></tr>
<tr><td style="text-align:left">2</td><td>0.068</td><td>0.748<sup>***</sup></td><td>0.748<sup>***</sup></td><td>0.781<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.060)</td><td>(0.165)</td><td>(0.162)</td><td>(0.173)</td></tr>
<tr><td style="text-align:left">3</td><td>0.070</td><td>0.819<sup>***</sup></td><td>0.819<sup>***</sup></td><td>0.861<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.044)</td><td>(0.181)</td><td>(0.181)</td><td>(0.190)</td></tr>
<tr><td style="text-align:left">4</td><td>0.022</td><td>0.841<sup>***</sup></td><td>0.841<sup>***</sup></td><td>0.892<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.031)</td><td>(0.183)</td><td>(0.184)</td><td>(0.194)</td></tr>
<tr><td style="text-align:left">5</td><td>0.027</td><td>0.868<sup>***</sup></td><td>0.868<sup>***</sup></td><td>0.904<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.030)</td><td>(0.189)</td><td>(0.189)</td><td>(0.199)</td></tr>
<tr><td style="text-align:left">6</td><td>0.031</td><td>0.900<sup>***</sup></td><td>0.900<sup>***</sup></td><td>0.922<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.047)</td><td>(0.202)</td><td>(0.208)</td><td>(0.210)</td></tr>
<tr><td style="text-align:left">7</td><td>0.015</td><td>0.915<sup>***</sup></td><td>0.915<sup>***</sup></td><td>0.939<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.015)</td><td>(0.205)</td><td>(0.210)</td><td>(0.212)</td></tr>
<tr><td style="text-align:left">8</td><td>-0.042</td><td>0.873<sup>***</sup></td><td>0.873<sup>***</sup></td><td>0.904<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.034)</td><td>(0.214)</td><td>(0.218)</td><td>(0.219)</td></tr>
<tr><td style="text-align:left">9</td><td>-0.010</td><td>0.862<sup>***</sup></td><td>0.862<sup>***</sup></td><td>0.884<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.051)</td><td>(0.236)</td><td>(0.245)</td><td>(0.239)</td></tr>
<tr><td style="text-align:left">10</td><td>-0.116<sup>*</sup></td><td>0.746<sup>***</sup></td><td>0.746<sup>***</sup></td><td>0.752<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.069)</td><td>(0.257)</td><td>(0.262)</td><td>(0.259)</td></tr>
<tr><td style="text-align:left">11</td><td>-0.067</td><td>0.680<sup>**</sup></td><td>0.680<sup>**</sup></td><td>0.677<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.052)</td><td>(0.266)</td><td>(0.272)</td><td>(0.267)</td></tr>
<tr><td style="text-align:left">12</td><td>-0.143<sup>*</sup></td><td>0.537<sup>**</sup></td><td>0.537<sup>**</sup></td><td>0.551<sup>**</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.076)</td><td>(0.268)</td><td>(0.271)</td><td>(0.272)</td></tr>
<tr><td style="text-align:left">13</td><td>-0.083<sup>*</sup></td><td>0.454<sup>*</sup></td><td>0.454<sup>*</sup></td><td>0.491<sup>*</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.043)</td><td>(0.267)</td><td>(0.273)</td><td>(0.275)</td></tr>
<tr><td style="text-align:left">14</td><td>-0.057</td><td>0.397</td><td>0.397</td><td>0.427</td></tr>
<tr><td style="text-align:left"></td><td>(0.035)</td><td>(0.273)</td><td>(0.284)</td><td>(0.278)</td></tr>
<tr><td style="text-align:left">15</td><td>-0.032</td><td>0.366</td><td>0.366</td><td>0.406</td></tr>
<tr><td style="text-align:left"></td><td>(0.028)</td><td>(0.276)</td><td>(0.287)</td><td>(0.280)</td></tr>
<tr><td style="text-align:left">16</td><td>-0.005</td><td>0.360</td><td>0.360</td><td>0.408</td></tr>
<tr><td style="text-align:left"></td><td>(0.055)</td><td>(0.283)</td><td>(0.293)</td><td>(0.286)</td></tr>
<tr><td style="text-align:left">17</td><td>0.003</td><td>0.363</td><td>0.363</td><td>0.395</td></tr>
<tr><td style="text-align:left"></td><td>(0.018)</td><td>(0.287)</td><td>(0.294)</td><td>(0.290)</td></tr>
<tr><td style="text-align:left">18</td><td>0.003</td><td>0.366</td><td>0.366</td><td>0.386</td></tr>
<tr><td style="text-align:left"></td><td>(0.017)</td><td>(0.293)</td><td>(0.301)</td><td>(0.295)</td></tr>
<tr><td style="text-align:left">Constant</td><td>-0.343</td><td>-0.343</td><td>-0.343</td><td>-0.241</td></tr>
<tr><td style="text-align:left"></td><td>(0.269)</td><td>(0.269)</td><td>(0.256)</td><td>(0.934)</td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">Monthly indicators?</td><td>no</td><td>no</td><td>no</td><td>yes</td></tr>
<tr><td style="text-align:left">HAC truncation</td><td>7</td><td>7</td><td>14</td><td>7</td></tr>
<tr><td style="text-align:left">Observations</td><td>594</td><td>594</td><td>594</td><td>594</td></tr>
<tr><td style="text-align:left">Adjusted R<sup>2</sup></td><td>0.109</td><td>0.109</td><td>0.109</td><td>0.101</td></tr>
<tr><td colspan="5" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"><em>Note:</em></td><td colspan="4" style="text-align:right"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>
</table>
<caption><p style='text-align:center'><span id="tab:deoafddotpooj">Table 15.1: </span> Dynamic Effects of a Freezing Degree Day on the Price of Orange Juice</p></caption>


<p>According to column (1) of Table <a href="15-6-orange-juice-prices-and-cold-weather.html#tab:deoafddotpooj">15.1</a>, the contemporaneous effect of a freezing degree day is an increase of <span class="math inline">\(0.5\%\)</span> in orange juice prices. The estimated effect is only <span class="math inline">\(0.17\%\)</span> for the next month and close to zero for subsequent months. In fact, for all lags larger than 1, we cannot reject the null hypotheses that the respective coefficients are zero using individual <span class="math inline">\(t\)</span>-tests. The model <tt>FOJC_mod_DM</tt> only explains little of the variation in the dependent variable (<span class="math inline">\(\bar{R}^2 = 0.11\)</span>).</p>
<p>Columns (2) and (3) present estimates of the dynamic cumulative multipliers of model <tt>FOJC_mod_CM1</tt>. Apparently, it does not matter whether we choose <span class="math inline">\(m=7\)</span> or <span class="math inline">\(m=14\)</span> when computing HAC standard errors so we stick with <span class="math inline">\(m=7\)</span> and the standard errors reported in column (2).</p>
<p>If the demand for orange juice is higher in winter, <span class="math inline">\(FDD_t\)</span> would be correlated with the error term since freezes occur rather in winter so we would face omitted variable bias. The third model estimate, <tt>FOJC_mod_CM2</tt>, accounts for this possible issue by using an additional set of 11 monthly dummies. For brevity, estimates of the dummy coefficients are excluded from the output produced by stargazer (this is achieved by setting <tt>omit = ‘season’</tt>). We may check that the dummy for January was omitted to prevent perfect multicollinearity.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimates on mothly dummies</span>
FOJC_mod_CM2<span class="op">$</span>coefficients[<span class="op">-</span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>)]</code></pre></div>
<pre><code>## season(FDD)Feb season(FDD)Mar season(FDD)Apr season(FDD)May season(FDD)Jun 
##     -0.9565759     -0.6358007      0.5006770     -1.0801764      0.3195624 
## season(FDD)Jul season(FDD)Aug season(FDD)Sep season(FDD)Oct season(FDD)Nov 
##      0.1951113      0.3644312     -0.4130969     -0.1566622      0.3116534 
## season(FDD)Dec 
##      0.1481589</code></pre>
<p>A comparison of the estimates presented in columns (3) and (4) indicates that adding monthly dummies has a negligible effect. Further evidence for this comes from a joint test of the hypothesis that the 11 dummy coefficients are zero. Instead of using <tt>linearHypothesis()</tt>, we use the function <tt>waldtest()</tt> and supply two model objects instead: <tt>unres_model</tt>, the unrestricted model object which is the same as <tt>FOJC_mod_CM2</tt> (except for the coefficient names since we have modified them above) and <tt>res_model</tt>, the model where the restriction that all dummy coefficients are zero is imposed. <tt>res_model</tt> is conveniently obtained using the function <tt>update()</tt>. It extracts the argument <tt>formula</tt> of a model object, updates it as specified and then re-fits the model. By setting <tt>formula = . ~ . - season(FDD)</tt> we impose that the monthly dummies do not enter the model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if coefficients on monthly dummies are zero</span>
unres_model &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(FDD), <span class="dv">0</span><span class="op">:</span><span class="dv">17</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">18</span>) <span class="op">+</span><span class="st"> </span><span class="kw">season</span>(FDD))

res_model &lt;-<span class="st"> </span><span class="kw">update</span>(unres_model, <span class="dt">formula =</span> . <span class="op">~</span><span class="st"> </span>. <span class="op">-</span><span class="st"> </span><span class="kw">season</span>(FDD))

<span class="kw">waldtest</span>(unres_model, 
         res_model, 
         <span class="dt">vcov =</span> <span class="kw">NeweyWest</span>(unres_model, <span class="dt">lag =</span> <span class="dv">7</span>, <span class="dt">prewhite =</span> F))</code></pre></div>
<pre><code>## Wald test
## 
## Model 1: FOJC_pctc ~ L(d(FDD), 0:17) + L(FDD, 18) + season(FDD)
## Model 2: FOJC_pctc ~ L(d(FDD), 0:17) + L(FDD, 18)
##   Res.Df  Df      F Pr(&gt;F)
## 1    563                  
## 2    574 -11 0.9683 0.4743</code></pre>
<p>The <span class="math inline">\(p\)</span>-value is <span class="math inline">\(0.47\)</span> so we cannot reject the hypothesis that the coefficients on the monthly dummies are zero, even at the <span class="math inline">\(10\%\)</span> level. We conclude that the seasonal fluctuations in demand for orange juice do not pose a serious threat to internal validity of the model.</p>
<p>It is convenient to use plots of dynamic multipliers and cumulative dynamic multipliers. The following two code chunks reproduce Figures 15.2 (a) and 15.2 (b) of the book which display point estimates of dynamic and cumulative multipliers along with upper and lower bounds of their <span class="math inline">\(95\%\)</span> confidence intervals computed using the above HAC standard errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 95% CI bounds</span>
point_estimates &lt;-<span class="st"> </span>FOJC_mod_DM<span class="op">$</span>coefficients

CI_bounds &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="st">&quot;lower&quot;</span> =<span class="st"> </span>point_estimates <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>SEs[[<span class="dv">1</span>]],
                   <span class="st">&quot;upper&quot;</span> =<span class="st"> </span>point_estimates <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>SEs[[<span class="dv">1</span>]])[<span class="op">-</span><span class="dv">1</span>, ]

<span class="co"># plot the estimated dynamic multipliers</span>
<span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, point_estimates[<span class="op">-</span><span class="dv">1</span>], 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.4</span>, <span class="dv">1</span>),
     <span class="dt">xlab =</span> <span class="st">&quot;Lag&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Dynamic multiplier&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Dynamic Effect of FDD on Orange Juice Price&quot;</span>)

<span class="co"># add a dashed line at 0</span>
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>)

<span class="co"># add CI bounds</span>
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, CI_bounds[,<span class="dv">1</span>], <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, CI_bounds[,<span class="dv">2</span>], <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:DM"></span>
<img src="Introduction_to_Econometrics_with_R_files/figure-html/DM-1.png" alt="Dynamic Multipliers" width="672" />
<p class="caption">
Figure 15.1: Dynamic Multipliers
</p>
</div>
<p>The <span class="math inline">\(95\%\)</span> confidence intervals plotted in Figure <a href="15-6-orange-juice-prices-and-cold-weather.html#fig:DM">15.1</a> indeed include zero for lags larger than 1 such that the null of a zero multiplier cannot be rejected for these lags.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 95% CI bounds</span>
point_estimates &lt;-<span class="st"> </span>FOJC_mod_CM1<span class="op">$</span>coefficients

CI_bounds &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="st">&quot;lower&quot;</span> =<span class="st"> </span>point_estimates <span class="op">-</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>SEs[[<span class="dv">2</span>]],
                   <span class="st">&quot;upper&quot;</span> =<span class="st"> </span>point_estimates <span class="op">+</span><span class="st"> </span><span class="fl">1.96</span> <span class="op">*</span><span class="st"> </span>SEs[[<span class="dv">2</span>]])[<span class="op">-</span><span class="dv">1</span>,]


<span class="co"># plot estimated dynamic multipliers</span>
<span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, point_estimates[<span class="op">-</span><span class="dv">1</span>], 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.4</span>, <span class="fl">1.6</span>),
     <span class="dt">xlab =</span> <span class="st">&quot;Lag&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Cumulative dynamic multiplier&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Cumulative Dynamic Effect of FDD on Orange Juice Price&quot;</span>)

<span class="co"># add dashed line at 0</span>
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>)

<span class="co"># add CI bounds</span>
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, CI_bounds[, <span class="dv">1</span>], <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, CI_bounds[, <span class="dv">2</span>], <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:DCM"></span>
<img src="Introduction_to_Econometrics_with_R_files/figure-html/DCM-1.png" alt="Dynamic Cumulative Multipliers" width="672" />
<p class="caption">
Figure 15.2: Dynamic Cumulative Multipliers
</p>
</div>
<p>As can be seen from Figure <a href="15-6-orange-juice-prices-and-cold-weather.html#fig:DCM">15.2</a>, the estimated dynamic cumulative multipliers grow until the seventh month up to a price increase of about <span class="math inline">\(0.91\%\)</span> and then decrease slightly to the estimated long-run cumulative multiplier of <span class="math inline">\(0.37\%\)</span> which, however, is not significantly different from zero at the <span class="math inline">\(5\%\)</span> level.</p>
<p>Have the dynamic multipliers been stable over time? One way to see this is to estimate these multipliers for different subperiods of the sample span. For example, consider periods 1950 - 1966, 1967 - 1983 and 1984 - 2000. If the multipliers are the same for all three periods the estimates should be close and thus the estimated cumulative multipliers should be similar, too. We investigate this by re-estimating <tt>FOJC_mod_CM1</tt> for the three different time spans and then plot the estimated cumulative dynamic multipliers for the comparison.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate cumulative multiplieres using different sample periods</span>
FOJC_mod_CM1950 &lt;-<span class="st"> </span><span class="kw">update</span>(FOJC_mod_CM1, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1950</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">1966</span>, <span class="dv">12</span>))

FOJC_mod_CM1967 &lt;-<span class="st"> </span><span class="kw">update</span>(FOJC_mod_CM1, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1967</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">1983</span>, <span class="dv">12</span>))

FOJC_mod_CM1984 &lt;-<span class="st"> </span><span class="kw">update</span>(FOJC_mod_CM1, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1984</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2000</span>, <span class="dv">12</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot estimated dynamic cumulative multipliers (1950-1966)</span>
<span class="kw">plot</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, FOJC_mod_CM1950<span class="op">$</span>coefficients[<span class="op">-</span><span class="dv">1</span>], 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>,
     <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">20</span>),
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="dv">2</span>),
     <span class="dt">xlab =</span> <span class="st">&quot;Lag&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Cumulative dynamic multiplier&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Cumulative Dynamic Effect for Different Sample Periods&quot;</span>)

<span class="co"># plot estimated dynamic multipliers (1967-1983)</span>
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, FOJC_mod_CM1967<span class="op">$</span>coefficients[<span class="op">-</span><span class="dv">1</span>], <span class="dt">lwd =</span> <span class="dv">2</span>)

<span class="co"># plot estimated dynamic multipliers (1984-2000)</span>
<span class="kw">lines</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">18</span>, FOJC_mod_CM1984<span class="op">$</span>coefficients[<span class="op">-</span><span class="dv">1</span>], <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>)

<span class="co"># add dashed line at 0</span>
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>)

<span class="co"># add annotations</span>
<span class="kw">text</span>(<span class="dv">18</span>, <span class="op">-</span><span class="fl">0.24</span>, <span class="st">&quot;1984 - 2000&quot;</span>)
<span class="kw">text</span>(<span class="dv">18</span>, <span class="fl">0.6</span>, <span class="st">&quot;1967 - 1983&quot;</span>)
<span class="kw">text</span>(<span class="dv">18</span>, <span class="fl">1.2</span>, <span class="st">&quot;1950 - 1966&quot;</span>)</code></pre></div>
<p><img src="Introduction_to_Econometrics_with_R_files/figure-html/unnamed-chunk-683-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Clearly, the cumulative dynamic multipliers have changed considerably over time. The effect of a freeze was stronger and more persistent in the 1950s and 1960s. For the 1970s the magnitude of the effect was lower but still highly persistent. We observe an even lower magnitude for the final third of the sample span (1984 - 2000) where the long-run effect is much less persistent and essentially zero after a year.</p>
<p>A QLR test for a break in the distributed lag regression of column (1) in Table @ref{tab:deoafddotpooj} with <span class="math inline">\(15\%\)</span> trimming using a HAC variance-covariance matrix estimate supports the conjecture that the population regression coefficients have changed over time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up a range of possible break dates</span>
tau &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">window</span>(<span class="kw">time</span>(FDD), 
                <span class="kw">time</span>(FDD)[<span class="kw">round</span>(<span class="dv">612</span><span class="op">/</span><span class="dv">100</span><span class="op">*</span><span class="dv">15</span>)], 
                <span class="kw">time</span>(FDD)[<span class="kw">round</span>(<span class="dv">612</span><span class="op">/</span><span class="dv">100</span><span class="op">*</span><span class="dv">85</span>)]))

<span class="co"># initialize the vector of F-statistics</span>
Fstats &lt;-<span class="st"> </span><span class="kw">numeric</span>(<span class="kw">length</span>(tau))

<span class="co"># the restricted model</span>
res_model &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))

<span class="co"># estimation, loop over break dates</span>
<span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(tau)) {
  
  <span class="co"># set up dummy variable</span>
  D &lt;-<span class="st"> </span><span class="kw">time</span>(FOJC_pctc) <span class="op">&gt;</span><span class="st"> </span>tau[i]
  
  <span class="co"># estimate DL model with intercations</span>
  unres_model &lt;-<span class="st"> </span><span class="kw">dynlm</span>(FOJC_pctc <span class="op">~</span><span class="st"> </span>D <span class="op">*</span><span class="st"> </span><span class="kw">L</span>(FDD, <span class="dv">0</span><span class="op">:</span><span class="dv">18</span>))
                 
  <span class="co"># compute and save F-statistic</span>
  Fstats[i] &lt;-<span class="st"> </span><span class="kw">waldtest</span>(res_model, 
                        unres_model, 
                        <span class="dt">vcov =</span> <span class="kw">NeweyWest</span>(unres_model, <span class="dt">lag =</span> <span class="dv">7</span>, <span class="dt">prewhite =</span> F))<span class="op">$</span>F[<span class="dv">2</span>]
    
}</code></pre></div>
<p>Note that this code takes a couple of seconds to run since a total of <tt>length(tau)</tt> regressions with <span class="math inline">\(40\)</span> model coefficients each are estimated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># QLR test statistic</span>
<span class="kw">max</span>(Fstats)</code></pre></div>
<pre><code>## [1] 36.76819</code></pre>
<p>The QLR statistic is <span class="math inline">\(36.77\)</span>. From Table 14.5 of the book we see that the <span class="math inline">\(1\%\)</span> critical value for the QLR test with <span class="math inline">\(15\%\)</span> trimming and <span class="math inline">\(q=20\)</span> restrictions is <span class="math inline">\(2.43\)</span>. Since this is a right-sided test, the QLR statistic clearly lies in the region of rejection so we can discard the null hypothesis of no break in the population regression function.</p>
<p>See Chapter 15.7 of the book for a discussion of empirical examples where it is questionable whether the assumption of (past and present) exogeneity of the regressors is plausible.</p>
<div id="summary-7" class="section level4 unnumbered">
<h4>Summary</h4>
<ul>
<li><p>We have seen how <tt>R</tt> can be used to estimate the time path of the effect on <span class="math inline">\(Y\)</span> of a change in <span class="math inline">\(X\)</span> (the dynamic causal effect on <span class="math inline">\(Y\)</span> of a change in <span class="math inline">\(X\)</span>) using time series data on both. The corresponding model is called the distributed lag model. Distributed lag models are conveniently estimated using the function <tt>dynlm()</tt> from the package <tt>dynlm</tt>.</p></li>
<li><p>The regression error in distributed lag models is often serially correlated such that standard errors which are robust to heteroskedasticity <em>and</em> autocorrelation should be used to obtain valid inference. The package <tt>sandwich</tt> provides functions for computation of so-called HAC covariance matrix estimators, for example <tt>vcovHAC()</tt> and <tt>NeweyWest()</tt>.</p></li>
<li><p>When <span class="math inline">\(X\)</span> is <em>strictly exogeneous</em>, more efficient estimates can be obtained using an ADL model or by GLS estimation. Feasible GLS algorithms can be found in the <tt>R</tt> packages <tt>orcutt</tt> and <tt>nlme</tt>. Chapter 15.7 of the book emphasizes that the assumption of strict exogeneity is often implausible in empirical applications.</p></li>
</ul>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="15-5-estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="16-atitsr.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
