<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Econometrics with R</title>
  <meta name="description" content="<em>Introduction to Econometrics with R</em> is an interactive companion to the well-received textbook <em>Introduction to Econometrics</em> by James H. Stock and Mark W. Watson (2015). It intends to guide students in implementing the empirical applications presented throughout the book using the statistical software package R.">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="<em>Introduction to Econometrics with R</em> is an interactive companion to the well-received textbook <em>Introduction to Econometrics</em> by James H. Stock and Mark W. Watson (2015). It intends to guide students in implementing the empirical applications presented throughout the book using the statistical software package R." />
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="<em>Introduction to Econometrics with R</em> is an interactive companion to the well-received textbook <em>Introduction to Econometrics</em> by James H. Stock and Mark W. Watson (2015). It intends to guide students in implementing the empirical applications presented throughout the book using the statistical software package R." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="2-1-binary-dependent-variables-and-the-linear-probability-model.html">
<link rel="next" href="2-3-estimation-and-inference-in-the-logit-and-probit-models.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!-- function to adjust height of iframes automatically depending on content loaded -->

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="MathJax-2.7.2/MathJax.js?config=default"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.oek.wiwi.uni-due.de/en/">Chair of Econometrics @ Uni-DUE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-a-very-short-introduction-to-r-and-rstudio.html"><a href="1-1-a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-rwabdv.html"><a href="2-rwabdv.html"><i class="fa fa-check"></i><b>2</b> Regression with a Binary Dependent Variable</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-binary-dependent-variables-and-the-linear-probability-model.html"><a href="2-1-binary-dependent-variables-and-the-linear-probability-model.html"><i class="fa fa-check"></i><b>2.1</b> Binary Dependent Variables and the Linear Probability Model</a></li>
<li class="chapter" data-level="2.2" data-path="2-2-palr.html"><a href="2-2-palr.html"><i class="fa fa-check"></i><b>2.2</b> Probit and Logit Regression</a><ul>
<li class="chapter" data-level="" data-path="2-2-palr.html"><a href="2-2-palr.html#probit-regression"><i class="fa fa-check"></i>Probit Regression</a></li>
<li class="chapter" data-level="" data-path="2-2-palr.html"><a href="2-2-palr.html#logit-regression"><i class="fa fa-check"></i>Logit Regression</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-estimation-and-inference-in-the-logit-and-probit-models.html"><a href="2-3-estimation-and-inference-in-the-logit-and-probit-models.html"><i class="fa fa-check"></i><b>2.3</b> Estimation and Inference in the Logit and Probit Models</a></li>
<li class="chapter" data-level="2.4" data-path="2-4-application-to-the-boston-hmda-data.html"><a href="2-4-application-to-the-boston-hmda-data.html"><i class="fa fa-check"></i><b>2.4</b> Application to the Boston HMDA Data</a></li>
<li class="chapter" data-level="2.5" data-path="2-5-exercises.html"><a href="2-5-exercises.html"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><em>Introduction to Econometrics with R</em></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="palr" class="section level2">
<h2><span class="header-section-number">2.2</span> Probit and Logit Regression</h2>
<p>The linear probability model has a major flaw: it assumes the conditional probability function to be linear. This does not restrict <span class="math inline">\(P(Y=1\vert X_1,\dots,X_k)\)</span> to lie between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>. We can easily see this in our reproduction of Figure 11.1 of the book: for <span class="math inline">\(P/I \ ratio \geq 1.75\)</span>, <a href="2-1-binary-dependent-variables-and-the-linear-probability-model.html#eq:lpm">(2.2)</a> predicts the probability of a mortgage application denial to be bigger than <span class="math inline">\(1\)</span>. For applications with <span class="math inline">\(P/I \ ratio\)</span> close to <span class="math inline">\(0\)</span>, the predicted probability of denial is even negative so that the model has no meaningful interpretation here.</p>
<p>This circumstance calls for an approach that uses a nonlinear function to model the conditional probability function of a binary dependent variable. Commonly used methods are Probit and Logit regression.</p>
<div id="probit-regression" class="section level3 unnumbered">
<h3>Probit Regression</h3>
In Probit regression, the cumulative standard normal distribution function <span class="math inline">\(\Phi(\cdot)\)</span> is used to model the regression function when the dependent variable is binary, that is, we assume
<span class="math display" id="eq:probitmodel">\[\begin{align}
  E(Y\vert X) = P(Y=1\vert X) = \Phi(\beta_0 + \beta_1 X). \tag{2.4}
\end{align}\]</span>
<p><span class="math inline">\(\beta_0 + \beta_1 X\)</span> in <a href="2-2-palr.html#eq:probitmodel">(2.4)</a> plays the role of a quantile <span class="math inline">\(z\)</span>. Remember that <span class="math display">\[\Phi(z) = P(Z \leq z) \ , \ Z \sim \mathcal{N}(0,1)\]</span> such that the Probit coefficient <span class="math inline">\(\beta_1\)</span> in <a href="2-2-palr.html#eq:probitmodel">(2.4)</a> is the change in <span class="math inline">\(z\)</span> associated with a one unit change in <span class="math inline">\(X\)</span>. Although the effect on <span class="math inline">\(z\)</span> of a change in <span class="math inline">\(X\)</span> is linear, the link between <span class="math inline">\(z\)</span> and the dependent variable <span class="math inline">\(Y\)</span> is nonlinear since <span class="math inline">\(\Phi\)</span> is a nonlinear function of <span class="math inline">\(X\)</span>.</p>
<p>Since the dependent variable is a nonlinear function of the regressors, the coefficient on <span class="math inline">\(X\)</span> has no simple interpretation. According to Key Concept 8.1, the expected change in the probability that <span class="math inline">\(Y=1\)</span> due to a change in <span class="math inline">\(P/I \ ratio\)</span> can be computed as follows:</p>
<ol style="list-style-type: decimal">
<li>Compute the predicted probability that <span class="math inline">\(Y=1\)</span> for the original value of <span class="math inline">\(X\)</span>.</li>
<li>Compute the predicted probability that <span class="math inline">\(Y=1\)</span> for <span class="math inline">\(X + \Delta X\)</span>.</li>
<li>Compute the difference between both predicted probabilities.</li>
</ol>
<p>Of course we can generalize <a href="2-2-palr.html#eq:probitmodel">(2.4)</a> to Probit regression with multiple regressors to mitigate the risk of facing omitted variable bias. Probit regression essentials are summarized in Key Concept 11.2.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 11.2
</h3>
<h3 class="left">
Probit Model, Predicted Probabilities and Estimated Effects
</h3>
<p>Assume that <span class="math inline">\(Y\)</span> is a binary variable. The model</p>
<p><span class="math display">\[ Y= \beta_0 + \beta_1 + X_1 + \beta_2 X_2 + \dots + \beta_k X_k + u \]</span> with <span class="math display">\[P(Y = 1 \vert X_1, X_2, \dots ,X_k) = \Phi(\beta_0 + \beta_1 + X_1 + \beta_2 X_2 + \dots + \beta_k X_k)\]</span> is the population Probit model with multiple regressors <span class="math inline">\(X_1, X_2, \dots, X_k\)</span> and <span class="math inline">\(\Phi(\cdot)\)</span> is the cumulative standard normal distribution function.</p>
<p>The predicted probability that <span class="math inline">\(Y=1\)</span> given <span class="math inline">\(X_1, X_2, \dots, X_k\)</span> can be calculated in two steps:</p>
<ol style="list-style-type: decimal">
<li><p>Compute <span class="math inline">\(z = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_k X_k\)</span></p></li>
<li><p>Look up <span class="math inline">\(\Phi(z)\)</span> by calling <tt>pnorm()</tt>.</p></li>
</ol>
<p><span class="math inline">\(\beta_j\)</span> is the effect on <span class="math inline">\(z\)</span> of a one unit change in regressor <span class="math inline">\(X_j\)</span>, holding constant all other <span class="math inline">\(k-1\)</span> regressors.</p>
<p>The effect on the predicted probability of a change in a regressor can be computed as in Key Concept 8.1.</p>
<p>In <tt>R</tt>, Probit models can be estimated using the function <tt>glm()</tt> from the package <tt>stats</tt>. Using the argument <tt>family</tt> we specify that we want to use a Probit link function.</p>
</div>
<p>We now estimate a simple Probit model of the probability of a mortgage denial.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate the simple probit model</span>
denyprobit &lt;-<span class="st"> </span><span class="kw">glm</span>(deny <span class="op">~</span><span class="st"> </span>pirat, 
                  <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;probit&quot;</span>), 
                  <span class="dt">data =</span> HMDA)

<span class="kw">coeftest</span>(denyprobit, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -2.19415    0.18901 -11.6087 &lt; 2.2e-16 ***
## pirat        2.96787    0.53698   5.5269 3.259e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated model is</p>
<span class="math display" id="eq:denyprobit">\[\begin{align}
  \widehat{P(deny\vert P/I \ ratio}) = \Phi(-\underset{(0.19)}{2.19} + \underset{(0.54)}{2.97} P/I \ ratio). \tag{2.5}
\end{align}\]</span>
<p>Just as in the linear probability model we find that the relation between the probability of denial and the payments-to-income ratio is positive and that the corresponding coefficient is highly significant.</p>
<p>The following code chunk reproduces Figure 11.2 of the book.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot data</span>
<span class="kw">plot</span>(<span class="dt">x =</span> HMDA<span class="op">$</span>pirat, 
     <span class="dt">y =</span> HMDA<span class="op">$</span>deny,
     <span class="dt">main =</span> <span class="st">&quot;Probit Model of the Probability of Denial, Given P/I Ratio&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;P/I ratio&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Deny&quot;</span>,
     <span class="dt">pch =</span> <span class="dv">20</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.4</span>, <span class="fl">1.4</span>),
     <span class="dt">cex.main =</span> <span class="fl">0.85</span>)

<span class="co"># add horizontal dashed lines and text</span>
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">1</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">text</span>(<span class="fl">2.5</span>, <span class="fl">0.9</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>, <span class="st">&quot;Mortgage denied&quot;</span>)
<span class="kw">text</span>(<span class="fl">2.5</span>, <span class="op">-</span><span class="fl">0.1</span>, <span class="dt">cex=</span> <span class="fl">0.8</span>, <span class="st">&quot;Mortgage approved&quot;</span>)

<span class="co"># add estimated regression line</span>
x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="fl">0.01</span>)
y &lt;-<span class="st"> </span><span class="kw">predict</span>(denyprobit, <span class="kw">list</span>(<span class="dt">pirat =</span> x), <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

<span class="kw">lines</span>(x, y, <span class="dt">lwd =</span> <span class="fl">1.5</span>, <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>)</code></pre></div>
<p><img src="Introduction_to_Econometrics_with_R_files/figure-html/unnamed-chunk-25-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The estimated regression function has a stretched “S”-shape which is typical for the CDF of a continuous random variable with symmetric PDF like that of a normal random variable. The function is clearly nonlinear and flattens out for large and small values of <span class="math inline">\(P/I \ ratio\)</span>. The functional form thus also ensures that the predicted conditional probabilities of a denial lie between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>.</p>
<p>We use <tt>predict()</tt> to compute the predicted change in the denial probability when <span class="math inline">\(P/I \ ratio\)</span> is increased from <span class="math inline">\(0.3\)</span> to <span class="math inline">\(0.4\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 1. compute predictions for P/I ratio = 0.3, 0.4</span>
predictions &lt;-<span class="st"> </span><span class="kw">predict</span>(denyprobit, 
                       <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="st">&quot;pirat&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.4</span>)),
                       <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

<span class="co"># 2. Compute difference in probabilities</span>
<span class="kw">diff</span>(predictions)</code></pre></div>
<pre><code>##          2 
## 0.06081433</code></pre>
<p>We find that an increase in the payment-to-income ratio from <span class="math inline">\(0.3\)</span> to <span class="math inline">\(0.4\)</span> is predicted to increase the probability of denial by approximately <span class="math inline">\(6.2\%\)</span>.</p>
<p>We continue by using an augmented Probit model to estimate the effect of race on the probability of a mortgage application denial.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">denyprobit2 &lt;-<span class="st"> </span><span class="kw">glm</span>(deny <span class="op">~</span><span class="st"> </span>pirat <span class="op">+</span><span class="st"> </span>black, 
                   <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;probit&quot;</span>), 
                   <span class="dt">data =</span> HMDA)

<span class="kw">coeftest</span>(denyprobit2, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## z test of coefficients:
## 
##              Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -2.258787   0.176608 -12.7898 &lt; 2.2e-16 ***
## pirat        2.741779   0.497673   5.5092 3.605e-08 ***
## blackyes     0.708155   0.083091   8.5227 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated model equation is</p>
<span class="math display" id="eq:denyprobit2">\[\begin{align}
  \widehat{P(deny\vert P/I \ ratio, black)} = \Phi (-\underset{(0.18)}{2.26} + \underset{(0.50)}{2.74} P/I \ ratio + \underset{(0.08)}{0.71} black). \tag{2.6} 
\end{align}\]</span>
<p>While all coefficients are highly significant, both the estimated coefficients on the payments-to-income ratio and the indicator for African American descent are positive. Again, the coefficients are difficult to interpret but they indicate that, first, African Americans have a higher probability of denial than white applicants, holding constant the payments-to-income ratio and second, applicants with a high payments-to-income ratio face a higher risk of being rejected.</p>
<p>How big is the estimated difference in denial probabilities between two hypothetical applicants with the same payments-to-income ratio? As before, we may use <tt>predict()</tt> to compute this difference.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 1. compute predictions for P/I ratio = 0.3</span>
predictions &lt;-<span class="st"> </span><span class="kw">predict</span>(denyprobit2, 
                       <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="st">&quot;black&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>), 
                                            <span class="st">&quot;pirat&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.3</span>)),
                       <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

<span class="co"># 2. compute difference in probabilities</span>
<span class="kw">diff</span>(predictions)</code></pre></div>
<pre><code>##         2 
## 0.1578117</code></pre>
<p>In this case, the estimated difference in denial probabilities is about <span class="math inline">\(15.8\%\)</span>.</p>
</div>
<div id="logit-regression" class="section level3 unnumbered">
<h3>Logit Regression</h3>
<p>Key Concept 11.3 summarizes the Logit regression function.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 11.3
</h3>
<h3 class="left">
Logit Regression
</h3>
<p>The population Logit regression function is</p>
<span class="math display">\[\begin{align*}
  P(Y=1\vert X_1, X_2, \dots, X_k) =&amp; \, F(\beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_k X_k) \\
  =&amp; \, \frac{1}{1+e^{-(\beta_0 + \beta_1 X_1 + \beta_2 X_2 + \dots + \beta_k X_k)}}.
\end{align*}\]</span>
<p>The idea is similar to Probit regression except that a different CDF is used: <span class="math display">\[F(x) = \frac{1}{1+e^{-x}}\]</span> is the CDF of a standard logistically distributed random variable.</p>
</div>
<p>As for Probit regression, there is no simple interpretation of the model coefficients and it is best to consider predicted probabilities or differences in predicted probabilities. Here again, <span class="math inline">\(t\)</span>-statistics and confidence intervals based on large sample normal approximations can be computed as usual.</p>
<p>It is fairly easy to estimate a Logit regression model using <tt>R</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">denylogit &lt;-<span class="st"> </span><span class="kw">glm</span>(deny <span class="op">~</span><span class="st"> </span>pirat, 
                 <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>), 
                 <span class="dt">data =</span> HMDA)

<span class="kw">coeftest</span>(denylogit, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -4.02843    0.35898 -11.2218 &lt; 2.2e-16 ***
## pirat        5.88450    1.00015   5.8836 4.014e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The subsequent code chunk reproduces Figure 11.3 of the book.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot data</span>
<span class="kw">plot</span>(<span class="dt">x =</span> HMDA<span class="op">$</span>pirat, 
     <span class="dt">y =</span> HMDA<span class="op">$</span>deny,
     <span class="dt">main =</span> <span class="st">&quot;Probit and Logit Models Model of the Probability of Denial, Given P/I Ratio&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;P/I ratio&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Deny&quot;</span>,
     <span class="dt">pch =</span> <span class="dv">20</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.4</span>, <span class="fl">1.4</span>),
     <span class="dt">cex.main =</span> <span class="fl">0.9</span>)

<span class="co"># add horizontal dashed lines and text</span>
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">1</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">abline</span>(<span class="dt">h =</span> <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">text</span>(<span class="fl">2.5</span>, <span class="fl">0.9</span>, <span class="dt">cex =</span> <span class="fl">0.8</span>, <span class="st">&quot;Mortgage denied&quot;</span>)
<span class="kw">text</span>(<span class="fl">2.5</span>, <span class="op">-</span><span class="fl">0.1</span>, <span class="dt">cex=</span> <span class="fl">0.8</span>, <span class="st">&quot;Mortgage approved&quot;</span>)

<span class="co"># add estimated regression line of Probit and Logit models</span>
x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="fl">0.01</span>)
y_probit &lt;-<span class="st"> </span><span class="kw">predict</span>(denyprobit, <span class="kw">list</span>(<span class="dt">pirat =</span> x), <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)
y_logit &lt;-<span class="st"> </span><span class="kw">predict</span>(denylogit, <span class="kw">list</span>(<span class="dt">pirat =</span> x), <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

<span class="kw">lines</span>(x, y_probit, <span class="dt">lwd =</span> <span class="fl">1.5</span>, <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>)
<span class="kw">lines</span>(x, y_logit, <span class="dt">lwd =</span> <span class="fl">1.5</span>, <span class="dt">col =</span> <span class="st">&quot;black&quot;</span>, <span class="dt">lty =</span> <span class="dv">2</span>)

<span class="co"># add a legend</span>
<span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,
       <span class="dt">horiz =</span> <span class="ot">TRUE</span>,
       <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;Probit&quot;</span>, <span class="st">&quot;Logit&quot;</span>),
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;black&quot;</span>), 
       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</code></pre></div>
<p><img src="Introduction_to_Econometrics_with_R_files/figure-html/unnamed-chunk-32-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>Both models produce very similar estimates of the probability that a mortgage application will be denied depending on the applicants payment-to-income ratio.</p>
<p>Following the book we extend the simple Logit model of mortgage denial with the additional regressor <span class="math inline">\(black\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate a Logit regression with multiple regressors</span>
denylogit2 &lt;-<span class="st"> </span><span class="kw">glm</span>(deny <span class="op">~</span><span class="st"> </span>pirat <span class="op">+</span><span class="st"> </span>black, 
                  <span class="dt">family =</span> <span class="kw">binomial</span>(<span class="dt">link =</span> <span class="st">&quot;logit&quot;</span>), 
                  <span class="dt">data =</span> HMDA)

<span class="kw">coeftest</span>(denylogit2, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## z test of coefficients:
## 
##             Estimate Std. Error  z value  Pr(&gt;|z|)    
## (Intercept) -4.12556    0.34597 -11.9245 &lt; 2.2e-16 ***
## pirat        5.37036    0.96376   5.5723 2.514e-08 ***
## blackyes     1.27278    0.14616   8.7081 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We obtain</p>
<span class="math display" id="eq:denylogit2">\[\begin{align}
  \widehat{P(deny=1 \vert P/I ratio, black)} = F(-\underset{(0.35)}{4.13} + \underset{(0.96)}{5.37} P/I \ ratio + \underset{(0.15)}{1.27} black). \tag{2.7}
\end{align}\]</span>
<p>As for the Probit model <a href="2-2-palr.html#eq:denyprobit2">(2.6)</a> all model coefficients are highly significant and we obtain positive estimates for the coefficients on <span class="math inline">\(P/I \ ratio\)</span> and <span class="math inline">\(black\)</span>. For comparison we compute the predicted probability of denial for two hypothetical applicants that differ in race and have a <span class="math inline">\(P/I \ ratio\)</span> of <span class="math inline">\(0.3\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 1. compute predictions for P/I ratio = 0.3</span>
predictions &lt;-<span class="st"> </span><span class="kw">predict</span>(denylogit2, 
                       <span class="dt">newdata =</span> <span class="kw">data.frame</span>(<span class="st">&quot;black&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>), 
                                            <span class="st">&quot;pirat&quot;</span> =<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.3</span>)),
                       <span class="dt">type =</span> <span class="st">&quot;response&quot;</span>)

predictions</code></pre></div>
<pre><code>##          1          2 
## 0.07485143 0.22414592</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 2. Compute difference in probabilities</span>
<span class="kw">diff</span>(predictions)</code></pre></div>
<pre><code>##         2 
## 0.1492945</code></pre>
<p>We find that the white applicant faces a denial probability of only <span class="math inline">\(7.5\%\)</span>, while the African American is rejected with a probability of <span class="math inline">\(22.4\%\)</span>, a difference of <span class="math inline">\(14.9\%\)</span>.</p>
<div id="comparison-of-the-models" class="section level4 unnumbered">
<h4>Comparison of the Models</h4>
<p>The Probit model and the Logit model deliver only approximations to the unknown population regression function <span class="math inline">\(E(Y\vert X)\)</span>. It is not obvious how to decide which model to use in practice. The linear probability model has the clear drawback of not being able to capture the nonlinear nature of the population regression function and it may predict probabilities to lie outside the interval <span class="math inline">\([0,1]\)</span>. Probit and Logit models are harder to interpret but capture the nonlinearities better than the linear approach: both models produce predictions of probabilities that lie inside the interval <span class="math inline">\([0,1]\)</span>. Predictions of all three models are often close to each other. The book suggests to use the method that is easiest to use in the statistical software of choice. As we have seen, it is equally easy to estimate Probit and Logit model using <tt>R</tt>. We can therefore give no general recommendation which method to use.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-1-binary-dependent-variables-and-the-linear-probability-model.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="2-3-estimation-and-inference-in-the-logit-and-probit-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
