<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.3 Autoregressions | Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="2.3 Autoregressions | Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://www.econometrics-with-r.org/" />
  <meta property="og:image" content="https://www.econometrics-with-r.org/images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="mca91/EconometricsWithR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.3 Autoregressions | Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="https://www.econometrics-with-r.org/images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer" />


<meta name="date" content="2019-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="2-2-tsdasc.html">
<link rel="next" href="2-4-cybtmpi.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!--<script src="js/hideOutput.js"></script>-->

<!-- Mathjax -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="images/logo.png" alt="logo" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="1-introduction.html"><a href="1-introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-a-very-short-introduction-to-r-and-rstudio.html"><a href="1-1-a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-ittsraf.html"><a href="2-ittsraf.html"><i class="fa fa-check"></i><b>2</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-using-regression-models-for-forecasting.html"><a href="2-1-using-regression-models-for-forecasting.html"><i class="fa fa-check"></i><b>2.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="2.2" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html"><i class="fa fa-check"></i><b>2.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-autoregressions.html"><a href="2-3-autoregressions.html"><i class="fa fa-check"></i><b>2.3</b> Autoregressions</a><ul>
<li><a href="2-3-autoregressions.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-4-cybtmpi.html"><a href="2-4-cybtmpi.html"><i class="fa fa-check"></i><b>2.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="2.5" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html"><i class="fa fa-check"></i><b>2.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="2-6-llsuic.html"><a href="2-6-llsuic.html"><i class="fa fa-check"></i><b>2.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="2.7" data-path="2-7-nit.html"><a href="2-7-nit.html"><i class="fa fa-check"></i><b>2.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="2.8" data-path="2-8-niib.html"><a href="2-8-niib.html"><i class="fa fa-check"></i><b>2.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="2.9" data-path="2-9-can-you-beat-the-market-part-ii.html"><a href="2-9-can-you-beat-the-market-part-ii.html"><i class="fa fa-check"></i><b>2.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="autoregressions" class="section level2">
<h2><span class="header-section-number">2.3</span> Autoregressions</h2>
<p>Autoregressive models are heavily used in economic forecasting. An autoregressive model relates a time series variable to its past values. This section discusses the basic ideas of autoregressions models, shows how they are estimated and discusses an application to forecasting GDP growth using <tt>R</tt>.</p>
<div id="the-first-order-autoregressive-model" class="section level4 unnumbered">
<h4>The First-Order Autoregressive Model</h4>
<p>It is intuitive that the immediate past of a variable should have power to predict its near future. The simplest autoregressive model uses only the most recent outcome of the time series observed to predict future values. For a time series <span class="math inline">\(Y_t\)</span> such a model is called a first-order autoregressive model, often abbreviated AR(1), where the 1 indicates that the order of autoregression is one:
<span class="math display">\[\begin{align*}
  Y_t = \beta_0 + \beta_1 Y_{t-1} + u_t
\end{align*}\]</span>
is the AR(1) population model of a time series <span class="math inline">\(Y_t\)</span>.</p>
<p>For the GDP growth series, an autoregressive model of order one uses only the information on GDP growth observed in the last quarter to predict a future growth rate. The first-order autoregression model of GDP growth can be estimated by computing OLS estimates in the regression of <span class="math inline">\(GDPGR_t\)</span> on <span class="math inline">\(GDPGR_{t-1}\)</span>,
<span class="math display" id="eq:GDPGRAR1">\[\begin{align}
  \widehat{GDPGR}_t = \hat\beta_0 + \hat\beta_1  GDPGR_{t-1}. \tag{2.1}
\end{align}\]</span>
Following the book we use data from 1962 to 2012 to estimate <a href="2-3-autoregressions.html#eq:GDPGRAR1">(2.1)</a>. This is easily done with the function <tt>ar.ols()</tt> from the package <tt>stats</tt>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="2-3-autoregressions.html#cb29-1"></a><span class="co"># subset data</span></span>
<span id="cb29-2"><a href="2-3-autoregressions.html#cb29-2"></a>GDPGRSub &lt;-<span class="st"> </span>GDPGrowth[<span class="st">&quot;1962::2012&quot;</span>]</span>
<span id="cb29-3"><a href="2-3-autoregressions.html#cb29-3"></a></span>
<span id="cb29-4"><a href="2-3-autoregressions.html#cb29-4"></a><span class="co"># estimate the model</span></span>
<span id="cb29-5"><a href="2-3-autoregressions.html#cb29-5"></a><span class="kw">ar.ols</span>(GDPGRSub, </span>
<span id="cb29-6"><a href="2-3-autoregressions.html#cb29-6"></a>       <span class="dt">order.max =</span> <span class="dv">1</span>, </span>
<span id="cb29-7"><a href="2-3-autoregressions.html#cb29-7"></a>       <span class="dt">demean =</span> F, </span>
<span id="cb29-8"><a href="2-3-autoregressions.html#cb29-8"></a>       <span class="dt">intercept =</span> T)</span></code></pre></div>
<pre><code>## 
## Call:
## ar.ols(x = GDPGRSub, order.max = 1, demean = F, intercept = T)
## 
## Coefficients:
##      1  
## 0.3384  
## 
## Intercept: 1.995 (0.2993) 
## 
## Order selected 1  sigma^2 estimated as  9.886</code></pre>
<p>We can check that the computations done by <tt>ar.ols()</tt> are the same as done by <tt>lm()</tt>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="2-3-autoregressions.html#cb31-1"></a><span class="co"># length of data set</span></span>
<span id="cb31-2"><a href="2-3-autoregressions.html#cb31-2"></a>N &lt;-<span class="kw">length</span>(GDPGRSub)</span>
<span id="cb31-3"><a href="2-3-autoregressions.html#cb31-3"></a></span>
<span id="cb31-4"><a href="2-3-autoregressions.html#cb31-4"></a>GDPGR_level &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(GDPGRSub[<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb31-5"><a href="2-3-autoregressions.html#cb31-5"></a>GDPGR_lags &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(GDPGRSub[<span class="op">-</span>N])</span>
<span id="cb31-6"><a href="2-3-autoregressions.html#cb31-6"></a></span>
<span id="cb31-7"><a href="2-3-autoregressions.html#cb31-7"></a><span class="co"># estimate the model</span></span>
<span id="cb31-8"><a href="2-3-autoregressions.html#cb31-8"></a>armod &lt;-<span class="st"> </span><span class="kw">lm</span>(GDPGR_level <span class="op">~</span><span class="st"> </span>GDPGR_lags)</span>
<span id="cb31-9"><a href="2-3-autoregressions.html#cb31-9"></a>armod</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = GDPGR_level ~ GDPGR_lags)
## 
## Coefficients:
## (Intercept)   GDPGR_lags  
##      1.9950       0.3384</code></pre>
<p>As usual, we may use <tt>coeftest()</tt> to obtain a robust summary on the estimated regression coefficients.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="2-3-autoregressions.html#cb33-1"></a><span class="co"># robust summary</span></span>
<span id="cb33-2"><a href="2-3-autoregressions.html#cb33-2"></a><span class="kw">coeftest</span>(armod, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 1.994986   0.351274  5.6793 4.691e-08 ***
## GDPGR_lags  0.338436   0.076188  4.4421 1.470e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Thus the estimated model is
<span class="math display" id="eq:gdpgrar1">\[\begin{align}
  \widehat{GDPGR}_t = \underset{(0.351)}{1.995} + \underset{(0.076)}{0.338} GDPGR_{t-1} \tag{2.2}.
\end{align}\]</span></p>
<p>We omit the first observation for <span class="math inline">\(GDPGR_{1962 \ Q1}\)</span> from the vector of the dependent variable since <span class="math inline">\(GDPGR_{1962 \ Q1 - 1} = GDPGR_{1961 \ Q4}\)</span>, is not included in the sample. Similarly, the last observation, <span class="math inline">\(GDPGR_{2012 \ Q4}\)</span>, is excluded from the predictor vector since the data does not include <span class="math inline">\(GDPGR_{2012 \ Q4 + 1} = GDPGR_{2013 \ Q1}\)</span>. Put differently, when estimating the model, one observation is lost because of the time series structure of the data.</p>
</div>
<div id="forecasts-and-forecast-errors" class="section level4 unnumbered">
<h4>Forecasts and Forecast Errors</h4>
<p>Suppose <span class="math inline">\(Y_t\)</span> follows an AR(1) model with an intercept and that you have an OLS estimate of the model on the basis of observations for <span class="math inline">\(T\)</span> periods. Then you may use the AR(1) model to obtain <span class="math inline">\(\widehat{Y}_{T+1\vert T}\)</span>, a forecast for <span class="math inline">\(Y_{T+1}\)</span> using data up to period <span class="math inline">\(T\)</span> where
<span class="math display">\[\begin{align*}
  \widehat{Y}_{T+1\vert T} = \hat{\beta}_0 + \hat{\beta}_1 Y_T.
\end{align*}\]</span></p>
<p>The forecast error is
<span class="math display">\[\begin{align*}
  \text{Forecast error} = Y_{T+1} - \widehat{Y}_{T+1\vert T}.
\end{align*}\]</span></p>
</div>
<div id="forecasts-and-predicted-values" class="section level4 unnumbered">
<h4>Forecasts and Predicted Values</h4>
<p>Forecasted values of <span class="math inline">\(Y_t\)</span> are <em>not</em> what we refer to as <em>OLS predicted values</em> of <span class="math inline">\(Y_t\)</span>. Also, the forecast error is <em>not</em> an OLS residual. Forecasts and forecast errors are obtained using <em>out-of-sample</em> values while predicted values and residuals are computed for <em>in-sample</em> values that were actually observed and used in estimating the model.</p>
<p>The root mean squared forecast error (RMSFE) measures the typical size of the forecast error and is defined as
<span class="math display">\[\begin{align*}
  RMSFE = \sqrt{E\left[\left(Y_{T+1} - \widehat{Y}_{T+1\vert T}\right)^2\right]}.
\end{align*}\]</span></p>
<p>The <span class="math inline">\(RMSFE\)</span> is composed of the future errors <span class="math inline">\(u_t\)</span> and the error made when estimating the coefficients. When the sample size is large, the former may be much larger than the latter so that <span class="math inline">\(RMSFE \approx \sqrt{Var()u_t}\)</span> which can be estimated by the standard error of the regression.</p>
</div>
<div id="application-to-gdp-growth" class="section level4 unnumbered">
<h4>Application to GDP Growth</h4>
<p>Using <a href="2-3-autoregressions.html#eq:gdpgrar1">(2.2)</a>, the estimated AR(1) model of GDP growth, we perform the forecast for GDP growth for 2013:Q1 (remember that the model was estimated using data for periods 1962:Q1 - 2012:Q4, so 2013:Q1 is an out-of-sample period). Plugging <span class="math inline">\(GDPGR_{2012:Q4} \approx 0.15\)</span> into <a href="2-3-autoregressions.html#eq:gdpgrar1">(2.2)</a>,</p>
<p><span class="math display">\[\begin{align*}
  \widehat{GDPGR}_{2013:Q1} = 1.995 + 0.348 \cdot 0.15 = 2.047.
\end{align*}\]</span></p>
<p>The function <tt>forecast()</tt> from the <tt>forecast</tt> package has some useful features for forecasting time series data.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="2-3-autoregressions.html#cb35-1"></a><span class="kw">library</span>(forecast)</span>
<span id="cb35-2"><a href="2-3-autoregressions.html#cb35-2"></a></span>
<span id="cb35-3"><a href="2-3-autoregressions.html#cb35-3"></a><span class="co"># assign GDP growth rate in 2012:Q4</span></span>
<span id="cb35-4"><a href="2-3-autoregressions.html#cb35-4"></a>new &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="st">&quot;GDPGR_lags&quot;</span> =<span class="st"> </span>GDPGR_level[N<span class="dv">-1</span>])</span>
<span id="cb35-5"><a href="2-3-autoregressions.html#cb35-5"></a></span>
<span id="cb35-6"><a href="2-3-autoregressions.html#cb35-6"></a><span class="co"># forecast GDP growth rate in 2013:Q1</span></span>
<span id="cb35-7"><a href="2-3-autoregressions.html#cb35-7"></a><span class="kw">forecast</span>(armod, <span class="dt">newdata =</span> new)</span></code></pre></div>
<pre><code>##   Point Forecast     Lo 80    Hi 80     Lo 95    Hi 95
## 1       2.044155 -2.036225 6.124534 -4.213414 8.301723</code></pre>
<p>Using <tt>forecast()</tt>produces the same point forecast of about 2.0, along with <span class="math inline">\(80\%\)</span> and <span class="math inline">\(95\%\)</span> forecast intervals, see section <a href="2-5-apatadlm.html#apatadlm">2.5</a>. We conclude that our AR(1) model forecasts GDP growth to be <span class="math inline">\(2\%\)</span> in 2013:Q1.</p>
<p>How accurate is this forecast? The forecast error is quite large: <span class="math inline">\(GDPGR_{2013:Q1} \approx 1.1\%\)</span> while our forecast is <span class="math inline">\(2\%\)</span>.
Second, by calling <code>summary(armod)</code> shows that the model explains only little of the variation in the growth rate of GDP and the <span class="math inline">\(SER\)</span> is about <span class="math inline">\(3.16\)</span>. Leaving aside forecast uncertainty due to estimation of the model coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, the <span class="math inline">\(RMSFE\)</span> must be at least <span class="math inline">\(3.16\%\)</span>, the estimate of the standard deviation of the errors. We conclude that this forecast is pretty inaccurate.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="2-3-autoregressions.html#cb37-1"></a><span class="co"># compute the forecast error</span></span>
<span id="cb37-2"><a href="2-3-autoregressions.html#cb37-2"></a><span class="kw">forecast</span>(armod, <span class="dt">newdata =</span> new)<span class="op">$</span>mean <span class="op">-</span><span class="st"> </span>GDPGrowth[<span class="st">&quot;2013&quot;</span>][<span class="dv">1</span>]</span></code></pre></div>
<pre><code>##                 x
## 2013 Q1 0.9049532</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="2-3-autoregressions.html#cb39-1"></a><span class="co"># R^2</span></span>
<span id="cb39-2"><a href="2-3-autoregressions.html#cb39-2"></a><span class="kw">summary</span>(armod)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1149576</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="2-3-autoregressions.html#cb41-1"></a><span class="co"># SER</span></span>
<span id="cb41-2"><a href="2-3-autoregressions.html#cb41-2"></a><span class="kw">summary</span>(armod)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 3.15979</code></pre>
</div>
<div id="autoregressive-models-of-order-p" class="section level3 unnumbered">
<h3>Autoregressive Models of Order <span class="math inline">\(p\)</span></h3>
<p>For forecasting GDP growth, the AR(<span class="math inline">\(1\)</span>) model <a href="2-3-autoregressions.html#eq:gdpgrar1">(2.2)</a> disregards any information in the past of the series that is more distant than one period. An AR(<span class="math inline">\(p\)</span>) model incorporates the information of <span class="math inline">\(p\)</span> lags of the series. The idea is explained in Key Concept 14.3.</p>
<div id="KC14.3" class="keyconcept">
<h3 class="right">
Key Concept 14.3
</h3>
<h3 class="left">
Autoregressions
</h3>
<p>
An AR(<span class="math inline">\(p\)</span>) model assumes that a time series <span class="math inline">\(Y_t\)</span> can be modeld by a linear function of the first <span class="math inline">\(p\)</span> of its lagged values.
<span class="math display">\[\begin{align*}
  Y_t = \beta_0 + \beta_1 Y_{t-1} + \beta_2 Y_{t-2} + \dots + \beta_p Y_{t-p} + u_t
\end{align*}\]</span>
is an autoregressive model of order <span class="math inline">\(p\)</span> where <span class="math inline">\(E(u_t\vert Y_{t-1}, Y_{t-2}, \dots,Y_{t-p})=0\)</span>.
</p>
</div>
<p>Following the book, we estimate an AR(<span class="math inline">\(2\)</span>) model of the GDP growth series from 1962:Q1 to 2012:Q4.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="2-3-autoregressions.html#cb43-1"></a><span class="co"># estimate the AR(2) model</span></span>
<span id="cb43-2"><a href="2-3-autoregressions.html#cb43-2"></a>GDPGR_AR2 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">ts</span>(GDPGR_level) <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">ts</span>(GDPGR_level)) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">ts</span>(GDPGR_level), <span class="dv">2</span>))</span>
<span id="cb43-3"><a href="2-3-autoregressions.html#cb43-3"></a></span>
<span id="cb43-4"><a href="2-3-autoregressions.html#cb43-4"></a><span class="kw">coeftest</span>(GDPGR_AR2, <span class="dt">vcov. =</span> sandwich)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                       Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)           1.631747   0.402023  4.0588 7.096e-05 ***
## L(ts(GDPGR_level))    0.277787   0.079250  3.5052 0.0005643 ***
## L(ts(GDPGR_level), 2) 0.179269   0.079951  2.2422 0.0260560 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimation yields
<span class="math display" id="eq:GDPGRAR2">\[\begin{align}
  \widehat{GDPGR}_t = \underset{(0.40)}{1.63} + \underset{(0.08)}{0.28} GDPGR_{t-1} + \underset{(0.08)}{0.18} GDPGR_{t-1}. \tag{2.3}
\end{align}\]</span>
We see that the coefficient on the second lag is significantly different from zero. The fit improves slightly: <span class="math inline">\(\bar{R}^2\)</span> grows from <span class="math inline">\(0.11\)</span> for the AR(<span class="math inline">\(1\)</span>) model to about <span class="math inline">\(0.14\)</span> and the <span class="math inline">\(SER\)</span> reduces to <span class="math inline">\(3.13\)</span>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="2-3-autoregressions.html#cb45-1"></a><span class="co"># R^2</span></span>
<span id="cb45-2"><a href="2-3-autoregressions.html#cb45-2"></a><span class="kw">summary</span>(GDPGR_AR2)<span class="op">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.1425484</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="2-3-autoregressions.html#cb47-1"></a><span class="co"># SER</span></span>
<span id="cb47-2"><a href="2-3-autoregressions.html#cb47-2"></a><span class="kw">summary</span>(GDPGR_AR2)<span class="op">$</span>sigma</span></code></pre></div>
<pre><code>## [1] 3.132122</code></pre>
<p>We may use the AR(<span class="math inline">\(2\)</span>) model to obtain a forecast for GDP growth in 2013:Q1 in the same manner as for the AR(1) model.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="2-3-autoregressions.html#cb49-1"></a><span class="co"># AR(2) forecast of GDP growth in 2013:Q1 </span></span>
<span id="cb49-2"><a href="2-3-autoregressions.html#cb49-2"></a>forecast &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;2013:Q1&quot;</span> =<span class="st"> </span><span class="kw">coef</span>(GDPGR_AR2) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, GDPGR_level[N<span class="dv">-1</span>], GDPGR_level[N<span class="dv">-2</span>]))</span></code></pre></div>
<p>This leads to a forecast error of roughly <span class="math inline">\(-1\%\)</span>.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="2-3-autoregressions.html#cb50-1"></a><span class="co"># compute AR(2) forecast error </span></span>
<span id="cb50-2"><a href="2-3-autoregressions.html#cb50-2"></a>GDPGrowth[<span class="st">&quot;2013&quot;</span>][<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>forecast</span></code></pre></div>
<pre><code>##                 x
## 2013 Q1 -1.025358</code></pre>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-2-tsdasc.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="2-4-cybtmpi.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/mca91/EconometricsWithR/edit/master/14-ch14.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["ITER.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
