<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.5 Additional Predictors and The ADL Model | Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="2.5 Additional Predictors and The ADL Model | Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://www.econometrics-with-r.org/" />
  <meta property="og:image" content="https://www.econometrics-with-r.org/images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="mca91/EconometricsWithR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.5 Additional Predictors and The ADL Model | Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="https://www.econometrics-with-r.org/images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer" />


<meta name="date" content="2019-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="2-4-cybtmpi.html">
<link rel="next" href="2-6-llsuic.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!--<script src="js/hideOutput.js"></script>-->

<!-- Mathjax -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="images/logo.png" alt="logo" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="1-introduction.html"><a href="1-introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-a-very-short-introduction-to-r-and-rstudio.html"><a href="1-1-a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-ittsraf.html"><a href="2-ittsraf.html"><i class="fa fa-check"></i><b>2</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-using-regression-models-for-forecasting.html"><a href="2-1-using-regression-models-for-forecasting.html"><i class="fa fa-check"></i><b>2.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="2.2" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html"><i class="fa fa-check"></i><b>2.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-autoregressions.html"><a href="2-3-autoregressions.html"><i class="fa fa-check"></i><b>2.3</b> Autoregressions</a><ul>
<li><a href="2-3-autoregressions.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-4-cybtmpi.html"><a href="2-4-cybtmpi.html"><i class="fa fa-check"></i><b>2.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="2.5" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html"><i class="fa fa-check"></i><b>2.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="2-6-llsuic.html"><a href="2-6-llsuic.html"><i class="fa fa-check"></i><b>2.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="2.7" data-path="2-7-nit.html"><a href="2-7-nit.html"><i class="fa fa-check"></i><b>2.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="2.8" data-path="2-8-niib.html"><a href="2-8-niib.html"><i class="fa fa-check"></i><b>2.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="2.9" data-path="2-9-can-you-beat-the-market-part-ii.html"><a href="2-9-can-you-beat-the-market-part-ii.html"><i class="fa fa-check"></i><b>2.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="apatadlm" class="section level2">
<h2><span class="header-section-number">2.5</span> Additional Predictors and The ADL Model</h2>
<p>Instead of only using the dependent variable’s lags as predictors, an autoregressive distributed lag (ADL) model also uses lags of other variables for forecasting. The general ADL model is summarized in Key Concept 14.4:</p>
<div id="KC14.4" class="keyconcept">
<h3 class="right">
Key Concept 14.4
</h3>
<h3 class="left">
The Autoregressive Distributed Lag Model
</h3>
<p>
An ADL(<span class="math inline">\(p\)</span>,<span class="math inline">\(q\)</span>) model assumes that a time series <span class="math inline">\(Y_t\)</span> can be represented by a linear function of <span class="math inline">\(p\)</span> of its lagged values and <span class="math inline">\(q\)</span> lags of another time series <span class="math inline">\(X_t\)</span>:
<span class="math display">\[\begin{align*}
  Y_t =&amp; \, \beta_0 + \beta_1 Y_{t-1} + \beta_2 Y_{t-2} + \dots + \beta_p Y_{t-p} \\ 
      &amp;+ \, \delta_1 X_{t-1} + \delta_2 X_{t-2} + \dots + \delta_q X_{t-q} X_{t-q} + u_t.
\end{align*}\]</span>
is an <em>autoregressive distributed lag model</em> with <span class="math inline">\(p\)</span> lags of <span class="math inline">\(Y_t\)</span> and <span class="math inline">\(q\)</span> lags of <span class="math inline">\(X_t\)</span> where <span class="math display">\[E(u_t\vert Y_{t-1}, Y_{t-2}, \dots, X_{t-1}, X_{t-2}, \dots)=0.\]</span>
</p>
</div>
<div id="forecasting-gdp-growth-using-the-term-spread" class="section level4 unnumbered">
<h4>Forecasting GDP Growth Using the Term Spread</h4>
<p>Interest rates on long-term and short term treasury bonds are closely linked to macroeconomic conditions. While interest rates on both types of bonds have the same long-run tendencies, they behave quite differently in the short run.
The difference in interest rates of two bonds with distinct maturity is called the <em>term spread</em>.</p>
<p>The following code chunks reproduce Figure 14.3 of the book which displays interest rates of 10-year U.S. Treasury bonds and 3-months U.S. Treasury bills from 1960 to 2012.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="2-5-apatadlm.html#cb57-1"></a><span class="co"># 3-months Treasury bills interest rate</span></span>
<span id="cb57-2"><a href="2-5-apatadlm.html#cb57-2"></a>TB3MS &lt;-<span class="st"> </span><span class="kw">xts</span>(USMacroSWQ<span class="op">$</span>TB3MS, USMacroSWQ<span class="op">$</span>Date)[<span class="st">&quot;1960::2012&quot;</span>]</span>
<span id="cb57-3"><a href="2-5-apatadlm.html#cb57-3"></a></span>
<span id="cb57-4"><a href="2-5-apatadlm.html#cb57-4"></a><span class="co"># 10-years Treasury bonds interest rate</span></span>
<span id="cb57-5"><a href="2-5-apatadlm.html#cb57-5"></a>TB10YS &lt;-<span class="st"> </span><span class="kw">xts</span>(USMacroSWQ<span class="op">$</span>GS10, USMacroSWQ<span class="op">$</span>Date)[<span class="st">&quot;1960::2012&quot;</span>]</span>
<span id="cb57-6"><a href="2-5-apatadlm.html#cb57-6"></a></span>
<span id="cb57-7"><a href="2-5-apatadlm.html#cb57-7"></a><span class="co"># term spread</span></span>
<span id="cb57-8"><a href="2-5-apatadlm.html#cb57-8"></a>TSpread &lt;-<span class="st"> </span>TB10YS <span class="op">-</span><span class="st"> </span>TB3MS</span></code></pre></div>
<div class="unfolded">
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="2-5-apatadlm.html#cb58-1"></a><span class="co"># reproduce Figure 14.2 (a) of the book</span></span>
<span id="cb58-2"><a href="2-5-apatadlm.html#cb58-2"></a><span class="kw">plot</span>(<span class="kw">merge</span>(<span class="kw">as.zoo</span>(TB3MS), <span class="kw">as.zoo</span>(TB10YS)), </span>
<span id="cb58-3"><a href="2-5-apatadlm.html#cb58-3"></a>     <span class="dt">plot.type =</span> <span class="st">&quot;single&quot;</span>, </span>
<span id="cb58-4"><a href="2-5-apatadlm.html#cb58-4"></a>     <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;steelblue&quot;</span>),</span>
<span id="cb58-5"><a href="2-5-apatadlm.html#cb58-5"></a>     <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb58-6"><a href="2-5-apatadlm.html#cb58-6"></a>     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb58-7"><a href="2-5-apatadlm.html#cb58-7"></a>     <span class="dt">ylab =</span> <span class="st">&quot;Percent per annum&quot;</span>,</span>
<span id="cb58-8"><a href="2-5-apatadlm.html#cb58-8"></a>     <span class="dt">main =</span> <span class="st">&quot;Interest Rates&quot;</span>)</span>
<span id="cb58-9"><a href="2-5-apatadlm.html#cb58-9"></a></span>
<span id="cb58-10"><a href="2-5-apatadlm.html#cb58-10"></a><span class="co"># define function that transform years to class &#39;yearqtr&#39;</span></span>
<span id="cb58-11"><a href="2-5-apatadlm.html#cb58-11"></a>YToYQTR &lt;-<span class="st"> </span><span class="cf">function</span>(years) {</span>
<span id="cb58-12"><a href="2-5-apatadlm.html#cb58-12"></a>  <span class="kw">return</span>(</span>
<span id="cb58-13"><a href="2-5-apatadlm.html#cb58-13"></a>      <span class="kw">sort</span>(<span class="kw">as.yearqtr</span>(<span class="kw">sapply</span>(years, paste, <span class="kw">c</span>(<span class="st">&quot;Q1&quot;</span>, <span class="st">&quot;Q2&quot;</span>, <span class="st">&quot;Q3&quot;</span>, <span class="st">&quot;Q4&quot;</span>))))</span>
<span id="cb58-14"><a href="2-5-apatadlm.html#cb58-14"></a>  )</span>
<span id="cb58-15"><a href="2-5-apatadlm.html#cb58-15"></a>}</span>
<span id="cb58-16"><a href="2-5-apatadlm.html#cb58-16"></a></span>
<span id="cb58-17"><a href="2-5-apatadlm.html#cb58-17"></a><span class="co"># recessions</span></span>
<span id="cb58-18"><a href="2-5-apatadlm.html#cb58-18"></a>recessions &lt;-<span class="st"> </span><span class="kw">YToYQTR</span>(<span class="kw">c</span>(<span class="dv">1961</span><span class="op">:</span><span class="dv">1962</span>, <span class="dv">1970</span>, <span class="dv">1974</span><span class="op">:</span><span class="dv">1975</span>, <span class="dv">1980</span><span class="op">:</span><span class="dv">1982</span>, <span class="dv">1990</span><span class="op">:</span><span class="dv">1991</span>, <span class="dv">2001</span>, <span class="dv">2007</span><span class="op">:</span><span class="dv">2008</span>))</span>
<span id="cb58-19"><a href="2-5-apatadlm.html#cb58-19"></a>          </span>
<span id="cb58-20"><a href="2-5-apatadlm.html#cb58-20"></a><span class="co"># add color shading for recessions</span></span>
<span id="cb58-21"><a href="2-5-apatadlm.html#cb58-21"></a><span class="kw">xblocks</span>(<span class="kw">time</span>(<span class="kw">as.zoo</span>(TB3MS)), </span>
<span id="cb58-22"><a href="2-5-apatadlm.html#cb58-22"></a>        <span class="kw">c</span>(<span class="kw">time</span>(TB3MS) <span class="op">%in%</span><span class="st"> </span>recessions), </span>
<span id="cb58-23"><a href="2-5-apatadlm.html#cb58-23"></a>        <span class="dt">col =</span> <span class="kw">alpha</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.3</span>))</span>
<span id="cb58-24"><a href="2-5-apatadlm.html#cb58-24"></a></span>
<span id="cb58-25"><a href="2-5-apatadlm.html#cb58-25"></a><span class="co"># add a legend</span></span>
<span id="cb58-26"><a href="2-5-apatadlm.html#cb58-26"></a><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, </span>
<span id="cb58-27"><a href="2-5-apatadlm.html#cb58-27"></a>       <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;TB3MS&quot;</span>, <span class="st">&quot;TB10YS&quot;</span>),</span>
<span id="cb58-28"><a href="2-5-apatadlm.html#cb58-28"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;steelblue&quot;</span>),</span>
<span id="cb58-29"><a href="2-5-apatadlm.html#cb58-29"></a>       <span class="dt">lwd =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-54-1.png" width="80%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="2-5-apatadlm.html#cb59-1"></a><span class="co"># reproduce Figure 14.2 (b) of the book</span></span>
<span id="cb59-2"><a href="2-5-apatadlm.html#cb59-2"></a><span class="kw">plot</span>(<span class="kw">as.zoo</span>(TSpread), </span>
<span id="cb59-3"><a href="2-5-apatadlm.html#cb59-3"></a>     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>,</span>
<span id="cb59-4"><a href="2-5-apatadlm.html#cb59-4"></a>     <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb59-5"><a href="2-5-apatadlm.html#cb59-5"></a>     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb59-6"><a href="2-5-apatadlm.html#cb59-6"></a>     <span class="dt">ylab =</span> <span class="st">&quot;Percent per annum&quot;</span>,</span>
<span id="cb59-7"><a href="2-5-apatadlm.html#cb59-7"></a>     <span class="dt">main =</span> <span class="st">&quot;Term Spread&quot;</span>)</span>
<span id="cb59-8"><a href="2-5-apatadlm.html#cb59-8"></a></span>
<span id="cb59-9"><a href="2-5-apatadlm.html#cb59-9"></a><span class="co"># add color shading for recessions</span></span>
<span id="cb59-10"><a href="2-5-apatadlm.html#cb59-10"></a><span class="kw">xblocks</span>(<span class="kw">time</span>(<span class="kw">as.zoo</span>(TB3MS)), </span>
<span id="cb59-11"><a href="2-5-apatadlm.html#cb59-11"></a>        <span class="kw">c</span>(<span class="kw">time</span>(TB3MS) <span class="op">%in%</span><span class="st"> </span>recessions), </span>
<span id="cb59-12"><a href="2-5-apatadlm.html#cb59-12"></a>        <span class="dt">col =</span> <span class="kw">alpha</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.3</span>))</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-54-2.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p>Before recessions, the gap between interest rates on long-term bonds and short term bills narrows and consequently the term spread declines drastically towards zero or even becomes negative in times of economic stress. This information might be used to improve GDP growth forecasts of future.</p>
<p>We check this by estimating an ADL(<span class="math inline">\(2\)</span>, <span class="math inline">\(1\)</span>) model and an ADL(<span class="math inline">\(2\)</span>, <span class="math inline">\(2\)</span>) model of the GDP growth rate using lags of GDP growth and lags of the term spread as regressors. We then use both models for forecasting GDP growth in 2013:Q1.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="2-5-apatadlm.html#cb60-1"></a><span class="co"># convert growth and spread series to ts objects</span></span>
<span id="cb60-2"><a href="2-5-apatadlm.html#cb60-2"></a>GDPGrowth_ts &lt;-<span class="st"> </span><span class="kw">ts</span>(GDPGrowth, </span>
<span id="cb60-3"><a href="2-5-apatadlm.html#cb60-3"></a>                  <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1960</span>, <span class="dv">1</span>), </span>
<span id="cb60-4"><a href="2-5-apatadlm.html#cb60-4"></a>                  <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">4</span>), </span>
<span id="cb60-5"><a href="2-5-apatadlm.html#cb60-5"></a>                  <span class="dt">frequency =</span> <span class="dv">4</span>)</span>
<span id="cb60-6"><a href="2-5-apatadlm.html#cb60-6"></a></span>
<span id="cb60-7"><a href="2-5-apatadlm.html#cb60-7"></a>TSpread_ts &lt;-<span class="st"> </span><span class="kw">ts</span>(TSpread, </span>
<span id="cb60-8"><a href="2-5-apatadlm.html#cb60-8"></a>                <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1960</span>, <span class="dv">1</span>), </span>
<span id="cb60-9"><a href="2-5-apatadlm.html#cb60-9"></a>                <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>), </span>
<span id="cb60-10"><a href="2-5-apatadlm.html#cb60-10"></a>                <span class="dt">frequency =</span> <span class="dv">4</span>)</span>
<span id="cb60-11"><a href="2-5-apatadlm.html#cb60-11"></a></span>
<span id="cb60-12"><a href="2-5-apatadlm.html#cb60-12"></a><span class="co"># join both ts objects</span></span>
<span id="cb60-13"><a href="2-5-apatadlm.html#cb60-13"></a>ADLdata &lt;-<span class="st"> </span><span class="kw">ts.union</span>(GDPGrowth_ts, TSpread_ts)</span></code></pre></div>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="2-5-apatadlm.html#cb61-1"></a><span class="co"># estimate the ADL(2,1) model of GDP growth</span></span>
<span id="cb61-2"><a href="2-5-apatadlm.html#cb61-2"></a>GDPGR_ADL21 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(GDPGrowth_ts <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth_ts) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth_ts, <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread_ts), </span>
<span id="cb61-3"><a href="2-5-apatadlm.html#cb61-3"></a>      <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))</span>
<span id="cb61-4"><a href="2-5-apatadlm.html#cb61-4"></a></span>
<span id="cb61-5"><a href="2-5-apatadlm.html#cb61-5"></a><span class="kw">coeftest</span>(GDPGR_ADL21, <span class="dt">vcov. =</span> sandwich)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                    Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)        0.954990   0.486976  1.9611 0.051260 . 
## L(GDPGrowth_ts)    0.267729   0.082562  3.2428 0.001387 **
## L(GDPGrowth_ts, 2) 0.192370   0.077683  2.4763 0.014104 * 
## L(TSpread_ts)      0.444047   0.182637  2.4313 0.015925 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated equation of the ADL(<span class="math inline">\(2\)</span>, <span class="math inline">\(1\)</span>) model is
<span class="math display" id="eq:gdpgradl21">\[\begin{align}
  \widehat{GDPGR}_t = \underset{(0.49)}{0.96} + \underset{(0.08)}{0.26} GDPGR_{t-1} + \underset{(0.08)}{0.19} GDPGR_{t-2} + \underset{(0.18)}{0.44} TSpread_{t-1} \tag{2.4}
\end{align}\]</span></p>
<p>All coefficients are significant at the level of <span class="math inline">\(5\%\)</span>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="2-5-apatadlm.html#cb63-1"></a><span class="co"># 2012:Q3 / 2012:Q4 data on GDP growth and term spread</span></span>
<span id="cb63-2"><a href="2-5-apatadlm.html#cb63-2"></a>subset &lt;-<span class="st"> </span><span class="kw">window</span>(ADLdata, <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">3</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))</span>
<span id="cb63-3"><a href="2-5-apatadlm.html#cb63-3"></a></span>
<span id="cb63-4"><a href="2-5-apatadlm.html#cb63-4"></a><span class="co"># ADL(2,1) GDP growth forecast for 2013:Q1</span></span>
<span id="cb63-5"><a href="2-5-apatadlm.html#cb63-5"></a>ADL21_forecast &lt;-<span class="st"> </span><span class="kw">coef</span>(GDPGR_ADL21) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, subset[<span class="dv">2</span>, <span class="dv">1</span>], subset[<span class="dv">1</span>, <span class="dv">1</span>], subset[<span class="dv">2</span>, <span class="dv">2</span>])</span>
<span id="cb63-6"><a href="2-5-apatadlm.html#cb63-6"></a>ADL21_forecast</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 2.241689</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="2-5-apatadlm.html#cb65-1"></a><span class="co"># compute the forecast error</span></span>
<span id="cb65-2"><a href="2-5-apatadlm.html#cb65-2"></a><span class="kw">window</span>(GDPGrowth_ts, <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">1</span>)) <span class="op">-</span><span class="st"> </span>ADL21_forecast</span></code></pre></div>
<pre><code>##           Qtr1
## 2013 -1.102487</code></pre>
<p>Model <a href="2-5-apatadlm.html#eq:gdpgradl21">(2.4)</a> predicts the GDP growth in 2013:Q1 to be <span class="math inline">\(2.24\%\)</span> which leads to a forecast error of <span class="math inline">\(-1.10\%\)</span>.</p>
<p>We estimate the ADL(<span class="math inline">\(2\)</span>,<span class="math inline">\(2\)</span>) specification to see whether adding additional information on past term spread improves the forecast.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="2-5-apatadlm.html#cb67-1"></a><span class="co"># estimate the ADL(2,2) model of GDP growth</span></span>
<span id="cb67-2"><a href="2-5-apatadlm.html#cb67-2"></a>GDPGR_ADL22 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(GDPGrowth_ts <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth_ts) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth_ts, <span class="dv">2</span>) </span>
<span id="cb67-3"><a href="2-5-apatadlm.html#cb67-3"></a>                     <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread_ts) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread_ts, <span class="dv">2</span>), </span>
<span id="cb67-4"><a href="2-5-apatadlm.html#cb67-4"></a>                     <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))</span>
<span id="cb67-5"><a href="2-5-apatadlm.html#cb67-5"></a></span>
<span id="cb67-6"><a href="2-5-apatadlm.html#cb67-6"></a><span class="kw">coeftest</span>(GDPGR_ADL22, <span class="dt">vcov. =</span> sandwich)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                     Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)         0.967967   0.472470  2.0487 0.041800 * 
## L(GDPGrowth_ts)     0.243175   0.077836  3.1242 0.002049 **
## L(GDPGrowth_ts, 2)  0.177070   0.077027  2.2988 0.022555 * 
## L(TSpread_ts)      -0.139554   0.422162 -0.3306 0.741317   
## L(TSpread_ts, 2)    0.656347   0.429802  1.5271 0.128326   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We obtain
<span class="math display" id="eq:gdpgradl22">\[\begin{align}
  \begin{split}
    \widehat{GDPGR}_t =&amp; \underset{(0.47)}{0.98} + \underset{(0.08)}{0.24} GDPGR_{t-1} \\
    &amp; + \underset{(0.08)}{0.18} GDPGR_{t-2} -\underset{(0.42)}{0.14} TSpread_{t-1} + \underset{(0.43)}{0.66} TSpread_{t-2}.
  \end{split} \tag{2.5}
\end{align}\]</span></p>
<p>The coefficients on both lags of the term spread are not significant at the <span class="math inline">\(10\%\)</span> level.</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="2-5-apatadlm.html#cb69-1"></a><span class="co"># ADL(2,2) GDP growth forecast for 2013:Q1</span></span>
<span id="cb69-2"><a href="2-5-apatadlm.html#cb69-2"></a>ADL22_forecast &lt;-<span class="st"> </span><span class="kw">coef</span>(GDPGR_ADL22) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, subset[<span class="dv">2</span>, <span class="dv">1</span>], subset[<span class="dv">1</span>, <span class="dv">1</span>], subset[<span class="dv">2</span>, <span class="dv">2</span>], subset[<span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb69-3"><a href="2-5-apatadlm.html#cb69-3"></a>ADL22_forecast</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 2.274407</code></pre>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="2-5-apatadlm.html#cb71-1"></a><span class="co"># compute the forecast error</span></span>
<span id="cb71-2"><a href="2-5-apatadlm.html#cb71-2"></a><span class="kw">window</span>(GDPGrowth_ts, <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">1</span>)) <span class="op">-</span><span class="st"> </span>ADL22_forecast</span></code></pre></div>
<pre><code>##           Qtr1
## 2013 -1.135206</code></pre>
<p>The ADL(<span class="math inline">\(2\)</span>,<span class="math inline">\(2\)</span>) forecast of GDP growth in 2013:Q1 is <span class="math inline">\(2.27\%\)</span> which implies a forecast error of <span class="math inline">\(1.14\%\)</span>.</p>
<p>Do the ADL models <a href="2-5-apatadlm.html#eq:gdpgradl21">(2.4)</a> and <a href="2-5-apatadlm.html#eq:gdpgradl22">(2.5)</a> improve upon the simple AR(<span class="math inline">\(2\)</span>) model <a href="2-3-autoregressions.html#eq:GDPGRAR2">(2.3)</a>? The answer is yes: while <span class="math inline">\(SER\)</span> and <span class="math inline">\(\bar{R}^2\)</span> improve only slightly, an <span class="math inline">\(F\)</span>-test on the term spread coefficients in <a href="2-5-apatadlm.html#eq:gdpgradl22">(2.5)</a> provides evidence that the model does better in explaining GDP growth than the AR(<span class="math inline">\(2\)</span>) model as the hypothesis that both coefficients are zero cannot be rejected at the level of <span class="math inline">\(5\%\)</span>.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="2-5-apatadlm.html#cb73-1"></a><span class="co"># compare adj. R2</span></span>
<span id="cb73-2"><a href="2-5-apatadlm.html#cb73-2"></a><span class="kw">c</span>(<span class="st">&quot;Adj.R2 AR(2)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_AR2)<span class="op">$</span>r.squared,</span>
<span id="cb73-3"><a href="2-5-apatadlm.html#cb73-3"></a>  <span class="st">&quot;Adj.R2 ADL(2,1)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_ADL21)<span class="op">$</span>r.squared,</span>
<span id="cb73-4"><a href="2-5-apatadlm.html#cb73-4"></a>  <span class="st">&quot;Adj.R2 ADL(2,2)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_ADL22)<span class="op">$</span>r.squared)</span></code></pre></div>
<pre><code>##    Adj.R2 AR(2) Adj.R2 ADL(2,1) Adj.R2 ADL(2,2) 
##       0.1425484       0.1743996       0.1855245</code></pre>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="2-5-apatadlm.html#cb75-1"></a><span class="co"># compare SER</span></span>
<span id="cb75-2"><a href="2-5-apatadlm.html#cb75-2"></a><span class="kw">c</span>(<span class="st">&quot;SER AR(2)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_AR2)<span class="op">$</span>sigma,</span>
<span id="cb75-3"><a href="2-5-apatadlm.html#cb75-3"></a>  <span class="st">&quot;SER ADL(2,1)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_ADL21)<span class="op">$</span>sigma,</span>
<span id="cb75-4"><a href="2-5-apatadlm.html#cb75-4"></a>  <span class="st">&quot;SER ADL(2,2)&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(GDPGR_ADL22)<span class="op">$</span>sigma)</span></code></pre></div>
<pre><code>##    SER AR(2) SER ADL(2,1) SER ADL(2,2) 
##     3.132122     3.070760     3.057655</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="2-5-apatadlm.html#cb77-1"></a><span class="co"># F-test on coefficients of term spread</span></span>
<span id="cb77-2"><a href="2-5-apatadlm.html#cb77-2"></a><span class="kw">linearHypothesis</span>(GDPGR_ADL22, </span>
<span id="cb77-3"><a href="2-5-apatadlm.html#cb77-3"></a>                 <span class="kw">c</span>(<span class="st">&quot;L(TSpread_ts)=0&quot;</span>, <span class="st">&quot;L(TSpread_ts, 2)=0&quot;</span>),</span>
<span id="cb77-4"><a href="2-5-apatadlm.html#cb77-4"></a>                 <span class="dt">vcov. =</span> sandwich)</span></code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## L(TSpread_ts) = 0
## L(TSpread_ts, 2) = 0
## 
## Model 1: restricted model
## Model 2: GDPGrowth_ts ~ L(GDPGrowth_ts) + L(GDPGrowth_ts, 2) + L(TSpread_ts) + 
##     L(TSpread_ts, 2)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F  Pr(&gt;F)  
## 1    201                    
## 2    199  2 4.4344 0.01306 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
<div id="stationarity" class="section level4 unnumbered">
<h4>Stationarity</h4>
<p>In general, forecasts can be improved by using multiple predictors — just as in cross-sectional regression. When constructing time series models one should take into account whether the variables are <em>stationary</em> or <em>nonstationary</em>. Key Concept 14.5 explains what stationarity is.</p>
<div id="KC14.5" class="keyconcept">
<h3 class="right">
Key Concept 14.5
</h3>
<h3 class="left">
Stationarity
</h3>
<p>A time series <span class="math inline">\(Y_t\)</span> is stationary if its probability distribution is time independent, that is the joint distribution of <span class="math inline">\(Y_{s+1}, Y_{s+2},\dots,Y_{s+T}\)</span> does not change as <span class="math inline">\(s\)</span> is varied, regardless of <span class="math inline">\(T\)</span>.</p>
<p>Similarly, two time series <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> are <em>jointly stationary</em> if the joint distribution of <span class="math inline">\((X_{s+1},Y_{s+1}, X_{s+2},Y_{s+2} \dots, X_{s+T},Y_{s+T})\)</span> does not depend on <span class="math inline">\(s\)</span>, regardless of <span class="math inline">\(T\)</span>.</p>
<p>Stationarity makes it easier to learn about the characteristics of past data.</p>
</div>
</div>
<div id="time-series-regression-with-multiple-predictors" class="section level4 unnumbered">
<h4>Time Series Regression with Multiple Predictors</h4>
<p>The concept of stationarity is a key assumption in the general time series regression model with multiple predictors. Key Concept 14.6 lays out this model and its assumptions.</p>
<div id="KC14.6" class="keyconcept">
<h3 class="right">
Key Concept 14.6
</h3>
<h3 class="left">
Time Series Regression with Multiple Predictors
</h3>
<p>The general time series regression model extends the ADL model such that multiple regressors and their lags are included. It uses <span class="math inline">\(p\)</span> lags of the dependent variable and <span class="math inline">\(q_l\)</span> lags of <span class="math inline">\(l\)</span> additional predictors where <span class="math inline">\(l=1,\dots,k\)</span>:</p>
<p><span class="math display">\[\begin{equation}
  \begin{aligned}
  Y_t =&amp;  \beta_0 + \beta_1 Y_{t-1} + \beta_2 Y_{t-2} + \dots + \beta_{p} Y_{t-p} \\
      &amp;+  \delta_{11} X_{1,t-1} + \delta_{12} X_{1,t-2} + \dots + \delta_{1q} X_{1,t-q} \\
      &amp;+  \dots \\
      &amp;+  \delta_{k1} X_{k,t-1} + \delta_{k2} X_{k,t-2} + \dots + \delta_{kq} X_{k,t-q} \\
      &amp;+  u_t 
  \end{aligned}
\end{equation}\]</span></p>
<p>For estimation we make the following assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>The error term <span class="math inline">\(u_t\)</span> has conditional mean zero given all regressors and their lags: <span class="math display">\[E(u_t\vert Y_{t-1}, Y_{t-2}, \dots, X_{1,t-1}, X_{1,t-2} \dots, X_{k,t-1}, X_{k,t-2}, \dots)\]</span> This assumption is an extension of the conditional mean zero assumption used for AR and ADL models and guarantees that the general time series regression model stated above gives the best forecast of <span class="math inline">\(Y_t\)</span> given its lags, the additional regressors <span class="math inline">\(X_{1,t},\dots,X_{k,t}\)</span> and their lags.</p></li>
<li><p>The i.i.d. assumption for cross-sectional data is not (entirely) meaningful for time series data. We replace it by the following assumption witch consists of two parts:</p>
<ol style="list-style-type: lower-alpha">
<li><p>The <span class="math inline">\((Y_{t}, X_{1,t}, \dots, X_{k,t})\)</span> have a stationary distribution (the “identically distributed” part of the i.i.d. assumption for cross-setional data). If this does not hold, forecasts <em>may</em> be biased and inference <em>can</em> be strongly misleading.</p></li>
<li><p><span class="math inline">\((Y_{t}, X_{1,t}, \dots, X_{k,t})\)</span> and <span class="math inline">\((Y_{t-j}, X_{1,t-j}, \dots, X_{k,t-j})\)</span> become independent as <span class="math inline">\(j\)</span> gets large (the “idependently” distributed part of the i.i.d. assumption for cross-sectional data). This assumption is also called <em>weak dependence</em>. It ensures that the WLLN and the CLT hold in large samples.</p></li>
</ol></li>
<li><p>Large outliers are unlikely: <span class="math inline">\(E(X_{1,t}^4), E(X_{2,t}^4), \dots, E(X_{k,t}^4)\)</span> and <span class="math inline">\(E(Y_t^4)\)</span> have nonzero, finite fourth moments.</p></li>
<li><p>No perfect multicollinearity.</p></li>
</ol>
</div>
<p>Since many economic time series appear to be nonstationary, assumption two of Key Concept 14.6 is a crucial one in applied macroeconomics and finance which is why statistical test for stationarity or nonstationarity have been developed. Chapters <a href="2-6-llsuic.html#llsuic">2.6</a> and <a href="2-7-nit.html#nit">2.7</a> are devoted to this topic.</p>
</div>
<div id="statistical-inference-and-the-granger-causality-test" class="section level4 unnumbered">
<h4>Statistical inference and the Granger causality test</h4>
<p>If a <span class="math inline">\(X\)</span> is a useful predictor for <span class="math inline">\(Y\)</span>, in a regression of <span class="math inline">\(Y_t\)</span> on lags of its own and lags of <span class="math inline">\(X_t\)</span>, not all of the coefficients on the lags on <span class="math inline">\(X_t\)</span> are zero. This concept is called <em>Granger causality</em> and is an interesting hypothesis to test. Key Concept 14.7 summarizes the idea.</p>
<div id="KC14.7" class="keyconcept">
<h3 class="right">
Key Concept 14.7
</h3>
<h3 class="left">
Granger Causality Tests
</h3>
<p>The Granger causality test <span class="citation">Granger (<a href="#ref-granger1969" role="doc-biblioref">1969</a>)</span> is an <span class="math inline">\(F\)</span> test of the null hypothesis that <em>all</em> lags of a variable <span class="math inline">\(X\)</span> included in a time series regression model do not have predictive power for <span class="math inline">\(Y_t\)</span>. The Granger causality test does not test whether <span class="math inline">\(X\)</span> actually <em>causes</em> <span class="math inline">\(Y\)</span> but whether the included lags are informative in terms of predicting <span class="math inline">\(Y\)</span>.</p>
</div>
<p>We have already performed a Granger causality test on the coefficients of term spread in <a href="2-5-apatadlm.html#eq:gdpgradl22">(2.5)</a>, the ADL(<span class="math inline">\(2\)</span>,<span class="math inline">\(2\)</span>) model of GDP growth and concluded that at least one of the first two lags of term spread has predictive power for GDP growth.</p>
</div>
<div id="forecast-uncertainty-and-forecast-intervals" class="section level3 unnumbered">
<h3>Forecast Uncertainty and Forecast Intervals</h3>
<p>In general, it is good practice to report a measure of the uncertainty when presenting results that are affected by the latter. Uncertainty is particularly of interest when forecasting a time series. For example, consider a simple ADL<span class="math inline">\((1,1)\)</span> model
<span class="math display">\[\begin{align*}
  Y_t = \beta_0 + \beta_1 Y_{t-1} + \delta_1 X_{t-1} + u_t
\end{align*}\]</span>
where <span class="math inline">\(u_t\)</span> is a homoskedastic error term. The forecast error is
<span class="math display">\[\begin{align*}
  Y_{T+1} - \widehat{Y}_{T+1\vert T} = u_{T+1} - \left[(\widehat{\beta}_0 - \beta_0) + (\widehat{\beta}_1 - \beta_1) Y_T + (\widehat{\delta_1} - \delta_1) X_T \right].
\end{align*}\]</span>
The mean squared forecast error (MSFE) and the RMFSE are
<span class="math display">\[\begin{align*}
  MFSE =&amp; \, E\left[(Y_{T+1} - \widehat{Y}_{T+1\vert T})^2 \right] \\
       =&amp; \, \sigma_u^2 + Var\left[ (\widehat{\beta}_0 - \beta_0) + (\widehat{\beta}_1 - \beta_1) Y_T + (\widehat{\delta_1} - \delta_1) X_T \right], \\
  RMFSE =&amp; \, \sqrt{\sigma_u^2 + Var\left[ (\widehat{\beta}_0 - \beta_0) + (\widehat{\beta}_1 - \beta_1) Y_T + (\widehat{\delta_1} - \delta_1) X_T \right]}.
\end{align*}\]</span></p>
<p>A <span class="math inline">\(95\%\)</span> forecast interval is an interval that covers the true value of <span class="math inline">\(Y_{T+1}\)</span> in <span class="math inline">\(95\%\)</span> of repeated applications. There is a major difference in computing a confidence interval and a forecast interval: when computing a confidence interval of a point estimate we use large sample approximations that are justified by the CLT and thus are valid for a large range of error term distributions. For computation of a forecast interval of <span class="math inline">\(Y_{T+1}\)</span>, however, we must make an additional assumption about the distribution of <span class="math inline">\(u_{T+1}\)</span>, the error term in period <span class="math inline">\(T+1\)</span>. Assuming that <span class="math inline">\(u_{T+1}\)</span> is normally distributed one can construct a <span class="math inline">\(95\%\)</span> <em>forecast interval</em> for <span class="math inline">\(Y_{T+1}\)</span> using <span class="math inline">\(SE(Y_{T+1} - \widehat{Y}_{T+1\vert T})\)</span>, an estimate of the RMSFE:
<span class="math display">\[\begin{align*}
  \widehat{Y}_{T+1\vert T} \pm 1.96 \cdot SE(Y_{T+1} - \widehat{Y}_{T+1\vert T})
\end{align*}\]</span>
Of course, the computation gets more complicated when the error term is heteroskedastic or if we are interested in computing a forecast interval for <span class="math inline">\(T+s, s&gt;1\)</span>.</p>
<p>In some applications it is useful to report multiple forecast intervals for subsequent periods, see the box <em>The River of Blood</em> on p. 592 of the book. These can be visualized in a so-called fan chart. We will not replicate the fan chart presented in Figure 14.2 of book because the underlying model is by far more complex than the simple AR and ADL models treated here. Instead, in the example below we use simulated time series data and estimate an AR(<span class="math inline">\(2\)</span>) model which is then used for forecasting the subsequent <span class="math inline">\(25\)</span> future outcomes of the series.</p>
<div class="unfolded">
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="2-5-apatadlm.html#cb79-1"></a><span class="co"># set seed</span></span>
<span id="cb79-2"><a href="2-5-apatadlm.html#cb79-2"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb79-3"><a href="2-5-apatadlm.html#cb79-3"></a></span>
<span id="cb79-4"><a href="2-5-apatadlm.html#cb79-4"></a><span class="co"># simulate the time series</span></span>
<span id="cb79-5"><a href="2-5-apatadlm.html#cb79-5"></a>Y &lt;-<span class="st"> </span><span class="kw">arima.sim</span>(<span class="kw">list</span>(<span class="dt">order =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>), <span class="dt">ar =</span> <span class="kw">c</span>(<span class="fl">0.2</span>, <span class="fl">0.2</span>)),  <span class="dt">n =</span> <span class="dv">200</span>)</span>
<span id="cb79-6"><a href="2-5-apatadlm.html#cb79-6"></a></span>
<span id="cb79-7"><a href="2-5-apatadlm.html#cb79-7"></a><span class="co"># estimate an AR(2) model using &#39;arima()&#39;, see ?arima</span></span>
<span id="cb79-8"><a href="2-5-apatadlm.html#cb79-8"></a>model &lt;-<span class="st"> </span><span class="kw">arima</span>(Y, <span class="dt">order =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb79-9"><a href="2-5-apatadlm.html#cb79-9"></a></span>
<span id="cb79-10"><a href="2-5-apatadlm.html#cb79-10"></a><span class="co"># compute points forecasts and prediction intervals for the next 25 periods</span></span>
<span id="cb79-11"><a href="2-5-apatadlm.html#cb79-11"></a>fc &lt;-<span class="st"> </span><span class="kw">forecast</span>(model, <span class="dt">h =</span> <span class="dv">25</span>, <span class="dt">level =</span> <span class="kw">seq</span>(<span class="dv">5</span>, <span class="dv">99</span>, <span class="dv">10</span>))</span>
<span id="cb79-12"><a href="2-5-apatadlm.html#cb79-12"></a></span>
<span id="cb79-13"><a href="2-5-apatadlm.html#cb79-13"></a><span class="co"># plot a fan chart</span></span>
<span id="cb79-14"><a href="2-5-apatadlm.html#cb79-14"></a><span class="kw">plot</span>(fc, </span>
<span id="cb79-15"><a href="2-5-apatadlm.html#cb79-15"></a>     <span class="dt">main =</span> <span class="st">&quot;Forecast Fan Chart for AR(2) Model of Simulated Data&quot;</span>, </span>
<span id="cb79-16"><a href="2-5-apatadlm.html#cb79-16"></a>     <span class="dt">showgap =</span> F, </span>
<span id="cb79-17"><a href="2-5-apatadlm.html#cb79-17"></a>     <span class="dt">fcol =</span> <span class="st">&quot;red&quot;</span>,</span>
<span id="cb79-18"><a href="2-5-apatadlm.html#cb79-18"></a>     <span class="dt">flty =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-67-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p><tt>arima.sim()</tt> simulates autoregressive integrated moving average (ARIMA) models. AR models belong to this class of models. We use <tt>list(order = c(2, 0, 0), ar = c(0.2, 0.2))</tt> so the DGP is <span class="math display">\[Y_t = 0.2 Y_{t-1} + 0.2 Y_{t-2} + u_t.\]</span></p>
<p>We choose <tt>level = seq(5, 99, 10)</tt> in the call of <tt>forecast()</tt> such that forecast intervals with levels <span class="math inline">\(5\%, 15\%, \dots, 95\%\)</span> are computed for each point forecast of the series.</p>
<p>The dashed red line shows point forecasts of the series for the next 25 periods based on an <span class="math inline">\(ADL(1,1)\)</span> model and the shaded areas represent the prediction intervals. The degree of shading indicates the level of the prediction interval. The darkest of the blue bands displays the <span class="math inline">\(5\%\)</span> forecast intervals and the color fades towards grey as the level of the intervals increases.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-granger1969">
<p>Granger, C. W. (1969). Investigating Causal Relations by Econometric Models and Cross-Spectral Methods. <em>Econometrica</em>, <em>37</em>(3), 424–438.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-4-cybtmpi.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="2-6-llsuic.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/mca91/EconometricsWithR/edit/master/14-ch14.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["ITER.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
