<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.7 Nonstationarity I: Trends | Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="2.7 Nonstationarity I: Trends | Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://www.econometrics-with-r.org/" />
  <meta property="og:image" content="https://www.econometrics-with-r.org/images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="mca91/EconometricsWithR" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.7 Nonstationarity I: Trends | Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programming and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="https://www.econometrics-with-r.org/images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer" />


<meta name="date" content="2019-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="2-6-llsuic.html">
<link rel="next" href="2-8-niib.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!--<script src="js/hideOutput.js"></script>-->

<!-- Mathjax -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><center><img src="images/logo.png" alt="logo" width="50%" height="50%"style="margin: 15px 0 0 0"></center></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="1-introduction.html"><a href="1-introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="1-1-a-very-short-introduction-to-r-and-rstudio.html"><a href="1-1-a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-ittsraf.html"><a href="2-ittsraf.html"><i class="fa fa-check"></i><b>2</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="2.1" data-path="2-1-using-regression-models-for-forecasting.html"><a href="2-1-using-regression-models-for-forecasting.html"><i class="fa fa-check"></i><b>2.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="2.2" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html"><i class="fa fa-check"></i><b>2.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="2-2-tsdasc.html"><a href="2-2-tsdasc.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-3-autoregressions.html"><a href="2-3-autoregressions.html"><i class="fa fa-check"></i><b>2.3</b> Autoregressions</a><ul>
<li><a href="2-3-autoregressions.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-4-cybtmpi.html"><a href="2-4-cybtmpi.html"><i class="fa fa-check"></i><b>2.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="2.5" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html"><i class="fa fa-check"></i><b>2.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="2-5-apatadlm.html"><a href="2-5-apatadlm.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="2-6-llsuic.html"><a href="2-6-llsuic.html"><i class="fa fa-check"></i><b>2.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="2.7" data-path="2-7-nit.html"><a href="2-7-nit.html"><i class="fa fa-check"></i><b>2.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="2.8" data-path="2-8-niib.html"><a href="2-8-niib.html"><i class="fa fa-check"></i><b>2.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="2.9" data-path="2-9-can-you-beat-the-market-part-ii.html"><a href="2-9-can-you-beat-the-market-part-ii.html"><i class="fa fa-check"></i><b>2.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="nit" class="section level2">
<h2><span class="header-section-number">2.7</span> Nonstationarity I: Trends</h2>
<p>If a series is nonstationary, conventional hypothesis tests, confidence intervals and forecasts can be strongly misleading. The assumption of stationarity is violated if a series exhibits trends or breaks and the resulting complications in an econometric analysis depend on the specific type of the nonstationarity. This section focuses on time series that exhibit trends.</p>
<p>A series is said to exhibit a trend if it has a persistent long-term movement. One distinguishes between <em>deterministic</em> and <em>stochastic</em> trends.</p>
<ul>
<li><p>A trend is <em>deterministic</em> if it is a nonrandom function of time.</p></li>
<li><p>A trend is said to be <em>stochastic</em> if it is a random function of time.</p></li>
</ul>
<p>The figures we have produced in Chapter <a href="2-2-tsdasc.html#tsdasc">2.2</a> reveal that many economic time series show a trending behavior that is probably best modeled by stochastic trends. This is why the book focuses on the treatment of stochastic trends.</p>
<div id="the-random-walk-model-of-a-trend" class="section level4 unnumbered">
<h4>The Random Walk Model of a Trend</h4>
<p>The simplest way to model a time series <span class="math inline">\(Y_t\)</span> that has stochastic trend is the <em>random walk</em>
<span class="math display" id="eq:randomwalk">\[\begin{align}
  Y_t = Y_{t-1} + u_t, \tag{2.6}
\end{align}\]</span>
where the <span class="math inline">\(u_t\)</span> are i.i.d. errors with <span class="math inline">\(E(u_t\vert Y_{t-1}, Y_{t-2}, \dots) = 0\)</span>. Note that
<span class="math display">\[\begin{align*}
  E(Y_t\vert Y_{t-1}, Y_{t-2}\dots) =&amp; \, E(Y_{t-1}\vert Y_{t-1}, Y_{t-2}\dots) + E(u_t\vert Y_{t-1}, Y_{t-2}\dots) \\
  =&amp; \, Y_{t-1}
\end{align*}\]</span>
so the best forecast for <span class="math inline">\(Y_t\)</span> is yesterday’s observation <span class="math inline">\(Y_{t-1}\)</span>. Hence the difference between <span class="math inline">\(Y_t\)</span> and <span class="math inline">\(Y_{t-1}\)</span> is unpredictable. The path followed by <span class="math inline">\(Y_t\)</span> consists of random steps <span class="math inline">\(u_t\)</span>, hence it is called a random walk.</p>
<p>Assume that <span class="math inline">\(Y_0\)</span>, the starting value of the random walk is <span class="math inline">\(0\)</span>. Another way to write <a href="2-7-nit.html#eq:randomwalk">(2.6)</a> is
<span class="math display">\[\begin{align*}
  Y_0 =&amp; \, 0 \\
  Y_1 =&amp; \, 0 + u_1 \\
  Y_2 =&amp; \, 0 + u_1 + u_2 \\
  \vdots &amp; \, \\
  Y_t =&amp; \, \sum_{i=1}^t u_i.
\end{align*}\]</span>
Therefore we have
<span class="math display">\[\begin{align*}
  Var(Y_t) =&amp; \, Var(u_1 + u_2 + \dots + u_t) \\
           =&amp; \, t \sigma_u^2.
\end{align*}\]</span>
Thus the variance of a random walk depends on <span class="math inline">\(t\)</span> which violates the assumption presented in Key Concept 14.5: a random walk is nonstationary.</p>
<p>Obviously, <a href="2-7-nit.html#eq:randomwalk">(2.6)</a> is a special case of an AR(<span class="math inline">\(1\)</span>) model where <span class="math inline">\(\beta_1 = 1\)</span>. One can show that a time series that follows an AR(<span class="math inline">\(1\)</span>) model is stationary if <span class="math inline">\(\lvert\beta_1\rvert &lt; 1\)</span>. In a general AR(<span class="math inline">\(p\)</span>) model, stationarity is linked to the roots of the polynomial <span class="math display">\[1-\beta_1 z - \beta_2 z^2 - \beta_3 z^3 - \dots - \beta_p z^p.\]</span> If all roots are greater than <span class="math inline">\(1\)</span> in absolute value, the AR(<span class="math inline">\(p\)</span>) series is stationary. If at least one root equals <span class="math inline">\(1\)</span>, the AR(<span class="math inline">\(p\)</span>) is said to have a <em>unit root</em> and thus has a stochastic trend.</p>
<p>It is straightforward to simulate random walks in <tt>R</tt> using <tt>arima.sim()</tt>. The function <tt>matplot()</tt> is convenient for simple plots of the columns of a matrix.</p>
<div class="unfolded">
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="2-7-nit.html#cb91-1"></a><span class="co"># simulate and plot random walks starting at 0</span></span>
<span id="cb91-2"><a href="2-7-nit.html#cb91-2"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb91-3"><a href="2-7-nit.html#cb91-3"></a></span>
<span id="cb91-4"><a href="2-7-nit.html#cb91-4"></a>RWs &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">4</span>, </span>
<span id="cb91-5"><a href="2-7-nit.html#cb91-5"></a>            <span class="kw">arima.sim</span>(<span class="dt">model =</span> <span class="kw">list</span>(<span class="dt">order =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span> ,<span class="dv">0</span>)), <span class="dt">n =</span> <span class="dv">100</span>)))</span>
<span id="cb91-6"><a href="2-7-nit.html#cb91-6"></a></span>
<span id="cb91-7"><a href="2-7-nit.html#cb91-7"></a><span class="kw">matplot</span>(RWs, </span>
<span id="cb91-8"><a href="2-7-nit.html#cb91-8"></a>        <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb91-9"><a href="2-7-nit.html#cb91-9"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;orange&quot;</span>), </span>
<span id="cb91-10"><a href="2-7-nit.html#cb91-10"></a>        <span class="dt">lty =</span> <span class="dv">1</span>, </span>
<span id="cb91-11"><a href="2-7-nit.html#cb91-11"></a>        <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb91-12"><a href="2-7-nit.html#cb91-12"></a>        <span class="dt">main =</span> <span class="st">&quot;Four Random Walks&quot;</span>,</span>
<span id="cb91-13"><a href="2-7-nit.html#cb91-13"></a>        <span class="dt">xlab =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb91-14"><a href="2-7-nit.html#cb91-14"></a>        <span class="dt">ylab =</span> <span class="st">&quot;Value&quot;</span>)</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-73-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p>Adding a constant to <a href="2-7-nit.html#eq:randomwalk">(2.6)</a> yields
<span class="math display" id="eq:randomwalkdrift">\[\begin{align}
  Y_t = \beta_0 + Y_{t-1} + u_t \tag{2.7},
\end{align}\]</span>
a <em>random walk model with a drift</em> which allows to model the tendency of a series to move upwards or downwards. If <span class="math inline">\(\beta_0\)</span> is positive, the series drifts upwards and it follows a downward trend if <span class="math inline">\(\beta_0\)</span> is negative.</p>
<div class="unfolded">
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="2-7-nit.html#cb92-1"></a><span class="co"># simulate and plot random walks with drift</span></span>
<span id="cb92-2"><a href="2-7-nit.html#cb92-2"></a><span class="kw">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb92-3"><a href="2-7-nit.html#cb92-3"></a></span>
<span id="cb92-4"><a href="2-7-nit.html#cb92-4"></a>RWsd &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">4</span>, </span>
<span id="cb92-5"><a href="2-7-nit.html#cb92-5"></a>           <span class="kw">arima.sim</span>(<span class="dt">model =</span> <span class="kw">list</span>(<span class="dt">order =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)), </span>
<span id="cb92-6"><a href="2-7-nit.html#cb92-6"></a>                     <span class="dt">n =</span> <span class="dv">100</span>,</span>
<span id="cb92-7"><a href="2-7-nit.html#cb92-7"></a>                     <span class="dt">mean =</span> <span class="fl">-0.2</span>)))</span>
<span id="cb92-8"><a href="2-7-nit.html#cb92-8"></a></span>
<span id="cb92-9"><a href="2-7-nit.html#cb92-9"></a><span class="kw">matplot</span>(RWsd, </span>
<span id="cb92-10"><a href="2-7-nit.html#cb92-10"></a>        <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb92-11"><a href="2-7-nit.html#cb92-11"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;orange&quot;</span>), </span>
<span id="cb92-12"><a href="2-7-nit.html#cb92-12"></a>        <span class="dt">lty =</span> <span class="dv">1</span>, </span>
<span id="cb92-13"><a href="2-7-nit.html#cb92-13"></a>        <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb92-14"><a href="2-7-nit.html#cb92-14"></a>        <span class="dt">main =</span> <span class="st">&quot;Four Random Walks with Drift&quot;</span>,</span>
<span id="cb92-15"><a href="2-7-nit.html#cb92-15"></a>        <span class="dt">xlab =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb92-16"><a href="2-7-nit.html#cb92-16"></a>        <span class="dt">ylab =</span> <span class="st">&quot;Value&quot;</span>)</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-74-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="problems-caused-by-stochastic-trends" class="section level4 unnumbered">
<h4>Problems Caused by Stochastic Trends</h4>
<p>OLS estimation of the coefficients on regressors that have a stochastic trend is problematic because the distribution of the estimator and its <span class="math inline">\(t\)</span>-statistic is non-normal, even asymptotically. This has various consequences:</p>
<ul>
<li><p><strong>Downward bias of autoregressive coefficients</strong>:</p>
<p>If <span class="math inline">\(Y_t\)</span> is a random walk, <span class="math inline">\(\beta_1\)</span> can be consistently estimated by OLS but the estimator is biased toward zero. This bias is roughly <span class="math inline">\(E(\widehat{\beta}_1) \approx 1 - 5.3/T\)</span> which is substantial for sample sizes typically encountered in macroeconomics. This estimation bias causes forecasts of <span class="math inline">\(Y_t\)</span> to perform worse than a pure random walk model.</p></li>
<li><p><strong>Non-normally distributed <span class="math inline">\(t\)</span>-statistics</strong>:</p>
<p>The nonnormal distribution of the estimated coefficient of a stochastic regressor translates to a nonnormal distribution of its <span class="math inline">\(t\)</span>-statistic so that normal critical values are invalid and therefore usual confidence intervals and hypothesis tests are invalid, too, and the true distribution of the <span class="math inline">\(t\)</span>-statistic cannot be readily determined.</p></li>
<li><p><strong>Spurious Regression</strong>:</p>
<p>When two stochastically trending time series are regressed onto each other, the estimated relationship may appear highly significant using conventional normal critical values although the series are unrelated. This is what econometricians call a <em>spurious</em> relationship.</p></li>
</ul>
<p>As an example for spurious regression, consider again the green and the red random walks that we have simulated above. We know that there is no relationship between both series: they are generated independently of each other.</p>
<div class="unfolded">
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="2-7-nit.html#cb93-1"></a><span class="co"># plot spurious relationship</span></span>
<span id="cb93-2"><a href="2-7-nit.html#cb93-2"></a><span class="kw">matplot</span>(RWs[, <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">3</span>)], </span>
<span id="cb93-3"><a href="2-7-nit.html#cb93-3"></a>        <span class="dt">lty =</span> <span class="dv">1</span>,</span>
<span id="cb93-4"><a href="2-7-nit.html#cb93-4"></a>        <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb93-5"><a href="2-7-nit.html#cb93-5"></a>        <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,</span>
<span id="cb93-6"><a href="2-7-nit.html#cb93-6"></a>        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;darkred&quot;</span>),</span>
<span id="cb93-7"><a href="2-7-nit.html#cb93-7"></a>        <span class="dt">xlab =</span> <span class="st">&quot;Time&quot;</span>,</span>
<span id="cb93-8"><a href="2-7-nit.html#cb93-8"></a>        <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb93-9"><a href="2-7-nit.html#cb93-9"></a>        <span class="dt">main =</span> <span class="st">&quot;A Spurious Relationship&quot;</span>)    </span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-75-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p>Imagine we did not have this information and instead conjectured that the green series is useful for predicting the red series and thus end up estimating the ADL(<span class="math inline">\(0\)</span>,<span class="math inline">\(1\)</span>) model
<span class="math display">\[\begin{align*}
  Red_t = \beta_0 + \beta_1 Green_{t-1} + u_t.
\end{align*}\]</span></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="2-7-nit.html#cb94-1"></a><span class="co"># estimate spurious AR model</span></span>
<span id="cb94-2"><a href="2-7-nit.html#cb94-2"></a><span class="kw">summary</span>(<span class="kw">dynlm</span>(RWs[, <span class="dv">2</span>] <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(RWs[, <span class="dv">3</span>])))<span class="op">$</span>coefficients</span></code></pre></div>
<pre><code>##              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept) -3.459488  0.3635104 -9.516889 1.354156e-15
## L(RWs[, 3])  1.047195  0.1450874  7.217687 1.135828e-10</code></pre>
<p>The result is obviously spurious: the coefficient on <span class="math inline">\(Green_{t-1}\)</span> is estimated to be about <span class="math inline">\(1\)</span> and the <span class="math inline">\(p\)</span>-value of <span class="math inline">\(1.14 \cdot 10^{-10}\)</span> of the corresponding <span class="math inline">\(t\)</span>-test indicates that the coefficient is highly significant while its true value is in fact zero.</p>
<p>As an empirical example, consider the U.S. unemployment rate and the Japanese industrial production. Both series show an upward trending behavior from the mid-1960s through the early 1980s.</p>
<div class="unfolded">
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="2-7-nit.html#cb96-1"></a><span class="co"># plot U.S. unemployment rate &amp; Japanese industrial production</span></span>
<span id="cb96-2"><a href="2-7-nit.html#cb96-2"></a><span class="kw">plot</span>(<span class="kw">merge</span>(<span class="kw">as.zoo</span>(USUnemp), <span class="kw">as.zoo</span>(JPIndProd)), </span>
<span id="cb96-3"><a href="2-7-nit.html#cb96-3"></a>     <span class="dt">plot.type =</span> <span class="st">&quot;single&quot;</span>, </span>
<span id="cb96-4"><a href="2-7-nit.html#cb96-4"></a>     <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;steelblue&quot;</span>),</span>
<span id="cb96-5"><a href="2-7-nit.html#cb96-5"></a>     <span class="dt">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb96-6"><a href="2-7-nit.html#cb96-6"></a>     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,</span>
<span id="cb96-7"><a href="2-7-nit.html#cb96-7"></a>     <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb96-8"><a href="2-7-nit.html#cb96-8"></a>     <span class="dt">main =</span> <span class="st">&quot;Spurious Regression: Macroeconomic Time series&quot;</span>)</span>
<span id="cb96-9"><a href="2-7-nit.html#cb96-9"></a></span>
<span id="cb96-10"><a href="2-7-nit.html#cb96-10"></a><span class="co"># add a legend</span></span>
<span id="cb96-11"><a href="2-7-nit.html#cb96-11"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, </span>
<span id="cb96-12"><a href="2-7-nit.html#cb96-12"></a>       <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;USUnemp&quot;</span>, <span class="st">&quot;JPIndProd&quot;</span>),</span>
<span id="cb96-13"><a href="2-7-nit.html#cb96-13"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;steelblue&quot;</span>),</span>
<span id="cb96-14"><a href="2-7-nit.html#cb96-14"></a>       <span class="dt">lwd =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-77-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="2-7-nit.html#cb97-1"></a><span class="co"># estimate regression using data from 1962 to 1985</span></span>
<span id="cb97-2"><a href="2-7-nit.html#cb97-2"></a>SR_Unemp1 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">ts</span>(USUnemp[<span class="st">&quot;1962::1985&quot;</span>]) <span class="op">~</span><span class="st"> </span><span class="kw">ts</span>(JPIndProd[<span class="st">&quot;1962::1985&quot;</span>]))</span>
<span id="cb97-3"><a href="2-7-nit.html#cb97-3"></a><span class="kw">coeftest</span>(SR_Unemp1, <span class="dt">vcov =</span> sandwich)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)                 -2.37452    1.12041 -2.1193    0.0367 *  
## ts(JPIndProd[&quot;1962::1985&quot;])  2.22057    0.29233  7.5961 2.227e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>A simple regression of the U.S. unemployment rate on Japanese industrial production using data from 1962 to 1985 yields
<span class="math display" id="eq:urjpip1">\[\begin{align}
  \widehat{U.S. UR}_t = -\underset{(1.12)}{2.37} + \underset{(0.29)}{2.22} \log(JapaneseIP_t). \tag{2.8}
\end{align}\]</span>
This appears to be a significant relationship: the <span class="math inline">\(t\)</span>-statistic of the coefficient on <span class="math inline">\(\log(JapaneseIP_t)\)</span> is bigger than 7.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="2-7-nit.html#cb99-1"></a><span class="co"># Estimate regression using data from 1986 to 2012</span></span>
<span id="cb99-2"><a href="2-7-nit.html#cb99-2"></a>SR_Unemp2 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">ts</span>(USUnemp[<span class="st">&quot;1986::2012&quot;</span>]) <span class="op">~</span><span class="st"> </span><span class="kw">ts</span>(JPIndProd[<span class="st">&quot;1986::2012&quot;</span>]))</span>
<span id="cb99-3"><a href="2-7-nit.html#cb99-3"></a><span class="kw">coeftest</span>(SR_Unemp2, <span class="dt">vcov =</span> sandwich)</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)                  41.7763     5.4066  7.7270 6.596e-12 ***
## ts(JPIndProd[&quot;1986::2012&quot;])  -7.7771     1.1714 -6.6391 1.386e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>When estimating the same model, this time with data from 1986 to 2012, we obtain
<span class="math display" id="eq:urjpip2">\[\begin{align}
  \widehat{U.S. UR}_t = \underset{(5.41)}{41.78} -\underset{(1.17)}{7.78} \log(JapaneseIP)_t \tag{2.9}
\end{align}\]</span>
which surprisingly is quite different. <a href="2-7-nit.html#eq:urjpip1">(2.8)</a> indicates a moderate positive relationship, in contrast to the large negative coefficient in <a href="2-7-nit.html#eq:urjpip2">(2.9)</a>. This phenomenon can be attributed to stochastic trends in the series: since there is no economic reasoning that relates both trends, both regressions may be spurious.</p>
</div>
<div id="testing-for-a-unit-ar-root" class="section level4 unnumbered">
<h4>Testing for a Unit AR Root</h4>
<p>A formal test for a stochastic trend has been proposed by <span class="citation">Dickey &amp; Fuller (<a href="#ref-dickey1979" role="doc-biblioref">1979</a>)</span> which thus is termed the <em>Dickey-Fuller test</em>. As discussed above, a time series that follows an AR(<span class="math inline">\(1\)</span>) model with <span class="math inline">\(\beta_1 = 1\)</span> has a stochastic trend. Thus, the testing problem is
<span class="math display">\[\begin{align*}
  H_0: \beta_1 = 1 \ \ \ \text{vs.} \ \ \ H_1: \lvert\beta_1\rvert &lt; 1.
\end{align*}\]</span>
The null hypothesis is that the AR(<span class="math inline">\(1\)</span>) model has a unit root and the alternative hypothesis is that it is stationary. One often rewrites the AR(<span class="math inline">\(1\)</span>) model by subtracting <span class="math inline">\(Y_{t-1}\)</span> on both sides:
<span class="math display">\[\begin{align}
  Y_t = \beta_0 + \beta_1 Y_{t-1} + u_t \ \ \Leftrightarrow \ \ \Delta Y_t = \beta_0 + \delta Y_{t-1} + u_t \label{eq:dfmod}
\end{align}\]</span>
where <span class="math inline">\(\delta = \beta_1 - 1\)</span>. The testing problem then becomes
<span class="math display">\[\begin{align*}
  H_0: \delta = 0 \ \ \ \text{vs.} \ \ \ H_1: \delta &lt; 0
\end{align*}\]</span>
which is convenient since the corresponding test statistic is reported by many relevant <tt>R</tt> functions.<a href="references.html#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p>
<p>The Dickey-Fuller test can also be applied in an AR(<span class="math inline">\(p\)</span>) model. The <em>Augmented Dickey-Fuller (ADF) test</em> is summarized in Key Concept 14.8.</p>
<div id="KC14.8" class="keyconcept">
<h3 class="right">
Key Concept 14.8
</h3>
<h3 class="left">
The ADF Test for a Unit Root
</h3>
<p>
<p>Consider the regression
<span class="math display" id="eq:ADFreg1">\[\begin{align}
  \Delta Y_t = \beta_0 + \delta Y_{t-1} + \gamma_1 \Delta_1 Y_{t-1} + \gamma_2 \Delta Y_{t-2} + \dots + \gamma_p \Delta Y_{t-p} + u_t. \tag{2.10}
\end{align}\]</span></p>
<p>The ADF test for a unit autoregressive root tests the hypothesis <span class="math inline">\(H_0: \delta = 0\)</span> (stochastic trend) against the one-sided alternative <span class="math inline">\(H_1: \delta &lt; 0\)</span> (stationarity) using the usual OLS <span class="math inline">\(t\)</span>-statistic.</p>
<p>If it is assumed that <span class="math inline">\(Y_t\)</span> is stationary around a deterministic linear time trend, the model is augmented by the regressor <span class="math inline">\(t\)</span>:
<span class="math display" id="eq:ADFreg2">\[\begin{align}
  \Delta Y_t = \beta_0 + at + \delta Y_{t-1} + \gamma_1 \Delta_1 Y_{t-1} + \gamma_2 \Delta Y_{t-2} + \dots + \gamma_p \Delta Y_{t-p} + u_t,  \tag{2.11}
\end{align}\]</span>
where again <span class="math inline">\(H_0: \delta = 0\)</span> is tested against <span class="math inline">\(H_1: \delta &lt; 0\)</span>.</p>
<p>The optimal lag length <span class="math inline">\(p\)</span> can be estimated using information criteria. In <a href="2-7-nit.html#eq:ADFreg1">(2.10)</a>, <span class="math inline">\(p=0\)</span> (no lags of <span class="math inline">\(\Delta Y_t\)</span> are used as regressors) corresponds to a simple AR(<span class="math inline">\(1\)</span>).</p>
Under the null, the <span class="math inline">\(t\)</span>-statistic corresponding to <span class="math inline">\(H_0: \delta = 0\)</span> does not have a normal distribution. The critical values can only be obtained from simulation and differ for regressions <a href="2-7-nit.html#eq:ADFreg1">(2.10)</a> and <a href="2-7-nit.html#eq:ADFreg2">(2.11)</a> since the distribution of the ADF test statistic is sensitive to the deterministic components included in the regression.
</p>
</div>
</div>
<div id="critical-values-for-the-adf-statistic" class="section level4 unnumbered">
<h4>Critical Values for the ADF Statistic</h4>
<p>Key Concept 14.8 states that the critical values for the ADF test in the regressions <a href="2-7-nit.html#eq:ADFreg1">(2.10)</a> and <a href="2-7-nit.html#eq:ADFreg2">(2.11)</a> can only be determined using simulation. The idea of the simulation study is to simulate a large number of ADF test statistics and use them to estimate quantiles of their <em>asymptotic</em> distribution. This section shows how this can be done using <tt>R</tt>.</p>
<p>First, consider the following AR(<span class="math inline">\(1\)</span>) model with intercept
<span class="math display">\[\begin{align*}
  Y_t =&amp; \, \alpha + z_t, \ \ z_t = \rho z_{t-1} + u_t.
\end{align*}\]</span>
This can be written as
<span class="math display">\[\begin{align*}
  Y_t =&amp; \, (1-\rho) \alpha + \rho y_{t-1} + u_t,
\end{align*}\]</span>
i.e., <span class="math inline">\(Y_t\)</span> is a random walk without drift under the null <span class="math inline">\(\rho = 1\)</span>. One can show that <span class="math inline">\(Y_t\)</span> is a stationary process with mean <span class="math inline">\(\alpha\)</span> for <span class="math inline">\(\lvert\rho\rvert&lt;1\)</span>.</p>
<p>The procedure for simulating critical values of a unit root test using the <span class="math inline">\(t\)</span>-ratio of <span class="math inline">\(\delta\)</span> in () is as follows:</p>
<ul>
<li><p>Simulate <span class="math inline">\(N\)</span> random walks with <span class="math inline">\(n\)</span> observations using the data generating process
<span class="math display">\[\begin{align*}
Y_t =&amp; \, a + z_t, \ \ z_t = \rho z_{t-1} + u_t,
\end{align*}\]</span>
<span class="math inline">\(t=1,\dots,n\)</span> where <span class="math inline">\(N\)</span> and <span class="math inline">\(n\)</span> are large numbers, <span class="math inline">\(a\)</span> is a constant and <span class="math inline">\(u\)</span> is a zero mean error term.</p></li>
<li><p>For each random walk, estimate the regression
<span class="math display">\[\begin{align*}
\Delta Y_t =&amp; \, \beta_0 + \delta Y_{t-1} + u_t
\end{align*}\]</span>
and compute the ADF test statistic. Save all <span class="math inline">\(N\)</span> test statistics.</p></li>
<li><p>Estimate quantiles of the distribution of the ADF test statistic using the <span class="math inline">\(N\)</span> test statistics obtained from the simulation.</p></li>
</ul>
<p>For the case with drift <em>and</em> linear time trend we replace the data generating process by
<span class="math display">\[\begin{align}
  Y_t =&amp; \, a + b \cdot t + z_t, \ \ z_t = \rho z_{t-1} + u_t \label{eq:rwdt}
\end{align}\]</span>
where <span class="math inline">\(b \cdot t\)</span> is a linear time trend. <span class="math inline">\(Y_t\)</span> in () is a random walk with (without) drift if <span class="math inline">\(b\neq0\)</span> (<span class="math inline">\(b=0\)</span>) under the null of <span class="math inline">\(\rho=1\)</span> (can you show this?). We estimate the regression
<span class="math display">\[\begin{align*}
  \Delta Y_t =&amp; \, \beta_0 + \alpha \cdot t + \delta Y_{t-1} + u_t.
\end{align*}\]</span></p>
<p>Loosely speaking, the precision of the estimated quantiles depends on two factors: <span class="math inline">\(n\)</span>, the length of the underlying series and <span class="math inline">\(N\)</span>, the number of test statistics used. Since we are interested in estimating quantiles of the <em>asymptotic</em> distribution (the Dickey-Fuller distribution) of the ADF test statistic both using many observations and large number of simulated test statistics will increase the precision of the estimated quantiles. We choose <span class="math inline">\(n=N=1000\)</span> as the computational burden grows quickly with <span class="math inline">\(n\)</span> and <span class="math inline">\(N\)</span>.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="2-7-nit.html#cb101-1"></a><span class="co"># repetitions</span></span>
<span id="cb101-2"><a href="2-7-nit.html#cb101-2"></a>N &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb101-3"><a href="2-7-nit.html#cb101-3"></a></span>
<span id="cb101-4"><a href="2-7-nit.html#cb101-4"></a><span class="co"># observations</span></span>
<span id="cb101-5"><a href="2-7-nit.html#cb101-5"></a>n &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb101-6"><a href="2-7-nit.html#cb101-6"></a></span>
<span id="cb101-7"><a href="2-7-nit.html#cb101-7"></a><span class="co"># define constant, trend and rho</span></span>
<span id="cb101-8"><a href="2-7-nit.html#cb101-8"></a>drift &lt;-<span class="st"> </span><span class="fl">0.5</span></span>
<span id="cb101-9"><a href="2-7-nit.html#cb101-9"></a>trend &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span>n</span>
<span id="cb101-10"><a href="2-7-nit.html#cb101-10"></a>rho &lt;-<span class="st"> </span><span class="dv">1</span></span>
<span id="cb101-11"><a href="2-7-nit.html#cb101-11"></a></span>
<span id="cb101-12"><a href="2-7-nit.html#cb101-12"></a><span class="co"># function which simulates an AR(1) process</span></span>
<span id="cb101-13"><a href="2-7-nit.html#cb101-13"></a>AR1 &lt;-<span class="st"> </span><span class="cf">function</span>(rho) {</span>
<span id="cb101-14"><a href="2-7-nit.html#cb101-14"></a>  out &lt;-<span class="st"> </span><span class="kw">numeric</span>(n)</span>
<span id="cb101-15"><a href="2-7-nit.html#cb101-15"></a>  <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span>n) {</span>
<span id="cb101-16"><a href="2-7-nit.html#cb101-16"></a>    out[i] &lt;-<span class="st"> </span>rho <span class="op">*</span><span class="st"> </span>out[i<span class="dv">-1</span>] <span class="op">+</span><span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">1</span>)</span>
<span id="cb101-17"><a href="2-7-nit.html#cb101-17"></a>  }</span>
<span id="cb101-18"><a href="2-7-nit.html#cb101-18"></a>  <span class="kw">return</span>(out)</span>
<span id="cb101-19"><a href="2-7-nit.html#cb101-19"></a>}</span>
<span id="cb101-20"><a href="2-7-nit.html#cb101-20"></a></span>
<span id="cb101-21"><a href="2-7-nit.html#cb101-21"></a><span class="co"># simulate from DGP with constant </span></span>
<span id="cb101-22"><a href="2-7-nit.html#cb101-22"></a>RWD &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">replicate</span>(<span class="dt">n =</span> N, drift <span class="op">+</span><span class="st"> </span><span class="kw">AR1</span>(rho)))</span>
<span id="cb101-23"><a href="2-7-nit.html#cb101-23"></a></span>
<span id="cb101-24"><a href="2-7-nit.html#cb101-24"></a><span class="co"># compute ADF test statistics and store them in &#39;ADFD&#39;</span></span>
<span id="cb101-25"><a href="2-7-nit.html#cb101-25"></a>ADFD &lt;-<span class="st"> </span><span class="kw">numeric</span>(N)</span>
<span id="cb101-26"><a href="2-7-nit.html#cb101-26"></a></span>
<span id="cb101-27"><a href="2-7-nit.html#cb101-27"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(RWD)) {</span>
<span id="cb101-28"><a href="2-7-nit.html#cb101-28"></a>  ADFD[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(</span>
<span id="cb101-29"><a href="2-7-nit.html#cb101-29"></a>    <span class="kw">dynlm</span>(<span class="kw">diff</span>(RWD[, i], <span class="dv">1</span>) <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(RWD[, i], <span class="dv">1</span>)))<span class="op">$</span>coef[<span class="dv">2</span>, <span class="dv">3</span>]</span>
<span id="cb101-30"><a href="2-7-nit.html#cb101-30"></a>}</span>
<span id="cb101-31"><a href="2-7-nit.html#cb101-31"></a></span>
<span id="cb101-32"><a href="2-7-nit.html#cb101-32"></a><span class="co"># simulate from DGP with constant and trend</span></span>
<span id="cb101-33"><a href="2-7-nit.html#cb101-33"></a>RWDT &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">replicate</span>(<span class="dt">n =</span> N, drift <span class="op">+</span><span class="st"> </span>trend <span class="op">+</span><span class="st"> </span><span class="kw">AR1</span>(rho)))</span>
<span id="cb101-34"><a href="2-7-nit.html#cb101-34"></a></span>
<span id="cb101-35"><a href="2-7-nit.html#cb101-35"></a><span class="co"># compute ADF test statistics and store them in &#39;ADFDT&#39;</span></span>
<span id="cb101-36"><a href="2-7-nit.html#cb101-36"></a>ADFDT &lt;-<span class="st"> </span><span class="kw">numeric</span>(N)</span>
<span id="cb101-37"><a href="2-7-nit.html#cb101-37"></a></span>
<span id="cb101-38"><a href="2-7-nit.html#cb101-38"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(RWDT)) {</span>
<span id="cb101-39"><a href="2-7-nit.html#cb101-39"></a>  ADFDT[i] &lt;-<span class="st"> </span><span class="kw">summary</span>(</span>
<span id="cb101-40"><a href="2-7-nit.html#cb101-40"></a>    <span class="kw">dynlm</span>(<span class="kw">diff</span>(RWDT[, i], <span class="dv">1</span>) <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(RWDT[, i], <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">trend</span>(RWDT[, i]))</span>
<span id="cb101-41"><a href="2-7-nit.html#cb101-41"></a>  )<span class="op">$</span>coef[<span class="dv">2</span>, <span class="dv">3</span>]</span>
<span id="cb101-42"><a href="2-7-nit.html#cb101-42"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="2-7-nit.html#cb102-1"></a><span class="co"># estimate quantiles for ADF regression with a drift</span></span>
<span id="cb102-2"><a href="2-7-nit.html#cb102-2"></a><span class="kw">round</span>(<span class="kw">quantile</span>(ADFD, <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.05</span>, <span class="fl">0.01</span>)), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   10%    5%    1% 
## -2.62 -2.83 -3.39</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="2-7-nit.html#cb104-1"></a><span class="co"># estimate quantiles for ADF regression with drift and trend</span></span>
<span id="cb104-2"><a href="2-7-nit.html#cb104-2"></a><span class="kw">round</span>(<span class="kw">quantile</span>(ADFDT, <span class="kw">c</span>(<span class="fl">0.1</span>, <span class="fl">0.05</span>, <span class="fl">0.01</span>)), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##   10%    5%    1% 
## -3.11 -3.43 -3.97</code></pre>
<p>The estimated quantiles are close to the large-sample critical values of the ADF test statistic reported in Table 14.4 of the book.</p>
<table>
<caption><span id="tab:DFcrits">Table 2.2: </span> Large Sample Critical Values of ADF Test</caption>
<thead>
<tr class="header">
<th align="left">Deterministic Regressors</th>
<th align="left">10%</th>
<th align="left">5%</th>
<th align="left">1%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Intercept only</td>
<td align="left">-2.57</td>
<td align="left">-2.86</td>
<td align="left">-3.43</td>
</tr>
<tr class="even">
<td align="left">Intercept and time trend</td>
<td align="left">-3.12</td>
<td align="left">-3.41</td>
<td align="left">-3.96</td>
</tr>
</tbody>
</table>
<p>The results show that using standard normal critical values is erroneous: the 5% critical value of the standard normal distribution is <span class="math inline">\(-1.64\)</span>. For the Dickey-Fuller distributions the estimated critical values are <span class="math inline">\(-2.87\)</span> (drift) and <span class="math inline">\(-3.43\)</span> (drift and linear time trend). This implies that a true null (the series has a stochastic trend) would be rejected far too often if inappropriate normal critical values were used.</p>
<p>We may use the simulated test statistics for a graphical comparison of the standard normal density and (estimates of) both Dickey-Fuller densities.</p>
<div class="unfolded">
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="2-7-nit.html#cb106-1"></a><span class="co"># plot standard normal density</span></span>
<span id="cb106-2"><a href="2-7-nit.html#cb106-2"></a><span class="kw">curve</span>(<span class="kw">dnorm</span>(x), </span>
<span id="cb106-3"><a href="2-7-nit.html#cb106-3"></a>      <span class="dt">from =</span> <span class="dv">-6</span>, <span class="dt">to =</span> <span class="dv">3</span>, </span>
<span id="cb106-4"><a href="2-7-nit.html#cb106-4"></a>      <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.6</span>), </span>
<span id="cb106-5"><a href="2-7-nit.html#cb106-5"></a>      <span class="dt">lty =</span> <span class="dv">2</span>,</span>
<span id="cb106-6"><a href="2-7-nit.html#cb106-6"></a>      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>,</span>
<span id="cb106-7"><a href="2-7-nit.html#cb106-7"></a>      <span class="dt">xlab =</span> <span class="st">&quot;t-Statistic&quot;</span>,</span>
<span id="cb106-8"><a href="2-7-nit.html#cb106-8"></a>      <span class="dt">main =</span> <span class="st">&quot;Distributions of ADF Test Statistics&quot;</span>,</span>
<span id="cb106-9"><a href="2-7-nit.html#cb106-9"></a>      <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>, </span>
<span id="cb106-10"><a href="2-7-nit.html#cb106-10"></a>      <span class="dt">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb106-11"><a href="2-7-nit.html#cb106-11"></a></span>
<span id="cb106-12"><a href="2-7-nit.html#cb106-12"></a><span class="co"># plot density estimates of both Dickey-Fuller distributions</span></span>
<span id="cb106-13"><a href="2-7-nit.html#cb106-13"></a><span class="kw">lines</span>(<span class="kw">density</span>(ADFD), <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb106-14"><a href="2-7-nit.html#cb106-14"></a><span class="kw">lines</span>(<span class="kw">density</span>(ADFDT), <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</span>
<span id="cb106-15"><a href="2-7-nit.html#cb106-15"></a></span>
<span id="cb106-16"><a href="2-7-nit.html#cb106-16"></a><span class="co"># add a legend</span></span>
<span id="cb106-17"><a href="2-7-nit.html#cb106-17"></a><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, </span>
<span id="cb106-18"><a href="2-7-nit.html#cb106-18"></a>       <span class="kw">c</span>(<span class="st">&quot;N(0,1)&quot;</span>, <span class="st">&quot;Drift&quot;</span>, <span class="st">&quot;Drift+Trend&quot;</span>),</span>
<span id="cb106-19"><a href="2-7-nit.html#cb106-19"></a>       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;darkred&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>, <span class="st">&quot;blue&quot;</span>),</span>
<span id="cb106-20"><a href="2-7-nit.html#cb106-20"></a>       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb106-21"><a href="2-7-nit.html#cb106-21"></a>       <span class="dt">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-84-1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<p>The deviations from the standard normal distribution are significant: both Dickey-Fuller distributions are skewed to the left and have a heavier left tail than the standard normal distribution.</p>
</div>
<div id="does-u.s.-gdp-have-a-unit-root" class="section level4 unnumbered">
<h4>Does U.S. GDP Have a Unit Root?</h4>
<p>As an empirical example, we use the ADF test to assess whether there is a stochastic trend in U.S. GDP using the regression
<span class="math display">\[\begin{align*}
  \Delta\log(GDP_t) = \beta_0 + \alpha t + \beta_1 \log(GDP_{t-1}) + \beta_2 \Delta \log(GDP_{t-1}) + \beta_3 \Delta \log(GDP_{t-2}) + u_t.
\end{align*}\]</span></p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="2-7-nit.html#cb107-1"></a><span class="co"># generate log GDP series</span></span>
<span id="cb107-2"><a href="2-7-nit.html#cb107-2"></a>LogGDP &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">log</span>(GDP[<span class="st">&quot;1962::2012&quot;</span>]))</span>
<span id="cb107-3"><a href="2-7-nit.html#cb107-3"></a></span>
<span id="cb107-4"><a href="2-7-nit.html#cb107-4"></a><span class="co"># estimate the model</span></span>
<span id="cb107-5"><a href="2-7-nit.html#cb107-5"></a><span class="kw">coeftest</span>(</span>
<span id="cb107-6"><a href="2-7-nit.html#cb107-6"></a>  <span class="kw">dynlm</span>(<span class="kw">diff</span>(LogGDP) <span class="op">~</span><span class="st"> </span><span class="kw">trend</span>(LogGDP, <span class="dt">scale =</span> F) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(LogGDP) </span>
<span id="cb107-7"><a href="2-7-nit.html#cb107-7"></a>                     <span class="op">+</span><span class="st"> </span><span class="kw">diff</span>(<span class="kw">L</span>(LogGDP)) <span class="op">+</span><span class="st"> </span><span class="kw">diff</span>(<span class="kw">L</span>(LogGDP), <span class="dv">2</span>)))</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                             Estimate  Std. Error t value Pr(&gt;|t|)   
## (Intercept)               0.27877045  0.11793233  2.3638 0.019066 * 
## trend(LogGDP, scale = F)  0.00023818  0.00011090  2.1476 0.032970 * 
## L(LogGDP)                -0.03332452  0.01441436 -2.3119 0.021822 * 
## diff(L(LogGDP))           0.08317976  0.11295542  0.7364 0.462371   
## diff(L(LogGDP), 2)        0.18763384  0.07055574  2.6594 0.008476 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimation yields
<span class="math display">\[\begin{align*}
  \Delta\log(GDP_t) =&amp; \underset{(0.118)}{0.28} + \underset{(0.0001)}{0.0002} t -\underset{(0.014)}{0.033} \log(GDP_{t-1}) \\
   &amp; + \underset{(0.113)}{0.083} \Delta \log(GDP_{t-1}) + \underset{(0.071)}{0.188} \Delta \log(GDP_{t-2}) + u_t,
\end{align*}\]</span>
so the ADF test statistic is <span class="math inline">\(t=-0.033/0.014 = - 2.35\)</span>. The corresponding <span class="math inline">\(5\%\)</span> critical value from Table <a href="2-7-nit.html#tab:DFcrits">2.2</a> is <span class="math inline">\(-3.41\)</span> so we cannot reject the null hypothesis that <span class="math inline">\(\log(GDP)\)</span> has a stochastic trend in favor of the alternative that it is stationary around a deterministic linear time trend.</p>
<p>The ADF test can be done conveniently using <tt>ur.df()</tt> from the package <tt>urca</tt>.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="2-7-nit.html#cb109-1"></a><span class="co"># test for unit root in GDP using &#39;ur.df()&#39; from the package &#39;urca&#39;</span></span>
<span id="cb109-2"><a href="2-7-nit.html#cb109-2"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(LogGDP, </span>
<span id="cb109-3"><a href="2-7-nit.html#cb109-3"></a>              <span class="dt">type =</span> <span class="st">&quot;trend&quot;</span>, </span>
<span id="cb109-4"><a href="2-7-nit.html#cb109-4"></a>              <span class="dt">lags =</span> <span class="dv">2</span>, </span>
<span id="cb109-5"><a href="2-7-nit.html#cb109-5"></a>              <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.025580 -0.004109  0.000321  0.004869  0.032781 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.2790086  0.1180427   2.364 0.019076 *  
## z.lag.1     -0.0333245  0.0144144  -2.312 0.021822 *  
## tt           0.0002382  0.0001109   2.148 0.032970 *  
## z.diff.lag1  0.2708136  0.0697696   3.882 0.000142 ***
## z.diff.lag2  0.1876338  0.0705557   2.659 0.008476 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.007704 on 196 degrees of freedom
## Multiple R-squared:  0.1783, Adjusted R-squared:  0.1616 
## F-statistic: 10.63 on 4 and 196 DF,  p-value: 8.076e-08
## 
## 
## Value of test-statistic is: -2.3119 11.2558 4.267 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -3.99 -3.43 -3.13
## phi2  6.22  4.75  4.07
## phi3  8.43  6.49  5.47</code></pre>
<p>The first test statistic at the bottom of the output is the one we are interested in. The number of test statistics reported depends on the test regression. For <tt>type = “trend”</tt>, the second statistics corresponds to the test that there is no unit root and no time trend while the third one corresponds to a test of the hypothesis that there is a unit root, no time trend and no drift term.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-dickey1979">
<p>Dickey, D. A., &amp; Fuller, W. A. (1979). Distribution of the Estimators for Autoregressive Time Series with a Unit Root. <em>Journal of the American Statistical Association</em>, <em>74</em>(366), pp. 427–431.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="2-6-llsuic.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="2-8-niib.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/mca91/EconometricsWithR/edit/master/14-ch14.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["ITER.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
