<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Using R for Introduction to Econometrics</title>
  <meta name="description" content="Using <tt>R</tt> for Introduction to Econometrics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Using R for Introduction to Econometrics" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Using R for Introduction to Econometrics" />
  
  
  

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-07-29">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html">
<link rel="next" href="joint-hypothesis-testing-using-the-f-statistic.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="MathJax-2.7.2/MathJax.js?config=default"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>

<!-- datacamp-light-latest -->

<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>


<!-- <script src="js/d3.v3.min.js"></script>
<script src="js/leastsquares.js"></script>
<script src="js/d3functions.js"></script>
<script src="d3.slider.js"></script>
<script src="slrm.js"></script> -->


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">URFITE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="a-very-short-introduction-to-r-and-rstudio.html"><a href="a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="htaciimr.html"><a href="htaciimr.html"><i class="fa fa-check"></i><b>2</b> Hypothesis Tests and Confidence Intervals in Multiple Regression</a><ul>
<li class="chapter" data-level="2.1" data-path="hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html"><a href="hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html"><i class="fa fa-check"></i><b>2.1</b> Hypothesis Tests and Confidence Intervals for a Single Coefficient</a></li>
<li class="chapter" data-level="2.2" data-path="an-application-to-test-scores-and-the-student-teacher-ratio.html"><a href="an-application-to-test-scores-and-the-student-teacher-ratio.html"><i class="fa fa-check"></i><b>2.2</b> An Application to Test Scores and the Student-Teacher Ratio</a><ul>
<li class="chapter" data-level="" data-path="an-application-to-test-scores-and-the-student-teacher-ratio.html"><a href="an-application-to-test-scores-and-the-student-teacher-ratio.html#another-augmentation-of-the-model"><i class="fa fa-check"></i>Another Augmentation of the Model</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="joint-hypothesis-testing-using-the-f-statistic.html"><a href="joint-hypothesis-testing-using-the-f-statistic.html"><i class="fa fa-check"></i><b>2.3</b> Joint Hypothesis Testing Using the F-Statistic</a></li>
<li class="chapter" data-level="2.4" data-path="confidence-sets-for-multiple-coefficients.html"><a href="confidence-sets-for-multiple-coefficients.html"><i class="fa fa-check"></i><b>2.4</b> Confidence Sets for Multiple Coefficients</a></li>
<li class="chapter" data-level="2.5" data-path="model-specification-for-multiple-regression.html"><a href="model-specification-for-multiple-regression.html"><i class="fa fa-check"></i><b>2.5</b> Model Specification for Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="model-specification-for-multiple-regression.html"><a href="model-specification-for-multiple-regression.html#model-specification-in-theory-and-in-practice"><i class="fa fa-check"></i>Model Specification in Theory and in Practice</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="analysis-of-the-test-score-data-set.html"><a href="analysis-of-the-test-score-data-set.html"><i class="fa fa-check"></i><b>2.6</b> Analysis of the Test Score Data Set</a></li>
<li class="chapter" data-level="2.7" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>2.7</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using <tt>R</tt> for Introduction to Econometrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="an-application-to-test-scores-and-the-student-teacher-ratio" class="section level2">
<h2><span class="header-section-number">2.2</span> An Application to Test Scores and the Student-Teacher Ratio</h2>
<p>Let us take a look at the regression from Section <a href="#mofimr"><strong>??</strong></a> again.</p>
<p>Computing confidence intervals for individual coefficients in the multiple regression model proceeds as in the simple regression model using the function <tt>confint()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>english, <span class="dt">data =</span> CASchools)
<span class="kw">confint</span>(model)</code></pre></div>
<pre><code>##                   2.5 %      97.5 %
## (Intercept) 671.4640580 700.6004311
## size         -1.8487969  -0.3537944
## english      -0.7271113  -0.5724424</code></pre>
<p>To obtain confidence intervals at another level, say <span class="math inline">\(90\%\)</span>, just set the argument <tt>level</tt> in our call of <tt>confint()</tt> accordingly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(model, <span class="dt">level =</span> <span class="fl">0.9</span>)</code></pre></div>
<pre><code>##                     5 %        95 %
## (Intercept) 673.8145793 698.2499098
## size         -1.7281904  -0.4744009
## english      -0.7146336  -0.5849200</code></pre>
<p>The output now reports the desired <span class="math inline">\(90\%\)</span> confidence intervals for all coefficients.</p>
<p>A disadvantage of <tt>confint()</tt> is that is does not use robust standard errors to compute the confidence interval. For large-sample confidence intervals, this is quickly done manually as follows.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute robust standard errors</span>
rob_se &lt;-<span class="st"> </span><span class="kw">diag</span>(<span class="kw">vcovHC</span>(model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))<span class="op">^</span><span class="fl">0.5</span>

<span class="co"># compute robust 95% confidence intervals</span>
<span class="kw">rbind</span>(
  <span class="st">&quot;lower&quot;</span> =<span class="st"> </span><span class="kw">coef</span>(model) <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>) <span class="op">*</span><span class="st"> </span>rob_se,
  <span class="st">&quot;upper&quot;</span> =<span class="st"> </span><span class="kw">coef</span>(model) <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.975</span>) <span class="op">*</span><span class="st"> </span>rob_se
)</code></pre></div>
<pre><code>##       (Intercept)       size    english
## lower    668.9252 -1.9496606 -0.7105980
## upper    703.1393 -0.2529307 -0.5889557</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute robust 90% confidence intervals</span>

<span class="kw">rbind</span>(
  <span class="st">&quot;lower&quot;</span> =<span class="st"> </span><span class="kw">coef</span>(model) <span class="op">-</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.95</span>) <span class="op">*</span><span class="st"> </span>rob_se,
  <span class="st">&quot;upper&quot;</span> =<span class="st"> </span><span class="kw">coef</span>(model) <span class="op">+</span><span class="st"> </span><span class="kw">qnorm</span>(<span class="fl">0.95</span>) <span class="op">*</span><span class="st"> </span>rob_se
)</code></pre></div>
<pre><code>##       (Intercept)       size    english
## lower    671.6756 -1.8132659 -0.7008195
## upper    700.3889 -0.3893254 -0.5987341</code></pre>
<p>Knowing how to use <tt>R</tt> to make inference about the coefficients in multiple regression models, you can now answer the following question:</p>
<p>Can the null hypothesis that a change in the student-teacher ratio, <tt>size</tt>, has no significant influence on test scores, <tt>scores</tt>, — if we control for the percentage of students learning English in the district, <tt>english</tt>, — be rejected at the <span class="math inline">\(10\%\)</span> and the <span class="math inline">\(5\%\)</span> level of significance?</p>
<p>The output above shows that zero is not an element of the confidence interval for the coefficient on <tt>size</tt> such that we can reject the null hypothesis at significance levels of <span class="math inline">\(5\%\)</span> and <span class="math inline">\(10\%\)</span>. The same conclusion can be made via the <span class="math inline">\(p\)</span>-value for <tt>size</tt>: <span class="math inline">\(0.00398 &lt; 0.05 = \alpha\)</span>.</p>
<p>Note that rejection at the <span class="math inline">\(5\%\)</span>-level implies rejection at the <span class="math inline">\(10\%\)</span> level (why?).</p>
<p>Recall from Chapter <a href="#cifrc"><strong>??</strong></a> the <span class="math inline">\(95\%\)</span> confidence interval computed above <em>does not</em> tell us that a one-unit decrease in the student-teacher ratio has an effect on test scores that lies in the interval with a lower bound of <span class="math inline">\(-1.9497\)</span> and an upper bound of <span class="math inline">\(-0.2529\)</span>. Once a confidence interval has been computed, a probabilistic statement like this is wrong: either the interval contains the true parameter or it does not. We do not know which is true.</p>
<div id="another-augmentation-of-the-model" class="section level3 unnumbered">
<h3>Another Augmentation of the Model</h3>
<p>What is the average effect on test scores of reducing the student-teacher ratio when the expenditures per pupil and the percentage of english learning pupils are held constant?</p>
<p>Let us augment our model by an additional regressor that is a measure for expenditure per pupil. Using <tt>?CASchools</tt> we find that <tt>CASchools</tt> contains the variable <tt>expenditure</tt>, which provides expenditure per student.</p>
<p>Our model now is <span class="math display">\[ TestScore = \beta_0 + \beta_1 \times size + \beta_2 \times english + \beta_3 \times expenditure + u \]</span></p>
<p>with <span class="math inline">\(expenditure\)</span> the total amount of expenditure per pupil in the district (thousands of dollars).</p>
<p>Let us now estimate the model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># scale expenditure to thousands of dollars</span>
CASchools<span class="op">$</span>expenditure &lt;-<span class="st"> </span>CASchools<span class="op">$</span>expenditure<span class="op">/</span><span class="dv">1000</span>

<span class="co"># estimate the model</span>
model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>size <span class="op">+</span><span class="st"> </span>english <span class="op">+</span><span class="st"> </span>expenditure, <span class="dt">data =</span> CASchools)
<span class="kw">coeftest</span>(model, <span class="dt">vcov. =</span> <span class="kw">vcovHC</span>(model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error  t value Pr(&gt;|t|)    
## (Intercept) 649.577947  15.458344  42.0212  &lt; 2e-16 ***
## size         -0.286399   0.482073  -0.5941  0.55277    
## english      -0.656023   0.031784 -20.6398  &lt; 2e-16 ***
## expenditure   3.867901   1.580722   2.4469  0.01482 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated effect of a one unit change in the student-teacher ratio on test scores with expenditure and the share of english learning pupils held constant is <span class="math inline">\(-0.29\)</span>, which is rather small. What is more, the coefficient on <span class="math inline">\(size\)</span> is not significantly different from zero anymore even at <span class="math inline">\(10\%\)</span> since <span class="math inline">\(p\text{-value}=0.55\)</span>. Can you come up with an interpretation for these findings (see Chapter 7.1 of the book)? The insignificance of <span class="math inline">\(\hat\beta_1\)</span> could be due to a larger standard error of <span class="math inline">\(\hat{\beta}_1\)</span> resulting from adding <span class="math inline">\(expenditure\)</span> to the model so that we estimate the coefficient on <span class="math inline">\(size\)</span> less precisely. This illustrates the issue of strongly correlated regressors (imperfect multicollinearity). The correlation between <span class="math inline">\(size\)</span> and <span class="math inline">\(expenditure\)</span> can be computed using <tt>cor()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the sample correlation between &#39;size&#39; and &#39;expenditure&#39;</span>
<span class="kw">cor</span>(CASchools<span class="op">$</span>size, CASchools<span class="op">$</span>expenditure)</code></pre></div>
<pre><code>## [1] -0.6199822</code></pre>
<p>Altogether, we conclude that the new model provides no evidence that changing the student-teacher ratio, e.g., by hiring new teachers, has any effect on the test scores while keeping expenditures per student and the share of English learners constant.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hypothesis-tests-and-confidence-intervals-for-a-single-coefficient.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="joint-hypothesis-testing-using-the-f-statistic.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": ["URFITE.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
