<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-10-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="eodce.html">
<link rel="next" href="references.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!-- function to adjust height of iframes automatically depending on content loaded -->

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.oek.wiwi.uni-due.de/en/">Chair of Econometrics at UDE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-very-short-introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="pt.html"><a href="pt.html"><i class="fa fa-check"></i><b>2</b> Probability Theory</a><ul>
<li class="chapter" data-level="2.1" data-path="pt.html"><a href="pt.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>2.1</b> Random Variables and Probability Distributions</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-discrete-random-variables"><i class="fa fa-check"></i>Probability Distributions of Discrete Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#bernoulli-trials"><i class="fa fa-check"></i>Bernoulli Trials</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#expected-value-mean-and-variance"><i class="fa fa-check"></i>Expected Value, Mean and Variance</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-continuous-random-variables"><i class="fa fa-check"></i>Probability Distributions of Continuous Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-chi-squared-distribution"><i class="fa fa-check"></i>The Chi-Squared Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#thetdist"><i class="fa fa-check"></i>The Student t Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-f-distribution"><i class="fa fa-check"></i>The F Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="pt.html"><a href="pt.html#RSATDOSA"><i class="fa fa-check"></i><b>2.2</b> Random Sampling and the Distribution of Sample Averages</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i>Mean and Variance of the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#large-sample-approximations-to-sampling-distributions"><i class="fa fa-check"></i>Large Sample Approximations to Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="pt.html"><a href="pt.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="arosur.html"><a href="arosur.html"><i class="fa fa-check"></i><b>3</b> A Review of Statistics using R</a><ul>
<li class="chapter" data-level="3.1" data-path="arosur.html"><a href="arosur.html#estimation-of-the-population-mean"><i class="fa fa-check"></i><b>3.1</b> Estimation of the Population Mean</a></li>
<li class="chapter" data-level="3.2" data-path="arosur.html"><a href="arosur.html#potsm"><i class="fa fa-check"></i><b>3.2</b> Properties of the Sample Mean</a></li>
<li class="chapter" data-level="3.3" data-path="arosur.html"><a href="arosur.html#hypothesis-tests-concerning-the-population-mean"><i class="fa fa-check"></i><b>3.3</b> Hypothesis Tests Concerning the Population Mean</a><ul>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-p-value"><i class="fa fa-check"></i>The p-Value</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-known"><i class="fa fa-check"></i>Calculating the p-Value when the Standard Deviation is Known</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#SVSSDASE"><i class="fa fa-check"></i>Sample Variance, Sample Standard Deviation and Standard Error</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-unknown"><i class="fa fa-check"></i>Calculating the p-value When the Standard Deviation is Unknown</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-t-statistic"><i class="fa fa-check"></i>The t-statistic</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#hypothesis-testing-with-a-prespecified-significance-level"><i class="fa fa-check"></i>Hypothesis Testing with a Prespecified Significance Level</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#one-sided-alternatives"><i class="fa fa-check"></i>One-sided Alternatives</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="arosur.html"><a href="arosur.html#confidence-intervals-for-the-population-mean"><i class="fa fa-check"></i><b>3.4</b> Confidence Intervals for the Population Mean</a></li>
<li class="chapter" data-level="3.5" data-path="arosur.html"><a href="arosur.html#cmfdp"><i class="fa fa-check"></i><b>3.5</b> Comparing Means from Different Populations</a></li>
<li class="chapter" data-level="3.6" data-path="arosur.html"><a href="arosur.html#aattggoe"><i class="fa fa-check"></i><b>3.6</b> An Application to the Gender Gap of Earnings</a></li>
<li class="chapter" data-level="3.7" data-path="arosur.html"><a href="arosur.html#scatterplots-sample-covariance-and-sample-correlation"><i class="fa fa-check"></i><b>3.7</b> Scatterplots, Sample Covariance and Sample Correlation</a></li>
<li class="chapter" data-level="3.8" data-path="arosur.html"><a href="arosur.html#exercises-1"><i class="fa fa-check"></i><b>3.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lrwor.html"><a href="lrwor.html"><i class="fa fa-check"></i><b>4</b> Linear Regression with One Regressor</a><ul>
<li class="chapter" data-level="4.1" data-path="lrwor.html"><a href="lrwor.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="lrwor.html"><a href="lrwor.html#estimating-the-coefficients-of-the-linear-regression-model"><i class="fa fa-check"></i><b>4.2</b> Estimating the Coefficients of the Linear Regression Model</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-ordinary-least-squares-estimator"><i class="fa fa-check"></i>The Ordinary Least Squares Estimator</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lrwor.html"><a href="lrwor.html#measures-of-fit"><i class="fa fa-check"></i><b>4.3</b> Measures of Fit</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-coefficient-of-determination"><i class="fa fa-check"></i>The Coefficient of Determination</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-standard-error-of-the-regression"><i class="fa fa-check"></i>The Standard Error of the Regression</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#application-to-the-test-score-data"><i class="fa fa-check"></i>Application to the Test Score Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="lrwor.html"><a href="lrwor.html#tlsa"><i class="fa fa-check"></i><b>4.4</b> The Least Squares Assumptions</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-1-the-error-term-has-conditional-mean-of-zero"><i class="fa fa-check"></i>Assumption 1: The Error Term has Conditional Mean of Zero</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-2-independently-and-identically-distributed-data"><i class="fa fa-check"></i>Assumption 2: Independently and Identically Distributed Data</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-3-large-outliers-are-unlikely"><i class="fa fa-check"></i>Assumption 3: Large Outliers are Unlikely</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="lrwor.html"><a href="lrwor.html#tsdotoe"><i class="fa fa-check"></i><b>4.5</b> The Sampling Distribution of the OLS Estimator</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-1"><i class="fa fa-check"></i>Simulation Study 1</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-2"><i class="fa fa-check"></i>Simulation Study 2</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-3"><i class="fa fa-check"></i>Simulation Study 3</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="lrwor.html"><a href="lrwor.html#exercises-2"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="htaciitslrm.html"><a href="htaciitslrm.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests and Confidence Intervals in the Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="5.1" data-path="htaciitslrm.html"><a href="htaciitslrm.html#testing-two-sided-hypotheses-concerning-the-slope-coefficient"><i class="fa fa-check"></i><b>5.1</b> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</a></li>
<li class="chapter" data-level="5.2" data-path="htaciitslrm.html"><a href="htaciitslrm.html#cifrc"><i class="fa fa-check"></i><b>5.2</b> Confidence Intervals for Regression Coefficients</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-confidence-intervals"><i class="fa fa-check"></i>Simulation Study: Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="htaciitslrm.html"><a href="htaciitslrm.html#rwxiabv"><i class="fa fa-check"></i><b>5.3</b> Regression when X is a Binary Variable</a></li>
<li class="chapter" data-level="5.4" data-path="htaciitslrm.html"><a href="htaciitslrm.html#hah"><i class="fa fa-check"></i><b>5.4</b> Heteroskedasticity and Homoskedasticity</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#a-real-world-example-for-heteroskedasticity"><i class="fa fa-check"></i>A Real-World Example for Heteroskedasticity</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#should-we-care-about-heteroskedasticity"><i class="fa fa-check"></i>Should We Care About Heteroskedasticity?</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#computation-of-heteroskedasticity-robust-standard-errors"><i class="fa fa-check"></i>Computation of Heteroskedasticity-Robust Standard Errors</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="htaciitslrm.html"><a href="htaciitslrm.html#the-gauss-markov-theorem"><i class="fa fa-check"></i><b>5.5</b> The Gauss-Markov Theorem</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-blue-estimator"><i class="fa fa-check"></i>Simulation Study: BLUE Estimator</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="htaciitslrm.html"><a href="htaciitslrm.html#using-the-t-statistic-in-regression-when-the-sample-size-is-small"><i class="fa fa-check"></i><b>5.6</b> Using the t-Statistic in Regression When the Sample Size Is Small</a></li>
<li class="chapter" data-level="5.7" data-path="htaciitslrm.html"><a href="htaciitslrm.html#exercises-3"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rmwmr.html"><a href="rmwmr.html"><i class="fa fa-check"></i><b>6</b> Regression Models with Multiple Regressors</a><ul>
<li class="chapter" data-level="6.1" data-path="rmwmr.html"><a href="rmwmr.html#omitted-variable-bias"><i class="fa fa-check"></i><b>6.1</b> Omitted Variable Bias</a></li>
<li class="chapter" data-level="6.2" data-path="rmwmr.html"><a href="rmwmr.html#tmrm"><i class="fa fa-check"></i><b>6.2</b> The Multiple Regression Model</a></li>
<li class="chapter" data-level="6.3" data-path="rmwmr.html"><a href="rmwmr.html#mofimr"><i class="fa fa-check"></i><b>6.3</b> Measures of Fit in Multiple Regression</a></li>
<li class="chapter" data-level="6.4" data-path="rmwmr.html"><a href="rmwmr.html#ols-assumptions-in-multiple-regression"><i class="fa fa-check"></i><b>6.4</b> OLS Assumptions in Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#multicollinearity"><i class="fa fa-check"></i>Multicollinearity</a></li>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#simulation-study-imperfect-multicollinearity"><i class="fa fa-check"></i>Simulation Study: Imperfect Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rmwmr.html"><a href="rmwmr.html#the-distribution-of-the-ols-estimators-in-multiple-regression"><i class="fa fa-check"></i><b>6.5</b> The Distribution of the OLS Estimators in Multiple Regression</a></li>
<li class="chapter" data-level="6.6" data-path="rmwmr.html"><a href="rmwmr.html#exercises-4"><i class="fa fa-check"></i><b>6.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="htaciimr.html"><a href="htaciimr.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Tests and Confidence Intervals in Multiple Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="htaciimr.html"><a href="htaciimr.html#hypothesis-tests-and-confidence-intervals-for-a-single-coefficient"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Tests and Confidence Intervals for a Single Coefficient</a></li>
<li class="chapter" data-level="7.2" data-path="htaciimr.html"><a href="htaciimr.html#an-application-to-test-scores-and-the-student-teacher-ratio"><i class="fa fa-check"></i><b>7.2</b> An Application to Test Scores and the Student-Teacher Ratio</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#another-augmentation-of-the-model"><i class="fa fa-check"></i>Another Augmentation of the Model</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="htaciimr.html"><a href="htaciimr.html#joint-hypothesis-testing-using-the-f-statistic"><i class="fa fa-check"></i><b>7.3</b> Joint Hypothesis Testing Using the F-Statistic</a></li>
<li class="chapter" data-level="7.4" data-path="htaciimr.html"><a href="htaciimr.html#confidence-sets-for-multiple-coefficients"><i class="fa fa-check"></i><b>7.4</b> Confidence Sets for Multiple Coefficients</a></li>
<li class="chapter" data-level="7.5" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-for-multiple-regression"><i class="fa fa-check"></i><b>7.5</b> Model Specification for Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-in-theory-and-in-practice"><i class="fa fa-check"></i>Model Specification in Theory and in Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="htaciimr.html"><a href="htaciimr.html#analysis-of-the-test-score-data-set"><i class="fa fa-check"></i><b>7.6</b> Analysis of the Test Score Data Set</a></li>
<li class="chapter" data-level="7.7" data-path="htaciimr.html"><a href="htaciimr.html#exercises-5"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nrf.html"><a href="nrf.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Regression Functions</a><ul>
<li class="chapter" data-level="8.1" data-path="nrf.html"><a href="nrf.html#a-general-strategy-for-modelling-nonlinear-regression-functions"><i class="fa fa-check"></i><b>8.1</b> A General Strategy for Modelling Nonlinear Regression Functions</a></li>
<li class="chapter" data-level="8.2" data-path="nrf.html"><a href="nrf.html#nfoasiv"><i class="fa fa-check"></i><b>8.2</b> Nonlinear Functions of a Single Independent Variable</a><ul>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#polynomials"><i class="fa fa-check"></i>Polynomials</a></li>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#logarithms"><i class="fa fa-check"></i>Logarithms</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nrf.html"><a href="nrf.html#interactions-between-independent-variables"><i class="fa fa-check"></i><b>8.3</b> Interactions Between Independent Variables</a></li>
<li class="chapter" data-level="8.4" data-path="nrf.html"><a href="nrf.html#nonlinear-effects-on-test-scores-of-the-student-teacher-ratio"><i class="fa fa-check"></i><b>8.4</b> Nonlinear Effects on Test Scores of the Student-Teacher Ratio</a></li>
<li class="chapter" data-level="8.5" data-path="nrf.html"><a href="nrf.html#exercises-6"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="asbomr.html"><a href="asbomr.html"><i class="fa fa-check"></i><b>9</b> Assessing Studies Based on Multiple Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity"><i class="fa fa-check"></i><b>9.1</b> Internal and External Validity</a></li>
<li class="chapter" data-level="9.2" data-path="asbomr.html"><a href="asbomr.html#ttivomra"><i class="fa fa-check"></i><b>9.2</b> Threats to Internal Validity of Multiple Regression Analysis</a></li>
<li class="chapter" data-level="9.3" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity-when-the-regression-is-used-for-forecasting"><i class="fa fa-check"></i><b>9.3</b> Internal and External Validity when the Regression is Used for Forecasting</a></li>
<li class="chapter" data-level="9.4" data-path="asbomr.html"><a href="asbomr.html#etsacs"><i class="fa fa-check"></i><b>9.4</b> Example: Test Scores and Class Size</a></li>
<li class="chapter" data-level="9.5" data-path="asbomr.html"><a href="asbomr.html#exercises-7"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="rwpd.html"><a href="rwpd.html"><i class="fa fa-check"></i><b>10</b> Regression with Panel Data</a><ul>
<li class="chapter" data-level="10.1" data-path="rwpd.html"><a href="rwpd.html#panel-data"><i class="fa fa-check"></i><b>10.1</b> Panel Data</a></li>
<li class="chapter" data-level="10.2" data-path="rwpd.html"><a href="rwpd.html#PDWTTP"><i class="fa fa-check"></i><b>10.2</b> Panel Data with Two Time Periods: “Before and After” Comparisons</a></li>
<li class="chapter" data-level="10.3" data-path="rwpd.html"><a href="rwpd.html#fixed-effects-regression"><i class="fa fa-check"></i><b>10.3</b> Fixed Effects Regression</a><ul>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#estimation-and-inference"><i class="fa fa-check"></i>Estimation and Inference</a></li>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#application-to-traffic-deaths"><i class="fa fa-check"></i>Application to Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="rwpd.html"><a href="rwpd.html#regression-with-time-fixed-effects"><i class="fa fa-check"></i><b>10.4</b> Regression with Time Fixed Effects</a></li>
<li class="chapter" data-level="10.5" data-path="rwpd.html"><a href="rwpd.html#tferaaseffer"><i class="fa fa-check"></i><b>10.5</b> The Fixed Effects Regression Assumptions and Standard Errors for Fixed Effects Regression</a></li>
<li class="chapter" data-level="10.6" data-path="rwpd.html"><a href="rwpd.html#drunk-driving-laws-and-traffic-deaths"><i class="fa fa-check"></i><b>10.6</b> Drunk Driving Laws and Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="rwabdv.html"><a href="rwabdv.html"><i class="fa fa-check"></i><b>11</b> Regression with a Binary Dependent Variable</a><ul>
<li class="chapter" data-level="11.1" data-path="rwabdv.html"><a href="rwabdv.html#binary-dependent-variables-and-the-linear-probability-model"><i class="fa fa-check"></i><b>11.1</b> Binary Dependent Variables and the Linear Probability Model</a></li>
<li class="chapter" data-level="11.2" data-path="rwabdv.html"><a href="rwabdv.html#palr"><i class="fa fa-check"></i><b>11.2</b> Probit and Logit Regression</a><ul>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#probit-regression"><i class="fa fa-check"></i>Probit Regression</a></li>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#logit-regression"><i class="fa fa-check"></i>Logit Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="rwabdv.html"><a href="rwabdv.html#estimation-and-inference-in-the-logit-and-probit-models"><i class="fa fa-check"></i><b>11.3</b> Estimation and Inference in the Logit and Probit Models</a></li>
<li class="chapter" data-level="11.4" data-path="rwabdv.html"><a href="rwabdv.html#application-to-the-boston-hmda-data"><i class="fa fa-check"></i><b>11.4</b> Application to the Boston HMDA Data</a></li>
<li class="chapter" data-level="11.5" data-path="rwabdv.html"><a href="rwabdv.html#exercises-8"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ivr.html"><a href="ivr.html"><i class="fa fa-check"></i><b>12</b> Instrumental Variables Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="ivr.html"><a href="ivr.html#TIVEWASRAASI"><i class="fa fa-check"></i><b>12.1</b> The IV Estimator with a Single Regressor and a Single Instrument</a></li>
<li class="chapter" data-level="12.2" data-path="ivr.html"><a href="ivr.html#TGIVRM"><i class="fa fa-check"></i><b>12.2</b> The General IV Regression Model</a></li>
<li class="chapter" data-level="12.3" data-path="ivr.html"><a href="ivr.html#civ"><i class="fa fa-check"></i><b>12.3</b> Checking Instrument Validity</a></li>
<li class="chapter" data-level="12.4" data-path="ivr.html"><a href="ivr.html#attdfc"><i class="fa fa-check"></i><b>12.4</b> Application to the Demand for Cigarettes</a></li>
<li class="chapter" data-level="12.5" data-path="ivr.html"><a href="ivr.html#where-do-valid-instruments-come-from"><i class="fa fa-check"></i><b>12.5</b> Where Do Valid Instruments Come From?</a></li>
<li class="chapter" data-level="12.6" data-path="ivr.html"><a href="ivr.html#exercises-9"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="eaqe.html"><a href="eaqe.html"><i class="fa fa-check"></i><b>13</b> Experiments and Quasi-Experiments</a><ul>
<li class="chapter" data-level="13.1" data-path="eaqe.html"><a href="eaqe.html#potential-outcomes-causal-effects-and-idealized-experiments"><i class="fa fa-check"></i><b>13.1</b> Potential Outcomes, Causal Effects and Idealized Experiments</a></li>
<li class="chapter" data-level="13.2" data-path="eaqe.html"><a href="eaqe.html#threats-to-validity-of-experiments"><i class="fa fa-check"></i><b>13.2</b> Threats to Validity of Experiments</a></li>
<li class="chapter" data-level="13.3" data-path="eaqe.html"><a href="eaqe.html#experimental-estimates-of-the-effect-of-class-size-reductions"><i class="fa fa-check"></i><b>13.3</b> Experimental Estimates of the Effect of Class Size Reductions</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#experimental-design-and-the-data-set"><i class="fa fa-check"></i>Experimental Design and the Data Set</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#analysis-of-the-star-data"><i class="fa fa-check"></i>Analysis of the STAR Data</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="eaqe.html"><a href="eaqe.html#quasi-experiments"><i class="fa fa-check"></i><b>13.4</b> Quasi Experiments</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#the-differences-in-differences-estimator"><i class="fa fa-check"></i>The Differences-in-Differences Estimator</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#regression-discontinuity-estimators"><i class="fa fa-check"></i>Regression Discontinuity Estimators</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ittsraf.html"><a href="ittsraf.html"><i class="fa fa-check"></i><b>14</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="14.1" data-path="ittsraf.html"><a href="ittsraf.html#using-regression-models-for-forecasting"><i class="fa fa-check"></i><b>14.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="14.2" data-path="ittsraf.html"><a href="ittsraf.html#tsdasc"><i class="fa fa-check"></i><b>14.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ittsraf.html"><a href="ittsraf.html#autoregressions"><i class="fa fa-check"></i><b>14.3</b> Autoregressions</a><ul>
<li><a href="ittsraf.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ittsraf.html"><a href="ittsraf.html#cybtmpi"><i class="fa fa-check"></i><b>14.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="14.5" data-path="ittsraf.html"><a href="ittsraf.html#apatadlm"><i class="fa fa-check"></i><b>14.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="ittsraf.html"><a href="ittsraf.html#llsuic"><i class="fa fa-check"></i><b>14.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="14.7" data-path="ittsraf.html"><a href="ittsraf.html#nit"><i class="fa fa-check"></i><b>14.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="14.8" data-path="ittsraf.html"><a href="ittsraf.html#niib"><i class="fa fa-check"></i><b>14.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="14.9" data-path="ittsraf.html"><a href="ittsraf.html#can-you-beat-the-market-part-ii"><i class="fa fa-check"></i><b>14.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="eodce.html"><a href="eodce.html"><i class="fa fa-check"></i><b>15</b> Estimation of Dynamic Causal Effects</a><ul>
<li class="chapter" data-level="15.1" data-path="eodce.html"><a href="eodce.html#the-orange-juice-data"><i class="fa fa-check"></i><b>15.1</b> The Orange Juice Data</a></li>
<li class="chapter" data-level="15.2" data-path="eodce.html"><a href="eodce.html#dynamic-causal-effects"><i class="fa fa-check"></i><b>15.2</b> Dynamic Causal Effects</a></li>
<li class="chapter" data-level="15.3" data-path="eodce.html"><a href="eodce.html#dynamic-multipliers-and-cumulative-dynamic-multipliers"><i class="fa fa-check"></i><b>15.3</b> Dynamic Multipliers and Cumulative Dynamic Multipliers</a></li>
<li class="chapter" data-level="15.4" data-path="eodce.html"><a href="eodce.html#hac-standard-errors"><i class="fa fa-check"></i><b>15.4</b> HAC Standard Errors</a></li>
<li class="chapter" data-level="15.5" data-path="eodce.html"><a href="eodce.html#estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors"><i class="fa fa-check"></i><b>15.5</b> Estimation of Dynamic Causal Effects with Strictly Exogeneous Regressors</a></li>
<li class="chapter" data-level="15.6" data-path="eodce.html"><a href="eodce.html#orange-juice-prices-and-cold-weather"><i class="fa fa-check"></i><b>15.6</b> Orange Juice Prices and Cold Weather</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="atitsr.html"><a href="atitsr.html"><i class="fa fa-check"></i><b>16</b> Additional Topics in Time Series Regression</a><ul>
<li class="chapter" data-level="16.1" data-path="atitsr.html"><a href="atitsr.html#vector-autoregressions"><i class="fa fa-check"></i><b>16.1</b> Vector Autoregressions</a></li>
<li class="chapter" data-level="16.2" data-path="atitsr.html"><a href="atitsr.html#ooiatdfglsurt"><i class="fa fa-check"></i><b>16.2</b> Orders of Integration and the DF-GLS Unit Root Test</a></li>
<li class="chapter" data-level="16.3" data-path="atitsr.html"><a href="atitsr.html#cointegration"><i class="fa fa-check"></i><b>16.3</b> Cointegration</a></li>
<li class="chapter" data-level="16.4" data-path="atitsr.html"><a href="atitsr.html#volatility-clustering-and-autoregressive-conditional-heteroskedasticity"><i class="fa fa-check"></i><b>16.4</b> Volatility Clustering and Autoregressive Conditional Heteroskedasticity</a><ul>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#arch-and-garch-models"><i class="fa fa-check"></i>ARCH and GARCH Models</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#application-to-stock-price-volatility"><i class="fa fa-check"></i>Application to Stock Price Volatility</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#summary-8"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="atitsr" class="section level1">
<h1><span class="header-section-number">16</span> Additional Topics in Time Series Regression</h1>
<p>This chapter discusses the following advanced topics in time series regression and demonstrates how core techniques can be applied using <tt>R</tt>:</p>
<ul>
<li><em>Vector autoregressions</em> (VARs). We focus on using VARs for forecasting. Another branch of the literature is concerned with so-called <em>Structural VARs</em> which are, however, beyond the scope of this chapter.</li>
<li>Multiperiod forecasts. This includes a discussion of iterated and direct (multivariate) forecasts.</li>
<li>The DF-GLS test, a modification of the ADF test that has more power than the latter when the series has deterministic components and is close to being nonstationarity.</li>
<li>Cointegration analysis with an application to short- and long-term interest rates. We demonstrate how to estimate a vector error correction model.</li>
<li>Autoregressive conditional heteroskedasticity (ARCH) models. We show how a simple generalized ARCH (GARCH) model can be helpful in quantifying the risk associated with investing in the stock market in terms of estimation and forecasting of the volatility of asset returns.</li>
</ul>
<p>To reproduce the code examples, install the <tt>R</tt> packages listed below and make sure that the subsequent code chunk executes without any errors.</p>
<ul>
<li><tt>AER</tt> <span class="citation">(Christian Kleiber &amp; Zeileis, <a href="#ref-R-AER">2017</a>)</span></li>
<li><tt>dynlm</tt> <span class="citation">(Zeileis, <a href="#ref-R-dynlm">2016</a>)</span></li>
<li><tt>fGarch</tt> <span class="citation">(Wuertz et al., <a href="#ref-R-fGarch">2017</a>)</span></li>
<li><tt>quantmod</tt> <span class="citation">(Ryan &amp; Ulrich, <a href="#ref-R-quantmod">2018</a>)</span></li>
<li><tt>readxl</tt> <span class="citation">(Wickham &amp; Bryan, <a href="#ref-R-readxl">2018</a>)</span></li>
<li><tt>scales</tt> <span class="citation">(Wickham, <a href="#ref-R-scales">2017</a>)</span></li>
<li><tt>vars</tt> <span class="citation">(Pfaff, <a href="#ref-R-vars">2013</a>)</span></li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(AER)
<span class="kw">library</span>(readxl)
<span class="kw">library</span>(dynlm)
<span class="kw">library</span>(vars)
<span class="kw">library</span>(quantmod)
<span class="kw">library</span>(scales)
<span class="kw">library</span>(fGarch)</code></pre></div>
<div id="vector-autoregressions" class="section level2">
<h2><span class="header-section-number">16.1</span> Vector Autoregressions</h2>
<p>A Vector autoregressive (VAR) model is useful when one is interested in predicting multiple time series variables using a single model. At its core, the VAR model is an extension of the univariate autoregressive model we have dealt with in Chapters <a href="ittsraf.html#ittsraf">14</a> and <a href="eodce.html#eodce">15</a>. Key Concept 16.1 summarizes the essentials of VAR.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept <br> 16.1
</h3>
<h3 class="left">
Vector Autoregressions
</h3>
<p>
<p>The vector autoregression (VAR) model extends the idea of univariate autoregression to <span class="math inline">\(k\)</span> time series regressions, where the lagged values of <em>all</em> <span class="math inline">\(k\)</span> series appear as regressors. Put differently, in a VAR model we regress a <em>vector</em> of time series variables on lagged vectors of these variables. As for AR(<span class="math inline">\(p\)</span>) models, the lag order is denoted by <span class="math inline">\(p\)</span> so the VAR(<span class="math inline">\(p\)</span>) model of two variables <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> (<span class="math inline">\(k=2\)</span>) is given by the equations</p>
<span class="math display">\[\begin{align*}
  Y_t =&amp; \, \beta_{10} + \beta_{11} Y_{t-1} + \dots + \beta_{1p} Y_{t-p} + \gamma_{11} X_{t-1} + \dots + \gamma_{1p} X_{t-p} + u_{1t}, \\
  X_t =&amp; \, \beta_{20} + \beta_{21} Y_{t-1} + \dots + \beta_{2p} Y_{t-p} + \gamma_{21} X_{t-1} + \dots + \gamma_{2p} X_{t-p} + u_{2t}.
\end{align*}\]</span>
<p>The <span class="math inline">\(\beta\)</span>s and <span class="math inline">\(\gamma\)</span>s can be estimated using OLS on each equation. The assumptions for VARs are the time series assumptions presented in Key Concept 14.6 applied to each of the equations.</p>
<p>It is straightforward to estimate VAR models in <tt>R</tt>. A feasible approach is to simply use <tt>lm()</tt> for estimation of the individual equations. Furthermore, the <tt>R</tt>package <tt>vars</tt> provides standard tools for estimation, diagnostic testing and prediction using this type of models.</p>
</p>
</div>
<p>When the assumptions of Key Concept 16.1 hold, the OLS estimators of the VAR coefficients are consistent and jointly normal in large samples so that the usual inferential methods such as confidence intervals and <span class="math inline">\(t\)</span>-statistics can be used.</p>
The structure of VARs also allows to jointly test restrictions across multiple equations. For instance, it may be of interest to test whether the coefficients on all regressors of the lag <span class="math inline">\(p\)</span> are zero. This corresponds to testing the null that the lag order <span class="math inline">\(p-1\)</span> is correct. Large sample joint normality of the coefficient estimates is convenient because it implies that we may simply use an <span class="math inline">\(F\)</span>-test for this testing problem. The explicit formula for such a test statistic is rather complicated but fortunately such computations are easily done using the <tt>R</tt> functions we work with in this chapter. Another way to determine optimal lag lengths are information criteria like the <span class="math inline">\(BIC\)</span> which we have introduced for univariate time series regressions in Chapter <a href="ittsraf.html#llsuic">14.6</a>. Just as in the case of a single equation, for a multiple equation model we choose the specification which has the smallest <span class="math inline">\(BIC(p)\)</span>, where
<span class="math display">\[\begin{align*}
  BIC(p) =&amp; \, \log\left[\text{det}(\widehat{\Sigma}_u)\right] + k(kp+1) \frac{\log(T)}{T}.
\end{align*}\]</span>
<p>with <span class="math inline">\(\widehat{\Sigma}_u\)</span> denoting the estimate of the <span class="math inline">\(k \times k\)</span> covariance matrix of the VAR errors and <span class="math inline">\(\text{det}(\cdot)\)</span> denotes the determinant.</p>
<p>As for univariate distributed lag models, one should think carefully about variables to include in a VAR, as adding unrelated variables reduces the forecast accuracy by increasing the estimation error. This is particularly important because the number of parameters to be estimated grows qudratically to the number of variables modeled by the VAR. In the application below we shall see that economic theory and empirical evidence are helpful for this decision.</p>
<div id="a-var-model-of-the-growth-rate-of-gdp-and-the-term-spread" class="section level4 unnumbered">
<h4>A VAR Model of the Growth Rate of GDP and the Term Spread</h4>
<p>We now show how to estimate a VAR model of the GDP growth rate, <span class="math inline">\(GDPGR\)</span>, and the term spread, <span class="math inline">\(TSpread\)</span>. As following the discussion on nonstationarity of GDP growth in Chapter <a href="ittsraf.html#nit">14.7</a> (recall the possible break in the early 1980s detected by the <span class="math inline">\(QLR\)</span> test statistic), we use data from 1981:Q1 to 2012:Q4. The two model equations are</p>
<span class="math display">\[\begin{align*}
 GDPGR_t =&amp; \, \beta_{10} + \beta_{11} GDPGR_{t-1} + \beta_{12} GDPGR_{t-2} + \gamma_{11} TSpread_{t-1} + \gamma_{12} TSpread_{t-2} + u_{1t}, \\
 TSpread_t =&amp; \, \beta_{20} + \beta_{21} GDPGR_{t-1} + \beta_{22} GDPGR_{t-2} + \gamma_{21} TSpread_{t-1} + \gamma_{22} TSpread_{t-2} + u_{2t}.
\end{align*}\]</span>
<p>The data set <tt>us_macro_quarterly.xlsx</tt> is provided on the companion website to <span class="citation">J. Stock &amp; Watson (<a href="#ref-stock2015">2015</a>)</span> and can be downloaded <a href="http://wps.aw.com/aw_stock_ie_3/178/45691/11696965.cw/index.html">here</a>. It contains quarterly data on U.S. real (i.e., inflation adjusted) GDP from 1947 to 2004. We begin by importing the data set and do some formatting (we already worked with this data set in Chapter <a href="ittsraf.html#ittsraf">14</a> so you may skip these steps if you have already loaded the data in your working environment).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load the U.S. macroeconomic data set</span>
USMacroSWQ &lt;-<span class="st"> </span><span class="kw">read_xlsx</span>(<span class="st">&quot;Data/us_macro_quarterly.xlsx&quot;</span>,
                         <span class="dt">sheet =</span> <span class="dv">1</span>,
                         <span class="dt">col_types =</span> <span class="kw">c</span>(<span class="st">&quot;text&quot;</span>, <span class="kw">rep</span>(<span class="st">&quot;numeric&quot;</span>, <span class="dv">9</span>)))

<span class="co"># set the column names</span>
<span class="kw">colnames</span>(USMacroSWQ) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Date&quot;</span>, <span class="st">&quot;GDPC96&quot;</span>, <span class="st">&quot;JAPAN_IP&quot;</span>, <span class="st">&quot;PCECTPI&quot;</span>, <span class="st">&quot;GS10&quot;</span>, 
                          <span class="st">&quot;GS1&quot;</span>, <span class="st">&quot;TB3MS&quot;</span>, <span class="st">&quot;UNRATE&quot;</span>, <span class="st">&quot;EXUSUK&quot;</span>, <span class="st">&quot;CPIAUCSL&quot;</span>)

<span class="co"># format the date column</span>
USMacroSWQ<span class="op">$</span>Date &lt;-<span class="st"> </span><span class="kw">as.yearqtr</span>(USMacroSWQ<span class="op">$</span>Date, <span class="dt">format =</span> <span class="st">&quot;%Y:0%q&quot;</span>)

<span class="co"># define GDP as ts object</span>
GDP &lt;-<span class="st"> </span><span class="kw">ts</span>(USMacroSWQ<span class="op">$</span>GDPC96,
          <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1957</span>, <span class="dv">1</span>), 
          <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">4</span>), 
          <span class="dt">frequency =</span> <span class="dv">4</span>)

<span class="co"># define GDP growth as a ts object</span>
GDPGrowth &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="dv">400</span><span class="op">*</span><span class="kw">log</span>(GDP[<span class="op">-</span><span class="dv">1</span>]<span class="op">/</span>GDP[<span class="op">-</span><span class="kw">length</span>(GDP)]),
                <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1957</span>, <span class="dv">2</span>), 
                <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">4</span>), 
                <span class="dt">frequency =</span> <span class="dv">4</span>)

<span class="co"># 3-months Treasury bill interest rate as a &#39;ts&#39; object</span>
TB3MS &lt;-<span class="st"> </span><span class="kw">ts</span>(USMacroSWQ<span class="op">$</span>TB3MS,
            <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1957</span>, <span class="dv">1</span>), 
            <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">4</span>), 
            <span class="dt">frequency =</span> <span class="dv">4</span>)

<span class="co"># 10-years Treasury bonds interest rate as a &#39;ts&#39; object</span>
TB10YS &lt;-<span class="st"> </span><span class="kw">ts</span>(USMacroSWQ<span class="op">$</span>GS10, 
              <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1957</span>, <span class="dv">1</span>), 
              <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2013</span>, <span class="dv">4</span>), 
              <span class="dt">frequency =</span> <span class="dv">4</span>)

<span class="co"># generate the term spread series</span>
TSpread &lt;-<span class="st"> </span>TB10YS <span class="op">-</span><span class="st"> </span>TB3MS</code></pre></div>
<p>We estimate both equations separately by OLS and use <tt>coeftest()</tt> to obtain robust standard errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Estimate both equations using &#39;dynlm()&#39;</span>
VAR_EQ1 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(GDPGrowth <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>), 
                 <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1981</span>, <span class="dv">1</span>), 
                 <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

VAR_EQ2 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(TSpread <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread, <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>),
                 <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1981</span>, <span class="dv">1</span>),
                 <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

<span class="co"># rename regressors for better readability</span>
<span class="kw">names</span>(VAR_EQ1<span class="op">$</span>coefficients) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Intercept&quot;</span>,<span class="st">&quot;Growth_t-1&quot;</span>, 
                                 <span class="st">&quot;Growth_t-2&quot;</span>, <span class="st">&quot;TSpread_t-1&quot;</span>, <span class="st">&quot;TSpread_t-2&quot;</span>)
<span class="kw">names</span>(VAR_EQ2<span class="op">$</span>coefficients) &lt;-<span class="st"> </span><span class="kw">names</span>(VAR_EQ1<span class="op">$</span>coefficients)

<span class="co"># robust coefficient summaries</span>
<span class="kw">coeftest</span>(VAR_EQ1, <span class="dt">vcov. =</span> sandwich)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error t value  Pr(&gt;|t|)    
## Intercept    0.516344   0.524429  0.9846 0.3267616    
## Growth_t-1   0.289553   0.110827  2.6127 0.0101038 *  
## Growth_t-2   0.216392   0.085879  2.5197 0.0130255 *  
## TSpread_t-1 -0.902549   0.358290 -2.5190 0.0130498 *  
## TSpread_t-2  1.329831   0.392660  3.3867 0.0009503 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coeftest</span>(VAR_EQ2, <span class="dt">vcov. =</span> sandwich)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value  Pr(&gt;|t|)    
## Intercept    0.4557740  0.1214227  3.7536 0.0002674 ***
## Growth_t-1   0.0099785  0.0218424  0.4568 0.6485920    
## Growth_t-2  -0.0572451  0.0264099 -2.1676 0.0321186 *  
## TSpread_t-1  1.0582279  0.0983750 10.7571 &lt; 2.2e-16 ***
## TSpread_t-2 -0.2191902  0.1086198 -2.0180 0.0457712 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We end up with the following results:</p>
<span class="math display">\[\begin{align*}
 GDPGR_t =&amp; \, \underset{(0.46)}{0.52} + \underset{(0.11)}{0.29} GDPGR_{t-1} + \underset{(0.09)}{0.22} GDPGR_{t-2} -\underset{(0.36)}{0.90} TSpread_{t-1} + \underset{(0.39)}{1.33} TSpread_{t-2} \\
 TSpread_t =&amp; \, \underset{(0.12)}{0.46} + \underset{(0.02)}{0.01} GDPGR_{t-1} -\underset{(0.03)}{0.06} GDPGR_{t-2} + \underset{(0.10)}{1.06} TSpread_{t-1} -\underset{(0.11)}{0.22} TSpread_{t-2} 
\end{align*}\]</span>
<p>The function <tt>VAR()</tt> can be used to obtain the same coefficient estimates as presented above since it applies OLS per equation, too.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up data for estimation using `VAR()`</span>
VAR_data &lt;-<span class="st"> </span><span class="kw">window</span>(<span class="kw">ts.union</span>(GDPGrowth, TSpread), <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1980</span>, <span class="dv">3</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

<span class="co"># estimate model coefficients using `VAR()`</span>
VAR_est &lt;-<span class="st"> </span><span class="kw">VAR</span>(<span class="dt">y =</span> VAR_data, <span class="dt">p =</span> <span class="dv">2</span>)
VAR_est</code></pre></div>
<pre><code>## 
## VAR Estimation Results:
## ======================= 
## 
## Estimated coefficients for equation GDPGrowth: 
## ============================================== 
## Call:
## GDPGrowth = GDPGrowth.l1 + TSpread.l1 + GDPGrowth.l2 + TSpread.l2 + const 
## 
## GDPGrowth.l1   TSpread.l1 GDPGrowth.l2   TSpread.l2        const 
##    0.2895533   -0.9025493    0.2163919    1.3298305    0.5163440 
## 
## 
## Estimated coefficients for equation TSpread: 
## ============================================ 
## Call:
## TSpread = GDPGrowth.l1 + TSpread.l1 + GDPGrowth.l2 + TSpread.l2 + const 
## 
## GDPGrowth.l1   TSpread.l1 GDPGrowth.l2   TSpread.l2        const 
##  0.009978489  1.058227945 -0.057245123 -0.219190243  0.455773969</code></pre>
<p><tt>VAR()</tt> returns a <tt>list</tt> of <tt>lm</tt> objects which can be passed to the usual functions, for example <tt>summary()</tt> and so it is straightforward to obtain model statistics for the individual equations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># obtain the adj. R^2 from the output of &#39;VAR()&#39;</span>
<span class="kw">summary</span>(VAR_est<span class="op">$</span>varresult<span class="op">$</span>GDPGrowth)<span class="op">$</span>adj.r.squared</code></pre></div>
<pre><code>## [1] 0.2887223</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(VAR_est<span class="op">$</span>varresult<span class="op">$</span>TSpread)<span class="op">$</span>adj.r.squared</code></pre></div>
<pre><code>## [1] 0.8254311</code></pre>
<p>We may use the individual model objects to conduct Granger causality tests.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Granger causality tests:</span>

<span class="co"># test if term spread has no power in explaining GDP growth</span>
<span class="kw">linearHypothesis</span>(VAR_EQ1, 
                 <span class="dt">hypothesis.matrix =</span> <span class="kw">c</span>(<span class="st">&quot;TSpread_t-1&quot;</span>, <span class="st">&quot;TSpread_t-2&quot;</span>),
                 <span class="dt">vcov. =</span> sandwich)</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## TSpread_t - 0
## TSpread_t - 2 = 0
## 
## Model 1: restricted model
## Model 2: GDPGrowth ~ L(GDPGrowth, 1:2) + L(TSpread, 1:2)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F   Pr(&gt;F)   
## 1    125                      
## 2    123  2 5.9094 0.003544 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if GDP growth has no power in explaining term spread</span>
<span class="kw">linearHypothesis</span>(VAR_EQ2, 
                 <span class="dt">hypothesis.matrix =</span> <span class="kw">c</span>(<span class="st">&quot;Growth_t-1&quot;</span>, <span class="st">&quot;Growth_t-2&quot;</span>),
                 <span class="dt">vcov. =</span> sandwich)</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## Growth_t - 0
## Growth_t - 2 = 0
## 
## Model 1: restricted model
## Model 2: TSpread ~ L(GDPGrowth, 1:2) + L(TSpread, 1:2)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F  Pr(&gt;F)  
## 1    125                    
## 2    123  2 3.4777 0.03395 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Both Granger causality tests reject at the level of <span class="math inline">\(5\%\)</span>. This is evidence in favor of the conjecture that the term spread has power in explaining GDP growth and vice versa.</p>
</div>
<div id="iterated-multivariate-forecasts-using-an-iterated-var" class="section level4 unnumbered">
<h4>Iterated Multivariate Forecasts using an Iterated VAR</h4>
<p>The idea of an iterated forecast for period <span class="math inline">\(T+2\)</span> based on observations up to period <span class="math inline">\(T\)</span> is to use the one-period-ahead forecast as an intermediate step. That is, the forecast for period <span class="math inline">\(T+1\)</span> is used as an observation when predicting the level of a series for period <span class="math inline">\(T+2\)</span>. This can be generalized to a <span class="math inline">\(h\)</span>-period-ahead forecast where all intervening periods between <span class="math inline">\(T\)</span> and <span class="math inline">\(T+h\)</span> must be forecasted as they are used as observations in the process (see Chapter 16.2 of the book for a more detailed argument on this concept). Iterated multiperiod forecasts are summarized in Key Concept 16.2.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept <br> 16.2
</h3>
<h3 class="left">
Iterated Multiperiod Forecasts
</h3>
<p>
<p>The steps for an <em>iterated multiperiod AR forecast</em> are:</p>
<ol style="list-style-type: decimal">
<li><p>Estimate the AR(<span class="math inline">\(p\)</span>) model using OLS and compute the one-period-ahead forecast.</p></li>
<li><p>Use the one-period-ahead forecast to obtain the two-period-ahead forecast.</p></li>
<li><p>Continue by iterating to obtain forecasts farther into the future.</p></li>
</ol>
<p>An <em>iterated multiperiod VAR forecast</em> is done as follows:</p>
<ol style="list-style-type: decimal">
<li><p>Estimate the VAR(<span class="math inline">\(p\)</span>) model using OLS per equation and compute the one-period-ahead forecast for <em>all</em> variables in the VAR.</p></li>
<li><p>Use the one-period-ahead forecasts to obtain the two-period-ahead forecasts.</p></li>
<li><p>Continue by iterating to obtain forecasts of all variables in the VAR farther into the future.</p></li>
</ol>
</p>
</div>
<p>Since a VAR models all variables using lags of the respective other variables, we need to compute forecasts for <em>all</em> variables. It can be cumbersome to do so when the VAR is large but fortunately there are <tt>R</tt> functions that facilitate this. For example, the function <tt>predict()</tt> can be used to obtain iterated multivariate forecasts for VAR models estimated by the function <tt>VAR()</tt>.</p>
<p>The following code chunk shows how to compute iterated forecasts for GDP growth and the term spread up to period 2015:Q1, that is <span class="math inline">\(h=10\)</span>, using the model object <tt>VAR_est</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute iterated forecasts for GDP growth and term spread for the next 10 quarters</span>
forecasts &lt;-<span class="st"> </span><span class="kw">predict</span>(VAR_est)
forecasts</code></pre></div>
<pre><code>## $GDPGrowth
##           fcst     lower    upper       CI
##  [1,] 1.738653 -3.006124 6.483430 4.744777
##  [2,] 1.692193 -3.312731 6.697118 5.004925
##  [3,] 1.911852 -3.282880 7.106583 5.194731
##  [4,] 2.137070 -3.164247 7.438386 5.301317
##  [5,] 2.329667 -3.041435 7.700769 5.371102
##  [6,] 2.496815 -2.931819 7.925449 5.428634
##  [7,] 2.631849 -2.846390 8.110088 5.478239
##  [8,] 2.734819 -2.785426 8.255064 5.520245
##  [9,] 2.808291 -2.745597 8.362180 5.553889
## [10,] 2.856169 -2.722905 8.435243 5.579074
## 
## $TSpread
##           fcst        lower    upper        CI
##  [1,] 1.676746  0.708471226 2.645021 0.9682751
##  [2,] 1.884098  0.471880228 3.296316 1.4122179
##  [3,] 1.999409  0.336348101 3.662470 1.6630609
##  [4,] 2.080836  0.242407507 3.919265 1.8384285
##  [5,] 2.131402  0.175797245 4.087008 1.9556052
##  [6,] 2.156094  0.125220562 4.186968 2.0308738
##  [7,] 2.161783  0.085037834 4.238528 2.0767452
##  [8,] 2.154170  0.051061544 4.257278 2.1031082
##  [9,] 2.138164  0.020749780 4.255578 2.1174139
## [10,] 2.117733 -0.007139213 4.242605 2.1248722</code></pre>
<p>This reveals that the two-quarter-ahead forecast of GDP growth in 2013:Q2 using data through 2012:Q4 is <span class="math inline">\(1.69\)</span>. For the same period, the iterated VAR forecast for the term spread is <span class="math inline">\(1.88\)</span>.</p>
<p>The matrices returned by <code>predict(VAR_est)</code> also include <span class="math inline">\(95\%\)</span> prediction intervals (however, the function does not adjust for autocorrelation or heteroskedasticity of the errors!).</p>
<p>We may also plot the iterated forecasts for both variables by calling <tt>plot()</tt> on the output of <code>predict(VAR_est)</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># visualize the iterated forecasts</span>
<span class="kw">plot</span>(forecasts)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-714-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="direct-multiperiod-forecasts" class="section level4 unnumbered">
<h4>Direct Multiperiod Forecasts</h4>
<p>A direct multiperiod forecast uses a model where the predictors are lagged appropriately such that the available observations can be used <em>directly</em> to do the forecast. The idea of direct multiperiod forecasting is summarized in Key Concept 16.3.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept <br> 16.3
</h3>
<h3 class="left">
Direct Multiperiod Forecasts
</h3>
<p>
<p>A <em>direct multiperiod forecast</em> that forecasts <span class="math inline">\(h\)</span> periods into the future using a model of <span class="math inline">\(Y_t\)</span> and an additional predictor <span class="math inline">\(X_t\)</span> with <span class="math inline">\(p\)</span> lags is done by first estimating</p>
<span class="math display">\[\begin{align*}
  Y_t =&amp; \, \delta_0 + \delta_1 Y_{t-h} + \dots + \delta_{p} Y_{t-p-h+1} + \delta_{p+1} X_{t-h} \\
  +&amp; \dots + \delta_{2p} Y_{t-p-h+1} + u_t,  
\end{align*}\]</span>
which is then used to compute the forecast of <span class="math inline">\(Y_{T+h}\)</span> based on observations through period <span class="math inline">\(T\)</span>.
</p>
</div>
<p>For example, to obtain two-quarter-ahead forecasts of GDP growth and the term spread we first estimate the equations</p>
<span class="math display">\[\begin{align*}
 GDPGR_t =&amp; \, \beta_{10} + \beta_{11} GDPGR_{t-2} + \beta_{12} GDPGR_{t-3} + \gamma_{11} TSpread_{t-2} + \gamma_{12} TSpread_{t-3} + u_{1t}, \\
 TSpread_t =&amp; \, \beta_{20} + \beta_{21} GDPGR_{t-2} + \beta_{22} GDPGR_{t-3} + \gamma_{21} TSpread_{t-2} + \gamma_{22} TSpread_{t-3} + u_{2t}
\end{align*}\]</span>
<p>and then substitute the values of <span class="math inline">\(GDPGR_{2012:Q4}\)</span>, <span class="math inline">\(GDPGR_{2012:Q3}\)</span>, <span class="math inline">\(TSpread_{2012:Q4}\)</span> and <span class="math inline">\(TSpread_{2012:Q3}\)</span> into both equations. This is easily done manually.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate models for direct two-quarter-ahead forecasts</span>
VAR_EQ1_direct &lt;-<span class="st"> </span><span class="kw">dynlm</span>(GDPGrowth <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>), 
                        <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1981</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

VAR_EQ2_direct &lt;-<span class="st"> </span><span class="kw">dynlm</span>(TSpread <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(GDPGrowth, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(TSpread, <span class="dv">2</span><span class="op">:</span><span class="dv">3</span>), 
                        <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1981</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

<span class="co"># compute direct two-quarter-ahead forecasts</span>
<span class="kw">coef</span>(VAR_EQ1_direct) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="co"># intercept</span>
                           <span class="kw">window</span>(GDPGrowth, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">3</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)), 
                           <span class="kw">window</span>(TSpread, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">3</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)))</code></pre></div>
<pre><code>##          [,1]
## [1,] 2.439497</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(VAR_EQ2_direct) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="co"># intercept</span>
                           <span class="kw">window</span>(GDPGrowth, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">3</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)), 
                           <span class="kw">window</span>(TSpread, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">3</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)))</code></pre></div>
<pre><code>##         [,1]
## [1,] 1.66578</code></pre>
<p>Applied economists often use the iterated method since this forecasts are more reliable in terms of <span class="math inline">\(MSFE\)</span>, provided that the one-period-ahead model is correctly specified. If this is not the case, for example because one equation in a VAR is believed to be misspecified, it can be beneficial to use direct forecasts since the iterated method will then be biased and thus have a higher <span class="math inline">\(MSFE\)</span> than the direct method. See Chapter <a href="atitsr.html#ooiatdfglsurt">16.2</a> for a more detailed discussion on advantages and disadvantages of both methods.</p>
</div>
</div>
<div id="ooiatdfglsurt" class="section level2">
<h2><span class="header-section-number">16.2</span> Orders of Integration and the DF-GLS Unit Root Test</h2>
<p>Some economic time series have smoother trends than variables that can be described by random walk models. A way to model these time series is <span class="math display">\[\Delta Y_t = \beta_0 + \Delta Y_{t-1} + u_t,\]</span> where <span class="math inline">\(u_t\)</span> is a serially uncorrelated error term. This model states that the first difference of a series is a random walk. Consequently, the series of second differences of <span class="math inline">\(Y_t\)</span> is stationary. Key Concept 16.4 summarizes the notation.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept <br> 16.4
</h3>
<h3 class="left">
Orders of Integration, Differencing and Stationarity
</h3>
<p>
<ul>
<li><p>When a time series <span class="math inline">\(Y_t\)</span> has a unit autoregressive root, <span class="math inline">\(Y_t\)</span> is integrated of order one. This is often denoted by <span class="math inline">\(Y_t \sim I(1)\)</span>. We simply say that <span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(1)\)</span>. If <span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(1)\)</span>, its first difference <span class="math inline">\(\Delta Y_t\)</span> is stationary.</p></li>
<li><p><span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(2)\)</span> when <span class="math inline">\(Y_t\)</span> needs to be differenced twice in order to obtain a stationary series. Using the notation introduced here, if <span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(2)\)</span>, its first difference <span class="math inline">\(\Delta Y_t\)</span> is <span class="math inline">\(I(1)\)</span> and its second difference <span class="math inline">\(\Delta^2 Y_t\)</span> is stationary. <span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(d)\)</span> when <span class="math inline">\(Y_t\)</span> must be differenced <span class="math inline">\(d\)</span> times to obtain a stationary series.</p></li>
<li><p>When <span class="math inline">\(Y_t\)</span> is stationary, it is integrated of order <span class="math inline">\(0\)</span> so <span class="math inline">\(Y_t\)</span> is <span class="math inline">\(I(0)\)</span>.</p></li>
</ul>
<p>It is fairly easy to obtain differences of time series in <tt>R</tt>. For example, the function <tt>diff()</tt> returns suitably lagged and iterated differences of numeric vectors, matrices and time series objects of the class <tt>ts</tt>.</p>
</p>
</div>
<p>Following the book, we take the price level of the U.S. measured by the <em>Personal Consumption Expenditures Price Index</em> as an example.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define ts object of the U.S. PCE Price Index</span>
PCECTPI &lt;-<span class="st"> </span><span class="kw">ts</span>(<span class="kw">log</span>(USMacroSWQ<span class="op">$</span>PCECTPI), 
              <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1957</span>, <span class="dv">1</span>), 
              <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>), 
              <span class="dt">freq =</span> <span class="dv">4</span>)

<span class="co"># plot logarithm of the PCE Price Index</span>
<span class="kw">plot</span>(<span class="kw">log</span>(PCECTPI),
     <span class="dt">main =</span> <span class="st">&quot;Log of United States PCE Price Index&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Logarithm&quot;</span>,
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-720-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The logarithm of the price level has a smoothly varying trend. This is typical for an <span class="math inline">\(I(2)\)</span> series. If the price level is indeed <span class="math inline">\(I(2)\)</span>, the first differences of this series should be <span class="math inline">\(I(1)\)</span>. Since we are considering the logarithm of the price level, we obtain growth rates by taking first differences. Therefore, the differenced price level series is the series of quarterly inflation rates. This is quickly done in <tt>R</tt> using the function <tt>Delt()</tt> from the package <tt>quantmod</tt>. As explained in Chapter <a href="ittsraf.html#tsdasc">14.2</a>, multiplying the quarterly inflation rates by <span class="math inline">\(400\)</span> yields the quarterly rate of inflation, measured in percentage points at an annual rate.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot U.S. PCE price inflation</span>
<span class="kw">plot</span>(<span class="dv">400</span> <span class="op">*</span><span class="st"> </span><span class="kw">Delt</span>(PCECTPI),
     <span class="dt">main =</span> <span class="st">&quot;United States PCE Price Index&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Percent per annum&quot;</span>,
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>)

<span class="co"># add a dashed line at y =  0 </span>
<span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dt">lty =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-721-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The inflation rate behaves much more erratically than the smooth graph of the logarithm of the PCE price index.</p>
<div id="the-df-gls-test-for-a-unit-root" class="section level4 unnumbered">
<h4>The DF-GLS Test for a Unit Root</h4>
<p>The DF-GLS test for a unit root has been developed by <span class="citation">Elliott, Rothenberg, &amp; Stock (<a href="#ref-elliott1996">1996</a>)</span> and has higher power than the ADF test when the autoregressive root is large but less than one. That is, the DF-GLS has a higher probability of rejecting the false null of a stochastic trend when the sample data stems from a time series that is close to being integrated.</p>
<p>The idea of the DF-GLS test is to test for an autoregressive unit root in the detrended series, whereby GLS estimates of the deterministic components are used to obtain the detrended version of the original series. See Chapter 16.3 of the book for a more detailed explanation of the approach.</p>
<p>A function that performs the DF-GLS test is implemented in the package <tt>urca</tt> (this package is a dependency of the package <tt>vars</tt> so it should be already loaded if <tt>vars</tt> is attached). The function that computes the test statistic is <tt>ur.ers</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># DF-GLS test for unit root in GDP</span>
<span class="kw">summary</span>(<span class="kw">ur.ers</span>(<span class="kw">log</span>(<span class="kw">window</span>(GDP, <span class="dt">start =</span> <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="dt">end =</span> <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))),
        <span class="dt">model =</span> <span class="st">&quot;trend&quot;</span>, 
        <span class="dt">lag.max =</span> <span class="dv">2</span>))</code></pre></div>
<pre><code>## 
## ############################################### 
## # Elliot, Rothenberg and Stock Unit Root Test # 
## ############################################### 
## 
## Test of type DF-GLS 
## detrending of series with intercept and trend 
## 
## 
## Call:
## lm(formula = dfgls.form, data = data.dfgls)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.025739 -0.004054  0.000017  0.004619  0.033620 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## yd.lag       -0.01213    0.01012  -1.199  0.23207    
## yd.diff.lag1  0.28583    0.07002   4.082 6.47e-05 ***
## yd.diff.lag2  0.19320    0.07058   2.737  0.00676 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.007807 on 198 degrees of freedom
## Multiple R-squared:  0.1504, Adjusted R-squared:  0.1376 
## F-statistic: 11.69 on 3 and 198 DF,  p-value: 4.392e-07
## 
## 
## Value of test-statistic is: -1.1987 
## 
## Critical values of DF-GLS are:
##                  1pct  5pct 10pct
## critical values -3.48 -2.89 -2.57</code></pre>
<p>The summary of the test shows that the test statistic is about <span class="math inline">\(-1.2\)</span>. The the <span class="math inline">\(10\%\)</span> critical value for the DF-GLS test is <span class="math inline">\(-2.57\)</span>. This is, however, <strong>not</strong> the appropriate critical value for the ADF test when an intercept and a time trend are included in the Dickey-Fuller regression: the asymptotic distributions of both test statistics differ and so do their critical values!</p>
<p>The test is left-sided so we cannot reject the null hypothesis that U.S. inflation is nonstationary, using the DF-GLS test.</p>
</div>
</div>
<div id="cointegration" class="section level2">
<h2><span class="header-section-number">16.3</span> Cointegration</h2>
<div class="keyconcept">
<h3 class="right">
Key Concept <br> 16.5
</h3>
<h3 class="left">
Cointegration
</h3>
<p>
<p>When <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> are <span class="math inline">\(I(1)\)</span> and if there is a <span class="math inline">\(\theta\)</span> such that <span class="math inline">\(Y_t - \theta X_t\)</span> is <span class="math inline">\(I(0)\)</span>, <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> are cointegrated. Put differently, cointegration of <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> means that <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> have the same or a common stochastic trend and that this trend can be eliminated by taking a specific difference of the series such that the resulting series is stationary.</p>
<p><tt>R</tt> functions for cointegration analysis are implemented in the package <tt>urca</tt>.</p>
</p>
</div>
<p>As an example, reconsider the the relation between short- and long-term interest rates by the example of U.S. 3-month treasury bills, U.S. 10-years treasury bonds and the spread in their interest rates which have been introduced in Chapter <a href="ittsraf.html#cybtmpi">14.4</a>. The next code chunk shows how to reproduce Figure 16.2 of the book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># reproduce Figure 16.2 of the book</span>

<span class="co"># plot both interest series</span>
<span class="kw">plot</span>(<span class="kw">merge</span>(<span class="kw">as.zoo</span>(TB3MS), <span class="kw">as.zoo</span>(TB10YS)), 
     <span class="dt">plot.type =</span> <span class="st">&quot;single&quot;</span>, 
     <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>),
     <span class="dt">lwd =</span> <span class="dv">2</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Percent per annum&quot;</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">17</span>),
     <span class="dt">main =</span> <span class="st">&quot;Interest Rates&quot;</span>)

<span class="co"># add the term spread series</span>
<span class="kw">lines</span>(<span class="kw">as.zoo</span>(TSpread), 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>,
     <span class="dt">lwd =</span> <span class="dv">2</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Percent per annum&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Term Spread&quot;</span>)

<span class="co"># shade the term spread</span>
<span class="kw">polygon</span>(<span class="kw">c</span>(<span class="kw">time</span>(TB3MS), <span class="kw">rev</span>(<span class="kw">time</span>(TB3MS))), 
        <span class="kw">c</span>(TB10YS, <span class="kw">rev</span>(TB3MS)),
        <span class="dt">col =</span> <span class="kw">alpha</span>(<span class="st">&quot;steelblue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.3</span>),
        <span class="dt">border =</span> <span class="ot">NA</span>)

<span class="co"># add horizontal line add 0</span>
<span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>)

<span class="co"># add a legend</span>
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, 
       <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;TB3MS&quot;</span>, <span class="st">&quot;TB10YS&quot;</span>, <span class="st">&quot;Term Spread&quot;</span>),
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;black&quot;</span>, <span class="st">&quot;steelblue&quot;</span>),
       <span class="dt">lwd =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>),
       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>))</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-725-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The plot suggests that long-term and short-term interest rates are cointegrated: both interest series seem to have the same long-run behavior. They share a common stochastic trend. The term spread, which is obtained by taking the difference between long-term and short-term interest rates, seems to be stationary. In fact, the expectations theory of the term structure suggests the cointegrating coefficient <span class="math inline">\(\theta\)</span> to be 1. This is consistent with the visual result.</p>
<div id="testing-for-cointegration" class="section level4 unnumbered">
<h4>Testing for Cointegration</h4>
<p>Following Key Concept 16.5, it seems natural to construct a test for cointegration of two series in the following manner: if two series <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> are cointegrated, the series obtained by taking the difference <span class="math inline">\(Y_t - \theta X_t\)</span> must be stationary. If the series are not cointegrated, <span class="math inline">\(Y_t - \theta X_t\)</span> is nonstationary. This is an assumption that can be tested using a unit root test. We have to distinguish between two cases:</p>
<ol style="list-style-type: decimal">
<li><p><strong><span class="math inline">\(\theta\)</span> is known.</strong></p>
<p>Knowledge of <span class="math inline">\(\theta\)</span> enables us to compute differences <span class="math inline">\(z_t = Y_t - \theta X_t\)</span> so that Dickey-Fuller and DF-GLS unit root tests can be applied to <span class="math inline">\(z_t\)</span>. For these tests, the critical values are the critical values of the ADF or DF-GLS test.</p></li>
<li><p><strong><span class="math inline">\(\theta\)</span> is unknown.</strong></p>
<p>If <span class="math inline">\(\theta\)</span> is unknown, it must be estimated before the unit root test can be applied. This is done by estimating the regression <span class="math display">\[Y_t = \alpha + \theta X_t + z_t\]</span> using OLS (this is refered to as the first-stage regression). Then, a Dickey-Fuller test is used for testing the hypothesis that <span class="math inline">\(z_t\)</span> is a nonstationary series. This is known as the Engle-Granger Augmented Dickey-Fuller test for cointegration (or <em>EG-ADF test</em>) after <span class="citation">Engle &amp; Granger (<a href="#ref-engle1987">1987</a>)</span>. The critical values for this test are special as the associated null distribution is nonnormal and depends on the number of <span class="math inline">\(I(1)\)</span> variables used as regressors in the first stage regression. You may look them up in Table 16.2 of the book. When there are only two presumably cointegrated variables (and thus a single <span class="math inline">\(I(1)\)</span> variable is used in the first stage OLS regression) the critical values for the levels <span class="math inline">\(10\%\)</span>, <span class="math inline">\(5\%\)</span> and <span class="math inline">\(1\%\)</span> are <span class="math inline">\(-3.12\)</span>, <span class="math inline">\(-3.41\)</span> and <span class="math inline">\(-3.96\)</span>.</p></li>
</ol>
</div>
<div id="application-to-interest-rates" class="section level4 unnumbered">
<h4>Application to Interest Rates</h4>
<p>As has been mentioned above, the theory of the term structure suggests that long-term and short-term interest rates are cointegrated with a cointegration coefficient of <span class="math inline">\(\theta = 1\)</span>. In the previous section we have seen that there is visual evidence for this conjecture since the spread of 10-year and 3-month interest rates looks stationary.</p>
<p>We continue by using formal tests (the ADF and the DF-GLS test) to see whether the individual interest rate series are integrated and if their difference is stationary (for now, we assume that <span class="math inline">\(\theta = 1\)</span> is known). Both is conveniently done by using the functions <tt>ur.df()</tt> for computation of the ADF test and <tt>ur.ers</tt> for conducting the DF-GLS test. Following the book we use data from 1962:Q1 to 2012:Q4 and employ models that include a drift term. We set the maximum lag order to <span class="math inline">\(6\)</span> and use the <span class="math inline">\(AIC\)</span> for selection of the optimal lag length.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test for nonstationarity of 3-month treasury bills using ADF test</span>
<span class="kw">ur.df</span>(<span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)), 
      <span class="dt">lags =</span> <span class="dv">6</span>, 
      <span class="dt">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, 
      <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Augmented Dickey-Fuller Test Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -2.1004 2.2385</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test for nonstationarity of 10-years treasury bonds using ADF test</span>
<span class="kw">ur.df</span>(<span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)), 
      <span class="dt">lags =</span> <span class="dv">6</span>, 
      <span class="dt">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, 
      <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Augmented Dickey-Fuller Test Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -1.0079 0.5501</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test for nonstationarity of 3-month treasury bills using DF-GLS test</span>
<span class="kw">ur.ers</span>(<span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)),
       <span class="dt">model =</span> <span class="st">&quot;constant&quot;</span>, 
       <span class="dt">lag.max =</span> <span class="dv">6</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Elliot, Rothenberg and Stock Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -1.8042</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test for nonstationarity of 10-years treasury bonds using DF-GLS test</span>
<span class="kw">ur.ers</span>(<span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)),
       <span class="dt">model =</span> <span class="st">&quot;constant&quot;</span>, 
       <span class="dt">lag.max =</span> <span class="dv">6</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Elliot, Rothenberg and Stock Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -0.942</code></pre>
<p>The corresponding <span class="math inline">\(10\%\)</span> critical value for both tests is <span class="math inline">\(-2.57\)</span> so we cannot reject the null hypotheses of nonstationary for either series, even at the <span class="math inline">\(10\%\)</span> level of significance.<a href="#fn12" class="footnoteRef" id="fnref12"><sup>12</sup></a> We conclude that it is plausible to model both interest rate series as <span class="math inline">\(I(1)\)</span>.</p>
<p>Next, we apply the ADF and the DF-GLS test to test for nonstationarity of the term spread series, which means we test for non-cointegration of long- and short-term interest rates.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if term spread is stationairy (cointegration of interest rates) using ADF</span>
<span class="kw">ur.df</span>(<span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)) <span class="op">-</span><span class="st"> </span><span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span> ,<span class="dv">4</span>)), 
      <span class="dt">lags =</span> <span class="dv">6</span>, 
      <span class="dt">selectlags =</span> <span class="st">&quot;AIC&quot;</span>, 
      <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Augmented Dickey-Fuller Test Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -3.9308 7.7362</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if term spread is stationairy (cointegration of interest rates) using DF-GLS test</span>
<span class="kw">ur.ers</span>(<span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)) <span class="op">-</span><span class="st"> </span><span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)),
       <span class="dt">model =</span> <span class="st">&quot;constant&quot;</span>, 
       <span class="dt">lag.max =</span> <span class="dv">6</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Elliot, Rothenberg and Stock Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -3.8576</code></pre>
<p>Table <a href="atitsr.html#tab:spreadcoint">16.1</a> summarizes the results.</p>
<table>
<caption><span id="tab:spreadcoint">Table 16.1: </span> ADF and DF-GLS Test Statistics for Interest Rate Series</caption>
<thead>
<tr class="header">
<th>Series</th>
<th align="center">ADF Test Statistic</th>
<th align="center">DF-GLS Test Statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>TB3MS</td>
<td align="center"><span class="math inline">\(-2.10\)</span></td>
<td align="center"><span class="math inline">\(-1.80\)</span></td>
</tr>
<tr class="even">
<td>TB10YS</td>
<td align="center"><span class="math inline">\(-1.01\)</span></td>
<td align="center"><span class="math inline">\(-0.94\)</span></td>
</tr>
<tr class="odd">
<td>TB10YS - TB3MS</td>
<td align="center"><span class="math inline">\(-3.93\)</span></td>
<td align="center"><span class="math inline">\(-3.86\)</span></td>
</tr>
</tbody>
</table>
<p>Both tests reject the hypothesis of nonstationarity of the term spread series at the <span class="math inline">\(1\%\)</span> level of significance, which is strong evidence in favor of the hypothesis that the term spread is stationary, implying cointegration of long- and short-term interest rates.</p>
<p>Since theory suggests that <span class="math inline">\(\theta=1\)</span>, there is no need to estimate <span class="math inline">\(\theta\)</span> so it is not necessary to use the EG-ADF test which allows <span class="math inline">\(\theta\)</span> to be unknown. However, since it is instructive to do so, we follow the book and compute this test statistic. The first-stage OLS regression is <span class="math display">\[TB10YS_t = \beta_0 + \beta_1 TB3MS_t + z_t.\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate first-stage regression of EG-ADF test</span>
FS_EGADF &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)) <span class="op">~</span><span class="st"> </span><span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>)))
FS_EGADF</code></pre></div>
<pre><code>## 
## Time series regression with &quot;ts&quot; data:
## Start = 1962(1), End = 2012(4)
## 
## Call:
## dynlm(formula = window(TB10YS, c(1962, 1), c(2012, 4)) ~ window(TB3MS, 
##     c(1962, 1), c(2012, 4)))
## 
## Coefficients:
##                           (Intercept)  
##                                2.4642  
## window(TB3MS, c(1962, 1), c(2012, 4))  
##                                0.8147</code></pre>
Thus we have
<span class="math display">\[\begin{align*}
  \widehat{TB10YS}_t = 2.46 + 0.81 \cdot TB3MS_t,
\end{align*}\]</span>
<p>where <span class="math inline">\(\widehat{\theta} = 0.81\)</span>. Next, we take the residual series <span class="math inline">\(\{\widehat{z_t}\}\)</span> and compute the ADF test statistic.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the residuals</span>
z_hat &lt;-<span class="st"> </span><span class="kw">resid</span>(FS_EGADF)

<span class="co"># compute the ADF test statistic</span>
<span class="kw">ur.df</span>(z_hat, <span class="dt">lags =</span> <span class="dv">6</span>, <span class="dt">type =</span> <span class="st">&quot;none&quot;</span>, <span class="dt">selectlags =</span> <span class="st">&quot;AIC&quot;</span>)</code></pre></div>
<pre><code>## 
## ############################################################### 
## # Augmented Dickey-Fuller Test Unit Root / Cointegration Test # 
## ############################################################### 
## 
## The value of the test statistic is: -3.1935</code></pre>
<p>The test statistic is <span class="math inline">\(-3.19\)</span> which is smaller than the <span class="math inline">\(10\%\)</span> critical value but larger than the <span class="math inline">\(5\%\)</span> critical value (see Table 16.2 of the book). Thus, the null hypothesis of no cointegration can be rejected at the <span class="math inline">\(10\%\)</span> level but not at the <span class="math inline">\(5\%\)</span> level. This indicates lower power of the EG-ADF test due to the estimation of <span class="math inline">\(\theta\)</span>: when <span class="math inline">\(\theta=1\)</span> is the correct value, we expect the power of the ADF test for a unit root in the residuals series <span class="math inline">\(\widehat{z} = TB10YS - TB3MS\)</span> to be higher than when some estimate <span class="math inline">\(\widehat{\theta}\)</span> is used.</p>
<div id="a-vector-error-correction-model-for-tb10ys_t-and-tb3ms" class="section level5 unnumbered">
<h5>A Vector Error Correction Model for <span class="math inline">\(TB10YS_t\)</span> and <span class="math inline">\(TB3MS\)</span></h5>
<p>If two <span class="math inline">\(I(1)\)</span> time series <span class="math inline">\(X_t\)</span> and <span class="math inline">\(Y_t\)</span> are cointegrated, their differences are stationary and can be modeled in a VAR which is augmented by the regressor <span class="math inline">\(Y_{t-1} - \theta X_{t-1}\)</span>. This is called a <em>vector error correction model</em> (VECM) and <span class="math inline">\(Y_{t} - \theta X_{t}\)</span> is called the <em>error correction term</em>. Lagged values of the error correction term are useful for predicting <span class="math inline">\(\Delta X_t\)</span> and/or <span class="math inline">\(\Delta Y_t\)</span>.</p>
<p>A VECM can be used to model the two interest rates considered in the previous sections. Following the book we specify the VECM to include two lags of both series as regressors and choose <span class="math inline">\(\theta = 1\)</span>, as theory suggests (see above).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">TB10YS &lt;-<span class="st"> </span><span class="kw">window</span>(TB10YS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span> ,<span class="dv">4</span>))
TB3MS &lt;-<span class="st"> </span><span class="kw">window</span>(TB3MS, <span class="kw">c</span>(<span class="dv">1962</span>, <span class="dv">1</span>), <span class="kw">c</span>(<span class="dv">2012</span>, <span class="dv">4</span>))

<span class="co"># set up error correction term</span>
VECM_ECT &lt;-<span class="st"> </span>TB10YS <span class="op">-</span><span class="st"> </span>TB3MS

<span class="co"># estimate both equations of the VECM using &#39;dynlm()&#39;</span>
VECM_EQ1 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">d</span>(TB10YS) <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(TB3MS), <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(TB10YS), <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(VECM_ECT))
VECM_EQ2 &lt;-<span class="st"> </span><span class="kw">dynlm</span>(<span class="kw">d</span>(TB3MS) <span class="op">~</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(TB3MS), <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(<span class="kw">d</span>(TB10YS), <span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">L</span>(VECM_ECT))

<span class="co"># rename regressors for better readability</span>
<span class="kw">names</span>(VECM_EQ1<span class="op">$</span>coefficients) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Intercept&quot;</span>, <span class="st">&quot;D_TB3MS_l1&quot;</span>, <span class="st">&quot;D_TB3MS_l2&quot;</span>,
                                  <span class="st">&quot;D_TB10YS_l1&quot;</span>, <span class="st">&quot;D_TB10YS_l2&quot;</span>, <span class="st">&quot;ect_l1&quot;</span>)
<span class="kw">names</span>(VECM_EQ2<span class="op">$</span>coefficients) &lt;-<span class="st"> </span><span class="kw">names</span>(VECM_EQ1<span class="op">$</span>coefficients)

<span class="co"># coefficient summaries using HAC standard errors</span>
<span class="kw">coeftest</span>(VECM_EQ1, <span class="dt">vcov. =</span> <span class="kw">NeweyWest</span>(VECM_EQ1, <span class="dt">prewhite =</span> F, <span class="dt">adjust =</span> T))</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value Pr(&gt;|t|)   
## Intercept    0.1227089  0.0551419  2.2253 0.027205 * 
## D_TB3MS_l1  -0.0016601  0.0727060 -0.0228 0.981807   
## D_TB3MS_l2  -0.0680845  0.0435059 -1.5649 0.119216   
## D_TB10YS_l1  0.2264878  0.0957071  2.3665 0.018939 * 
## D_TB10YS_l2 -0.0734486  0.0703476 -1.0441 0.297740   
## ect_l1      -0.0878871  0.0285644 -3.0768 0.002393 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coeftest</span>(VECM_EQ2, <span class="dt">vcov. =</span> <span class="kw">NeweyWest</span>(VECM_EQ2, <span class="dt">prewhite =</span> F, <span class="dt">adjust =</span> T))</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error t value Pr(&gt;|t|)  
## Intercept   -0.060746   0.107937 -0.5628  0.57422  
## D_TB3MS_l1   0.240003   0.111611  2.1504  0.03276 *
## D_TB3MS_l2  -0.155883   0.153845 -1.0132  0.31220  
## D_TB10YS_l1  0.113740   0.125571  0.9058  0.36617  
## D_TB10YS_l2 -0.147519   0.112630 -1.3098  0.19182  
## ect_l1       0.031506   0.050519  0.6236  0.53359  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
Thus the two estimated equations of the VECM are
<span class="math display">\[\begin{align*}
 \widehat{\Delta TB3MS}_t =&amp; \, -\underset{(0.11)}{0.06} + \underset{(0.11)}{0.24} \Delta TB3MS_{t-1} -\underset{(0.15)}{0.16} \Delta TB3MS_{t-2} \\ &amp;+ \underset{(0.13)}{0.11} \Delta TB10YS_{t-1} -\underset{(0.11)}{0.15} \Delta TB10YS_{t-2} + \underset{(0.05)}{0.03} ECT_{t-1} \\
 \widehat{\Delta TB10YS}_t =&amp; \, \underset{(0.06)}{0.12} -\underset{(0.07)}{0.00} \Delta TB3MS_{t-1} -\underset{(0.04)}{0.07} \Delta TB3MS_{t-2} \\ &amp;+ \underset{(0.10)}{0.23} \Delta TB10YS_{t-1} -\underset{(0.07)}{0.07} \Delta TB10YS_{t-2} -\underset{(0.03)}{0.09} ECT_{t-1}.
\end{align*}\]</span>
<p>The output produced by <tt>coeftest()</tt> shows that there is little evidence that lagged values of the differenced interest series are useful for prediction. This finding is more pronounced for the equation of the differenced series of the 3-month treasury bill rate, where the error correction term (the lagged term spread) is not significantly different from zero at any common level of significance. However, for the differenced 10-years treasury bonds rate the error correction term is statistically significant at <span class="math inline">\(1\%\)</span> with an estimate of <span class="math inline">\(-0.09\)</span>. This can be interpreted as follows: although both interest rates are nonstationary, their conintegrating relationship allows to predict the <em>change</em> in the 10-years treasury bonds rate using the VECM. In particular, the negative estimate of the coefficient on the error correction term indicates that there will be a negative change in the next period’s 10-years treasury bonds rate when the 10-years treasury bonds rate is unusually high relative to the 3-month treasury bill rate in the current period.</p>
</div>
</div>
</div>
<div id="volatility-clustering-and-autoregressive-conditional-heteroskedasticity" class="section level2">
<h2><span class="header-section-number">16.4</span> Volatility Clustering and Autoregressive Conditional Heteroskedasticity</h2>
<p>Financial time series often exhibit a behavior that is known as <em>volatility clustering</em>: the volatility changes over time and its degree shows a tendency to persist, i.e., there are periods of low volatility and periods where volatility is high. Econometricians call this autoregressive <em>conditional heteroskedasticity</em>. Conditional heteroskedasticity is an interesting property because it can be exploited for forecasting the variance of future periods.</p>
<p>As an example, we consider daily changes in the Whilshire 5000 stock index. The data is available for download at the <a href="https://fred.stlouisfed.org/series/WILL5000INDFC">Federal Reserve Economic Data Base</a>. For consistency with the book we download data from 1989-29-12 to 2013-12-31 (choosing this somewhat larger time span is necessary since later on we will be working with daily changes of the series).</p>
<p>The following code chunk shows how to format the data and how to reproduce Figure 16.3 of the book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># import data on the Wilshire 5000 index</span>
W5000 &lt;-<span class="st"> </span><span class="kw">read.csv2</span>(<span class="st">&quot;data/Wilshire5000.csv&quot;</span>, 
                   <span class="dt">stringsAsFactors =</span> F, 
                   <span class="dt">header =</span> T, 
                   <span class="dt">sep =</span> <span class="st">&quot;,&quot;</span>, 
                   <span class="dt">na.strings =</span> <span class="st">&quot;.&quot;</span>)

<span class="co"># transform the columns</span>
W5000<span class="op">$</span>DATE &lt;-<span class="st"> </span><span class="kw">as.Date</span>(W5000<span class="op">$</span>DATE)
W5000<span class="op">$</span>WILL5000INDFC &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(W5000<span class="op">$</span>WILL5000INDFC)

<span class="co"># remove NAs</span>
W5000 &lt;-<span class="st"> </span><span class="kw">na.omit</span>(W5000)

<span class="co"># compute daily percentage changes</span>
W5000_PC &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="st">&quot;Date&quot;</span> =<span class="st"> </span>W5000<span class="op">$</span>DATE, 
                       <span class="st">&quot;Value&quot;</span> =<span class="st"> </span><span class="kw">as.numeric</span>(<span class="kw">Delt</span>(W5000<span class="op">$</span>WILL5000INDFC) <span class="op">*</span><span class="st"> </span><span class="dv">100</span>))
W5000_PC &lt;-<span class="st"> </span><span class="kw">na.omit</span>(W5000_PC)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot percentage changes</span>
<span class="kw">plot</span>(W5000_PC, 
     <span class="dt">ylab =</span> <span class="st">&quot;Percent&quot;</span>, 
     <span class="dt">main =</span> <span class="st">&quot;Daily Percentage Changes&quot;</span>,
     <span class="dt">type=</span><span class="st">&quot;l&quot;</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">lwd =</span> <span class="fl">0.5</span>)

<span class="co"># add horizontal line at y = 0</span>
<span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:pcw5000"></span>
<img src="ITER_files/figure-html/pcw5000-1.png" alt="Daily Percentage Returns in the Wilshire 5000 Indrx" width="672" />
<p class="caption">
Figure 16.1: Daily Percentage Returns in the Wilshire 5000 Indrx
</p>
</div>
<p>The series of daily percentage changes in the Wilshire index seems to randomly fluctuate around zero, meaning there is little autocorrelation. This is confirmed by a plot of the sample autocorrelation function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot sample autocorrelation of daily percentage changes</span>
<span class="kw">acf</span>(W5000_PC<span class="op">$</span>Value, <span class="dt">main =</span> <span class="st">&quot;Wilshire 5000 Series&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:acfw5000"></span>
<img src="ITER_files/figure-html/acfw5000-1.png" alt="Autocorrelation in Daily Price Changes of W5000 Index" width="672" />
<p class="caption">
Figure 16.2: Autocorrelation in Daily Price Changes of W5000 Index
</p>
</div>
<p>In Figure <a href="atitsr.html#fig:acfw5000">16.2</a> we see that autocorrelations are rather weak so that it is difficult to predict future outcomes using, e.g., an AR model.</p>
<p>However, there is visual evidence in <a href="atitsr.html#fig:pcw5000">16.1</a> that the series of returns exhibits conditional heteroskedasticity since we observe volatility clustering. For some applications it is useful to measure and forecast these patterns. This can be done using models which assume that the volatility can be described by an autoregressive process.</p>
<div id="arch-and-garch-models" class="section level3 unnumbered">
<h3>ARCH and GARCH Models</h3>
Consider <span class="math display">\[Y_t = \beta_0 + \beta_1 Y_{t-1} + \gamma_1 X_{t-1} + u_t,\]</span> an ADL(<span class="math inline">\(1\)</span>,<span class="math inline">\(1\)</span>) regression model. The econometrician Robert <span class="citation">Engle (<a href="#ref-engle1982">1982</a>)</span> proposed to model <span class="math inline">\(\sigma^2_t = Var(u_t | u_{t-1},u_{t-2},\ldots)\)</span>, the conditional variance of the error <span class="math inline">\(u_t\)</span> given its past, by an order <span class="math inline">\(p\)</span> distributed lag model,
<span class="math display" id="eq:archmodel">\[\begin{align}
 \sigma^2_t = \alpha_0 + \alpha_1 u_{t-1}^2 + \alpha_2 u_{t-2}^2 + \dots + \alpha_p u_{t-p}^2, \tag{16.1}
\end{align}\]</span>
<p>called the <em>autoregressive conditional heteroskedasticity</em> (ARCH) model of order <span class="math inline">\(p\)</span>, or short ARCH(<span class="math inline">\(p\)</span>).<a href="#fn13" class="footnoteRef" id="fnref13"><sup>13</sup></a> We assume <span class="math inline">\(\alpha_0&gt;0\)</span> and <span class="math inline">\(\alpha_1,\ldots,\alpha_p\geq0\)</span> to ensure a positive variance <span class="math inline">\(\sigma_t^2&gt;0\)</span>. The general idea is apparent from the model structure: positive coefficients <span class="math inline">\(\alpha_0,\alpha_1,\dots,\alpha_p\)</span> imply that recent large squared errors lead to a large variance, and thus large squared errors, in the current period.</p>
The generalized ARCH (GARCH) model, developed by Tim <span class="citation">Bollerslev (<a href="#ref-bollerslev1986">1986</a>)</span>, is an extension of the ARCH model, where <span class="math inline">\(\sigma^2_t\)</span> is allowed to depend on its own lags and lags of the squared error term. The GARCH(<span class="math inline">\(p\)</span>,<span class="math inline">\(q\)</span>) model is given by
<span class="math display" id="eq:garchmodel">\[\begin{align}
 \sigma^2_t = \alpha_0 + \alpha_1 u_{t-1}^2 + \alpha_2 u_{t-2}^2 + \dots + \alpha_p u_{t-p}^2 + \phi_1 \sigma^2_{t-1} + \dots + \phi_p \sigma^2_{t-q}. \tag{16.2}
\end{align}\]</span>
<p>The GARCH model is an ADL(<span class="math inline">\(p\)</span>,<span class="math inline">\(q\)</span>) model and thus can provide more parsimonious parameterizations than the ARCH model (see the discussion in Appendix 15.2 of the book).</p>
</div>
<div id="application-to-stock-price-volatility" class="section level3 unnumbered">
<h3>Application to Stock Price Volatility</h3>
<p>Maximum likelihood estimates of ARCH and GARCH models are efficient and have normal distributions in large samples, such that the usual methods for conducting inference about the unknown parameters can be applied. The <tt>R</tt> package <tt>fGarch</tt> is a collection of functions for analyzing and modelling the heteroskedastic behavior in time series models. The following application reproduces the results presented in Chapter 16.5 of the book by means of the function <tt>garchFit()</tt>. This function is somewhat sophisticated. It allows for different specifications of the optimization procedure, different error distributions and much more (use <code>?GarchFit</code> for a detailed description of the arguments). In particular, the reported standard errors reported by <tt>garchFit()</tt> are robust.</p>
The GARCH(<span class="math inline">\(1\)</span>,<span class="math inline">\(1\)</span>) model of daily changes in the Wilshire 5000 index we estimate is given by
<span class="math display" id="eq:w5000g11">\[\begin{align}
  R_t =&amp; \, \beta_0 + u_t \ , \ u_t \sim \mathcal{N}(0,\sigma^2_t), \\
  \sigma^2_t =&amp; \, \alpha_0 + \alpha_1 u_{t-1}^2 + \phi_1 \sigma_{t-1}^2 \tag{16.3}
\end{align}\]</span>
<p>where <span class="math inline">\(R_t\)</span> is the percentage change in period <span class="math inline">\(t\)</span>. <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\alpha_0\)</span>, <span class="math inline">\(\alpha_1\)</span> and <span class="math inline">\(\phi_1\)</span> are unknown coefficients and <span class="math inline">\(u_t\)</span> is an error term with conditional mean zero. We do not include any lagged predictors in the equation of <span class="math inline">\(R_t\)</span> because the daily changes in the Wilshire 5000 index reflect daily stock returns which are essentially unpredictable. Note that <span class="math inline">\(u_t\)</span> is assumed to be normally distributed and the variance <span class="math inline">\(\sigma^2_t\)</span> depends on <span class="math inline">\(t\)</span> as it follows the GARCH(<span class="math inline">\(1\)</span>,<span class="math inline">\(1\)</span>) recursion <a href="atitsr.html#eq:w5000g11">(16.3)</a>.</p>
<p>It is straightforward to estimate this model using <tt>garchFit()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate GARCH(1,1) model of daily percentage changes</span>
GARCH_Wilshire &lt;-<span class="st"> </span><span class="kw">garchFit</span>(<span class="dt">data =</span> W5000_PC<span class="op">$</span>Value, <span class="dt">trace =</span> F)</code></pre></div>
We obtain
<span class="math display" id="eq:w5000g11est2" id="eq:w5000g11est1">\[\begin{align}
  \widehat{R}_t =&amp; \, \underset{(0.010)}{0.068}, \tag{16.4} \\
  \widehat{\sigma}^2_t =&amp; \, \underset{(0.002)}{0.011} + \underset{(0.007)}{0.081} u_{t-1}^2 + \underset{(0.008)}{0.909} \sigma_{t-1}^2, \tag{16.5}
\end{align}\]</span>
<p>so the coefficients on <span class="math inline">\(u_{t-1}^2\)</span> and <span class="math inline">\(\sigma^2_{t-1}\)</span> are statistically significant at any common level of significance. One can show that the persistence of movements in <span class="math inline">\(\sigma^2_t\)</span> is determined by the sum of both coefficients, which is <span class="math inline">\(0.99\)</span> here. This indicates that movements in the conditional variance are highly persistent, implying long-lasting periods of high volatility which is consistent with the visual evidence for volatility clustering presented above.</p>
<p>The estimated conditional variance <span class="math inline">\(\widehat{\sigma}^2_t\)</span> can be computed by plugging the residuals from <a href="atitsr.html#eq:w5000g11est1">(16.4)</a> into equation <a href="atitsr.html#eq:w5000g11est2">(16.5)</a>. This is performed automatically by <tt>garchFit()</tt>, so to obtain the estimated conditional standard deviations <span class="math inline">\(\widehat{\sigma}_t\)</span> we only have to read out the values from <tt>GARCH_Wilshire</tt> by appending <tt>@sigma.t</tt>.</p>
<p>Using the <span class="math inline">\(\widehat{\sigma}_t\)</span> we plot bands of <span class="math inline">\(\pm\)</span> one conditional standard deviation along with deviations of the series of daily percentage changes in the Wilshire 5000 index from its mean. The following code chunk reproduces Figure 16.4 of the book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute deviations of the percentage changes from their mean</span>
dev_mean_W5000_PC &lt;-<span class="st"> </span>W5000_PC<span class="op">$</span>Value <span class="op">-</span><span class="st"> </span>GARCH_Wilshire<span class="op">@</span>fit<span class="op">$</span>coef[<span class="dv">1</span>]

<span class="co"># plot deviation of percentage changes from mean</span>
<span class="kw">plot</span>(W5000_PC<span class="op">$</span>Date, dev_mean_W5000_PC, 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Percent&quot;</span>, 
     <span class="dt">xlab =</span> <span class="st">&quot;Date&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Estimated Bands of +- One Conditional Standard Deviation&quot;</span>,
     <span class="dt">lwd =</span> <span class="fl">0.2</span>)

<span class="co"># add horizontal line at y = 0</span>
<span class="kw">abline</span>(<span class="dv">0</span>, <span class="dv">0</span>)

<span class="co"># add GARCH(1,1) confidence bands (one standard deviation) to the plot</span>
<span class="kw">lines</span>(W5000_PC<span class="op">$</span>Date, 
      GARCH_Wilshire<span class="op">@</span>fit<span class="op">$</span>coef[<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>GARCH_Wilshire<span class="op">@</span>sigma.t, 
      <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>, 
      <span class="dt">lwd =</span> <span class="fl">0.5</span>)

<span class="kw">lines</span>(W5000_PC<span class="op">$</span>Date, 
      GARCH_Wilshire<span class="op">@</span>fit<span class="op">$</span>coef[<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span>GARCH_Wilshire<span class="op">@</span>sigma.t, 
      <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>, 
      <span class="dt">lwd =</span> <span class="fl">0.5</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-733-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The bands of the estimated conditional standard deviations track the observed heteroskedasticity in the series of daily changes of the Wilshire 5000 index quite well. This is useful for quantifying the time-varying volatility and the resulting risk for investors holding stocks summarized by the index. Furthermore, this GARCH model may also be used to produce forecast intervals whose widths depend on the volatility of the most recent periods.</p>
</div>
<div id="summary-8" class="section level3 unnumbered">
<h3>Summary</h3>
<ul>
<li><p>We have discussed how vector autoregressions are conveniently estimated and used for forecasting in <tt>R</tt> by means of functions from the <tt>vars</tt> package.</p></li>
<li><p>The package <tt>urca</tt> supplies advanced methods for unit root and cointegration analysis like the DF-GLS and the EG-ADF tests. In an application we have found evidence that 3-months and 10-year interest rates have a common stochastic trend (that is, they are cointegrated) and thus can be modeled using a vector error correction model.</p></li>
<li><p>Furthermore, we have introduced the concept of volatility clustering and demonstrated how the function <tt>garchFit()</tt> from the package <tt>fGarch</tt> can be employed to estimate a GARCH(<span class="math inline">\(1\)</span>,<span class="math inline">\(1\)</span>) model of the conditional heteroskedasticity inherent to returns of the Wilshire 5000 stock index.</p></li>
</ul>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-AER">
<p>Kleiber, C., &amp; Zeileis, A. (2017). AER: Applied Econometrics with R (Version 1.2-5). Retrieved from <a href="https://CRAN.R-project.org/package=AER" class="uri">https://CRAN.R-project.org/package=AER</a></p>
</div>
<div id="ref-R-dynlm">
<p>Zeileis, A. (2016). dynlm: Dynamic Linear Regression (Version 0.3-5). Retrieved from <a href="https://CRAN.R-project.org/package=dynlm" class="uri">https://CRAN.R-project.org/package=dynlm</a></p>
</div>
<div id="ref-R-fGarch">
<p>Wuertz, D., Setz, T., Chalabi, Y., Boudt, C., Chausse, P., &amp; Miklovac, M. (2017). fGarch: Rmetrics - Autoregressive Conditional Heteroskedastic Modelling (Version 3042.83). Retrieved from <a href="https://CRAN.R-project.org/package=fGarch" class="uri">https://CRAN.R-project.org/package=fGarch</a></p>
</div>
<div id="ref-R-quantmod">
<p>Ryan, J. A., &amp; Ulrich, J. M. (2018). quantmod: Quantitative Financial Modelling Framework (Version 0.4-13). Retrieved from <a href="https://CRAN.R-project.org/package=quantmod" class="uri">https://CRAN.R-project.org/package=quantmod</a></p>
</div>
<div id="ref-R-readxl">
<p>Wickham, H., &amp; Bryan, J. (2018). readxl: Read Excel Files (Version 1.1.0). Retrieved from <a href="https://CRAN.R-project.org/package=readxl" class="uri">https://CRAN.R-project.org/package=readxl</a></p>
</div>
<div id="ref-R-scales">
<p>Wickham, H. (2017). scales: Scale Functions for Visualization (Version 0.5.0). Retrieved from <a href="https://CRAN.R-project.org/package=scales" class="uri">https://CRAN.R-project.org/package=scales</a></p>
</div>
<div id="ref-R-vars">
<p>Pfaff, B. (2013). vars: VAR Modelling (Version 1.5-2). Retrieved from <a href="https://CRAN.R-project.org/package=vars" class="uri">https://CRAN.R-project.org/package=vars</a></p>
</div>
<div id="ref-stock2015">
<p>Stock, J., &amp; Watson, M. (2015). <em>Introduction to Econometrics, Third Update, Global Edition</em>. Pearson Education Limited.</p>
</div>
<div id="ref-elliott1996">
<p>Elliott, G., Rothenberg, T. J., &amp; Stock, J. H. (1996). Efficient Tests for an Autoregressive Unit Root. <em>Econometrica</em>, <em>64</em>(4), 813–836.</p>
</div>
<div id="ref-engle1987">
<p>Engle, R., &amp; Granger, C. (1987). Co-integration and Error Correction: Representation, Estimation and Testing. <em>Econometrica</em>, <em>55</em>(2), 251–76.</p>
</div>
<div id="ref-engle1982">
<p>Engle, R. (1982). Autoregressive conditional heteroscedasticity with estimates of the variance of united kingdom inflation. <em>Econometrica</em>, <em>50</em>(4), 987–1007.</p>
</div>
<div id="ref-bollerslev1986">
<p>Bollerslev, T. (1986). Generalized Autoregressive Conditional Heteroskedasticity. <em>Journal of Econometrics</em>, <em>31</em>(3), 307–327.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="12">
<li id="fn12"><p>Note: <tt>ur.df()</tt> reports two test statistics when there is a drift in the ADF regression. The first of which (the one we are interested in here) is the <span class="math inline">\(t\)</span>-statistic for the test that the coefficient on the first lag of the series is 0. The second one is the <span class="math inline">\(t\)</span>-statistic for the hypothesis test that the drift term equals <span class="math inline">\(0\)</span>.<a href="atitsr.html#fnref12">↩</a></p></li>
<li id="fn13"><p>Although we introduce the ARCH model as a component in an ADL(<span class="math inline">\(1\)</span>,<span class="math inline">\(1\)</span>) model, it can be used for modelling the conditional zero-mean error term of any time series model.<a href="atitsr.html#fnref13">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="eodce.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
