<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Using R for Introduction to Econometrics</title>
  <meta name="description" content="Using <tt>R</tt> for Introduction to Econometrics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Using R for Introduction to Econometrics" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Using R for Introduction to Econometrics" />
  
  
  

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-07-29">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="a-general-strategy-for-modelling-nonlinear-regression-functions.html">
<link rel="next" href="interactions-between-independent-variables.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="MathJax-2.7.2/MathJax.js?config=default"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>

<!-- datacamp-light-latest -->

<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>


<!-- <script src="js/d3.v3.min.js"></script>
<script src="js/leastsquares.js"></script>
<script src="js/d3functions.js"></script>
<script src="d3.slider.js"></script>
<script src="slrm.js"></script> -->


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">URFITE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="a-very-short-introduction-to-r-and-rstudio.html"><a href="a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="nrf.html"><a href="nrf.html"><i class="fa fa-check"></i><b>2</b> Nonlinear Regression Functions</a><ul>
<li class="chapter" data-level="2.1" data-path="a-general-strategy-for-modelling-nonlinear-regression-functions.html"><a href="a-general-strategy-for-modelling-nonlinear-regression-functions.html"><i class="fa fa-check"></i><b>2.1</b> A General Strategy for Modelling Nonlinear Regression Functions</a></li>
<li class="chapter" data-level="2.2" data-path="nfoasiv.html"><a href="nfoasiv.html"><i class="fa fa-check"></i><b>2.2</b> Nonlinear Functions of a Single Independent Variable</a><ul>
<li class="chapter" data-level="" data-path="nfoasiv.html"><a href="nfoasiv.html#polynomials"><i class="fa fa-check"></i>Polynomials</a></li>
<li class="chapter" data-level="" data-path="nfoasiv.html"><a href="nfoasiv.html#logarithms"><i class="fa fa-check"></i>Logarithms</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="interactions-between-independent-variables.html"><a href="interactions-between-independent-variables.html"><i class="fa fa-check"></i><b>2.3</b> Interactions Between Independent Variables</a></li>
<li class="chapter" data-level="2.4" data-path="nonlinear-effects-on-test-scores-of-the-student-teacher-ratio.html"><a href="nonlinear-effects-on-test-scores-of-the-student-teacher-ratio.html"><i class="fa fa-check"></i><b>2.4</b> Nonlinear Effects on Test Scores of the Student-Teacher Ratio</a></li>
<li class="chapter" data-level="2.5" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>2.5</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using <tt>R</tt> for Introduction to Econometrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="nfoasiv" class="section level2">
<h2><span class="header-section-number">2.2</span> Nonlinear Functions of a Single Independent Variable</h2>
<div id="polynomials" class="section level3 unnumbered">
<h3>Polynomials</h3>
<p>The approach used to obtain a quadratic model can be generalized to polynomial models of arbitrary degree <span class="math inline">\(r\)</span>. <span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \beta_2 X_i^2 + \ldots + \beta_r X_i^r + u_i\]</span></p>
<p>A cubic model (<span class="math inline">\(r=3\)</span>) for instance can be estimated in the same way as the quadratic model; we just have to add <tt>I(income^3)</tt> to the <tt>formula</tt> argument in our call of <tt>lm()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cubic_model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(income<span class="op">^</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(income<span class="op">^</span><span class="dv">3</span>), <span class="dt">data =</span> CASchools)</code></pre></div>
<p>In practice the question will arise which polynomial order should be chosen. First note that, similarly as for <span class="math inline">\(r=2\)</span>, we can test the null hypothesis that the true relation is linear against the alternative hypothesis that the relationship is a polynomial of degree <span class="math inline">\(r\)</span>:</p>
<p><span class="math display">\[ H_0: \beta_2=0, \ \beta_3=0,\dots,\beta_r=0 \ \ \ \text{vs.} \ \ \ H_1: \text{at least one} \ \beta_j\neq0, \ j=2,\dots,r \]</span></p>
<p>This is a joint null hypothesis with <span class="math inline">\(r-1\)</span> restrictions so it can be tested using the <span class="math inline">\(F\)</span>-test presented in Chapter <a href="#htaciimr"><strong>??</strong></a>. Remember that the function <tt>linearHypothesis()</tt> can used to conduct such tests. If, for example, we would like to test the null hypothesis of a linear model against the alternative of a polynomial of a maximal degree <span class="math inline">\(r=3\)</span>, we could simply do the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test the hypothesis</span>
<span class="kw">linearHypothesis</span>(cubic_model, 
                 <span class="kw">c</span>(<span class="st">&quot;I(income^2)=0&quot;</span>, <span class="st">&quot;I(income^3)=0&quot;</span>),
                 <span class="dt">white.adj =</span> <span class="st">&quot;hc1&quot;</span>
)</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## I(income^2) = 0
## I(income^3) = 0
## 
## Model 1: restricted model
## Model 2: score ~ income + I(income^2) + I(income^3)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F    Pr(&gt;F)    
## 1    418                        
## 2    416  2 37.691 9.043e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The <span class="math inline">\(p\)</span>-value for this test is very small so that we reject the null hypothesis. However, this does not tell us <em>which</em> <span class="math inline">\(r\)</span> to choose. In practice, one approach to determine the degree of the polynomial is to use <em>sequential testing</em>:</p>
<ol style="list-style-type: decimal">
<li>Estimate a polynomial model for some maximum value <span class="math inline">\(r\)</span>.</li>
<li>Use a <span class="math inline">\(t\)</span>-test to test whether <span class="math inline">\(\beta_r = 0\)</span>. <b>Rejection</b> of the null means that <span class="math inline">\(X^r\)</span> belongs in the regression equation.</li>
<li><b>Acceptance</b> of the null in step 2 means that <span class="math inline">\(X^r\)</span> can be eliminated from the model. Continue by repeating step 1 with order <span class="math inline">\(r-1\)</span> and test whether <span class="math inline">\(\beta_{r-1}=0\)</span>. If the test rejects, use a polynomial model of order <span class="math inline">\(r-1\)</span>.</li>
<li>If the tests from step 3 rejects, continue with the procedure until the coefficient on the highest power is statistically significant.</li>
</ol>
<p>There is no unambiguous guideline how to choose <span class="math inline">\(r\)</span> in step one. However, as pointed out in <span class="citation">Stock &amp; Watson (<a href="#ref-stock2015">2015</a>)</span>, economic data is often smooth such that it is appropriate to choose small orders like <span class="math inline">\(2\)</span>, <span class="math inline">\(3\)</span>, or <span class="math inline">\(4\)</span>.</p>
<p>We will now demonstrate how to apply <it>sequential testing</it> by the example of the cubic model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(cubic_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = score ~ income + I(income^2) + I(income^3), data = CASchools)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -44.28  -9.21   0.20   8.32  31.16 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  6.001e+02  5.830e+00 102.937  &lt; 2e-16 ***
## income       5.019e+00  8.595e-01   5.839 1.06e-08 ***
## I(income^2) -9.581e-02  3.736e-02  -2.564   0.0107 *  
## I(income^3)  6.855e-04  4.720e-04   1.452   0.1471    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 12.71 on 416 degrees of freedom
## Multiple R-squared:  0.5584, Adjusted R-squared:  0.5552 
## F-statistic: 175.4 on 3 and 416 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The estimated cubic model stored in <tt>cubic_model</tt> is</p>
<p><span class="math display">\[ \widehat{TestScore}_i = \underset{(5.83)}{600.1} + \underset{(0.86)}{5.02} \times income -\underset{(0.03)}{0.96} \times income^2 - \underset{(0.00047)}{0.00069} \times income^3. \]</span></p>
<p>From the output we can tell that the <span class="math inline">\(t\)</span>-statistic on <span class="math inline">\(income^3\)</span> is <span class="math inline">\(1.42\)</span> so the null that the relationship is quadratic cannot be rejected, even at the <span class="math inline">\(10\%\)</span> level. This is contrary to the result presented book which reports robust standard errors throughout so we will also use robust variance-covariance estimation to reproduce these results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load the lmtest package for coeftest()</span>
<span class="kw">library</span>(lmtest)

<span class="co"># test the hypothesis using robust standard errors</span>
<span class="kw">coeftest</span>(cubic_model, <span class="dt">vcov. =</span> <span class="kw">vcovHC</span>(cubic_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                Estimate  Std. Error  t value  Pr(&gt;|t|)    
## (Intercept)  6.0008e+02  5.1021e+00 117.6150 &lt; 2.2e-16 ***
## income       5.0187e+00  7.0735e-01   7.0950 5.606e-12 ***
## I(income^2) -9.5805e-02  2.8954e-02  -3.3089  0.001018 ** 
## I(income^3)  6.8549e-04  3.4706e-04   1.9751  0.048918 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notice that the reported standard errors have changed. Furthermore, the coefficient for <code>income^3</code> is now significant at the <span class="math inline">\(5\%\)</span> level. This means we reject the hypothesis that the regression function is quadratic against the alternative that it is cubic. Furthermore, we can also test if the coefficients for <tt>income^2</tt> and <tt>income^3</tt> are jointly significant using a robust version of the <span class="math inline">\(F\)</span>-test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># robust F-test for </span>
<span class="kw">linearHypothesis</span>(cubic_model, 
                 <span class="dt">vcov. =</span> <span class="kw">vcovHC</span>(cubic_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>),
                 <span class="kw">c</span>(<span class="st">&quot;I(income^2)=0&quot;</span>, <span class="st">&quot;I(income^3)=0&quot;</span>)
                 )</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## I(income^2) = 0
## I(income^3) = 0
## 
## Model 1: restricted model
## Model 2: score ~ income + I(income^2) + I(income^3)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F    Pr(&gt;F)    
## 1    418                        
## 2    416  2 37.691 9.043e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>With a <span class="math inline">\(p\)</span>-value of <span class="math inline">\(9.043e^{-16}\)</span>, i.e. much less than <span class="math inline">\(0.05\)</span>, the null hypothesis of linearity is rejected in favor of the alternative that the relationship is quadratic <em>or</em> cubic.</p>
<div id="interpretation-of-coefficients-in-nonlinear-regression-models" class="section level4 unnumbered">
<h4>Interpretation of Coefficients in Nonlinear Regression Models</h4>
<p>The coefficients in polynomial regression models do not have a simple interpretation. Why is that? Think of a quadratic model: it is not helpful to think of the coefficient on <span class="math inline">\(X\)</span> as the expected change in <span class="math inline">\(Y\)</span> associated with a change in <span class="math inline">\(X\)</span> holding the other regressors constant because one other is <span class="math inline">\(X^2\)</span> which changes as <span class="math inline">\(X\)</span> is varied. This is also the case for other deviations from linearity, for example in models where regressors and/or the dependent variable are log-transformed. The best way to approach this is to calculate the estimated effect on <span class="math inline">\(Y\)</span> associated with a change in <span class="math inline">\(X\)</span> for one or more values of <span class="math inline">\(X\)</span>. This idea is summarized in Key Concept 8.1.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 8.1
</h3>
<h3 class="left">
The Expected Effect on <span class="math inline">\(Y\)</span> of a Change in <span class="math inline">\(X_1\)</span> in a Nonlinear Regression Model
</h3>
<p>Consider the nonlinear population regression model</p>
<p><span class="math display">\[ Y_i = f(X_{1i}, X_{2i}, \dots, X_{ki}) + u_i \ , \ i=1,\dots,n,\]</span></p>
<p>where <span class="math inline">\(f(X_{1i}, X_{2i}, \dots, X_{ki})\)</span> is the population regression function and <span class="math inline">\(u_i\)</span> is the error term.</p>
<p>Denote <span class="math inline">\(\Delta Y\)</span> the expected change in <span class="math inline">\(Y\)</span> associated with <span class="math inline">\(\Delta X_1\)</span>, the change in <span class="math inline">\(X_1\)</span> while holding <span class="math inline">\(X_2, \cdots , X_k\)</span> constant. That is, the expected change in <span class="math inline">\(Y\)</span> is the difference</p>
<p><span class="math display">\[\Delta Y = f(X_1 + \Delta X_1, X_2, \cdots, X_k) - f(X_1, X_2, \cdots, X_k).\]</span></p>
<p>The estimator of this unknown population difference is the difference between the predicted values for these two cases. Let <span class="math inline">\(\hat{f}(X_1, X_2, \cdots, X_k)\)</span> be the predicted value of of <span class="math inline">\(Y\)</span> based on the estimator <span class="math inline">\(\hat{f}\)</span> of the population regression function. Then the predicted change in <span class="math inline">\(Y\)</span> is</p>
<span class="math display">\[\Delta \widehat{Y} = \hat{f}(X_1 + \Delta X_1, X_2, \cdots, X_k) - \hat{f}(X_1, X_2, \cdots, X_k).\]</span>
</p>
</div>
<p>For example, we may ask the following: what is the predicted change in test scores associated with a one unit change (i.e. <span class="math inline">\(\$1000\)</span>) in income, based on the estimated quadratic regression function</p>
<p><span class="math display">\[\widehat{TestScore} = 607.3 + 3.85 \times income - 0.0423 \times income^2\ ?\]</span></p>
<p>Because the regression function is quadratic, this effect depends on the initial district income. We therefore consider two cases:</p>
<ol style="list-style-type: decimal">
<li><p>An increase in district income form <span class="math inline">\(10\)</span> to <span class="math inline">\(11\)</span> (i.e. from <span class="math inline">\(\$10000\)</span> per capita to <span class="math inline">\(\$11000\)</span>)</p></li>
<li><p>An increase in district income from <span class="math inline">\(40\)</span> to <span class="math inline">\(41\)</span> (that is from <span class="math inline">\(\$40000\)</span> to <span class="math inline">\(\$41000\)</span>).</p></li>
</ol>
<p>In order to obtain the <span class="math inline">\(\Delta \widehat{Y}\)</span> associated with a change in income form <span class="math inline">\(10\)</span> to <span class="math inline">\(11\)</span>, we use the following formula:</p>
<p><span class="math display">\[\Delta \widehat{Y} = \left(\hat{\beta}_0 + \hat{\beta}_1 \times 11 + \hat{\beta}_2 \times 11^2\right) - \left(\hat{\beta}_0 + \hat{\beta}_1 \times 10 + \hat{\beta}_2 \times 10^2\right) \]</span> To compute <span class="math inline">\(\widehat{Y}\)</span> using <tt>R</tt> we may use <tt>predict()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute and assign the quadratic model</span>
quadriatic_model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>income <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(income<span class="op">^</span><span class="dv">2</span>), <span class="dt">data =</span> CASchools)

<span class="co"># set up data to predict</span>
new_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">income =</span> <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">11</span>))

<span class="co"># do the prediction</span>
Y_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(quadriatic_model, <span class="dt">newdata =</span> new_data)

<span class="co"># compute the difference</span>
<span class="kw">diff</span>(Y_hat)</code></pre></div>
<pre><code>##        2 
## 2.962517</code></pre>
<p>Analogously we can compute the effect of a change in district income from <span class="math inline">\(40\)</span> to <span class="math inline">\(41\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up data to predict</span>
new_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">income =</span> <span class="kw">c</span>(<span class="dv">40</span>, <span class="dv">41</span>))

<span class="co"># do the prediction</span>
Y_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(quadriatic_model, <span class="dt">newdata =</span> new_data)

<span class="co"># compute the difference</span>
<span class="kw">diff</span>(Y_hat)</code></pre></div>
<pre><code>##         2 
## 0.4240097</code></pre>
<p>So for the quadratic model, the expected change in <span class="math inline">\(TestScore\)</span> induced by an increase in <span class="math inline">\(income\)</span> from <span class="math inline">\(10\)</span> to <span class="math inline">\(11\)</span> is about <span class="math inline">\(2.96\)</span> points but an increase in <span class="math inline">\(income\)</span> from <span class="math inline">\(40\)</span> to <span class="math inline">\(41\)</span> increases the predicted score by only <span class="math inline">\(0.42\)</span>. Hence the slope of the estimated quadratic regression function is <em>steeper</em> at low levels of income than at higher levels.</p>
</div>
</div>
<div id="logarithms" class="section level3 unnumbered">
<h3>Logarithms</h3>
<p>Another way to specify a nonlinear regression function is to use the natural logarithm of <span class="math inline">\(Y\)</span> and/or <span class="math inline">\(X\)</span>. Logarithms convert changes in variables into percentage changes which is convenient as many relationships are naturally expressed in terms of percentages.</p>
<p>There are three different cases in which logarithms might be used.</p>
<ol style="list-style-type: decimal">
<li><p><span class="math inline">\(X\)</span> could be transformed by taking its logarithm but <span class="math inline">\(Y\)</span> is not.</p></li>
<li><p>We could transform <span class="math inline">\(Y\)</span> to its logarithm but leave <span class="math inline">\(X\)</span> at level.</p></li>
<li><p>A third case is that both <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are transformed to their logarithms.</p></li>
</ol>
<p>The interpretation of the regression coefficients is different in each case.</p>
<div id="case-i-x-is-in-logarithm-y-is-not." class="section level4 unnumbered">
<h4>Case I: <span class="math inline">\(X\)</span> is in Logarithm, <span class="math inline">\(Y\)</span> is not.</h4>
<p>The regression model then is</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 \times \ln(X_i) + u_i \text{, } i=1,...,n. \]</span> Similar as for polynomial regression we do not have to create a new variable by computing <span class="math inline">\(\ln(X)\)</span>. We can simply adjust the <tt>formula</tt> argument of <tt>lm()</tt> to tell <tt>R</tt> that the log-transformation of a variable should be used.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate a level-log model</span>
LinearLog_model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(income), <span class="dt">data =</span> CASchools)

<span class="co"># compute robust summary</span>
<span class="kw">coeftest</span>(LinearLog_model, 
         <span class="dt">vcov =</span> <span class="kw">vcovHC</span>(LinearLog_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)
         )</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) 557.8323     3.8399 145.271 &lt; 2.2e-16 ***
## log(income)  36.4197     1.3969  26.071 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to the output the estimated regression function is:</p>
<p><span class="math display">\[\widehat{TestScore} = 557.8 + 36.42 \times \ln(income).\]</span></p>
<p>Let us draw a plot of this function.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># draw scatterplot</span>
<span class="kw">plot</span>(score <span class="op">~</span><span class="st"> </span>income, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>,
     <span class="dt">pch =</span> <span class="dv">20</span>,
     <span class="dt">data =</span> CASchools,
     <span class="dt">main =</span> <span class="st">&quot;Linear-Log Regression Line&quot;</span>)

<span class="co"># add Linear-Log regression line</span>
order_id  &lt;-<span class="st"> </span><span class="kw">order</span>(CASchools<span class="op">$</span>income)

<span class="kw">lines</span>(CASchools<span class="op">$</span>income[order_id],
      <span class="kw">fitted</span>(LinearLog_model)[order_id], 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, 
      <span class="dt">lwd =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="URFITE_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>We can interpret <span class="math inline">\(\hat{\beta}_1\)</span> as follows: a <span class="math inline">\(1\%\)</span> increase in income is associated with an increase in test scores of <span class="math inline">\(0.01 \times 36.42 = 0.36\)</span> points. In order to get the estimated effect of <it>a one unit </it> change in income (that is a change in the original units, thousands of dollars) on test scores, the method presented in Key Concept 8.1 can be used.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up new data</span>
new_data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">income =</span> <span class="kw">c</span>(<span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">40</span>, <span class="dv">41</span>))

<span class="co"># predict outcomes </span>
Y_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(LinearLog_model, <span class="dt">newdata =</span> new_data)

<span class="co"># compute expected difference</span>
changes &lt;-<span class="st"> </span><span class="kw">matrix</span>(Y_hat, <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)
changes[, <span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>changes[, <span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 3.471166 0.899297</code></pre>
<p>The estimated model states that for an income increase from <span class="math inline">\(\$10000\)</span> to <span class="math inline">\(\$11000\)</span>, test scores increase by an expected amount of <span class="math inline">\(3.47\)</span> points. When income increases from <span class="math inline">\(\$40000\)</span> to <span class="math inline">\(\$41000\)</span>, the expected increase in test scores is only about <span class="math inline">\(0.90\)</span> points.</p>
</div>
<div id="case-ii-y-is-in-logarithm-x-is-not" class="section level4 unnumbered">
<h4>Case II: <span class="math inline">\(Y\)</span> is in Logarithm, <span class="math inline">\(X\)</span> is not</h4>
<p>If you want to learn about the absolute impact of an explanatory variable on the dependent variable, it is not recommended to log-transform the latter. There are, however, cases where we want to learn about <span class="math inline">\(\ln(Y)\)</span> instead of <span class="math inline">\(Y\)</span>.</p>
<p>The corresponding regression model then is</p>
<p><span class="math display">\[ \ln(Y_i) = \beta_0 + \beta_1 \times X_i + u_i \ \ , \ \ i=1,...,n. \]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate a log-linear model </span>
LogLinear_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(score) <span class="op">~</span><span class="st"> </span>income, <span class="dt">data =</span> CASchools)

<span class="co"># compute a robust summary</span>
<span class="kw">coeftest</span>(LogLinear_model, 
         <span class="dt">vcov =</span> <span class="kw">vcovHC</span>(LogLinear_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)
         )</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept) 6.43936234 0.00289382 2225.210 &lt; 2.2e-16 ***
## income      0.00284407 0.00017509   16.244 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated regression function is <span class="math display">\[\widehat{\ln(TestScore)} = 6.439 + 0.00284 \times income.\]</span> Since we are interested in <span class="math inline">\(\ln(Y)\)</span> rather than <span class="math inline">\(Y\)</span>, we <em>do not</em> re-transform the dependent variable.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># scatterplot</span>
<span class="kw">plot</span>(<span class="kw">log</span>(score) <span class="op">~</span><span class="st"> </span>income, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">pch =</span> <span class="dv">20</span>, 
     <span class="dt">data =</span> CASchools,
     <span class="dt">main =</span> <span class="st">&quot;Log-Linear Regression Function&quot;</span>
     )

<span class="co"># add the Log-Linear regression line</span>
order_id  &lt;-<span class="st"> </span><span class="kw">order</span>(CASchools<span class="op">$</span>income)

<span class="kw">lines</span>(CASchools<span class="op">$</span>income[order_id], 
      <span class="kw">fitted</span>(LogLinear_model)[order_id], 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, 
      <span class="dt">lwd =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="URFITE_files/figure-html/unnamed-chunk-27-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>Note that the <span class="math inline">\(Y\)</span>-Axis is now log-transformed.</p>
<p>In a log-linear model, a one-unit change in <span class="math inline">\(X\)</span> is associated with an estimated <span class="math inline">\(100 \times \hat\beta_1 \%\)</span> change in <span class="math inline">\(Y\)</span>. This time we leave the <span class="math inline">\(X\)</span> values unchanged.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># do the predictions</span>
Y_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(LogLinear_model, <span class="dt">newdata =</span> new_data)

<span class="co"># compute difference in changes</span>
changes &lt;-<span class="st"> </span><span class="kw">matrix</span>(Y_hat, <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)
changes[, <span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>changes[, <span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 0.00284407 0.00284407</code></pre>
</div>
<div id="case-iii-x-and-y-are-in-logarithms" class="section level4 unnumbered">
<h4>Case III: <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are in Logarithms</h4>
<p>The log-log regression model is</p>
<p><span class="math display">\[\ln(Y_i) = \beta_0 + \beta_1 \times \ln(X_i) + u_i \ \ , \ \ i=1,...,n. \]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Estimate the Log-Log model</span>
LogLog_model &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="kw">log</span>(score) <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(income), <span class="dt">data =</span> CASchools)

<span class="co"># print robust summary to the console</span>
<span class="kw">coeftest</span>(LogLog_model, 
         <span class="dt">vcov =</span> <span class="kw">vcovHC</span>(LogLog_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)
         )</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error  t value  Pr(&gt;|t|)    
## (Intercept) 6.3363494  0.0059246 1069.501 &lt; 2.2e-16 ***
## log(income) 0.0554190  0.0021446   25.841 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated regression function hence is <span class="math display">\[\widehat{\ln(TestScore)} = 6.336 + 0.0554 \times \ln(income).\]</span></p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># scatterplot</span>
<span class="kw">plot</span>(<span class="kw">log</span>(score) <span class="op">~</span><span class="st"> </span>income, 
     <span class="dt">data =</span> CASchools,
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">pch =</span> <span class="dv">20</span>,
     <span class="dt">main =</span> <span class="st">&quot;Log-Log Regression Function&quot;</span>)

<span class="co"># plot the estimate log-log regression line</span>
<span class="kw">lines</span>(<span class="kw">sort</span>(CASchools<span class="op">$</span>income), 
      <span class="kw">fitted</span>(LogLog_model)[<span class="kw">order</span>(CASchools<span class="op">$</span>income)], 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, 
      <span class="dt">lwd =</span> <span class="dv">2</span>)</code></pre></div>
<p><img src="URFITE_files/figure-html/unnamed-chunk-29-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>In a log-log model, a <span class="math inline">\(1\%\)</span> change in <span class="math inline">\(X\)</span> is associated with an estimated <span class="math inline">\(\hat\beta_1 \%\)</span> change in <span class="math inline">\(Y\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># predict Y</span>
Y_hat &lt;-<span class="st"> </span><span class="kw">predict</span>(LogLog_model, <span class="dt">newdata =</span> new_data)

<span class="co"># compute changes</span>
changes &lt;-<span class="st"> </span><span class="kw">matrix</span>(Y_hat, <span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)
changes[ ,<span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>changes[ ,<span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 0.005281992 0.001368439</code></pre>
<p>Key Concept 8.2 summarizes the three logarithmic regression models.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 8.2
</h3>
<h3 class="left">
Logarithms in Regression: Three Cases
</h3>
<p>
<p>Logarithms can be used to transform the dependent variable <span class="math inline">\(Y\)</span> or the independent variable <span class="math inline">\(X\)</span>, or both (the variable being transformed must be positive). The following table summarizes these three cases and the interpretation of the regression coefficient <span class="math inline">\(\beta_1\)</span>. In each case, <span class="math inline">\(\beta_1\)</span>, can be estimated by applying OLS after taking the logarithm(s) of the dependent and/or the independent variable.</p>
<table>
<thead>
<tr class="header">
<th align="left">
Case
</th>
<th align="left">
Model Specification
</th>
<th align="left">
Interpretation of <span class="math inline">\(\beta_1\)</span>
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">
<span class="math inline">\((I)\)</span>
</td>
<td align="left">
<span class="math inline">\(Y_i = \beta_0 + \beta_1 \ln(X_i) + u_i\)</span>
</td>
<td align="left">
A <span class="math inline">\(1 \%\)</span> change in <span class="math inline">\(X\)</span> is associated with a change in <span class="math inline">\(Y\)</span> of <span class="math inline">\(0.01 \times \beta_1\)</span>.
</td>
</tr>
<tr class="even">
<td align="left">
<span class="math inline">\((II)\)</span>
</td>
<td align="left">
<span class="math inline">\(\ln(Y_i) = \beta_0 + \beta_1 X_i + u_i\)</span>
</td>
<td align="left">
A change in <span class="math inline">\(X\)</span> by one unit (<span class="math inline">\(\Delta X = 1\)</span>) is associated with a <span class="math inline">\(100 \times \beta_1 \%\)</span> change in <span class="math inline">\(Y\)</span>.
</td>
</tr>
<tr class="odd">
<td align="left">
<span class="math inline">\((III)\)</span>
</td>
<td align="left">
<span class="math inline">\(\ln(Y_i) = \beta_0 + \beta_1 \ln(X_i) + u_i\)</span>
</td>
<td align="left">
A <span class="math inline">\(1\%\)</span> change in <span class="math inline">\(X\)</span> is associated with a <span class="math inline">\(\beta_1\%\)</span> change in <span class="math inline">\(Y\)</span>, so <span class="math inline">\(\beta_1\)</span> is the elasticity of <span class="math inline">\(Y\)</span> with respect to <span class="math inline">\(X\)</span>.
</td>
</tr>
</tbody>
</table>
</p>
</div>
<p>Of course we can also estimate a <it>polylog</it> model like</p>
<p><span class="math display">\[ TestScore_i = \beta_0 + \beta_1 \times \ln(income_i) + \beta_2 \times \ln(income_i)^2 + \beta_3 \times \ln(income_i)^3 + u_i \]</span></p>
<p>which models the dependent variable <span class="math inline">\(TestScore\)</span> by a third-degree polynomial of the log-transformed regressor <span class="math inline">\(income\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate the polylog model</span>
polyLog_model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span><span class="kw">log</span>(income) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(<span class="kw">log</span>(income)<span class="op">^</span><span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="kw">I</span>(<span class="kw">log</span>(income)<span class="op">^</span><span class="dv">3</span>), 
                    <span class="dt">data =</span> CASchools)

<span class="co"># print robust summary to the console</span>
<span class="kw">coeftest</span>(polyLog_model, 
         <span class="dt">vcov =</span> <span class="kw">vcovHC</span>(polyLog_model, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##                  Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)      486.1341    79.3825  6.1239 2.115e-09 ***
## log(income)      113.3820    87.8837  1.2901    0.1977    
## I(log(income)^2) -26.9111    31.7457 -0.8477    0.3971    
## I(log(income)^3)   3.0632     3.7369  0.8197    0.4128    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Which of the models presented here is the most suitable one? Comparing by <span class="math inline">\(\overline{R^2}\)</span> we find that, leaving out the log-linear model, all models have a similar fit. In the class of polynomial models, the cubic specification has the highest <span class="math inline">\(\overline{R^2}\)</span> whereas the linear-log specification is the best of the log-models.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the adj. R^2 for the nonlinear models</span>
R2 &lt;-<span class="kw">rbind</span>(<span class="st">&quot;quadratic&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(quadratic_model)<span class="op">$</span>adj.r.squared,
           <span class="st">&quot;cubic&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(cubic_model)<span class="op">$</span>adj.r.squared,
           <span class="st">&quot;LinearLog&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(LinearLog_model)<span class="op">$</span>adj.r.squared,
           <span class="st">&quot;LogLinear&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(LogLinear_model)<span class="op">$</span>adj.r.squared,
           <span class="st">&quot;LogLog&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(LogLog_model)<span class="op">$</span>adj.r.squared,
           <span class="st">&quot;polyLog&quot;</span> =<span class="st"> </span><span class="kw">summary</span>(polyLog_model)<span class="op">$</span>adj.r.squared
)
<span class="kw">colnames</span>(R2) &lt;-<span class="st"> &quot;R^2&quot;</span>
R2</code></pre></div>
<pre><code>##                 R^2
## quadratic 0.5540444
## cubic     0.5552279
## LinearLog 0.5614605
## LogLinear 0.4970106
## LogLog    0.5567251
## polyLog   0.5599944</code></pre>
<p>Let us now compare the cubic model and the linear-log model graphically by plotting the corresponding estimated regression functions.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># scatter plot</span>
<span class="kw">plot</span>(score <span class="op">~</span><span class="st"> </span>income, 
     <span class="dt">data =</span> CASchools,
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">pch =</span> <span class="dv">20</span>,
     <span class="dt">main =</span> <span class="st">&quot;Linear-Log and Cubic Regression Functions&quot;</span>)

<span class="co"># add Linear-Log regression line</span>
order_id  &lt;-<span class="st"> </span><span class="kw">order</span>(CASchools<span class="op">$</span>income)

<span class="kw">lines</span>(CASchools<span class="op">$</span>income[order_id],
      <span class="kw">fitted</span>(LinearLog_model)[order_id], 
      <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>, 
      <span class="dt">lwd =</span> <span class="dv">2</span>)

<span class="co"># add cubic regression line</span>
<span class="kw">lines</span>(<span class="dt">x =</span> CASchools<span class="op">$</span>income[order_id], 
      <span class="dt">y =</span> <span class="kw">fitted</span>(cubic_model)[order_id],
      <span class="dt">col=</span><span class="st">&quot;darkred&quot;</span>, 
      <span class="dt">lwd=</span><span class="dv">2</span>) </code></pre></div>
<p><img src="URFITE_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>We see that both regression lines look nearly identical. Altogether The linear-log model is preferable since it has a slightly higher <span class="math inline">\(\overline{R^2}\)</span> and is more parsimonious in terms of regressors: it does not include higher-degree polynomials.</p>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-stock2015">
<p>Stock, J., &amp; Watson, M. (2015). <em>Introduction to econometrics, third update, global edition</em>. Pearson Education Limited.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="a-general-strategy-for-modelling-nonlinear-regression-functions.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="interactions-between-independent-variables.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": ["URFITE.pdf", "URFITE.epub"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
