<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-10-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="introduction.html">
<link rel="next" href="arosur.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!-- function to adjust height of iframes automatically depending on content loaded -->

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.oek.wiwi.uni-due.de/en/">Chair of Econometrics at UDE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-very-short-introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="pt.html"><a href="pt.html"><i class="fa fa-check"></i><b>2</b> Probability Theory</a><ul>
<li class="chapter" data-level="2.1" data-path="pt.html"><a href="pt.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>2.1</b> Random Variables and Probability Distributions</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-discrete-random-variables"><i class="fa fa-check"></i>Probability Distributions of Discrete Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#bernoulli-trials"><i class="fa fa-check"></i>Bernoulli Trials</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#expected-value-mean-and-variance"><i class="fa fa-check"></i>Expected Value, Mean and Variance</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-continuous-random-variables"><i class="fa fa-check"></i>Probability Distributions of Continuous Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-chi-squared-distribution"><i class="fa fa-check"></i>The Chi-Squared Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#thetdist"><i class="fa fa-check"></i>The Student t Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-f-distribution"><i class="fa fa-check"></i>The F Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="pt.html"><a href="pt.html#RSATDOSA"><i class="fa fa-check"></i><b>2.2</b> Random Sampling and the Distribution of Sample Averages</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i>Mean and Variance of the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#large-sample-approximations-to-sampling-distributions"><i class="fa fa-check"></i>Large Sample Approximations to Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="pt.html"><a href="pt.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="arosur.html"><a href="arosur.html"><i class="fa fa-check"></i><b>3</b> A Review of Statistics using R</a><ul>
<li class="chapter" data-level="3.1" data-path="arosur.html"><a href="arosur.html#estimation-of-the-population-mean"><i class="fa fa-check"></i><b>3.1</b> Estimation of the Population Mean</a></li>
<li class="chapter" data-level="3.2" data-path="arosur.html"><a href="arosur.html#potsm"><i class="fa fa-check"></i><b>3.2</b> Properties of the Sample Mean</a></li>
<li class="chapter" data-level="3.3" data-path="arosur.html"><a href="arosur.html#hypothesis-tests-concerning-the-population-mean"><i class="fa fa-check"></i><b>3.3</b> Hypothesis Tests Concerning the Population Mean</a><ul>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-p-value"><i class="fa fa-check"></i>The p-Value</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-known"><i class="fa fa-check"></i>Calculating the p-Value when the Standard Deviation is Known</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#SVSSDASE"><i class="fa fa-check"></i>Sample Variance, Sample Standard Deviation and Standard Error</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-unknown"><i class="fa fa-check"></i>Calculating the p-value When the Standard Deviation is Unknown</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-t-statistic"><i class="fa fa-check"></i>The t-statistic</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#hypothesis-testing-with-a-prespecified-significance-level"><i class="fa fa-check"></i>Hypothesis Testing with a Prespecified Significance Level</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#one-sided-alternatives"><i class="fa fa-check"></i>One-sided Alternatives</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="arosur.html"><a href="arosur.html#confidence-intervals-for-the-population-mean"><i class="fa fa-check"></i><b>3.4</b> Confidence Intervals for the Population Mean</a></li>
<li class="chapter" data-level="3.5" data-path="arosur.html"><a href="arosur.html#cmfdp"><i class="fa fa-check"></i><b>3.5</b> Comparing Means from Different Populations</a></li>
<li class="chapter" data-level="3.6" data-path="arosur.html"><a href="arosur.html#aattggoe"><i class="fa fa-check"></i><b>3.6</b> An Application to the Gender Gap of Earnings</a></li>
<li class="chapter" data-level="3.7" data-path="arosur.html"><a href="arosur.html#scatterplots-sample-covariance-and-sample-correlation"><i class="fa fa-check"></i><b>3.7</b> Scatterplots, Sample Covariance and Sample Correlation</a></li>
<li class="chapter" data-level="3.8" data-path="arosur.html"><a href="arosur.html#exercises-1"><i class="fa fa-check"></i><b>3.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lrwor.html"><a href="lrwor.html"><i class="fa fa-check"></i><b>4</b> Linear Regression with One Regressor</a><ul>
<li class="chapter" data-level="4.1" data-path="lrwor.html"><a href="lrwor.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="lrwor.html"><a href="lrwor.html#estimating-the-coefficients-of-the-linear-regression-model"><i class="fa fa-check"></i><b>4.2</b> Estimating the Coefficients of the Linear Regression Model</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-ordinary-least-squares-estimator"><i class="fa fa-check"></i>The Ordinary Least Squares Estimator</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lrwor.html"><a href="lrwor.html#measures-of-fit"><i class="fa fa-check"></i><b>4.3</b> Measures of Fit</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-coefficient-of-determination"><i class="fa fa-check"></i>The Coefficient of Determination</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-standard-error-of-the-regression"><i class="fa fa-check"></i>The Standard Error of the Regression</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#application-to-the-test-score-data"><i class="fa fa-check"></i>Application to the Test Score Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="lrwor.html"><a href="lrwor.html#tlsa"><i class="fa fa-check"></i><b>4.4</b> The Least Squares Assumptions</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-1-the-error-term-has-conditional-mean-of-zero"><i class="fa fa-check"></i>Assumption 1: The Error Term has Conditional Mean of Zero</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-2-independently-and-identically-distributed-data"><i class="fa fa-check"></i>Assumption 2: Independently and Identically Distributed Data</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-3-large-outliers-are-unlikely"><i class="fa fa-check"></i>Assumption 3: Large Outliers are Unlikely</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="lrwor.html"><a href="lrwor.html#tsdotoe"><i class="fa fa-check"></i><b>4.5</b> The Sampling Distribution of the OLS Estimator</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-1"><i class="fa fa-check"></i>Simulation Study 1</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-2"><i class="fa fa-check"></i>Simulation Study 2</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-3"><i class="fa fa-check"></i>Simulation Study 3</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="lrwor.html"><a href="lrwor.html#exercises-2"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="htaciitslrm.html"><a href="htaciitslrm.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests and Confidence Intervals in the Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="5.1" data-path="htaciitslrm.html"><a href="htaciitslrm.html#testing-two-sided-hypotheses-concerning-the-slope-coefficient"><i class="fa fa-check"></i><b>5.1</b> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</a></li>
<li class="chapter" data-level="5.2" data-path="htaciitslrm.html"><a href="htaciitslrm.html#cifrc"><i class="fa fa-check"></i><b>5.2</b> Confidence Intervals for Regression Coefficients</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-confidence-intervals"><i class="fa fa-check"></i>Simulation Study: Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="htaciitslrm.html"><a href="htaciitslrm.html#rwxiabv"><i class="fa fa-check"></i><b>5.3</b> Regression when X is a Binary Variable</a></li>
<li class="chapter" data-level="5.4" data-path="htaciitslrm.html"><a href="htaciitslrm.html#hah"><i class="fa fa-check"></i><b>5.4</b> Heteroskedasticity and Homoskedasticity</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#a-real-world-example-for-heteroskedasticity"><i class="fa fa-check"></i>A Real-World Example for Heteroskedasticity</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#should-we-care-about-heteroskedasticity"><i class="fa fa-check"></i>Should We Care About Heteroskedasticity?</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#computation-of-heteroskedasticity-robust-standard-errors"><i class="fa fa-check"></i>Computation of Heteroskedasticity-Robust Standard Errors</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="htaciitslrm.html"><a href="htaciitslrm.html#the-gauss-markov-theorem"><i class="fa fa-check"></i><b>5.5</b> The Gauss-Markov Theorem</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-blue-estimator"><i class="fa fa-check"></i>Simulation Study: BLUE Estimator</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="htaciitslrm.html"><a href="htaciitslrm.html#using-the-t-statistic-in-regression-when-the-sample-size-is-small"><i class="fa fa-check"></i><b>5.6</b> Using the t-Statistic in Regression When the Sample Size Is Small</a></li>
<li class="chapter" data-level="5.7" data-path="htaciitslrm.html"><a href="htaciitslrm.html#exercises-3"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rmwmr.html"><a href="rmwmr.html"><i class="fa fa-check"></i><b>6</b> Regression Models with Multiple Regressors</a><ul>
<li class="chapter" data-level="6.1" data-path="rmwmr.html"><a href="rmwmr.html#omitted-variable-bias"><i class="fa fa-check"></i><b>6.1</b> Omitted Variable Bias</a></li>
<li class="chapter" data-level="6.2" data-path="rmwmr.html"><a href="rmwmr.html#tmrm"><i class="fa fa-check"></i><b>6.2</b> The Multiple Regression Model</a></li>
<li class="chapter" data-level="6.3" data-path="rmwmr.html"><a href="rmwmr.html#mofimr"><i class="fa fa-check"></i><b>6.3</b> Measures of Fit in Multiple Regression</a></li>
<li class="chapter" data-level="6.4" data-path="rmwmr.html"><a href="rmwmr.html#ols-assumptions-in-multiple-regression"><i class="fa fa-check"></i><b>6.4</b> OLS Assumptions in Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#multicollinearity"><i class="fa fa-check"></i>Multicollinearity</a></li>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#simulation-study-imperfect-multicollinearity"><i class="fa fa-check"></i>Simulation Study: Imperfect Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rmwmr.html"><a href="rmwmr.html#the-distribution-of-the-ols-estimators-in-multiple-regression"><i class="fa fa-check"></i><b>6.5</b> The Distribution of the OLS Estimators in Multiple Regression</a></li>
<li class="chapter" data-level="6.6" data-path="rmwmr.html"><a href="rmwmr.html#exercises-4"><i class="fa fa-check"></i><b>6.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="htaciimr.html"><a href="htaciimr.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Tests and Confidence Intervals in Multiple Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="htaciimr.html"><a href="htaciimr.html#hypothesis-tests-and-confidence-intervals-for-a-single-coefficient"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Tests and Confidence Intervals for a Single Coefficient</a></li>
<li class="chapter" data-level="7.2" data-path="htaciimr.html"><a href="htaciimr.html#an-application-to-test-scores-and-the-student-teacher-ratio"><i class="fa fa-check"></i><b>7.2</b> An Application to Test Scores and the Student-Teacher Ratio</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#another-augmentation-of-the-model"><i class="fa fa-check"></i>Another Augmentation of the Model</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="htaciimr.html"><a href="htaciimr.html#joint-hypothesis-testing-using-the-f-statistic"><i class="fa fa-check"></i><b>7.3</b> Joint Hypothesis Testing Using the F-Statistic</a></li>
<li class="chapter" data-level="7.4" data-path="htaciimr.html"><a href="htaciimr.html#confidence-sets-for-multiple-coefficients"><i class="fa fa-check"></i><b>7.4</b> Confidence Sets for Multiple Coefficients</a></li>
<li class="chapter" data-level="7.5" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-for-multiple-regression"><i class="fa fa-check"></i><b>7.5</b> Model Specification for Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-in-theory-and-in-practice"><i class="fa fa-check"></i>Model Specification in Theory and in Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="htaciimr.html"><a href="htaciimr.html#analysis-of-the-test-score-data-set"><i class="fa fa-check"></i><b>7.6</b> Analysis of the Test Score Data Set</a></li>
<li class="chapter" data-level="7.7" data-path="htaciimr.html"><a href="htaciimr.html#exercises-5"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nrf.html"><a href="nrf.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Regression Functions</a><ul>
<li class="chapter" data-level="8.1" data-path="nrf.html"><a href="nrf.html#a-general-strategy-for-modelling-nonlinear-regression-functions"><i class="fa fa-check"></i><b>8.1</b> A General Strategy for Modelling Nonlinear Regression Functions</a></li>
<li class="chapter" data-level="8.2" data-path="nrf.html"><a href="nrf.html#nfoasiv"><i class="fa fa-check"></i><b>8.2</b> Nonlinear Functions of a Single Independent Variable</a><ul>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#polynomials"><i class="fa fa-check"></i>Polynomials</a></li>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#logarithms"><i class="fa fa-check"></i>Logarithms</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nrf.html"><a href="nrf.html#interactions-between-independent-variables"><i class="fa fa-check"></i><b>8.3</b> Interactions Between Independent Variables</a></li>
<li class="chapter" data-level="8.4" data-path="nrf.html"><a href="nrf.html#nonlinear-effects-on-test-scores-of-the-student-teacher-ratio"><i class="fa fa-check"></i><b>8.4</b> Nonlinear Effects on Test Scores of the Student-Teacher Ratio</a></li>
<li class="chapter" data-level="8.5" data-path="nrf.html"><a href="nrf.html#exercises-6"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="asbomr.html"><a href="asbomr.html"><i class="fa fa-check"></i><b>9</b> Assessing Studies Based on Multiple Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity"><i class="fa fa-check"></i><b>9.1</b> Internal and External Validity</a></li>
<li class="chapter" data-level="9.2" data-path="asbomr.html"><a href="asbomr.html#ttivomra"><i class="fa fa-check"></i><b>9.2</b> Threats to Internal Validity of Multiple Regression Analysis</a></li>
<li class="chapter" data-level="9.3" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity-when-the-regression-is-used-for-forecasting"><i class="fa fa-check"></i><b>9.3</b> Internal and External Validity when the Regression is Used for Forecasting</a></li>
<li class="chapter" data-level="9.4" data-path="asbomr.html"><a href="asbomr.html#etsacs"><i class="fa fa-check"></i><b>9.4</b> Example: Test Scores and Class Size</a></li>
<li class="chapter" data-level="9.5" data-path="asbomr.html"><a href="asbomr.html#exercises-7"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="rwpd.html"><a href="rwpd.html"><i class="fa fa-check"></i><b>10</b> Regression with Panel Data</a><ul>
<li class="chapter" data-level="10.1" data-path="rwpd.html"><a href="rwpd.html#panel-data"><i class="fa fa-check"></i><b>10.1</b> Panel Data</a></li>
<li class="chapter" data-level="10.2" data-path="rwpd.html"><a href="rwpd.html#PDWTTP"><i class="fa fa-check"></i><b>10.2</b> Panel Data with Two Time Periods: “Before and After” Comparisons</a></li>
<li class="chapter" data-level="10.3" data-path="rwpd.html"><a href="rwpd.html#fixed-effects-regression"><i class="fa fa-check"></i><b>10.3</b> Fixed Effects Regression</a><ul>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#estimation-and-inference"><i class="fa fa-check"></i>Estimation and Inference</a></li>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#application-to-traffic-deaths"><i class="fa fa-check"></i>Application to Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="rwpd.html"><a href="rwpd.html#regression-with-time-fixed-effects"><i class="fa fa-check"></i><b>10.4</b> Regression with Time Fixed Effects</a></li>
<li class="chapter" data-level="10.5" data-path="rwpd.html"><a href="rwpd.html#tferaaseffer"><i class="fa fa-check"></i><b>10.5</b> The Fixed Effects Regression Assumptions and Standard Errors for Fixed Effects Regression</a></li>
<li class="chapter" data-level="10.6" data-path="rwpd.html"><a href="rwpd.html#drunk-driving-laws-and-traffic-deaths"><i class="fa fa-check"></i><b>10.6</b> Drunk Driving Laws and Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="rwabdv.html"><a href="rwabdv.html"><i class="fa fa-check"></i><b>11</b> Regression with a Binary Dependent Variable</a><ul>
<li class="chapter" data-level="11.1" data-path="rwabdv.html"><a href="rwabdv.html#binary-dependent-variables-and-the-linear-probability-model"><i class="fa fa-check"></i><b>11.1</b> Binary Dependent Variables and the Linear Probability Model</a></li>
<li class="chapter" data-level="11.2" data-path="rwabdv.html"><a href="rwabdv.html#palr"><i class="fa fa-check"></i><b>11.2</b> Probit and Logit Regression</a><ul>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#probit-regression"><i class="fa fa-check"></i>Probit Regression</a></li>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#logit-regression"><i class="fa fa-check"></i>Logit Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="rwabdv.html"><a href="rwabdv.html#estimation-and-inference-in-the-logit-and-probit-models"><i class="fa fa-check"></i><b>11.3</b> Estimation and Inference in the Logit and Probit Models</a></li>
<li class="chapter" data-level="11.4" data-path="rwabdv.html"><a href="rwabdv.html#application-to-the-boston-hmda-data"><i class="fa fa-check"></i><b>11.4</b> Application to the Boston HMDA Data</a></li>
<li class="chapter" data-level="11.5" data-path="rwabdv.html"><a href="rwabdv.html#exercises-8"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ivr.html"><a href="ivr.html"><i class="fa fa-check"></i><b>12</b> Instrumental Variables Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="ivr.html"><a href="ivr.html#TIVEWASRAASI"><i class="fa fa-check"></i><b>12.1</b> The IV Estimator with a Single Regressor and a Single Instrument</a></li>
<li class="chapter" data-level="12.2" data-path="ivr.html"><a href="ivr.html#TGIVRM"><i class="fa fa-check"></i><b>12.2</b> The General IV Regression Model</a></li>
<li class="chapter" data-level="12.3" data-path="ivr.html"><a href="ivr.html#civ"><i class="fa fa-check"></i><b>12.3</b> Checking Instrument Validity</a></li>
<li class="chapter" data-level="12.4" data-path="ivr.html"><a href="ivr.html#attdfc"><i class="fa fa-check"></i><b>12.4</b> Application to the Demand for Cigarettes</a></li>
<li class="chapter" data-level="12.5" data-path="ivr.html"><a href="ivr.html#where-do-valid-instruments-come-from"><i class="fa fa-check"></i><b>12.5</b> Where Do Valid Instruments Come From?</a></li>
<li class="chapter" data-level="12.6" data-path="ivr.html"><a href="ivr.html#exercises-9"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="eaqe.html"><a href="eaqe.html"><i class="fa fa-check"></i><b>13</b> Experiments and Quasi-Experiments</a><ul>
<li class="chapter" data-level="13.1" data-path="eaqe.html"><a href="eaqe.html#potential-outcomes-causal-effects-and-idealized-experiments"><i class="fa fa-check"></i><b>13.1</b> Potential Outcomes, Causal Effects and Idealized Experiments</a></li>
<li class="chapter" data-level="13.2" data-path="eaqe.html"><a href="eaqe.html#threats-to-validity-of-experiments"><i class="fa fa-check"></i><b>13.2</b> Threats to Validity of Experiments</a></li>
<li class="chapter" data-level="13.3" data-path="eaqe.html"><a href="eaqe.html#experimental-estimates-of-the-effect-of-class-size-reductions"><i class="fa fa-check"></i><b>13.3</b> Experimental Estimates of the Effect of Class Size Reductions</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#experimental-design-and-the-data-set"><i class="fa fa-check"></i>Experimental Design and the Data Set</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#analysis-of-the-star-data"><i class="fa fa-check"></i>Analysis of the STAR Data</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="eaqe.html"><a href="eaqe.html#quasi-experiments"><i class="fa fa-check"></i><b>13.4</b> Quasi Experiments</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#the-differences-in-differences-estimator"><i class="fa fa-check"></i>The Differences-in-Differences Estimator</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#regression-discontinuity-estimators"><i class="fa fa-check"></i>Regression Discontinuity Estimators</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ittsraf.html"><a href="ittsraf.html"><i class="fa fa-check"></i><b>14</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="14.1" data-path="ittsraf.html"><a href="ittsraf.html#using-regression-models-for-forecasting"><i class="fa fa-check"></i><b>14.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="14.2" data-path="ittsraf.html"><a href="ittsraf.html#tsdasc"><i class="fa fa-check"></i><b>14.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ittsraf.html"><a href="ittsraf.html#autoregressions"><i class="fa fa-check"></i><b>14.3</b> Autoregressions</a><ul>
<li><a href="ittsraf.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ittsraf.html"><a href="ittsraf.html#cybtmpi"><i class="fa fa-check"></i><b>14.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="14.5" data-path="ittsraf.html"><a href="ittsraf.html#apatadlm"><i class="fa fa-check"></i><b>14.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="ittsraf.html"><a href="ittsraf.html#llsuic"><i class="fa fa-check"></i><b>14.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="14.7" data-path="ittsraf.html"><a href="ittsraf.html#nit"><i class="fa fa-check"></i><b>14.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="14.8" data-path="ittsraf.html"><a href="ittsraf.html#niib"><i class="fa fa-check"></i><b>14.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="14.9" data-path="ittsraf.html"><a href="ittsraf.html#can-you-beat-the-market-part-ii"><i class="fa fa-check"></i><b>14.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="eodce.html"><a href="eodce.html"><i class="fa fa-check"></i><b>15</b> Estimation of Dynamic Causal Effects</a><ul>
<li class="chapter" data-level="15.1" data-path="eodce.html"><a href="eodce.html#the-orange-juice-data"><i class="fa fa-check"></i><b>15.1</b> The Orange Juice Data</a></li>
<li class="chapter" data-level="15.2" data-path="eodce.html"><a href="eodce.html#dynamic-causal-effects"><i class="fa fa-check"></i><b>15.2</b> Dynamic Causal Effects</a></li>
<li class="chapter" data-level="15.3" data-path="eodce.html"><a href="eodce.html#dynamic-multipliers-and-cumulative-dynamic-multipliers"><i class="fa fa-check"></i><b>15.3</b> Dynamic Multipliers and Cumulative Dynamic Multipliers</a></li>
<li class="chapter" data-level="15.4" data-path="eodce.html"><a href="eodce.html#hac-standard-errors"><i class="fa fa-check"></i><b>15.4</b> HAC Standard Errors</a></li>
<li class="chapter" data-level="15.5" data-path="eodce.html"><a href="eodce.html#estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors"><i class="fa fa-check"></i><b>15.5</b> Estimation of Dynamic Causal Effects with Strictly Exogeneous Regressors</a></li>
<li class="chapter" data-level="15.6" data-path="eodce.html"><a href="eodce.html#orange-juice-prices-and-cold-weather"><i class="fa fa-check"></i><b>15.6</b> Orange Juice Prices and Cold Weather</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="atitsr.html"><a href="atitsr.html"><i class="fa fa-check"></i><b>16</b> Additional Topics in Time Series Regression</a><ul>
<li class="chapter" data-level="16.1" data-path="atitsr.html"><a href="atitsr.html#vector-autoregressions"><i class="fa fa-check"></i><b>16.1</b> Vector Autoregressions</a></li>
<li class="chapter" data-level="16.2" data-path="atitsr.html"><a href="atitsr.html#ooiatdfglsurt"><i class="fa fa-check"></i><b>16.2</b> Orders of Integration and the DF-GLS Unit Root Test</a></li>
<li class="chapter" data-level="16.3" data-path="atitsr.html"><a href="atitsr.html#cointegration"><i class="fa fa-check"></i><b>16.3</b> Cointegration</a></li>
<li class="chapter" data-level="16.4" data-path="atitsr.html"><a href="atitsr.html#volatility-clustering-and-autoregressive-conditional-heteroskedasticity"><i class="fa fa-check"></i><b>16.4</b> Volatility Clustering and Autoregressive Conditional Heteroskedasticity</a><ul>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#arch-and-garch-models"><i class="fa fa-check"></i>ARCH and GARCH Models</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#application-to-stock-price-volatility"><i class="fa fa-check"></i>Application to Stock Price Volatility</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#summary-8"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="pt" class="section level1">
<h1><span class="header-section-number">2</span> Probability Theory</h1>
<p>This chapter reviews some basic concepts of probability theory and demonstrates how they can be applied in <tt>R</tt>.</p>
<p>Most of the statistical functionalities in <tt>R</tt>’s standard version are collected in the <tt>stats</tt> package. It provides simple functions which compute descriptive measures and facilitate computations involving a variety of probability distributions. It also contains more sophisticated routines that, e.g., enable the user to estimate a large number of models based on the same data or help to conduct extensive simulation studies. <tt>stats</tt> is part of the base distribution of <tt>R</tt>, meaning that it is installed by default so there is no need to run <code>install.packages(&quot;stats&quot;)</code> or <code>library(&quot;stats&quot;)</code>. Simply execute <code>library(help = &quot;stats&quot;)</code> in the console to view the documentation and a complete list of all functions gathered in <tt>stats</tt>. For most packages a documentation that can be viewed within <em>RStudio</em> is available. Documentations can be invoked using the <tt>?</tt> operator, e.g., upon execution of <code>?stats</code> the documentation of the <tt>stats</tt> package is shown in the help tab of the bottom-right pane.</p>
<p>In what follows, our focus is on (some of) the probability distributions that are handled by <tt>R</tt> and show how to use the relevant functions to solve simple problems. Thereby, we refresh some core concepts of probability theory. Among other things, you will learn how to draw random numbers, how to compute densities, probabilities, quantiles and alike. As we shall see, it is very convenient to rely on these routines.</p>
<div id="random-variables-and-probability-distributions" class="section level2">
<h2><span class="header-section-number">2.1</span> Random Variables and Probability Distributions</h2>
<p>Let us briefly review some basic concepts of probability theory.</p>
<ul>
<li>The mutually exclusive results of a random process are called the <em>outcomes</em>. ‘Mutually exclusive’ means that only one of the possible outcomes can be observed.</li>
<li>We refer to the <em>probability</em> of an outcome as the proportion that the outcome occurs in the long run, that is, if the experiment is repeated very often.</li>
<li>The set of all possible outcomes of a random variable is called the <em>sample space</em>.</li>
<li>An <em>event</em> is a subset of the sample space and consists of one or more outcomes.</li>
</ul>
<p>These ideas are unified in the concept of a <em>random variable</em> which is a numerical summary of random outcomes. Random variables can be <em>discrete</em> or <em>continuous</em>.</p>
<ul>
<li>Discrete random variables have discrete outcomes, e.g., <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>.</li>
<li>A continuous random variable may take on a continuum of possible values.</li>
</ul>
<div id="probability-distributions-of-discrete-random-variables" class="section level3 unnumbered">
<h3>Probability Distributions of Discrete Random Variables</h3>
<p>A typical example for a discrete random variable <span class="math inline">\(D\)</span> is the result of a dice roll: in terms of a random experiment this is nothing but randomly selecting a sample of size <span class="math inline">\(1\)</span> from a set of numbers which are mutually exclusive outcomes. Here, the sample space is <span class="math inline">\(\{1,2,3,4,5,6\}\)</span> and we can think of many different events, e.g., ‘the observed outcome lies between <span class="math inline">\(2\)</span> and <span class="math inline">\(5\)</span>’.</p>
<p>A basic function to draw random samples from a specified set of elements is the the function <tt>sample()</tt>, see <code>?sample</code>. We can use it to simulate the random outcome of a dice roll. Let’s roll the dice!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dv">1</span>) </code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>The probability distribution of a discrete random variable is the list of all possible values of the variable and their probabilities which sum to <span class="math inline">\(1\)</span>. The cumulative probability distribution function gives the probability that the random variable is less than or equal to a particular value.</p>
<p>For the dice roll, the probability distribution and the cumulative probability distribution are summarized in Table <a href="pt.html#tab:pdist">2.1</a>.</p>
<table>
<caption>
<span id="tab:pdist">Table 2.1: </span>PDF and CDF of a Dice Roll
</caption>
<tbody>
<tr>
<td style="text-align:left;">
Outcome
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Probability
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
1/6
</td>
</tr>
<tr>
<td style="text-align:left;">
Cumulative Probability
</td>
<td style="text-align:left;">
1/6
</td>
<td style="text-align:left;">
2/6
</td>
<td style="text-align:left;">
3/6
</td>
<td style="text-align:left;">
4/6
</td>
<td style="text-align:left;">
5/6
</td>
<td style="text-align:left;">
1
</td>
</tr>
</tbody>
</table>
<p>We can easily plot both functions using <tt>R</tt>. Since the probability equals <span class="math inline">\(1/6\)</span> for each outcome, we set up the vector <tt>probability</tt> by using the function <tt>rep()</tt> which replicates a given value a specified number of times.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate the vector of probabilities </span>
probability &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>, <span class="dv">6</span>) 

<span class="co"># plot the probabilites </span>
<span class="kw">plot</span>(probability, 
     <span class="dt">main =</span> <span class="st">&quot;Probability Distribution&quot;</span>,
     <span class="dt">xlab =</span> <span class="st">&quot;outcomes&quot;</span>) </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>For the cumulative probability distribution we need the cumulative probabilities, i.e., we need the cumulative sums of the vector <tt>probability</tt>. These sums can be computed using <tt>cumsum()</tt>.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># generate the vector of cumulative probabilities </span>
cum_probability &lt;-<span class="st"> </span><span class="kw">cumsum</span>(probability) 

<span class="co"># plot the probabilites </span>
<span class="kw">plot</span>(cum_probability, 
     <span class="dt">xlab =</span> <span class="st">&quot;outcomes&quot;</span>, 
     <span class="dt">main =</span> <span class="st">&quot;Cumulative Probability Distribution&quot;</span>) </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="bernoulli-trials" class="section level3 unnumbered">
<h3>Bernoulli Trials</h3>
<p>The set of elements from which <tt>sample()</tt> draws outcomes does not have to consist of numbers only. We might as well simulate coin tossing with outcomes <span class="math inline">\(H\)</span> (heads) and <span class="math inline">\(T\)</span> (tails).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sample</span>(<span class="kw">c</span>(<span class="st">&quot;H&quot;</span>, <span class="st">&quot;T&quot;</span>), <span class="dv">1</span>) </code></pre></div>
<pre><code>## [1] &quot;T&quot;</code></pre>
<p>The result of a single coin toss is a <em>Bernoulli</em> distributed random variable, i.e., a variable with two possible distinct outcomes.</p>
<p>Imagine you are about to toss a coin <span class="math inline">\(10\)</span> times in a row and wonder how likely it is to end up with a <span class="math inline">\(5\)</span> times heads. This is a typical example of what we call a <em>Bernoulli experiment</em> as it consists of <span class="math inline">\(n=10\)</span> Bernoulli trials that are independent of each other and we are interested in the likelihood of observing <span class="math inline">\(k=5\)</span> successes <span class="math inline">\(H\)</span> that occur with probability <span class="math inline">\(p=0.5\)</span> (assuming a fair coin) in each trial. Note that the order of the outcomes does not matter here.</p>
<p>It is a <a href="https://en.wikipedia.org/wiki/Binomial_distribution">well known result</a> that the number of successes <span class="math inline">\(k\)</span> in a Bernoulli experiment follows a binomial distribution. We denote this as</p>
<p><span class="math display">\[k \sim B(n,p).\]</span></p>
<p>The probability of observing <span class="math inline">\(k\)</span> successes in the experiment <span class="math inline">\(B(n,p)\)</span> is given by</p>
<p><span class="math display">\[f(k)=P(k)=\begin{pmatrix}n\\ k \end{pmatrix} \cdot p^k \cdot
(1-p)^{n-k}=\frac{n!}{k!(n-k)!} \cdot p^k \cdot (1-p)^{n-k}\]</span></p>
<p>with <span class="math inline">\(\begin{pmatrix}n\\ k \end{pmatrix}\)</span> the binomial coefficient.</p>
<p>In <tt>R</tt>, we can solve the problem stated above by means of the function <tt>dbinom()</tt> which calculates the probability of the binomial distribution given the parameters <tt>x</tt>, <tt>size</tt>, and <tt>prob</tt>, see <code>?binom</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dbinom</span>(<span class="dt">x =</span> <span class="dv">5</span>,
       <span class="dt">size =</span> <span class="dv">10</span>,
       <span class="dt">prob =</span> <span class="fl">0.5</span>) </code></pre></div>
<pre><code>## [1] 0.2460938</code></pre>
<p>We conclude that the probability of observing Head <span class="math inline">\(k=5\)</span> times when tossing the coin <span class="math inline">\(n=10\)</span> times is about <span class="math inline">\(24.6\%\)</span>.</p>
<p>Now assume we are interested in <span class="math inline">\(P(4 \leq k \leq 7)\)</span>, i.e., the probability of observing <span class="math inline">\(4\)</span>, <span class="math inline">\(5\)</span>, <span class="math inline">\(6\)</span> or <span class="math inline">\(7\)</span> successes for <span class="math inline">\(B(10,0.5)\)</span>. This may be computed by providing a vector as the argument <tt>x</tt> in our call of <tt>dbinom()</tt> and summing up using <tt>sum()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute P(4 &lt;= k &lt;= 7) using &#39;dbinom()&#39;</span>
<span class="kw">sum</span>(<span class="kw">dbinom</span>(<span class="dt">x =</span> <span class="dv">4</span><span class="op">:</span><span class="dv">7</span>, 
         <span class="dt">size =</span> <span class="dv">10</span>, 
         <span class="dt">prob =</span> <span class="fl">0.5</span>))</code></pre></div>
<pre><code>## [1] 0.7734375</code></pre>
<p>An alternative approach is to use <tt>pbinom()</tt>, the distribution function of the binomial distribution to compute <span class="math display">\[P(4 \leq k \leq 7) = P(k \leq 7) - P(k\leq3 ).\]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute P(4 &lt;= k &lt;= 7) using &#39;pbinom()&#39;</span>
<span class="kw">pbinom</span>(<span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">prob =</span> <span class="fl">0.5</span>, <span class="dt">q =</span> <span class="dv">7</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pbinom</span>(<span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">prob =</span> <span class="fl">0.5</span>, <span class="dt">q =</span> <span class="dv">3</span>) </code></pre></div>
<pre><code>## [1] 0.7734375</code></pre>
<p>The probability distribution of a discrete random variable is nothing but a list of all possible outcomes that can occur and their respective probabilities. In the coin tossing example we have <span class="math inline">\(11\)</span> possible outcomes for <span class="math inline">\(k\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up vector of possible outcomes</span>
k &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">10</span></code></pre></div>
<p>To visualize the probability distribution function of <span class="math inline">\(k\)</span> we may therefore do the following:</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># assign the probabilities</span>
probability &lt;-<span class="st"> </span><span class="kw">dbinom</span>(<span class="dt">x =</span> k,
                      <span class="dt">size =</span> <span class="dv">10</span>, 
                      <span class="dt">prob =</span> <span class="fl">0.5</span>)

<span class="co"># plot the outcomes against their probabilities</span>
<span class="kw">plot</span>(<span class="dt">x =</span> k, 
     <span class="dt">y =</span> probability,
     <span class="dt">main =</span> <span class="st">&quot;Probability Distribution Function&quot;</span>) </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>In a similar fashion we may plot the cumulative distribution function of <span class="math inline">\(k\)</span> by executing the following code chunk:</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute cumulative probabilities</span>
prob &lt;-<span class="st"> </span><span class="kw">dbinom</span>(<span class="dt">x =</span> <span class="dv">0</span><span class="op">:</span><span class="dv">10</span>, 
               <span class="dt">size =</span> <span class="dv">10</span>, 
               <span class="dt">prob =</span> <span class="fl">0.5</span>)

<span class="co"># plot the cumulative probabilities</span>
<span class="kw">plot</span>(<span class="dt">x =</span> k, 
     <span class="dt">y =</span> prob,
     <span class="dt">main =</span> <span class="st">&quot;Cumulative Distribution Function&quot;</span>) </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-22-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="expected-value-mean-and-variance" class="section level3 unnumbered">
<h3>Expected Value, Mean and Variance</h3>
<p>The expected value of a random variable is, loosely, the long-run average value of its outcomes when the number of repeated trials is large. For a discrete random variable, the expected value is computed as a weighted average of its possible outcomes whereby the weights are the related probabilities. This is formalized in Key Concept 2.1.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.1
</h3>
<h3 class="left">
Expected Value and the Mean
</h3>
<p>
<p>Suppose the random variable <span class="math inline">\(Y\)</span> takes on <span class="math inline">\(k\)</span> possible values, <span class="math inline">\(y_1, \dots, y_k\)</span>, where <span class="math inline">\(y_1\)</span> denotes the first value, <span class="math inline">\(y_2\)</span> denotes the second value, and so forth, and that the probability that <span class="math inline">\(Y\)</span> takes on <span class="math inline">\(y_1\)</span> is <span class="math inline">\(p_1\)</span>, the probability that <span class="math inline">\(Y\)</span> takes on <span class="math inline">\(y_2\)</span> is <span class="math inline">\(p_2\)</span> and so forth. The expected value of <span class="math inline">\(Y\)</span>, <span class="math inline">\(E(Y)\)</span> is defined as</p>
<p><span class="math display">\[ E(Y) = y_1 p_1 + y_2 p_2 + \cdots + y_k p_k = \sum_{i=1}^k y_i p_i \]</span></p>
where the notation <span class="math inline">\(\sum_{i=1}^k y_i p_i\)</span> means “the sum of <span class="math inline">\(y_i\)</span> <span class="math inline">\(p_i\)</span> for <span class="math inline">\(i\)</span> running from <span class="math inline">\(1\)</span> to <span class="math inline">\(k\)</span>”. The expected value of <span class="math inline">\(Y\)</span> is also called the mean of <span class="math inline">\(Y\)</span> or the expectation of <span class="math inline">\(Y\)</span> and is denoted by <span class="math inline">\(\mu_Y\)</span>.
</p>
</div>
<p>In the dice example, the random variable, <span class="math inline">\(D\)</span> say, takes on <span class="math inline">\(6\)</span> possible values <span class="math inline">\(d_1 = 1, d_2 = 2, \dots, d_6 = 6\)</span>. Assuming a fair dice, each of the <span class="math inline">\(6\)</span> outcomes occurs with a probability of <span class="math inline">\(1/6\)</span>. It is therefore easy to calculate the exact value of <span class="math inline">\(E(D)\)</span> by hand:</p>
<p><span class="math display">\[ E(D) = 1/6 \sum_{i=1}^6 d_i = 3.5 \]</span></p>
<p><span class="math inline">\(E(D)\)</span> is simply the average of the natural numbers from <span class="math inline">\(1\)</span> to <span class="math inline">\(6\)</span> since all wights <span class="math inline">\(p_i\)</span> are <span class="math inline">\(1/6\)</span>. This can be easily calculated using the function <tt>mean()</tt> which computes the arithmetic mean of a numeric vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute mean of natural numbers from 1 to 6</span>
<span class="kw">mean</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</code></pre></div>
<pre><code>## [1] 3.5</code></pre>
<p>An example of sampling with replacement is rolling a dice three times in a row.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set seed for reproducibility</span>
<span class="kw">set.seed</span>(<span class="dv">1</span>)

<span class="co"># rolling a dice three times in a row</span>
<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dv">3</span>, <span class="dt">replace =</span> T)</code></pre></div>
<pre><code>## [1] 2 3 4</code></pre>
<p>Of course we could also consider a much bigger number of trials, <span class="math inline">\(10000\)</span> say. Doing so, it would be pointless to simply print the results to the console: by default <tt>R</tt> displays up to <span class="math inline">\(1000\)</span> entries of large vectors and omits the remainder (give it a try). Eyeballing the numbers does not reveal much. Instead, let us calculate the sample average of the outcomes using <tt>mean()</tt> and see if the result comes close to the expected value <span class="math inline">\(E(D)=3.5\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set seed for reproducibility</span>
<span class="kw">set.seed</span>(<span class="dv">1</span>)

<span class="co"># compute the sample mean of 10000 dice rolls</span>
<span class="kw">mean</span>(<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, 
           <span class="dv">10000</span>, 
           <span class="dt">replace =</span> T))</code></pre></div>
<pre><code>## [1] 3.5039</code></pre>
<p>We find the sample mean to be fairly close to the expected value. This result will be discussed in Chapter <a href="pt.html#RSATDOSA">2.2</a> in more detail.</p>
<p>Other frequently encountered measures are the variance and the standard deviation. Both are measures of the <em>dispersion</em> of a random variable.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.2
</h3>
<h3 class="left">
Variance and Standard Deviation
</h3>
<p>
The variance of the discrete random variable <span class="math inline">\(Y\)</span>, denoted <span class="math inline">\(\sigma^2_Y\)</span>, is <span class="math display">\[ \sigma^2_Y = \text{Var}(Y) = E\left[(Y-\mu_y)^2\right] = \sum_{i=1}^k (y_i - \mu_y)^2 p_i \]</span> The standard deviation of <span class="math inline">\(Y\)</span> is <span class="math inline">\(\sigma_Y\)</span>, the square root of the variance. The units of the standard deviation are the same as the units of <span class="math inline">\(Y\)</span>.
</p>
</div>
<p>The variance as defined in Key Concept 2.2, being a population quantity, <em>is not</em> implemented as a function in R. Instead we have the function <tt>var()</tt> which computes the <em>sample variance</em></p>
<p><span class="math display">\[ s^2_Y = \frac{1}{n-1} \sum_{i=1}^n (y_i - \overline{y})^2. \]</span></p>
<p>Remember that <span class="math inline">\(s^2_Y\)</span> is different from the so called <em>population variance</em> of a discrete random variable <span class="math inline">\(Y\)</span>,</p>
<p><span class="math display">\[ \text{Var}(Y) = \frac{1}{N} \sum_{i=1}^N (y_i - \mu_Y)^2. \]</span></p>
<p>since it measures how the data is dispersed around the sample average <span class="math inline">\(\overline{y}\)</span> instead of the population mean <span class="math inline">\(\mu_Y\)</span>. This becomes clear when we look at our dice rolling example. For <span class="math inline">\(D\)</span> we have</p>
<p><span class="math display">\[ \text{Var}(D) = 1/6 \sum_{i=1}^6 (d_i - 3.5)^2 = 2.92  \]</span> which is obviously different from the result of <span class="math inline">\(s^2\)</span> as computed by <tt>var()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>)</code></pre></div>
<pre><code>## [1] 3.5</code></pre>
<p>The sample variance as computed by <tt>var()</tt> is an <em>estimator</em> of the population variance. You may check this using the widget below.</p>
<iframe src="DCL/playground.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
</div>
<div id="probability-distributions-of-continuous-random-variables" class="section level3 unnumbered">
<h3>Probability Distributions of Continuous Random Variables</h3>
<p>Since a continuous random variable takes on a continuum of possible values, we cannot use the concept of a probability distribution as used for discrete random variables. Instead, the probability distribution of a continuous random variable is summarized by its <em>probability density function</em> (PDF).</p>
<p>The cumulative probability distribution function (CDF) for a continuous random variable is defined just as in the discrete case. Hence, the cumulative probability distribution of a continuous random variables states the probability that the random variable is less than or equal to a particular value.</p>
<p>For completeness, we present revisions of Key Concepts 2.1 and 2.2 for the continuous case.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.3
</h3>
<h3 class="left">
Probabilities, Expected Value and Variance of a Continuous Random Variable
</h3>
<p>
<p>Let <span class="math inline">\(f_Y(y)\)</span> denote the probability density function of <span class="math inline">\(Y\)</span>. The probability that <span class="math inline">\(Y\)</span> falls between <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> where <span class="math inline">\(a &lt; b\)</span> is <span class="math display">\[ P(a \leq Y \leq b) = \int_a^b f_Y(y) \mathrm{d}y. \]</span> We further have that <span class="math inline">\(P(-\infty \leq Y \leq \infty) = 1\)</span> and therefore <span class="math inline">\(\int_{-\infty}^{\infty} f_Y(y) \mathrm{d}y = 1\)</span>.</p>
<p>As for the discrete case, the expected value of <span class="math inline">\(Y\)</span> is the probability weighted average of its values. Due to continuity, we use integrals instead of sums. The expected value of <span class="math inline">\(Y\)</span> is defined as</p>
<p><span class="math display">\[ E(Y) =  \mu_Y = \int y f_Y(y) \mathrm{d}y. \]</span></p>
<p>The variance is the expected value of <span class="math inline">\((Y - \mu_Y)^2\)</span>. We thus have</p>
<span class="math display">\[\text{Var}(Y) =  \sigma_Y^2 = \int (y - \mu_Y)^2 f_Y(y) \mathrm{d}y.\]</span>
</p>
</div>
<p>Let us discuss an example:</p>
<p>Consider the continuous random variable <span class="math inline">\(X\)</span> with probability density function</p>
<p><span class="math display">\[ f_X(x) = \frac{3}{x^4}, x&gt;1. \]</span></p>
<ul>
<li>We can show analytically that the integral of <span class="math inline">\(f_X(x)\)</span> over the real line equals <span class="math inline">\(1\)</span>.</li>
</ul>
<span class="math display">\[\begin{align}
 \int f_X(x) \mathrm{d}x =&amp;  \int_{1}^{\infty} \frac{3}{x^4} \mathrm{d}x \\
  =&amp; \lim_{t \rightarrow \infty} \int_{1}^{t} \frac{3}{x^4} \mathrm{d}x \\
  =&amp; \lim_{t \rightarrow \infty}  -x^{-3} \rvert_{x=1}^t \\
  =&amp; -\left(\lim_{t \rightarrow \infty}\frac{1}{t^3} - 1\right) \\
  =&amp; 1
\end{align}\]</span>
<ul>
<li>The expectation of <span class="math inline">\(X\)</span> can be computed as follows:</li>
</ul>
<span class="math display">\[\begin{align}
 E(X) = \int x \cdot f_X(x) \mathrm{d}x =&amp;  \int_{1}^{\infty} x \cdot \frac{3}{x^4} \mathrm{d}x \\
  =&amp; - \frac{3}{2} x^{-2} \rvert_{x=1}^{\infty} \\
  =&amp; -\frac{3}{2} \left( \lim_{t \rightarrow \infty} \frac{1}{t^2} - 1 \right) \\
  =&amp; \frac{3}{2}
\end{align}\]</span>
<ul>
<li>Note that the variance of <span class="math inline">\(X\)</span> can be expressed as <span class="math inline">\(\text{Var}(X) = E(X^2) - E(X)^2\)</span>. Since <span class="math inline">\(E(X)\)</span> has been computed in the previous step, we seek <span class="math inline">\(E(X^2)\)</span>:</li>
</ul>
<span class="math display">\[\begin{align}
 E(X^2)= \int x^2 \cdot f_X(x) \mathrm{d}x =&amp;  \int_{1}^{\infty} x^2 \cdot \frac{3}{x^4} \mathrm{d}x \\
  =&amp; -3 x^{-1} \rvert_{x=1}^{\infty} \\
  =&amp; -3 \left( \lim_{t \rightarrow \infty} \frac{1}{t} - 1 \right) \\
  =&amp; 3
\end{align}\]</span>
<p>So we have shown that the area under the curve equals one, that the expectation is <span class="math inline">\(E(X)=\frac{3}{2} \ \)</span> and we found the variance to be <span class="math inline">\(\text{Var}(X) = \frac{3}{4}\)</span>. However, this was tedious and, as we shall see, an analytic approach is not applicable for some probability density functions, e.g., if integrals have no closed form solutions.</p>
<p>Luckily, <tt>R</tt> also enables us to easily find the results derived above. The tool we use for this is the function <tt>integrate()</tt>. First, we have to define the functions we want to calculate integrals for as <tt>R</tt> functions, i.e., the PDF <span class="math inline">\(f_X(x)\)</span> as well as the expressions <span class="math inline">\(x\cdot f_X(x)\)</span> and <span class="math inline">\(x^2\cdot f_X(x)\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define functions</span>
f &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="dv">3</span> <span class="op">/</span><span class="st"> </span>x<span class="op">^</span><span class="dv">4</span>
g &lt;-<span class="st"> </span><span class="cf">function</span>(x) x <span class="op">*</span><span class="st"> </span><span class="kw">f</span>(x)
h &lt;-<span class="st"> </span><span class="cf">function</span>(x) x<span class="op">^</span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">f</span>(x)</code></pre></div>
<p>Next, we use <tt>integrate()</tt> and set lower and upper limits of integration to <span class="math inline">\(1\)</span> and <span class="math inline">\(\infty\)</span> using arguments <tt>lower</tt> and <tt>upper</tt>. By default, <tt>integrate()</tt> prints the result along with an estimate of the approximation error to the console. However, the outcome is not a numeric value one can readily do further calculation with. In order to get only a numeric value of the integral, we need to use the <tt><span class="math inline">\(&lt;/tt&gt; operator in conjunction with &lt;tt&gt;value&lt;/tt&gt;. The &lt;tt&gt;\)</span></tt> operator is used to extract elements by name from an object of type <tt>list</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute area under the density curve</span>
area &lt;-<span class="st"> </span><span class="kw">integrate</span>(f, 
                 <span class="dt">lower =</span> <span class="dv">1</span>, 
                 <span class="dt">upper =</span> <span class="ot">Inf</span>)<span class="op">$</span>value
area </code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute E(X)</span>
EX &lt;-<span class="st"> </span><span class="kw">integrate</span>(g,
                <span class="dt">lower =</span> <span class="dv">1</span>,
                <span class="dt">upper =</span> <span class="ot">Inf</span>)<span class="op">$</span>value
EX</code></pre></div>
<pre><code>## [1] 1.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute Var(X)</span>
VarX &lt;-<span class="st"> </span><span class="kw">integrate</span>(h,
                  <span class="dt">lower =</span> <span class="dv">1</span>,
                  <span class="dt">upper =</span> <span class="ot">Inf</span>)<span class="op">$</span>value <span class="op">-</span><span class="st"> </span>EX<span class="op">^</span><span class="dv">2</span> 
VarX</code></pre></div>
<pre><code>## [1] 0.75</code></pre>
<p>Although there is a wide variety of distributions, the ones most often encountered in econometrics are the normal, chi-squared, Student <span class="math inline">\(t\)</span> and <span class="math inline">\(F\)</span> distributions. Therefore we will discuss some core <tt>R</tt> functions that allow to do calculations involving densities, probabilities and quantiles of these distributions.</p>
<p>Every probability distribution that <tt>R</tt> handles has four basic functions whose names consist of a prefix followed by a root name. As an example, take the normal distribution. The root name of all four functions associated with the normal distribution is <tt>norm</tt>. The four prefixes are</p>
<ul>
<li><tt>d</tt> for “density” - probability function / probability density function</li>
<li><tt>p</tt> for “probability” - cumulative distribution function</li>
<li><tt>q</tt> for “quantile” - quantile function (inverse cumulative distribution function)</li>
<li><tt>r</tt> for “random” - random number generator</li>
</ul>
<p>Thus, for the normal distribution we have the <tt>R</tt> functions <tt>dnorm()</tt>, <tt>pnorm()</tt>, <tt>qnorm()</tt> and <tt>rnorm()</tt>.</p>
</div>
<div id="the-normal-distribution" class="section level3 unnumbered">
<h3>The Normal Distribution</h3>
<p>The probably most important probability distribution considered here is the normal distribution. This is not least due to the special role of the standard normal distribution and the Central Limit Theorem which is to be treated shortly. Normal distributions are symmetric and bell-shaped. A normal distribution is characterized by its mean <span class="math inline">\(\mu\)</span> and its standard deviation <span class="math inline">\(\sigma\)</span>, concisely expressed by <span class="math inline">\(\mathcal{N}(\mu,\sigma^2)\)</span>. The normal distribution has the PDF</p>
<span class="math display">\[\begin{align}
f(x) = \frac{1}{\sqrt{2 \pi} \sigma} \exp{-(x - \mu)^2/(2 \sigma^2)}.
\end{align}\]</span>
<p>For the standard normal distribution we have <span class="math inline">\(\mu=0\)</span> and <span class="math inline">\(\sigma=1\)</span>. Standard normal variates are often denoted by <span class="math inline">\(Z\)</span>. Usually, the standard normal PDF is denoted by <span class="math inline">\(\phi\)</span> and the standard normal CDF is denoted by <span class="math inline">\(\Phi\)</span>. Hence, <span class="math display">\[ \phi(c) = \Phi&#39;(c) \ \ , \ \ \Phi(c) = P(Z \leq c) \ \ , \ \ Z \sim \mathcal{N}(0,1).\]</span> In <tt>R</tt>, we can conveniently obtain densities of normal distributions using the function <tt>dnorm()</tt>. Let us draw a plot of the standard normal density function using <tt>curve()</tt> in conjunction with <tt>dnorm()</tt>.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># draw a plot of the N(0,1) PDF</span>
<span class="kw">curve</span>(<span class="kw">dnorm</span>(x),
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>),
      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, 
      <span class="dt">main =</span> <span class="st">&quot;Standard Normal Density Function&quot;</span>) </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-36-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>We can obtain the density at different positions by passing a vector to <tt>dnorm()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute denstiy at x=-1.96, x=0 and x=1.96</span>
<span class="kw">dnorm</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">1.96</span>, <span class="dv">0</span>, <span class="fl">1.96</span>))</code></pre></div>
<pre><code>## [1] 0.05844094 0.39894228 0.05844094</code></pre>
<p>Similar to the PDF, we can plot the standard normal CDF using <tt>curve()</tt>. We could use <tt>dnorm()</tt> for this but it is much more convenient to rely on <tt>pnorm()</tt>.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the standard normal CDF</span>
<span class="kw">curve</span>(<span class="kw">pnorm</span>(x), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">3.5</span>), 
      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, 
      <span class="dt">main =</span> <span class="st">&quot;Standard Normal Cumulative Distribution Function&quot;</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-38-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>We can also use <tt>R</tt> to calculate the probability of events associated with a standard normal variate.</p>
<p>Let us say we are interested in <span class="math inline">\(P(Z \leq 1.337)\)</span>. For some continuous random variable <span class="math inline">\(Z\)</span> on <span class="math inline">\([-\infty,\infty]\)</span> with density <span class="math inline">\(g(x)\)</span> we would have to determine <span class="math inline">\(G(x)\)</span>, the anti-derivative of <span class="math inline">\(g(x)\)</span> so that</p>
<p><span class="math display">\[ P(Z \leq 1.337 ) = G(1.337) = \int_{-\infty}^{1.337} g(x) \mathrm{d}x.  \]</span></p>
<p>If <span class="math inline">\(Z \sim \mathcal{N}(0,1)\)</span>, we have <span class="math inline">\(g(x)=\phi(x)\)</span>. There is no analytic solution to the integral above. Fortunately, <tt>R</tt> offers good approximations. The first approach makes use of the function <tt>integrate()</tt> which allows to solve one-dimensional integration problems using a numerical method. For this, we first define the function we want to compute the integral of as an <tt>R</tt> function <tt>f</tt>. In our example, <tt>f</tt> is the standard normal density function and hence takes a single argument <tt>x</tt>. Following the definition of <span class="math inline">\(\phi(x)\)</span> we define <tt>f</tt> as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define the standard normal PDF as an R function</span>
f &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
  <span class="dv">1</span><span class="op">/</span>(<span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>pi)) <span class="op">*</span><span class="st"> </span><span class="kw">exp</span>(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span><span class="st"> </span>x<span class="op">^</span><span class="dv">2</span>)
}</code></pre></div>
<p>Let us check if this function computes standard normal densities by passing a vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define a vector of reals</span>
quants &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">1.96</span>, <span class="dv">0</span>, <span class="fl">1.96</span>)

<span class="co"># compute densities</span>
<span class="kw">f</span>(quants)</code></pre></div>
<pre><code>## [1] 0.05844094 0.39894228 0.05844094</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compare to the results produced by &#39;dnorm()&#39;</span>
<span class="kw">f</span>(quants) <span class="op">==</span><span class="st"> </span><span class="kw">dnorm</span>(quants)</code></pre></div>
<pre><code>## [1] TRUE TRUE TRUE</code></pre>
<p>The results produced by <tt>f()</tt> are indeed equivalent to those given by <tt>dnorm()</tt>.</p>
<p>Next, we call <tt>integrate()</tt> on <tt>f()</tt> and specify the arguments <tt>lower</tt> and <tt>upper</tt>, the lower and upper limits of integration.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># integrate f()</span>
<span class="kw">integrate</span>(f, 
          <span class="dt">lower =</span> <span class="op">-</span><span class="ot">Inf</span>, 
          <span class="dt">upper =</span> <span class="fl">1.337</span>)</code></pre></div>
<pre><code>## 0.9093887 with absolute error &lt; 1.7e-07</code></pre>
<p>We find that the probability of observing <span class="math inline">\(Z \leq 1.337\)</span> is about <span class="math inline">\(0.9094\%\)</span>.</p>
<p>A second and much more convenient way is to use the function <tt>pnorm()</tt>, the standard normal cumulative distribution function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the probability using pnorm()</span>
<span class="kw">pnorm</span>(<span class="fl">1.337</span>)</code></pre></div>
<pre><code>## [1] 0.9093887</code></pre>
<p>The result matches the outcome of the approach using <tt>integrate()</tt>.</p>
<p>Let us discuss some further examples:</p>
<p>A commonly known result is that <span class="math inline">\(95\%\)</span> probability mass of a standard normal lies in the interval <span class="math inline">\([-1.96, 1.96]\)</span>, that is, in a distance of about <span class="math inline">\(2\)</span> standard deviations to the mean. We can easily confirm this by calculating <span class="math display">\[ P(-1.96 \leq Z \leq 1.96) = 1-2\times P(Z \leq -1.96) \]</span> due to symmetry of the standard normal PDF. Thanks to <tt>R</tt>, we can abandon the table of the standard normal CDF found in many other textbooks and instead solve this fast by using <tt>pnorm()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the probability</span>
<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="kw">pnorm</span>(<span class="op">-</span><span class="fl">1.96</span>)) </code></pre></div>
<pre><code>## [1] 0.9500042</code></pre>
<p>To make statements about the probability of observing outcomes of <span class="math inline">\(Y\)</span> in some specific range is more convenient when we standardize first as shown in Key Concept 2.4.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.4
</h3>
<h3 class="left">
Computing Probabilities Involving Normal Random Variables
</h3>
<p>
<p>Suppose <span class="math inline">\(Y\)</span> is normally distributed with mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>: <span class="math display">\[Y
\sim \mathcal{N}(\mu, \sigma^2)\]</span> Then <span class="math inline">\(Y\)</span> is standardized by subtracting its mean and dividing by its standard deviation: <span class="math display">\[ Z = \frac{Y -\mu}{\sigma} \]</span> Let <span class="math inline">\(c_1\)</span> and <span class="math inline">\(c_2\)</span> denote two numbers whereby <span class="math inline">\(c_1 &lt; c_2\)</span> and further <span class="math inline">\(d_1 = (c_1 - \mu) / \sigma\)</span> and <span class="math inline">\(d_2 = (c_2 - \mu)/\sigma\)</span>. Then</p>
<span class="math display">\[\begin{align*} 
P(Y \leq c_2) =&amp; \, P(Z \leq d_2) = \Phi(d_2), \\ 
P(Y \geq c_1) =&amp; \, P(Z \geq d_1) = 1 - \Phi(d_1), \\ 
P(c_1 \leq Y \leq c_2) =&amp; \, P(d_1 \leq Z \leq d_2) = \Phi(d_2) - \Phi(d_1). 
\end{align*}\]</span>
</p>
</div>
<p>Now consider a random variable <span class="math inline">\(Y\)</span> with <span class="math inline">\(Y \sim \mathcal{N}(5, 25)\)</span>. <tt>R</tt> functions that handle the normal distribution can perform the standardization. If we are interested in <span class="math inline">\(P(3 \leq Y \leq 4)\)</span> we can use <tt>pnorm()</tt> and adjust for a mean and/or a standard deviation that deviate from <span class="math inline">\(\mu=0\)</span> and <span class="math inline">\(\sigma = 1\)</span> by specifying the arguments <tt>mean</tt> and <tt>sd</tt> accordingly. <strong>Attention</strong>: the argument <tt>sd</tt> requires the standard deviation, not the variance!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pnorm</span>(<span class="dv">4</span>, <span class="dt">mean =</span> <span class="dv">5</span>, <span class="dt">sd =</span> <span class="dv">5</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">3</span>, <span class="dt">mean =</span> <span class="dv">5</span>, <span class="dt">sd =</span> <span class="dv">5</span>) </code></pre></div>
<pre><code>## [1] 0.07616203</code></pre>
<p>An extension of the normal distribution in a univariate setting is the multivariate normal distribution. The joint PDF of two random normal variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is given by</p>
<span class="math display" id="eq:bivnorm">\[\begin{align}
\begin{split}
g_{X,Y}(x,y) =&amp; \, \frac{1}{2\pi\sigma_X\sigma_Y\sqrt{1-\rho_{XY}^2}} \\ 
\cdot &amp; \, \exp \left\{ \frac{1}{-2(1-\rho_{XY}^2)} \left[ \left( \frac{x-\mu_x}{\sigma_X} \right)^2 - 2\rho_{XY}\left( \frac{x-\mu_X}{\sigma_X} \right)\left( \frac{y-\mu_Y}{\sigma_Y} \right) + \left( \frac{y-\mu_Y}{\sigma_Y} \right)^2 \right]  \right\}.
\end{split} \tag{2.1}
\end{align}\]</span>
<p>Equation <a href="pt.html#eq:bivnorm">(2.1)</a> contains the bivariate normal PDF. It is somewhat hard to gain insights from this complicated expression. Instead, let us consider the special case where <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are uncorrelated standard normal random variables with densities <span class="math inline">\(f_X(x)\)</span> and <span class="math inline">\(f_Y(y)\)</span> with joint normal distribution. We then have the parameters <span class="math inline">\(\sigma_X = \sigma_Y = 1\)</span>, <span class="math inline">\(\mu_X=\mu_Y=0\)</span> (due to marginal standard normality) and <span class="math inline">\(\rho_{XY}=0\)</span> (due to independence). The joint density of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> then becomes</p>
<p><span class="math display">\[ g_{X,Y}(x,y) = f_X(x) f_Y(y) = \frac{1}{2\pi} \cdot \exp \left\{ -\frac{1}{2} \left[x^2 + y^2 \right]  \right\}, \tag{2.2}  \]</span></p>
<p>the PDF of the bivariate standard normal distribution. The widget below provides an interactive three-dimensional plot of (<a href="#mjx-eqn-2.2">2.2</a>).</p>
<center>
<iframe scrolling="no" seamless="seamless" style="border:none" src="https://plot.ly/~mca_unidue/22.embed?width=550&amp;height=550?showlink=false/800/1200" width="600" height="400">
</iframe>
</center>
<p>By moving the cursor over the plot you can see that the density is rotationally invariant, i.e., the density at <span class="math inline">\((a, b)\)</span> solely depends on the distance of <span class="math inline">\((a, b)\)</span> to the origin: geometrically, regions of equal density are edges of concentric circles in the <span class="math inline">\(XY\)</span>-plane, centered at <span class="math inline">\((\mu_X = 0, \mu_Y = 0)\)</span>.</p>
<p>The normal distribution has some remarkable characteristics. For example, for two jointly normally distribued variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, the conditional expectation function is linear: one can show that <span class="math display">\[ E(Y\vert X) = E(Y) + \rho \frac{\sigma_Y}{\sigma_X} (X - E(X)). \]</span> The application below shows standard bivariate normally distributed sample data along with the conditional expectation function <span class="math inline">\(E(Y\vert X)\)</span> and the marginal densities of <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. All elements adjust accordingly as you vary the parameters.</p>
<iframe height="880" width="770" frameborder="0" scrolling="no" src="bivariatenormalv4.html">
</iframe>
<p><a name="chisquare"></a></p>
</div>
<div id="the-chi-squared-distribution" class="section level3 unnumbered">
<h3>The Chi-Squared Distribution</h3>
<p>The chi-squared distribution is another distribution relevant in econometrics. It is often needed when testing special types of hypotheses frequently encountered when dealing with regression models.</p>
<p>The sum of <span class="math inline">\(M\)</span> squared independent standard normal distributed random variables follows a chi-squared distribution with <span class="math inline">\(M\)</span> degrees of freedom:</p>
<span class="math display" id="eq:chisq">\[\begin{align*}
Z_1^2 + \dots + Z_M^2 = \sum_{m=1}^M Z_m^2 \sim \chi^2_M \ \ \text{with} \ \ Z_m \overset{i.i.d.}{\sim} \mathcal{N}(0,1) \tag{2.2}
\end{align*}\]</span>
<p>A <span class="math inline">\(\chi^2\)</span> distributed random variable with <span class="math inline">\(M\)</span> degrees of freedom has expectation <span class="math inline">\(M\)</span>, mode at <span class="math inline">\(M-2\)</span> for <span class="math inline">\(M \geq 2\)</span> and variance <span class="math inline">\(2 \cdot M\)</span>. For example, for</p>
<p><span class="math display">\[ Z_1,Z_2,Z_3 \overset{i.i.d.}{\sim} \mathcal{N}(0,1) \]</span></p>
<p>it holds that</p>
<p><span class="math display">\[ Z_1^2+Z_2^2+Z_3^3 \sim \chi^2_3. \tag{2.3} \]</span> Using the code below, we can display the PDF and the CDF of a <span class="math inline">\(\chi^2_3\)</span> random variable in a single plot. This is achieved by setting the argument <tt>add = TRUE</tt> in the second call of <tt>curve()</tt>. Further we adjust limits of both axes using <tt>xlim</tt> and <tt>ylim</tt> and choose different colors to make both functions better distinguishable. The plot is completed by adding a legend with help of <tt>legend()</tt>.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the PDF</span>
<span class="kw">curve</span>(<span class="kw">dchisq</span>(x, <span class="dt">df =</span> <span class="dv">3</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), 
      <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), 
      <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>,
      <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>,
      <span class="dt">main =</span> <span class="st">&quot;p.d.f. and c.d.f of Chi-Squared Distribution, M = 3&quot;</span>)

<span class="co"># add the CDF to the plot</span>
<span class="kw">curve</span>(<span class="kw">pchisq</span>(x, <span class="dt">df =</span> <span class="dv">3</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), 
      <span class="dt">add =</span> <span class="ot">TRUE</span>, 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)

<span class="co"># add a legend to the plot</span>
<span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>, 
       <span class="kw">c</span>(<span class="st">&quot;PDF&quot;</span>, <span class="st">&quot;CDF&quot;</span>), 
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), 
       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-48-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>Since the outcomes of a <span class="math inline">\(\chi^2_M\)</span> distributed random variable are always positive, the support of the related PDF and CDF is <span class="math inline">\(\mathbb{R}_{\geq0}\)</span>.</p>
<p>As expectation and variance depend (solely!) on the degrees of freedom, the distribution’s shape changes drastically if we vary the number of squared standard normals that are summed up. This relation is often depicted by overlaying densities for different <span class="math inline">\(M\)</span>, see the <a href="https://en.wikipedia.org/wiki/Chi-squared_distribution">Wikipedia Article</a>.</p>
<p>We reproduce this here by plotting the density of the <span class="math inline">\(\chi_1^2\)</span> distribution on the interval <span class="math inline">\([0,15]\)</span> with <tt>curve()</tt>. In the next step, we loop over degrees of freedom <span class="math inline">\(M=2,...,7\)</span> and add a density curve for each <span class="math inline">\(M\)</span> to the plot. We also adjust the line color for each iteration of the loop by setting <tt>col = M</tt>. At last, we add a legend that displays degrees of freedom and the associated colors.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the density for M=1</span>
<span class="kw">curve</span>(<span class="kw">dchisq</span>(x, <span class="dt">df =</span> <span class="dv">1</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">15</span>), 
      <span class="dt">xlab =</span> <span class="st">&quot;x&quot;</span>, 
      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, 
      <span class="dt">main =</span> <span class="st">&quot;Chi-Square Distributed Random Variables&quot;</span>)

<span class="co"># add densities for M=2,...,7 to the plot using a &#39;for()&#39; loop </span>
<span class="cf">for</span> (M <span class="cf">in</span> <span class="dv">2</span><span class="op">:</span><span class="dv">7</span>) {
  <span class="kw">curve</span>(<span class="kw">dchisq</span>(x, <span class="dt">df =</span> M),
        <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">15</span>), 
        <span class="dt">add =</span> T, 
        <span class="dt">col =</span> M)
}

<span class="co"># add a legend</span>
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, 
       <span class="kw">as.character</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>), 
       <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">7</span> , 
       <span class="dt">lty =</span> <span class="dv">1</span>, 
       <span class="dt">title =</span> <span class="st">&quot;D.F.&quot;</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-49-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>Increasing the degrees of freedom shifts the distribution to the right (the mode becomes larger) and increases the dispersion (the distribution’s variance grows).</p>
</div>
<div id="thetdist" class="section level3 unnumbered">
<h3>The Student t Distribution</h3>
<p><a name="tdist"></a></p>
<p>Let <span class="math inline">\(Z\)</span> be a standard normal variate, <span class="math inline">\(W\)</span> a <span class="math inline">\(\chi^2_M\)</span> random variable and further assume that <span class="math inline">\(Z\)</span> and <span class="math inline">\(W\)</span> are independent. Then it holds that</p>
<p><span class="math display">\[ \frac{Z}{\sqrt{W/M}} =:X \sim t_M \]</span> and <span class="math inline">\(X\)</span> follows a <em>Student <span class="math inline">\(t\)</span> distribution</em> (or simply <span class="math inline">\(t\)</span> distribution) with <span class="math inline">\(M\)</span> degrees of freedom.</p>
<p>Similar to the <span class="math inline">\(\chi^2_M\)</span> distribution, the shape of a <span class="math inline">\(t_M\)</span> distribution depends on <span class="math inline">\(M\)</span>. <span class="math inline">\(t\)</span> distributions are symmetric, bell-shaped and look similar to a normal distribution, especially when <span class="math inline">\(M\)</span> is large. This is not a coincidence: for a sufficiently large <span class="math inline">\(M\)</span>, the <span class="math inline">\(t_M\)</span> distribution can be approximated by the standard normal distribution. This approximation works reasonably well for <span class="math inline">\(M\geq 30\)</span>. As we will illustrate later by means of a small simulation study, the <span class="math inline">\(t_{\infty}\)</span> distribution <em>is</em> the standard normal distribution.</p>
<p>A <span class="math inline">\(t_M\)</span> distributed random variable <span class="math inline">\(X\)</span> has an expectation if <span class="math inline">\(M&gt;1\)</span> and it has a variance if <span class="math inline">\(M&gt;2\)</span>.</p>
<span class="math display">\[\begin{align}
  E(X) =&amp; 0, \ M&gt;1 \\
  \text{Var}(X) =&amp; \frac{M}{M-2}, \ M&gt;2
\end{align}\]</span>
<p>Let us plot some <span class="math inline">\(t\)</span> distributions with different <span class="math inline">\(M\)</span> and compare them to the standard normal distribution.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the standard normal density</span>
<span class="kw">curve</span>(<span class="kw">dnorm</span>(x), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>), 
      <span class="dt">xlab =</span> <span class="st">&quot;x&quot;</span>, 
      <span class="dt">lty =</span> <span class="dv">2</span>, 
      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, 
      <span class="dt">main =</span> <span class="st">&quot;Densities of t Distributions&quot;</span>)

<span class="co"># plot the t density for M=2</span>
<span class="kw">curve</span>(<span class="kw">dt</span>(x, <span class="dt">df =</span> <span class="dv">2</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>), 
      <span class="dt">col =</span> <span class="dv">2</span>, 
      <span class="dt">add =</span> T)

<span class="co"># plot the t density for M=4</span>
<span class="kw">curve</span>(<span class="kw">dt</span>(x, <span class="dt">df =</span> <span class="dv">4</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>), 
      <span class="dt">col =</span> <span class="dv">3</span>, 
      <span class="dt">add =</span> T)

<span class="co"># plot the t density for M=25</span>
<span class="kw">curve</span>(<span class="kw">dt</span>(x, <span class="dt">df =</span> <span class="dv">25</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>), 
      <span class="dt">col =</span> <span class="dv">4</span>, 
      <span class="dt">add =</span> T)

<span class="co"># add a legend</span>
<span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>, 
       <span class="kw">c</span>(<span class="st">&quot;N(0, 1)&quot;</span>, <span class="st">&quot;M=2&quot;</span>, <span class="st">&quot;M=4&quot;</span>, <span class="st">&quot;M=25&quot;</span>), 
       <span class="dt">col =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, 
       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-50-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The plot illustrates what has been said in the previous paragraph: as the degrees of freedom increase, the shape of the <span class="math inline">\(t\)</span> distribution comes closer to that of a standard normal bell curve. Already for <span class="math inline">\(M=25\)</span> we find little difference to the standard normal density. If <span class="math inline">\(M\)</span> is small, we find the distribution to have heavier tails than a standard normal, i.e., it has a “fatter” bell shape.</p>
</div>
<div id="the-f-distribution" class="section level3 unnumbered">
<h3>The F Distribution</h3>
<p>Another ratio of random variables important to econometricians is the ratio of two independent <span class="math inline">\(\chi^2\)</span> distributed random variables that are divided by their degrees of freedom <span class="math inline">\(M\)</span> and <span class="math inline">\(n\)</span>. The quantity</p>
<p><span class="math display">\[ \frac{W/M}{V/n} \sim F_{M,n} \ \ \text{with} \ \ W \sim \chi^2_M \ \ , \ \ V \sim \chi^2_n \]</span> follows an <span class="math inline">\(F\)</span> distribution with numerator degrees of freedom <span class="math inline">\(M\)</span> and denominator degrees of freedom <span class="math inline">\(n\)</span>, denoted <span class="math inline">\(F_{M,n}\)</span>. The distribution was first derived by George Snedecor but was named in honor of <a href="https://en.wikipedia.org/wiki/Ronald_Fisher">Sir Ronald Fisher</a>.</p>
<p>By definition, the support of both PDF and CDF of an <span class="math inline">\(F_{M,n}\)</span> distributed random variable is <span class="math inline">\(\mathbb{R}_{\geq0}\)</span>.</p>
<p>Say we have an <span class="math inline">\(F\)</span> distributed random variable <span class="math inline">\(Y\)</span> with numerator degrees of freedom <span class="math inline">\(3\)</span> and denominator degrees of freedom <span class="math inline">\(14\)</span> and are interested in <span class="math inline">\(P(Y \geq 2)\)</span>. This can be computed with help of the function <tt>pf()</tt>. By setting the argument <tt>lower.tail</tt> to <tt>TRUE</tt> we ensure that <tt>R</tt> computes <span class="math inline">\(1- P(Y \leq 2)\)</span>, i.e,the probability mass in the tail right of <span class="math inline">\(2\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pf</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">13</span>, <span class="dt">lower.tail =</span> F)</code></pre></div>
<pre><code>## [1] 0.1638271</code></pre>
<p>We can visualize this probability by drawing a line plot of the related density and adding a color shading with <tt>polygon()</tt>.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define coordinate vectors for vertices of the polygon</span>
x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="kw">seq</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="fl">0.01</span>), <span class="dv">10</span>)
y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">df</span>(<span class="kw">seq</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="fl">0.01</span>), <span class="dv">3</span>, <span class="dv">14</span>), <span class="dv">0</span>)

<span class="co"># draw density of F_{3, 14}</span>
<span class="kw">curve</span>(<span class="kw">df</span>(x ,<span class="dv">3</span> ,<span class="dv">14</span>), 
      <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.8</span>), 
      <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">10</span>), 
      <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>,
      <span class="dt">main =</span> <span class="st">&quot;Density Function&quot;</span>)

<span class="co"># draw the polygon</span>
<span class="kw">polygon</span>(x, y, <span class="dt">col =</span> <span class="st">&quot;orange&quot;</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-52-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The <span class="math inline">\(F\)</span> distribution is related to many other distributions. An important special case encountered in econometrics arises if the denominator degrees of freedom are large such that the <span class="math inline">\(F_{M,n}\)</span> distribution can be approximated by the <span class="math inline">\(F_{M,\infty}\)</span> distribution which turns out to be simply the distribution of a <span class="math inline">\(\chi^2_M\)</span> random variable divided by its degrees of freedom <span class="math inline">\(M\)</span>,</p>
<p><span class="math display">\[ W/M \sim F_{M,\infty} \ \ , \ \ W \sim \chi^2_M. \]</span></p>
<iframe src="DCL/playground.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
</div>
</div>
<div id="RSATDOSA" class="section level2">
<h2><span class="header-section-number">2.2</span> Random Sampling and the Distribution of Sample Averages</h2>
<p>To clarify the basic idea of random sampling, let us jump back to the dice rolling example:</p>
<p>Suppose we are rolling the dice <span class="math inline">\(n\)</span> times. This means we are interested in the outcomes of random <span class="math inline">\(Y_i, \ i=1,...,n\)</span> which are characterized by the same distribution. Since these outcomes are selected randomly, they are <em>random variables</em> themselves and their realizations will differ each time we draw a sample, i.e., each time we roll the dice <span class="math inline">\(n\)</span> times. Furthermore, each observation is randomly drawn from the same population, that is, the numbers from <span class="math inline">\(1\)</span> to <span class="math inline">\(6\)</span>, and their individual distribution is the same. Hence <span class="math inline">\(Y_1,\dots,Y_n\)</span> are identically distributed.</p>
<p>Moreover, we know that the value of any of the <span class="math inline">\(Y_i\)</span> does not provide any information on the remainder of the outcomes In our example, rolling a six as the first observation in our sample does not alter the distributions of <span class="math inline">\(Y_2,\dots,Y_n\)</span>: all numbers are equally likely to occur. This means that all <span class="math inline">\(Y_i\)</span> are also independently distributed. Thus <span class="math inline">\(Y_1,\dots,Y_n\)</span> are independently and identically distributed (<em>i.i.d.</em>). The dice example uses this most simple sampling scheme. That is why it is called <em>simple random sampling</em>. This concept is summarized in Key Concept 2.5.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.5
</h3>
<h3 class="left">
Simple Random Sampling and i.i.d. Random Variables
</h3>
<p>
In simple random sampling, <span class="math inline">\(n\)</span> objects are drawn at random from a population. Each object is equally likely to end up in the sample. We denote the value of the random variable <span class="math inline">\(Y\)</span> for the <span class="math inline">\(i^{th}\)</span> randomly drawn object as <span class="math inline">\(Y_i\)</span>. Since all objects are equally likely to be drawn and the distribution of <span class="math inline">\(Y_i\)</span> is the same for all <span class="math inline">\(i\)</span>, the <span class="math inline">\(Y_i, \dots, Y_n\)</span> are independently and identically distributed (i.i.d.). This means the distribution of <span class="math inline">\(Y_i\)</span> is the same for all <span class="math inline">\(i=1,\dots,n\)</span> and <span class="math inline">\(Y_1\)</span> is distributed independently of <span class="math inline">\(Y_2, \dots, Y_n\)</span> and <span class="math inline">\(Y_2\)</span> is distributed independently of <span class="math inline">\(Y_1, Y_3, \dots, Y_n\)</span> and so forth.
</p>
</div>
<p>What happens if we consider functions of the sample data? Consider the example of rolling a dice two times in a row once again. A sample now consists of two independent random draws from the set <span class="math inline">\(\{1,2,3,4,5,6\}\)</span>. In view of the afore, it is apparent that any function of these two random variables is also random, e.g., their sum. Convince yourself by executing the code below several times.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="kw">sample</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dv">2</span>, <span class="dt">replace =</span> T))</code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Clearly, this sum, let us call it <span class="math inline">\(S\)</span>, is a random variable as it depends on randomly drawn summands. For this example, we can completely enumerate all outcomes and hence write down the theoretical probability distribution of our function of the sample data, <span class="math inline">\(S\)</span>:</p>
<p>We face <span class="math inline">\(6^2=36\)</span> possible pairs. Those pairs are</p>
<span class="math display">\[\begin{align*}
  &amp;(1,1)    (1,2)   (1,3)   (1,4)   (1,5)   (1,6) \\ 
  &amp;(2,1)    (2,2)   (2,3)   (2,4)   (2,5)   (2,6) \\ 
  &amp;(3,1)    (3,2)   (3,3)   (3,4)   (3,5)   (3,6) \\ 
  &amp;(4,1)    (4,2)   (4,3)   (4,4)   (4,5)   (4,6) \\ 
  &amp;(5,1)    (5,2)   (5,3)   (5,4)   (5,5)   (5,6) \\ 
  &amp;(6,1)    (6,2)   (6,3)   (6,4)   (6,5)   (6,6)
\end{align*}\]</span>
<p>Thus, possible outcomes for <span class="math inline">\(S\)</span> are</p>
<p><span class="math display">\[ \left\{ 2,3,4,5,6,7,8,9,10,11,12 \right\} . \]</span> Enumeration of outcomes yields</p>
<span class="math display">\[\begin{align}
  P(S) = 
  \begin{cases} 
    1/36, \ &amp; S = 2 \\ 
    2/36, \ &amp; S = 3 \\
    3/36, \ &amp; S = 4 \\
    4/36, \ &amp; S = 5 \\
    5/36, \ &amp; S = 6 \\
    6/36, \ &amp; S = 7 \\
    5/36, \ &amp; S = 8 \\
    4/36, \ &amp; S = 9 \\
    3/36, \ &amp; S = 10 \\
    2/36, \ &amp; S = 11 \\
    1/36, \ &amp; S = 12
  \end{cases}
\end{align}\]</span>
<p>We can also compute <span class="math inline">\(E(S)\)</span> and <span class="math inline">\(\text{Var}(S)\)</span> as stated in Key Concept 2.1 and Key Concept 2.2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Vector of outcomes</span>
S &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">:</span><span class="dv">12</span>

<span class="co"># Vector of probabilities</span>
PS &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">6</span>, <span class="dv">5</span><span class="op">:</span><span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">36</span>

<span class="co"># Expectation of S</span>
ES &lt;-<span class="st"> </span>S <span class="op">%*%</span><span class="st"> </span>PS
ES</code></pre></div>
<pre><code>##      [,1]
## [1,]    7</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Variance of S</span>
VarS &lt;-<span class="st"> </span>(S <span class="op">-</span><span class="st"> </span><span class="kw">c</span>(ES))<span class="op">^</span><span class="dv">2</span> <span class="op">%*%</span><span class="st"> </span>PS
VarS</code></pre></div>
<pre><code>##          [,1]
## [1,] 5.833333</code></pre>
<p>The <tt>%*%</tt> operator is used to compute the scalar product of two vectors.</p>
<p>So the distribution of <span class="math inline">\(S\)</span> is known. It is also evident that its distribution differs considerably from the marginal distribution, i.e,the distribution of a single dice roll’s outcome, <span class="math inline">\(D\)</span> . Let us visualize this using bar plots.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># divide the plotting area into one row with two columns</span>
<span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))

<span class="co"># plot the distribution of S</span>
<span class="kw">barplot</span>(PS, 
        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>), 
        <span class="dt">xlab =</span> <span class="st">&quot;S&quot;</span>, 
        <span class="dt">ylab =</span> <span class="st">&quot;Probability&quot;</span>, 
        <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
        <span class="dt">space =</span> <span class="dv">0</span>, 
        <span class="dt">main =</span> <span class="st">&quot;Sum of Two Dice Rolls&quot;</span>)

<span class="co"># plot the distribution of D </span>
probability &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">6</span>, <span class="dv">6</span>)
<span class="kw">names</span>(probability) &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>

<span class="kw">barplot</span>(probability, 
        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>), 
        <span class="dt">xlab =</span> <span class="st">&quot;D&quot;</span>, 
        <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
        <span class="dt">space =</span> <span class="dv">0</span>, 
        <span class="dt">main =</span> <span class="st">&quot;Outcome of a Single Dice Roll&quot;</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-58-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>Many econometric procedures deal with averages of sampled data. It is typically assumed that observations are drawn randomly from a larger, unknown population. As demonstrated for the sample function <span class="math inline">\(S\)</span>, computing an average of a random sample has the effect that the average is a random variable itself. This random variable in turn has a probability distribution, called the sampling distribution. Knowledge about the sampling distribution of the average is therefore crucial for understanding the performance of econometric procedures.</p>
<p>The <em>sample average</em> of a sample of <span class="math inline">\(n\)</span> observations <span class="math inline">\(Y_1, \dots, Y_n\)</span> is</p>
<p><span class="math display">\[ \overline{Y} = \frac{1}{n} \sum_{i=1}^n Y_i = \frac{1}{n} (Y_1 + Y_2 + \cdots + Y_n). \]</span> <span class="math inline">\(\overline{Y}\)</span> is also called the sample mean.</p>
<div id="mean-and-variance-of-the-sample-mean" class="section level3 unnumbered">
<h3>Mean and Variance of the Sample Mean</h3>
<p>suppose that all observations <span class="math inline">\(Y_1,\dots,Y_n\)</span> are i.i.d. and denote <span class="math inline">\(\mu_Y\)</span> and <span class="math inline">\(\sigma_Y^2\)</span> the mean and the variance of the <span class="math inline">\(Y_i\)</span>. Then we have that</p>
<p><span class="math display">\[ E(\overline{Y}) = E\left(\frac{1}{n} \sum_{i=1}^n Y_i \right) = \frac{1}{n} E\left(\sum_{i=1}^n Y_i\right) = \frac{1}{n} \sum_{i=1}^n E\left(Y_i\right) = \frac{1}{n} \cdot n \cdot \mu_Y = \mu_Y    \]</span> and</p>
<span class="math display">\[\begin{align*}
  \text{Var}(\overline{Y}) =&amp; \text{Var}\left(\frac{1}{n} \sum_{i=1}^n Y_i \right) \\
  =&amp; \frac{1}{n^2} \sum_{i=1}^n \text{Var}(Y_i) + \frac{1}{n^2} \sum_{i=1}^n \sum_{j=1, j\neq i}^n \text{cov}(Y_i,Y_j) \\
  =&amp; \frac{\sigma^2_Y}{n} \\
  =&amp; \sigma_{\overline{Y}}^2.
\end{align*}\]</span>
<p>The second summand vanishes since <span class="math inline">\(\text{cov}(Y_i,Y_j)=0\)</span> for <span class="math inline">\(i\neq j\)</span> due to independence. Consequently, the standard deviation of the sample mean is given by <span class="math display">\[\sigma_{\overline{Y}} = \frac{\sigma_Y}{\sqrt{n}}.\]</span></p>
<p>It is worthwhile to mention that these results hold irrespective of the underlying distribution of the <span class="math inline">\(Y_i\)</span>.</p>
<div id="the-sampling-distribution-of-overliney-when-y-is-normally-distributed" class="section level4 unnumbered">
<h4>The Sampling Distribution of <span class="math inline">\(\overline{Y}\)</span> when <span class="math inline">\(Y\)</span> Is Normally Distributed</h4>
<p>If the <span class="math inline">\(Y_1,\dots,Y_n\)</span> are i.i.d. draws from a normal distribution with mean <span class="math inline">\(\mu_Y\)</span> and variance <span class="math inline">\(\sigma_Y^2\)</span>, the following holds for their sample average <span class="math inline">\(\overline{Y}\)</span>:</p>
<p><span class="math display">\[ \overline{Y} \sim \mathcal{N}(\mu_Y, \sigma_Y^2/n) \tag{2.4} \]</span></p>
<p>For example, if a sample <span class="math inline">\(Y_i\)</span> with <span class="math inline">\(i=1,\dots,10\)</span> is drawn from a standard normal distribution with mean <span class="math inline">\(\mu_Y = 0\)</span> and variance <span class="math inline">\(\sigma_Y^2=1\)</span> we have</p>
<p><span class="math display">\[ \overline{Y} \sim \mathcal{N}(0,0.1).\]</span></p>
<p>We can use <tt>R</tt>’s random number generation facilities to verify this result. The basic idea is to simulate outcomes of the true distribution of <span class="math inline">\(\overline{Y}\)</span> by repeatedly drawing random samples of 10 observation from the <span class="math inline">\(\mathcal{N}(0,1)\)</span> distribution and computing their respective averages. If we do this for a large number of repetitions, the simulated data set of averages should quite accurately reflect the theoretical distribution of <span class="math inline">\(\overline{Y}\)</span> if the theoretical result holds.</p>
<p>The approach sketched above is an example of what is commonly known as <em>Monte Carlo Simulation</em> or <em>Monte Carlo Experiment</em>. To perform this simulation in <tt>R</tt>, we proceed as follows:</p>
<ol style="list-style-type: decimal">
<li>Choose a sample size <tt>n</tt> and the number of samples to be drawn, <tt>reps</tt>.</li>
<li>Use the function <tt>replicate()</tt> in conjunction with <tt>rnorm()</tt> to draw <tt>n</tt> observations from the standard normal distribution <tt>rep</tt> times. <strong>Note</strong>: the outcome of <tt>replicate()</tt> is a matrix with dimensions <tt>n</tt> <span class="math inline">\(\times\)</span> <tt>rep</tt>. It contains the drawn samples as <em>columns</em>.</li>
<li>Compute sample means using <tt>colMeans()</tt>. This function computes the mean of each column, i.e., of each sample and returns a vector.</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set sample size and number of samples</span>
n &lt;-<span class="st"> </span><span class="dv">10</span>
reps &lt;-<span class="st"> </span><span class="dv">10000</span>

<span class="co"># perform random sampling</span>
samples &lt;-<span class="st"> </span><span class="kw">replicate</span>(reps, <span class="kw">rnorm</span>(n)) <span class="co"># 10 x 10000 sample matrix</span>

<span class="co"># compute sample means</span>
sample.avgs &lt;-<span class="st"> </span><span class="kw">colMeans</span>(samples)</code></pre></div>
<p>We then end up with a vector of sample averages. You can check the vector property of <tt>sample.avgs</tt>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check that &#39;sample.avgs&#39; is a vector</span>
<span class="kw">is.vector</span>(sample.avgs) </code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># print the first few entries to the console</span>
<span class="kw">head</span>(sample.avgs)</code></pre></div>
<pre><code>## [1] -0.12406767 -0.10649421 -0.01033423 -0.39905236 -0.41897968 -0.90883537</code></pre>
<p>A straightforward approach to examine the distribution of univariate numerical data is to plot it as a histogram and compare it to some known or assumed distribution. By default, <tt>hist()</tt> will give us a frequency histogram, i.e., a bar chart where observations are grouped into ranges, also called bins. The ordinate reports the number of observations falling into each of the bins. Instead, we want it to report density estimates for comparison purposes. This is achieved by setting the argument <tt>freq = FALSE</tt>. The number of bins is adjusted by the argument <tt>breaks</tt>.</p>
<p>Using <tt>curve()</tt>, we overlay the histogram with a red line, the theoretical density of a <span class="math inline">\(\mathcal{N}(0, 0.1)\)</span> random variable. Remember to use the argument <tt>add = TRUE</tt> to add the curve to the current plot. Otherwise <tt>R</tt> will open a new graphic device and discard the previous plot!<a href="#fn3" class="footnoteRef" id="fnref3"><sup>3</sup></a></p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Plot the density histogram</span>
<span class="kw">hist</span>(sample.avgs, 
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">1.4</span>), 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span> , 
     <span class="dt">freq =</span> F, 
     <span class="dt">breaks =</span> <span class="dv">20</span>)

<span class="co"># overlay the theoretical distribution of sample averages on top of the histogram</span>
<span class="kw">curve</span>(<span class="kw">dnorm</span>(x, <span class="dt">sd =</span> <span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(n)), 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, 
      <span class="dt">lwd =</span> <span class="st">&quot;2&quot;</span>, 
      <span class="dt">add =</span> T)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-61-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The sampling distribution of <span class="math inline">\(\overline{Y}\)</span> is indeed very close to that of a <span class="math inline">\(\mathcal{N}(0, 0.1)\)</span> distribution so the Monte Carlo Simulation supports the theoretical claim.</p>
<p>Let us discuss another example where using simple random sampling in a simulation setup helps to verify a well known result. As discussed before, the <a href="#chisquare">Chi-squared</a> distribution with <span class="math inline">\(M\)</span> degrees of freedom arises as the distribution of the sum of <span class="math inline">\(M\)</span> independent squared standard normal distributed random variables.</p>
<p>To visualize the claim stated in equation (<a href="#mjx-eqn-2.3">2.3</a>), we proceed similarly as in the example before:</p>
<ol style="list-style-type: decimal">
<li>Choose the degrees of freedom, <tt>DF</tt>, and the number of samples to be drawn <tt>reps</tt>.</li>
<li>Draw <tt>reps</tt> random samples of size <tt>DF</tt> from the standard normal distribution using <tt>replicate()</tt>.</li>
<li>For each sample, square the outcomes and sum them up column-wise. Store the results.</li>
</ol>
<p>Again, we produce a density estimate for the distribution underlying our simulated data using a density histogram and overlay it with a line graph of the theoretical density function of the <span class="math inline">\(\chi^2_3\)</span> distribution.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># number of repititions</span>
reps &lt;-<span class="st"> </span><span class="dv">10000</span>

<span class="co"># set degrees of freedom of a chi-Square Distribution</span>
DF &lt;-<span class="st"> </span><span class="dv">3</span> 

<span class="co"># sample 10000 column vectors à 3 N(0,1) R.V.S</span>
Z &lt;-<span class="st"> </span><span class="kw">replicate</span>(reps, <span class="kw">rnorm</span>(DF)) 

<span class="co"># column sums of squares</span>
X &lt;-<span class="st"> </span><span class="kw">colSums</span>(Z<span class="op">^</span><span class="dv">2</span>)

<span class="co"># histogram of column sums of squares</span>
<span class="kw">hist</span>(X, 
     <span class="dt">freq =</span> F, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">breaks =</span> <span class="dv">40</span>, 
     <span class="dt">ylab =</span> <span class="st">&quot;Density&quot;</span>, 
     <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)

<span class="co"># add theoretical density</span>
<span class="kw">curve</span>(<span class="kw">dchisq</span>(x, <span class="dt">df =</span> DF), 
      <span class="dt">type =</span> <span class="st">&#39;l&#39;</span>, 
      <span class="dt">lwd =</span> <span class="dv">2</span>, 
      <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>, 
      <span class="dt">add =</span> T)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-62-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="large-sample-approximations-to-sampling-distributions" class="section level3 unnumbered">
<h3>Large Sample Approximations to Sampling Distributions</h3>
<p>Sampling distributions as considered in the last section play an important role in the development of econometric methods. There are two main approaches in characterizing sampling distributions: an “exact” approach and an “approximate” approach.</p>
<p>The exact approach aims to find a general formula for the sampling distribution that holds for any sample size <span class="math inline">\(n\)</span>. We call this the <em>exact distribution</em> or <em>finite-sample distribution</em>. In the previous examples of dice rolling and normal variates, we have dealt with functions of random variables whose sample distributions are <em>excactly known</em> in the sense that we can write them down as analytic expressions. However, this is not always possible. For <span class="math inline">\(\overline{Y}\)</span>, result (<a href="#mjx-eqn-2.4">2.4</a>) tells us that normality of the <span class="math inline">\(Y_i\)</span> implies normality of <span class="math inline">\(\overline{Y}\)</span> (we demonstrated this for the special case of <span class="math inline">\(Y_i \overset{i.i.d.}{\sim} \mathcal{N}(0,1)\)</span> with <span class="math inline">\(n=10\)</span> using a simulation study that involves simple random sampling). Unfortunately, the <em>exact</em> distribution of <span class="math inline">\(\overline{Y}\)</span> is generally unknown and often hard to derive (or even untraceable) if we drop the assumption that the <span class="math inline">\(Y_i\)</span> have a normal distribution.</p>
<p>Therefore, as can be guessed from its name, the “approximate” approach aims to find an approximation to the sampling distribution where it is required that the sample size <span class="math inline">\(n\)</span> is large. A distribution that is used as a large-sample approximation to the sampling distribution is also called the <em>asymptotic distribution</em>. This is due to the fact that the asymptotic distribution <em>is</em> the sampling distribution for <span class="math inline">\(n \rightarrow \infty\)</span>, i.e., the approximation becomes exact if the sample size goes to infinity. However, the difference between the sampling distribution and the asymptotic distribution is negligible for moderate or even small samples sizes so that approximations using the asymptotic distribution are useful.</p>
<p>In this section we will discuss two well known results that are used to approximate sampling distributions and thus constitute key tools in econometric theory: the <em>law of large numbers</em> and the <em>central limit theorem</em>. The law of large numbers states that in large samples, <span class="math inline">\(\overline{Y}\)</span> is close to <span class="math inline">\(\mu_Y\)</span> with high probability. The central limit theorem says that the sampling distribution of the standardized sample average, that is, <span class="math inline">\((\overline{Y} - \mu_Y)/\sigma_{\overline{Y}}\)</span> is asymptotically normally distributed. It is particularly interesting that both results do not depend on the distribution of <span class="math inline">\(Y\)</span>. In other words, being unable to describe the complicated sampling distribution of <span class="math inline">\(\overline{Y}\)</span> if <span class="math inline">\(Y\)</span> is not normal, approximations of the latter using the central limit theorem simplify the development and applicability of econometric procedures enormously. This is a key component underlying the theory of statistical inference for regression models. Both results are summarized in Key Concept 2.6 and Key Concept 2.7.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.6
</h3>
<h3 class="left">
Convergence in Probability, Consistency and the Law of Large Numbers
</h3>
<p>
<p>The sample average <span class="math inline">\(\overline{Y}\)</span> converges in probability to <span class="math inline">\(\mu_Y\)</span>: <span class="math inline">\(\overline{Y}\)</span> is <em>consistent</em> for <span class="math inline">\(\mu_Y\)</span> if the probability that <span class="math inline">\(\overline{Y}\)</span> is in the range <span class="math inline">\((\mu_Y - \epsilon)\)</span> to <span class="math inline">\((\mu_Y + \epsilon)\)</span> becomes arbitrary close to <span class="math inline">\(1\)</span> as <span class="math inline">\(n\)</span> increases for any constant <span class="math inline">\(\epsilon &gt; 0\)</span>. We write this as</p>
<p><span class="math display">\[ \overline{Y} \xrightarrow[]{p} \mu_Y. \]</span></p>
<p>Consider the independently and identically distributed random variables <span class="math inline">\(Y_i, i=1,\dots,n\)</span> with expectation <span class="math inline">\(E(Y_i)=\mu_Y\)</span> and variance <span class="math inline">\(\text{Var}(Y_i)=\sigma^2_Y\)</span>. Under the condition that <span class="math inline">\(\sigma^2_Y&lt; \infty\)</span>, that is, large outliers are unlikely, the law of large numbers states</p>
<p><span class="math display">\[ \overline{Y} \xrightarrow[]{p} \mu_Y. \]</span></p>
The following application simulates a large number of coin tosses (you may set the number of trials using the slider) with a fair coin and computes the fraction of heads observed for each additional toss. The result is a random path that, as stated by the law of large numbers, shows a tendency to approach the value of <span class="math inline">\(0.5\)</span> as <span class="math inline">\(n\)</span> grows. <iframe height="570" width="800" frameborder="0" scrolling="no" src="CoinTossingWLLN.html"></iframe>
</p>
</div>
<p>The core statement of the law of large numbers is that under quite general conditions, the probability of obtaining a sample average <span class="math inline">\(\overline{Y}\)</span> that is close to <span class="math inline">\(\mu_Y\)</span> is high if we have a large sample size.</p>
<p>Consider the example of repeatedly tossing a coin where <span class="math inline">\(Y_i\)</span> is the result of the <span class="math inline">\(i^{th}\)</span> coin toss. <span class="math inline">\(Y_i\)</span> is a Bernoulli distributed random variable with <span class="math inline">\(p\)</span> the probability of observing head <span class="math display">\[ P(Y_i) = \begin{cases} p, &amp; Y_i = 1 \\ 1-p, &amp; Y_i = 0 \end{cases} \]</span> where <span class="math inline">\(p = 0.5\)</span> as we assume a fair coin. It is straightforward to show that</p>
<p><span class="math display">\[ \mu_Y = p = 0.5. \]</span> Let <span class="math inline">\(R_n\)</span> denote the proportion of heads in the first <span class="math inline">\(n\)</span> tosses,</p>
<p><span class="math display">\[ R_n = \frac{1}{n} \sum_{i=1}^n Y_i. \tag{2.5}\]</span></p>
<p>According to the law of large numbers, the observed proportion of heads converges in probability to <span class="math inline">\(\mu_Y = 0.5\)</span>, the probability of tossing head in a <em>single</em> coin toss, <span class="math display">\[ R_n \xrightarrow[]{p} \mu_Y=0.5 \ \ \text{as} \ \ n \rightarrow \infty.\]</span> This result is the as the one illustrated by the interactive application in Key Concept 2.6. We now show how to replicate this using <tt>R</tt>.</p>
<p>The procedure is as follows:</p>
<ol style="list-style-type: decimal">
<li>Sample <tt>N</tt> observations from the Bernoulli distribution, e.g., using <tt>sample()</tt>.</li>
<li>Calculate the proportion of heads <span class="math inline">\(R_n\)</span> as in (<a href="#mjx-eqn-2.5">2.5</a>). A way to achieve this is to call <tt>cumsum()</tt> on the vector of observations <tt>Y</tt> to obtain its cumulative sum and then divide by the respective number of observations.</li>
</ol>
<p>We continue by plotting the path and also add a dashed line for the benchmark probability <span class="math inline">\(p = 0.5\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set seed</span>
<span class="kw">set.seed</span>(<span class="dv">1</span>)

<span class="co"># set number of coin tosses and simulate</span>
N &lt;-<span class="st"> </span><span class="dv">30000</span>
Y &lt;-<span class="st"> </span><span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">1</span>, N, <span class="dt">replace =</span> T)

<span class="co"># Calculate R_n for 1:N</span>
S &lt;-<span class="st"> </span><span class="kw">cumsum</span>(Y)
R &lt;-<span class="st"> </span>S<span class="op">/</span>(<span class="dv">1</span><span class="op">:</span>N)

<span class="co"># Plot the path.</span>
<span class="kw">plot</span>(R, 
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="fl">0.3</span>, <span class="fl">0.7</span>), 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>, 
     <span class="dt">xlab =</span> <span class="st">&quot;n&quot;</span>, 
     <span class="dt">ylab =</span> <span class="st">&quot;R_n&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Converging Share of Heads in Repeated Coin Tossing&quot;</span>)

<span class="co"># Add a dashed line for R_n = 0.5</span>
<span class="kw">lines</span>(<span class="kw">c</span>(<span class="dv">0</span>, N), 
      <span class="kw">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>), 
      <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>, 
      <span class="dt">lty =</span> <span class="dv">2</span>, 
      <span class="dt">lwd =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-65-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>There are several things to be said about this plot.</p>
<ul>
<li><p>The blue graph shows the observed proportion of heads when tossing a coin <span class="math inline">\(n\)</span> times.</p></li>
<li><p>Since the <span class="math inline">\(Y_i\)</span> are random variables, <span class="math inline">\(R_n\)</span> is a random variate, too. The path depicted is only one of many possible realizations of <span class="math inline">\(R_n\)</span> as it is determined by the <span class="math inline">\(30000\)</span> observations sampled from the Bernoulli distribution. Thus, the code chunk above produces a different path every time you execute it (try this below!).</p></li>
<li><p>If the number of coin tosses <span class="math inline">\(n\)</span> is small, the proportion of heads may be anything but close to its theoretical value, <span class="math inline">\(\mu_Y = 0.5\)</span>. However, as more and more observation are included in the sample we find that the path stabilizes in the neighborhood of <span class="math inline">\(0.5\)</span>. The average of multiple trials shows a clear tendency to converge to its expected value as the sample size increases, just as claimed by the law of large numbers.</p></li>
</ul>
<div class="keyconcept">
<h3 class="right">
Key Concept 2.7
</h3>
<h3 class="left">
The Central Limit Theorem
</h3>
<p>
<p>Suppose that <span class="math inline">\(Y_1,\dots,Y_n\)</span> are independently and identically distributed random variables with expectation <span class="math inline">\(E(Y_i)=\mu_Y\)</span> and variance <span class="math inline">\(\text{Var}(Y_i)=\sigma^2_Y\)</span> where <span class="math inline">\(0&lt;\sigma^2_Y&lt;\infty\)</span>.<br> The Central Limit Theorem (CLT) states that, if the sample size <span class="math inline">\(n\)</span> goes to infinity, the distribution of the standardized sample average <span class="math display">\[ \frac{\overline{Y} - \mu_Y}{\sigma_{\overline{Y}}} = \frac{\overline{Y} - \mu_Y}{\sigma_Y/\sqrt{n}} \ \]</span> becomes arbitrarily well approximated by the standard normal distribution.</p>
<p>The application below demonstrates the CLT for the sample average of normally distributed random variables with mean <span class="math inline">\(5\)</span> and variance <span class="math inline">\(25^2\)</span>. You may check the following properties:</p>
<ul>
<li>The distribution of the sample average is normal.</li>
<li>As the sample size increases, the distribution of <span class="math inline">\(\overline{Y}\)</span> tightens around the true mean of <span class="math inline">\(5\)</span>.</li>
<li>The distribution of the standardized sample average is close to the standard normal distribution for large <span class="math inline">\(n\)</span>.</li>
</ul>
<iframe height="620" width="800" frameborder="0" scrolling="no" src="normaldisthistWLLN.html">
</iframe>
</p>
</div>
<p>According to the CLT, the distribution of the sample mean <span class="math inline">\(\overline{Y}\)</span> of the Bernoulli distributed random variables <span class="math inline">\(Y_i\)</span>, <span class="math inline">\(i=1,...,n\)</span>, is well approximated by the normal distribution with parameters <span class="math inline">\(\mu_Y=p=0.5\)</span> and <span class="math inline">\(\sigma^2_{Y} = p(1-p) = 0.25\)</span> for large <span class="math inline">\(n\)</span>. Consequently, for the standardized sample mean we conclude that <span class="math display">\[ \frac{\overline{Y} - 0.5}{0.5/\sqrt{n}} \tag{2.6}\]</span> should be well approximated by the standard normal distribution <span class="math inline">\(\mathcal{N}(0,1)\)</span>. We employ another simulation study to demonstrate this graphically. The idea is as follows.</p>
<p>Draw a large number of random samples, <span class="math inline">\(10000\)</span> say, of size <span class="math inline">\(n\)</span> from the Bernoulli distribution and compute the sample averages. Standardize the averages as shown in (<a href="#mjx-eqn-2.6">2.6</a>). Next, visualize the distribution of the generated standardized sample averages by means of a histogram and compare to the standard normal distribution. Repeat this for different sample sizes <span class="math inline">\(n\)</span> to see how increasing the sample size <span class="math inline">\(n\)</span> impacts the simulated distribution of the averages.</p>
<p>In <tt>R</tt>, realize this as follows:</p>
<ol style="list-style-type: decimal">
<li><p>We start by defining that the next four subsequently generated figures shall be drawn in a <span class="math inline">\(2\times2\)</span> array such that they can be easily compared. This is done by calling <tt>par(mfrow = c(2, 2))</tt> before the figures are generated.</p></li>
<li><p>We define the number of repetitions <tt>reps</tt> as <span class="math inline">\(10000\)</span> and create a vector of sample sizes named <tt>sample.sizes</tt>. We consider samples of sizes <span class="math inline">\(2\)</span>, <span class="math inline">\(10\)</span>, <span class="math inline">\(50\)</span> and <span class="math inline">\(100\)</span>.</p></li>
<li><p>Next, we combine two <tt>for()</tt> loops to simulate the data and plot the distributions. The inner loop generates <span class="math inline">\(10000\)</span> random samples, each consisting of <tt>n</tt> observations that are drawn from the Bernoulli distribution, and computes the standardized averages. The outer loop executes the inner loop for the different sample sizes <tt>n</tt> and produces a plot for each iteration.</p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># subdivide the plot panel into a 2-by-2 array</span>
<span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))

<span class="co"># set the number of repetitions and the sample sizes</span>
reps &lt;-<span class="st"> </span><span class="dv">10000</span>
sample.sizes &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="dv">50</span>, <span class="dv">100</span>)

<span class="co"># outer loop (loop over the sample sizes)</span>
  <span class="cf">for</span> (n <span class="cf">in</span> sample.sizes) {
    
    samplemean &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, reps) <span class="co">#initialize the vector of sample menas</span>
    stdsamplemean &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>, reps) <span class="co">#initialize the vector of standardized sample menas</span>

<span class="co"># inner loop (loop over repetitions)   </span>
    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span>reps) {
      x &lt;-<span class="st"> </span><span class="kw">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>)
      samplemean[i] &lt;-<span class="st"> </span><span class="kw">mean</span>(x)
      stdsamplemean[i] &lt;-<span class="st"> </span><span class="kw">sqrt</span>(n)<span class="op">*</span>(<span class="kw">mean</span>(x) <span class="op">-</span><span class="st"> </span><span class="fl">0.5</span>)<span class="op">/</span><span class="fl">0.5</span>
    }
    
<span class="co"># plot the histogram and overlay it with the N(0,1) density for every iteration    </span>
    <span class="kw">hist</span>(stdsamplemean, 
         <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
         <span class="dt">breaks =</span> <span class="dv">40</span>, 
         <span class="dt">freq =</span> <span class="ot">FALSE</span>, 
         <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>), 
         <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.4</span>), 
         <span class="dt">xlab =</span> <span class="kw">paste</span>(<span class="st">&quot;n =&quot;</span>, n), 
         <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)
    
    <span class="kw">curve</span>(<span class="kw">dnorm</span>(x), 
          <span class="dt">lwd =</span> <span class="dv">2</span>, 
          <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>, 
          <span class="dt">add =</span> <span class="ot">TRUE</span>)
  }  </code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-68-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We see that the simulated sampling distribution of the standardized average tends to deviate strongly from the standard normal distribution if the sample size is small, e.g., for <span class="math inline">\(n=5\)</span> and <span class="math inline">\(n=10\)</span>. However as <span class="math inline">\(n\)</span> grows, the histograms approach the standard normal distribution. The approximation works quite well, see <span class="math inline">\(n=100\)</span>.</p>
<iframe src="DCL/playground.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
</div>
</div>
<div id="exercises" class="section level2">
<h2><span class="header-section-number">2.3</span> Exercises</h2>
<div class="DCexercise">
<h4 id="sampling" class="unnumbered">1. Sampling</h4>
<p>Suppose you are the lottery fairy in a weekly lottery, where <span class="math inline">\(6\)</span> out of <span class="math inline">\(49\)</span> <em>unique</em> numbers are drawn.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Draw the winning numbers for this week.</li>
</ul>
<iframe src="DCL/ex2_1.html" frameborder="0" scrolling="no" style="width:100%;height:360px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>You may use the function <tt>sample()</tt> to draw random numbers, see <code>?sample</code>.</p></li>
<li><p>The set of elements to be sampled from here is <span class="math inline">\(\{1,...,49\}\)</span>.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="probability-density-function" class="unnumbered">2. Probability Density Function</h4>
<p>Consider a random variable <span class="math inline">\(X\)</span> with probability density function (PDF)</p>
<p><span class="math display">\[f_X(x)=\frac{x}{4}e^{-x^2/8},\quad x\geq 0.\]</span></p>
<p><strong>Instructions:</strong></p>
<ul>
<li><p>Define the PDF from above as a function <tt>f()</tt>. <tt>exp(a)</tt> computes <span class="math inline">\(e^a\)</span>.</p></li>
<li><p>Check whether the function you have defined is indeed a PDF.</p></li>
</ul>
<iframe src="DCL/ex2_2.html" frameborder="0" scrolling="no" style="width:100%;height:360px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>Use <tt>function(x) {…}</tt> to define a function which takes the argument <tt>x</tt>.</p></li>
<li><p>In order for <tt>f()</tt> to be a PDF, its integral over the whole domain has to equal 1: <span class="math inline">\(\int_0^\infty f_X(x)\mathrm{d}x=1\)</span>.</p></li>
<li><p>The function <tt>integrate()</tt> performs integration. You have to specify the function to be integrated as well as lower and upper limits of integration. These may be set to <span class="math inline">\([-\infty,\infty]\)</span> by setting the corresponding arguments to <tt>-Inf</tt> and <tt>Inf</tt>. You can access the numerical value of the computed integral by appending <tt>$value</tt>. See `?integral for a detailed description of the function.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="expected-value-and-variance" class="unnumbered">3. Expected Value and Variance</h4>
<p>In this exercise you have to compute the expected value and the variance of the random variable <span class="math inline">\(X\)</span> considered in the previous exercise.</p>
<p>The PDF <tt>f()</tt> from the previous exercise is available in your working environment.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li><p>Define a suitable function <tt>ex()</tt> which integrates to the expected value of <span class="math inline">\(X\)</span>.</p></li>
<li><p>Compute the expected value of <span class="math inline">\(X\)</span>. Store the result in <tt>expected_value</tt>.</p></li>
<li><p>Define a suitable function <tt>ex2()</tt> which integrates to the expected value of <span class="math inline">\(X^2\)</span>.</p></li>
<li><p>Compute the variance of <span class="math inline">\(X\)</span>. Store the result in <tt>variance</tt>.</p></li>
</ul>
<iframe src="DCL/ex2_3.html" frameborder="0" " scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>The expected value of <span class="math inline">\(X\)</span> is defined as <span class="math inline">\(E(X)=\int_0^\infty xf_X(x)dx\)</span>.</p></li>
<li><p>The value of an integral computed by <tt>integrate()</tt> can be obtained via <tt>$value</tt>.</p></li>
<li><p>The variance of <span class="math inline">\(X\)</span> is defined as <span class="math inline">\(Var(X)=E(X^2)-E(X)^2\)</span>, where <span class="math inline">\(E(X^2)=\int_0^\infty x^2f_X(x)\mathrm{d}x\)</span>.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="standard-normal-distribution-i" class="unnumbered">4. Standard Normal Distribution I</h4>
<p>Let <span class="math inline">\(Z\sim\mathcal{N}(0, 1)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute <span class="math inline">\(\phi(3)\)</span>, that is, the value of the standard normal density at <span class="math inline">\(c=3\)</span>.</li>
</ul>
<iframe src="DCL/ex2_4.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li>Values of <span class="math inline">\(\phi(\cdot)\)</span> can be computed using <tt>dnorm()</tt>. Note that by default <tt>dnorm()</tt> uses <tt>mean = 0</tt> and <tt>sd = 1</tt> so there is no need to set the corresponding arguments when you whish to obtain density values of the standard normal distribution.</li>
</ul>
</div>
<div class="DCexercise">
<h4 id="standard-normal-distribution-ii" class="unnumbered">5. Standard Normal Distribution II</h4>
<p>Let <span class="math inline">\(Z\sim\mathcal{N}(0, 1)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute <span class="math inline">\(P(|Z|\leq 1.64)\)</span> by using the function <tt>pnorm()</tt>.</li>
</ul>
<iframe src="DCL/ex2_5.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p><span class="math inline">\(P(|Z|\leq z) = P(-z \leq Z \leq z)\)</span>.</p></li>
<li><p>Probabilities of the form <span class="math inline">\(P(a \leq Z \leq b)\)</span> can be computed as <span class="math inline">\(P(Z\leq b)-P(Z\leq a)=F_Z(b)-F_Z(a)\)</span> with <span class="math inline">\(F_Z(\cdot)\)</span> the cumulative distribution function (CDF) of <span class="math inline">\(Z\)</span>. Alternatively, you may exploit the symmetry of the standard normal distribution.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="normal-distribution-i" class="unnumbered">6. Normal Distribution I</h4>
<p>Let <span class="math inline">\(Y\sim\mathcal{N}(5, 25)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute the 99% quantile of the given distribution, i.e., find <span class="math inline">\(y\)</span> such that <span class="math inline">\(\Phi(\frac{y-5}{5})=0.99\)</span>.</li>
</ul>
<iframe src="DCL/ex2_6.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>You can compute quantiles of the normal distribution by using the function <tt>qnorm()</tt>.</p></li>
<li><p>Besides the quantile to be computed you have to specify the mean and the standard deviation of the distribution. This is done via the arguments <tt>mean</tt> and <tt>sd</tt>. Note that <tt>sd</tt> sets the standard deviation, not the variance!</p></li>
<li><p><tt>sqrt(a)</tt> returns the square root of the numeric argument <tt>a</tt>.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="normal-distribution-ii" class="unnumbered">7. Normal Distribution II</h4>
<p>Let <span class="math inline">\(Y\sim\mathcal{N}(2, 12)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Generate <span class="math inline">\(10\)</span> random numbers from this distribution.</li>
</ul>
<iframe src="DCL/ex2_7.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>You can use <tt>rnorm()</tt> to draw random numbers from a normal distribution.</p></li>
<li><p>Besides the number of draws you have to specify the mean and the standard deviation of the distribution. This can be done via the arguments <tt>mean</tt> and <tt>sd</tt>. Note that <tt>sd</tt> requires the standard deviation, not the variance!</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="chi-squared-distribution-i" class="unnumbered">8. Chi-squared Distribution I</h4>
<p>Let <span class="math inline">\(W\sim\chi^2_{10}\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Plot the corresponding PDF using <tt>curve()</tt>. Specify the range of x-values as <span class="math inline">\([0,25]\)</span> via the argument <tt>xlim</tt>.</li>
</ul>
<iframe src="DCL/ex2_8.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p><tt>curve()</tt> expects a function and its parameters as arguments (here <tt>dchisq()</tt> and the degrees of freedom <tt>df</tt>).</p></li>
<li><p>The range of x-values in <tt>xlim</tt> can be passed as a vector of interval bounds.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="chi-squared-distribution-ii" class="unnumbered">9. Chi-squared Distribution II</h4>
<p>Let <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> be two independent normally distributed random variables with <span class="math inline">\(\mu=0\)</span> and <span class="math inline">\(\sigma^2=15\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute <span class="math inline">\(P(X_1^2+X_2^2&gt;10)\)</span>.</li>
</ul>
<iframe src="DCL/ex2_9.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li>Note that <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are not <span class="math inline">\(\mathcal{N}(0,1)\)</span> but <span class="math inline">\(\mathcal{N}(0,15)\)</span> distributed. Hence you have to scale appropriately. Afterwards you can use <tt>pchisq()</tt> to compute the probability.</li>
<li>The argument <tt>lower.tail</tt> may be helpful.</li>
</ul>
</div>
<div class="DCexercise">
<h4 id="student-t-distribution-i" class="unnumbered">10. Student t Distribution I</h4>
<p>Let <span class="math inline">\(X\sim t_{10000}\)</span> and <span class="math inline">\(Z\sim\mathcal{N}(0,1)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute the <span class="math inline">\(95\%\)</span> quantile of both distributions. What do you notice?</li>
</ul>
<iframe src="DCL/ex2_10.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>You may use <tt>qt()</tt> and <tt>qnorm()</tt> to compute quantiles of the given distributions.</p></li>
<li><p>For the <span class="math inline">\(t\)</span> distribution you have to specify the degrees of freedom <tt>df</tt>.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="student-t-distribution-ii" class="unnumbered">11. Student t Distribution II</h4>
<p>Let <span class="math inline">\(X\sim t_1\)</span>. Once the session has initialized you will see the plot of the corresponding probability density function (PDF).</p>
<p><strong>Instructions:</strong></p>
<ul>
<li><p>Generate <span class="math inline">\(1000\)</span> random numbers from this distribution and assign them to the variable <tt>x</tt>.</p></li>
<li><p>Compute the sample mean of <tt>x</tt>. Can you explain the result?</p></li>
</ul>
<iframe src="DCL/ex2_11.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>You can use <tt>rt()</tt> to draw random numbers from a t distribution.</p></li>
<li><p>Note that the t distribution is fully determined through the degree(s) of freedom. Specify them via the argument <tt>df</tt>.</p></li>
<li><p>To compute the sample mean of a vector you can use the function <tt>mean()</tt>.</p></li>
</ul>
</div>
<div class="DCexercise">
<h4 id="f-distribution-i" class="unnumbered">12. F Distribution I</h4>
<p>Let <span class="math inline">\(Y\sim F(10, 4)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Plot the quantile function of the given distribution using the function <tt>curve()</tt>.</li>
</ul>
<iframe src="DCL/ex2_12.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><tt>curve()</tt> expects the function with their respective parameters (here: degrees of freedom <tt>df1</tt> and <tt>df2</tt>) as an argument.</li>
</ul>
</div>
<div class="DCexercise">
<h4 id="f-distribution-ii" class="unnumbered">13. F Distribution II</h4>
<p>Let <span class="math inline">\(Y\sim F(4,5)\)</span>.</p>
<p><strong>Instructions:</strong></p>
<ul>
<li>Compute <span class="math inline">\(P(1&lt;Y&lt;10)\)</span> by integration of the PDF.</li>
</ul>
<iframe src="DCL/ex2_13.html" frameborder="0" scrolling="no" style="width:100%;height:340px">
</iframe>
<p><strong>Hints:</strong></p>
<ul>
<li><p>Besides providing the function to be integrated, you have to specify lower and upper bounds of integration.</p></li>
<li><p>The additional parameters of the distribution (here <tt>df1</tt> and <tt>df2</tt>) also have to be passed <em>inside</em> the call of <tt>integrate()</tt>.</p></li>
<li><p>The value of the integral can be obtained via <tt>$value</tt>.</p></li>
</ul>
</div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p><em>Hint:</em> <tt>T</tt> and <tt>F</tt> are alternatives for <tt>TRUE</tt> and <tt>FALSE</tt>.<a href="pt.html#fnref3">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="arosur.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
