<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Econometrics with R</title>
  <meta name="description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Econometrics with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Econometrics with R" />
  
  <meta name="twitter:description" content="Beginners with little background in statistics and econometrics often have a hard time understanding the benefits of having programming skills for learning and applying Econometrics. ‘Introduction to Econometrics with R’ is an interactive companion to the well-received textbook ‘Introduction to Econometrics’ by James H. Stock and Mark W. Watson (2015). It gives a gentle introduction to the essentials of R programing and guides students in implementing the empirical applications presented throughout the textbook using the newly aquired skills. This is supported by interactive programming exercises generated with DataCamp Light and integration of interactive visualizations of central concepts which are based on the flexible JavaScript library D3.js." />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-10-05">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="asbomr.html">
<link rel="next" href="rwabdv.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.7.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<link href="libs/plotlyjs-1.29.2/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotlyjs-1.29.2/plotly-latest.min.js"></script>
<!-- font families -->

<link href="https://fonts.googleapis.com/css?family=PT+Sans|Pacifico|Source+Sans+Pro" rel="stylesheet">

<!-- function to adjust height of iframes automatically depending on content loaded -->

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/default.js"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://www.oek.wiwi.uni-due.de/en/">Chair of Econometrics at UDE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-very-short-introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="pt.html"><a href="pt.html"><i class="fa fa-check"></i><b>2</b> Probability Theory</a><ul>
<li class="chapter" data-level="2.1" data-path="pt.html"><a href="pt.html#random-variables-and-probability-distributions"><i class="fa fa-check"></i><b>2.1</b> Random Variables and Probability Distributions</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-discrete-random-variables"><i class="fa fa-check"></i>Probability Distributions of Discrete Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#bernoulli-trials"><i class="fa fa-check"></i>Bernoulli Trials</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#expected-value-mean-and-variance"><i class="fa fa-check"></i>Expected Value, Mean and Variance</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#probability-distributions-of-continuous-random-variables"><i class="fa fa-check"></i>Probability Distributions of Continuous Random Variables</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-normal-distribution"><i class="fa fa-check"></i>The Normal Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-chi-squared-distribution"><i class="fa fa-check"></i>The Chi-Squared Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#thetdist"><i class="fa fa-check"></i>The Student t Distribution</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#the-f-distribution"><i class="fa fa-check"></i>The F Distribution</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="pt.html"><a href="pt.html#RSATDOSA"><i class="fa fa-check"></i><b>2.2</b> Random Sampling and the Distribution of Sample Averages</a><ul>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#mean-and-variance-of-the-sample-mean"><i class="fa fa-check"></i>Mean and Variance of the Sample Mean</a></li>
<li class="chapter" data-level="" data-path="pt.html"><a href="pt.html#large-sample-approximations-to-sampling-distributions"><i class="fa fa-check"></i>Large Sample Approximations to Sampling Distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="pt.html"><a href="pt.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="arosur.html"><a href="arosur.html"><i class="fa fa-check"></i><b>3</b> A Review of Statistics using R</a><ul>
<li class="chapter" data-level="3.1" data-path="arosur.html"><a href="arosur.html#estimation-of-the-population-mean"><i class="fa fa-check"></i><b>3.1</b> Estimation of the Population Mean</a></li>
<li class="chapter" data-level="3.2" data-path="arosur.html"><a href="arosur.html#potsm"><i class="fa fa-check"></i><b>3.2</b> Properties of the Sample Mean</a></li>
<li class="chapter" data-level="3.3" data-path="arosur.html"><a href="arosur.html#hypothesis-tests-concerning-the-population-mean"><i class="fa fa-check"></i><b>3.3</b> Hypothesis Tests Concerning the Population Mean</a><ul>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-p-value"><i class="fa fa-check"></i>The p-Value</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-known"><i class="fa fa-check"></i>Calculating the p-Value when the Standard Deviation is Known</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#SVSSDASE"><i class="fa fa-check"></i>Sample Variance, Sample Standard Deviation and Standard Error</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#calculating-the-p-value-when-the-standard-deviation-is-unknown"><i class="fa fa-check"></i>Calculating the p-value When the Standard Deviation is Unknown</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#the-t-statistic"><i class="fa fa-check"></i>The t-statistic</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#hypothesis-testing-with-a-prespecified-significance-level"><i class="fa fa-check"></i>Hypothesis Testing with a Prespecified Significance Level</a></li>
<li class="chapter" data-level="" data-path="arosur.html"><a href="arosur.html#one-sided-alternatives"><i class="fa fa-check"></i>One-sided Alternatives</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="arosur.html"><a href="arosur.html#confidence-intervals-for-the-population-mean"><i class="fa fa-check"></i><b>3.4</b> Confidence Intervals for the Population Mean</a></li>
<li class="chapter" data-level="3.5" data-path="arosur.html"><a href="arosur.html#cmfdp"><i class="fa fa-check"></i><b>3.5</b> Comparing Means from Different Populations</a></li>
<li class="chapter" data-level="3.6" data-path="arosur.html"><a href="arosur.html#aattggoe"><i class="fa fa-check"></i><b>3.6</b> An Application to the Gender Gap of Earnings</a></li>
<li class="chapter" data-level="3.7" data-path="arosur.html"><a href="arosur.html#scatterplots-sample-covariance-and-sample-correlation"><i class="fa fa-check"></i><b>3.7</b> Scatterplots, Sample Covariance and Sample Correlation</a></li>
<li class="chapter" data-level="3.8" data-path="arosur.html"><a href="arosur.html#exercises-1"><i class="fa fa-check"></i><b>3.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lrwor.html"><a href="lrwor.html"><i class="fa fa-check"></i><b>4</b> Linear Regression with One Regressor</a><ul>
<li class="chapter" data-level="4.1" data-path="lrwor.html"><a href="lrwor.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="4.2" data-path="lrwor.html"><a href="lrwor.html#estimating-the-coefficients-of-the-linear-regression-model"><i class="fa fa-check"></i><b>4.2</b> Estimating the Coefficients of the Linear Regression Model</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-ordinary-least-squares-estimator"><i class="fa fa-check"></i>The Ordinary Least Squares Estimator</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lrwor.html"><a href="lrwor.html#measures-of-fit"><i class="fa fa-check"></i><b>4.3</b> Measures of Fit</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-coefficient-of-determination"><i class="fa fa-check"></i>The Coefficient of Determination</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#the-standard-error-of-the-regression"><i class="fa fa-check"></i>The Standard Error of the Regression</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#application-to-the-test-score-data"><i class="fa fa-check"></i>Application to the Test Score Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="lrwor.html"><a href="lrwor.html#tlsa"><i class="fa fa-check"></i><b>4.4</b> The Least Squares Assumptions</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-1-the-error-term-has-conditional-mean-of-zero"><i class="fa fa-check"></i>Assumption 1: The Error Term has Conditional Mean of Zero</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-2-independently-and-identically-distributed-data"><i class="fa fa-check"></i>Assumption 2: Independently and Identically Distributed Data</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#assumption-3-large-outliers-are-unlikely"><i class="fa fa-check"></i>Assumption 3: Large Outliers are Unlikely</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="lrwor.html"><a href="lrwor.html#tsdotoe"><i class="fa fa-check"></i><b>4.5</b> The Sampling Distribution of the OLS Estimator</a><ul>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-1"><i class="fa fa-check"></i>Simulation Study 1</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-2"><i class="fa fa-check"></i>Simulation Study 2</a></li>
<li class="chapter" data-level="" data-path="lrwor.html"><a href="lrwor.html#simulation-study-3"><i class="fa fa-check"></i>Simulation Study 3</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="lrwor.html"><a href="lrwor.html#exercises-2"><i class="fa fa-check"></i><b>4.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="htaciitslrm.html"><a href="htaciitslrm.html"><i class="fa fa-check"></i><b>5</b> Hypothesis Tests and Confidence Intervals in the Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="5.1" data-path="htaciitslrm.html"><a href="htaciitslrm.html#testing-two-sided-hypotheses-concerning-the-slope-coefficient"><i class="fa fa-check"></i><b>5.1</b> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</a></li>
<li class="chapter" data-level="5.2" data-path="htaciitslrm.html"><a href="htaciitslrm.html#cifrc"><i class="fa fa-check"></i><b>5.2</b> Confidence Intervals for Regression Coefficients</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-confidence-intervals"><i class="fa fa-check"></i>Simulation Study: Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="htaciitslrm.html"><a href="htaciitslrm.html#rwxiabv"><i class="fa fa-check"></i><b>5.3</b> Regression when X is a Binary Variable</a></li>
<li class="chapter" data-level="5.4" data-path="htaciitslrm.html"><a href="htaciitslrm.html#hah"><i class="fa fa-check"></i><b>5.4</b> Heteroskedasticity and Homoskedasticity</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#a-real-world-example-for-heteroskedasticity"><i class="fa fa-check"></i>A Real-World Example for Heteroskedasticity</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#should-we-care-about-heteroskedasticity"><i class="fa fa-check"></i>Should We Care About Heteroskedasticity?</a></li>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#computation-of-heteroskedasticity-robust-standard-errors"><i class="fa fa-check"></i>Computation of Heteroskedasticity-Robust Standard Errors</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="htaciitslrm.html"><a href="htaciitslrm.html#the-gauss-markov-theorem"><i class="fa fa-check"></i><b>5.5</b> The Gauss-Markov Theorem</a><ul>
<li class="chapter" data-level="" data-path="htaciitslrm.html"><a href="htaciitslrm.html#simulation-study-blue-estimator"><i class="fa fa-check"></i>Simulation Study: BLUE Estimator</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="htaciitslrm.html"><a href="htaciitslrm.html#using-the-t-statistic-in-regression-when-the-sample-size-is-small"><i class="fa fa-check"></i><b>5.6</b> Using the t-Statistic in Regression When the Sample Size Is Small</a></li>
<li class="chapter" data-level="5.7" data-path="htaciitslrm.html"><a href="htaciitslrm.html#exercises-3"><i class="fa fa-check"></i><b>5.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="rmwmr.html"><a href="rmwmr.html"><i class="fa fa-check"></i><b>6</b> Regression Models with Multiple Regressors</a><ul>
<li class="chapter" data-level="6.1" data-path="rmwmr.html"><a href="rmwmr.html#omitted-variable-bias"><i class="fa fa-check"></i><b>6.1</b> Omitted Variable Bias</a></li>
<li class="chapter" data-level="6.2" data-path="rmwmr.html"><a href="rmwmr.html#tmrm"><i class="fa fa-check"></i><b>6.2</b> The Multiple Regression Model</a></li>
<li class="chapter" data-level="6.3" data-path="rmwmr.html"><a href="rmwmr.html#mofimr"><i class="fa fa-check"></i><b>6.3</b> Measures of Fit in Multiple Regression</a></li>
<li class="chapter" data-level="6.4" data-path="rmwmr.html"><a href="rmwmr.html#ols-assumptions-in-multiple-regression"><i class="fa fa-check"></i><b>6.4</b> OLS Assumptions in Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#multicollinearity"><i class="fa fa-check"></i>Multicollinearity</a></li>
<li class="chapter" data-level="" data-path="rmwmr.html"><a href="rmwmr.html#simulation-study-imperfect-multicollinearity"><i class="fa fa-check"></i>Simulation Study: Imperfect Multicollinearity</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="rmwmr.html"><a href="rmwmr.html#the-distribution-of-the-ols-estimators-in-multiple-regression"><i class="fa fa-check"></i><b>6.5</b> The Distribution of the OLS Estimators in Multiple Regression</a></li>
<li class="chapter" data-level="6.6" data-path="rmwmr.html"><a href="rmwmr.html#exercises-4"><i class="fa fa-check"></i><b>6.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="htaciimr.html"><a href="htaciimr.html"><i class="fa fa-check"></i><b>7</b> Hypothesis Tests and Confidence Intervals in Multiple Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="htaciimr.html"><a href="htaciimr.html#hypothesis-tests-and-confidence-intervals-for-a-single-coefficient"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Tests and Confidence Intervals for a Single Coefficient</a></li>
<li class="chapter" data-level="7.2" data-path="htaciimr.html"><a href="htaciimr.html#an-application-to-test-scores-and-the-student-teacher-ratio"><i class="fa fa-check"></i><b>7.2</b> An Application to Test Scores and the Student-Teacher Ratio</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#another-augmentation-of-the-model"><i class="fa fa-check"></i>Another Augmentation of the Model</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="htaciimr.html"><a href="htaciimr.html#joint-hypothesis-testing-using-the-f-statistic"><i class="fa fa-check"></i><b>7.3</b> Joint Hypothesis Testing Using the F-Statistic</a></li>
<li class="chapter" data-level="7.4" data-path="htaciimr.html"><a href="htaciimr.html#confidence-sets-for-multiple-coefficients"><i class="fa fa-check"></i><b>7.4</b> Confidence Sets for Multiple Coefficients</a></li>
<li class="chapter" data-level="7.5" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-for-multiple-regression"><i class="fa fa-check"></i><b>7.5</b> Model Specification for Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="htaciimr.html"><a href="htaciimr.html#model-specification-in-theory-and-in-practice"><i class="fa fa-check"></i>Model Specification in Theory and in Practice</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="htaciimr.html"><a href="htaciimr.html#analysis-of-the-test-score-data-set"><i class="fa fa-check"></i><b>7.6</b> Analysis of the Test Score Data Set</a></li>
<li class="chapter" data-level="7.7" data-path="htaciimr.html"><a href="htaciimr.html#exercises-5"><i class="fa fa-check"></i><b>7.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nrf.html"><a href="nrf.html"><i class="fa fa-check"></i><b>8</b> Nonlinear Regression Functions</a><ul>
<li class="chapter" data-level="8.1" data-path="nrf.html"><a href="nrf.html#a-general-strategy-for-modelling-nonlinear-regression-functions"><i class="fa fa-check"></i><b>8.1</b> A General Strategy for Modelling Nonlinear Regression Functions</a></li>
<li class="chapter" data-level="8.2" data-path="nrf.html"><a href="nrf.html#nfoasiv"><i class="fa fa-check"></i><b>8.2</b> Nonlinear Functions of a Single Independent Variable</a><ul>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#polynomials"><i class="fa fa-check"></i>Polynomials</a></li>
<li class="chapter" data-level="" data-path="nrf.html"><a href="nrf.html#logarithms"><i class="fa fa-check"></i>Logarithms</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="nrf.html"><a href="nrf.html#interactions-between-independent-variables"><i class="fa fa-check"></i><b>8.3</b> Interactions Between Independent Variables</a></li>
<li class="chapter" data-level="8.4" data-path="nrf.html"><a href="nrf.html#nonlinear-effects-on-test-scores-of-the-student-teacher-ratio"><i class="fa fa-check"></i><b>8.4</b> Nonlinear Effects on Test Scores of the Student-Teacher Ratio</a></li>
<li class="chapter" data-level="8.5" data-path="nrf.html"><a href="nrf.html#exercises-6"><i class="fa fa-check"></i><b>8.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="asbomr.html"><a href="asbomr.html"><i class="fa fa-check"></i><b>9</b> Assessing Studies Based on Multiple Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity"><i class="fa fa-check"></i><b>9.1</b> Internal and External Validity</a></li>
<li class="chapter" data-level="9.2" data-path="asbomr.html"><a href="asbomr.html#ttivomra"><i class="fa fa-check"></i><b>9.2</b> Threats to Internal Validity of Multiple Regression Analysis</a></li>
<li class="chapter" data-level="9.3" data-path="asbomr.html"><a href="asbomr.html#internal-and-external-validity-when-the-regression-is-used-for-forecasting"><i class="fa fa-check"></i><b>9.3</b> Internal and External Validity when the Regression is Used for Forecasting</a></li>
<li class="chapter" data-level="9.4" data-path="asbomr.html"><a href="asbomr.html#etsacs"><i class="fa fa-check"></i><b>9.4</b> Example: Test Scores and Class Size</a></li>
<li class="chapter" data-level="9.5" data-path="asbomr.html"><a href="asbomr.html#exercises-7"><i class="fa fa-check"></i><b>9.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="rwpd.html"><a href="rwpd.html"><i class="fa fa-check"></i><b>10</b> Regression with Panel Data</a><ul>
<li class="chapter" data-level="10.1" data-path="rwpd.html"><a href="rwpd.html#panel-data"><i class="fa fa-check"></i><b>10.1</b> Panel Data</a></li>
<li class="chapter" data-level="10.2" data-path="rwpd.html"><a href="rwpd.html#PDWTTP"><i class="fa fa-check"></i><b>10.2</b> Panel Data with Two Time Periods: “Before and After” Comparisons</a></li>
<li class="chapter" data-level="10.3" data-path="rwpd.html"><a href="rwpd.html#fixed-effects-regression"><i class="fa fa-check"></i><b>10.3</b> Fixed Effects Regression</a><ul>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#estimation-and-inference"><i class="fa fa-check"></i>Estimation and Inference</a></li>
<li class="chapter" data-level="" data-path="rwpd.html"><a href="rwpd.html#application-to-traffic-deaths"><i class="fa fa-check"></i>Application to Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="rwpd.html"><a href="rwpd.html#regression-with-time-fixed-effects"><i class="fa fa-check"></i><b>10.4</b> Regression with Time Fixed Effects</a></li>
<li class="chapter" data-level="10.5" data-path="rwpd.html"><a href="rwpd.html#tferaaseffer"><i class="fa fa-check"></i><b>10.5</b> The Fixed Effects Regression Assumptions and Standard Errors for Fixed Effects Regression</a></li>
<li class="chapter" data-level="10.6" data-path="rwpd.html"><a href="rwpd.html#drunk-driving-laws-and-traffic-deaths"><i class="fa fa-check"></i><b>10.6</b> Drunk Driving Laws and Traffic Deaths</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="rwabdv.html"><a href="rwabdv.html"><i class="fa fa-check"></i><b>11</b> Regression with a Binary Dependent Variable</a><ul>
<li class="chapter" data-level="11.1" data-path="rwabdv.html"><a href="rwabdv.html#binary-dependent-variables-and-the-linear-probability-model"><i class="fa fa-check"></i><b>11.1</b> Binary Dependent Variables and the Linear Probability Model</a></li>
<li class="chapter" data-level="11.2" data-path="rwabdv.html"><a href="rwabdv.html#palr"><i class="fa fa-check"></i><b>11.2</b> Probit and Logit Regression</a><ul>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#probit-regression"><i class="fa fa-check"></i>Probit Regression</a></li>
<li class="chapter" data-level="" data-path="rwabdv.html"><a href="rwabdv.html#logit-regression"><i class="fa fa-check"></i>Logit Regression</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="rwabdv.html"><a href="rwabdv.html#estimation-and-inference-in-the-logit-and-probit-models"><i class="fa fa-check"></i><b>11.3</b> Estimation and Inference in the Logit and Probit Models</a></li>
<li class="chapter" data-level="11.4" data-path="rwabdv.html"><a href="rwabdv.html#application-to-the-boston-hmda-data"><i class="fa fa-check"></i><b>11.4</b> Application to the Boston HMDA Data</a></li>
<li class="chapter" data-level="11.5" data-path="rwabdv.html"><a href="rwabdv.html#exercises-8"><i class="fa fa-check"></i><b>11.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="ivr.html"><a href="ivr.html"><i class="fa fa-check"></i><b>12</b> Instrumental Variables Regression</a><ul>
<li class="chapter" data-level="12.1" data-path="ivr.html"><a href="ivr.html#TIVEWASRAASI"><i class="fa fa-check"></i><b>12.1</b> The IV Estimator with a Single Regressor and a Single Instrument</a></li>
<li class="chapter" data-level="12.2" data-path="ivr.html"><a href="ivr.html#TGIVRM"><i class="fa fa-check"></i><b>12.2</b> The General IV Regression Model</a></li>
<li class="chapter" data-level="12.3" data-path="ivr.html"><a href="ivr.html#civ"><i class="fa fa-check"></i><b>12.3</b> Checking Instrument Validity</a></li>
<li class="chapter" data-level="12.4" data-path="ivr.html"><a href="ivr.html#attdfc"><i class="fa fa-check"></i><b>12.4</b> Application to the Demand for Cigarettes</a></li>
<li class="chapter" data-level="12.5" data-path="ivr.html"><a href="ivr.html#where-do-valid-instruments-come-from"><i class="fa fa-check"></i><b>12.5</b> Where Do Valid Instruments Come From?</a></li>
<li class="chapter" data-level="12.6" data-path="ivr.html"><a href="ivr.html#exercises-9"><i class="fa fa-check"></i><b>12.6</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="eaqe.html"><a href="eaqe.html"><i class="fa fa-check"></i><b>13</b> Experiments and Quasi-Experiments</a><ul>
<li class="chapter" data-level="13.1" data-path="eaqe.html"><a href="eaqe.html#potential-outcomes-causal-effects-and-idealized-experiments"><i class="fa fa-check"></i><b>13.1</b> Potential Outcomes, Causal Effects and Idealized Experiments</a></li>
<li class="chapter" data-level="13.2" data-path="eaqe.html"><a href="eaqe.html#threats-to-validity-of-experiments"><i class="fa fa-check"></i><b>13.2</b> Threats to Validity of Experiments</a></li>
<li class="chapter" data-level="13.3" data-path="eaqe.html"><a href="eaqe.html#experimental-estimates-of-the-effect-of-class-size-reductions"><i class="fa fa-check"></i><b>13.3</b> Experimental Estimates of the Effect of Class Size Reductions</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#experimental-design-and-the-data-set"><i class="fa fa-check"></i>Experimental Design and the Data Set</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#analysis-of-the-star-data"><i class="fa fa-check"></i>Analysis of the STAR Data</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="eaqe.html"><a href="eaqe.html#quasi-experiments"><i class="fa fa-check"></i><b>13.4</b> Quasi Experiments</a><ul>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#the-differences-in-differences-estimator"><i class="fa fa-check"></i>The Differences-in-Differences Estimator</a></li>
<li class="chapter" data-level="" data-path="eaqe.html"><a href="eaqe.html#regression-discontinuity-estimators"><i class="fa fa-check"></i>Regression Discontinuity Estimators</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="ittsraf.html"><a href="ittsraf.html"><i class="fa fa-check"></i><b>14</b> Introduction to Time Series Regression and Forecasting</a><ul>
<li class="chapter" data-level="14.1" data-path="ittsraf.html"><a href="ittsraf.html#using-regression-models-for-forecasting"><i class="fa fa-check"></i><b>14.1</b> Using Regression Models for Forecasting</a></li>
<li class="chapter" data-level="14.2" data-path="ittsraf.html"><a href="ittsraf.html#tsdasc"><i class="fa fa-check"></i><b>14.2</b> Time Series Data and Serial Correlation</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#notation-lags-differences-logarithms-and-growth-rates"><i class="fa fa-check"></i>Notation, Lags, Differences, Logarithms and Growth Rates</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="ittsraf.html"><a href="ittsraf.html#autoregressions"><i class="fa fa-check"></i><b>14.3</b> Autoregressions</a><ul>
<li><a href="ittsraf.html#autoregressive-models-of-order-p">Autoregressive Models of Order <span class="math inline">\(p\)</span></a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="ittsraf.html"><a href="ittsraf.html#cybtmpi"><i class="fa fa-check"></i><b>14.4</b> Can You Beat the Market? (Part I)</a></li>
<li class="chapter" data-level="14.5" data-path="ittsraf.html"><a href="ittsraf.html#apatadlm"><i class="fa fa-check"></i><b>14.5</b> Additional Predictors and The ADL Model</a><ul>
<li class="chapter" data-level="" data-path="ittsraf.html"><a href="ittsraf.html#forecast-uncertainty-and-forecast-intervals"><i class="fa fa-check"></i>Forecast Uncertainty and Forecast Intervals</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="ittsraf.html"><a href="ittsraf.html#llsuic"><i class="fa fa-check"></i><b>14.6</b> Lag Length Selection Using Information Criteria</a></li>
<li class="chapter" data-level="14.7" data-path="ittsraf.html"><a href="ittsraf.html#nit"><i class="fa fa-check"></i><b>14.7</b> Nonstationarity I: Trends</a></li>
<li class="chapter" data-level="14.8" data-path="ittsraf.html"><a href="ittsraf.html#niib"><i class="fa fa-check"></i><b>14.8</b> Nonstationarity II: Breaks</a></li>
<li class="chapter" data-level="14.9" data-path="ittsraf.html"><a href="ittsraf.html#can-you-beat-the-market-part-ii"><i class="fa fa-check"></i><b>14.9</b> Can You Beat the Market? (Part II)</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="eodce.html"><a href="eodce.html"><i class="fa fa-check"></i><b>15</b> Estimation of Dynamic Causal Effects</a><ul>
<li class="chapter" data-level="15.1" data-path="eodce.html"><a href="eodce.html#the-orange-juice-data"><i class="fa fa-check"></i><b>15.1</b> The Orange Juice Data</a></li>
<li class="chapter" data-level="15.2" data-path="eodce.html"><a href="eodce.html#dynamic-causal-effects"><i class="fa fa-check"></i><b>15.2</b> Dynamic Causal Effects</a></li>
<li class="chapter" data-level="15.3" data-path="eodce.html"><a href="eodce.html#dynamic-multipliers-and-cumulative-dynamic-multipliers"><i class="fa fa-check"></i><b>15.3</b> Dynamic Multipliers and Cumulative Dynamic Multipliers</a></li>
<li class="chapter" data-level="15.4" data-path="eodce.html"><a href="eodce.html#hac-standard-errors"><i class="fa fa-check"></i><b>15.4</b> HAC Standard Errors</a></li>
<li class="chapter" data-level="15.5" data-path="eodce.html"><a href="eodce.html#estimation-of-dynamic-causal-effects-with-strictly-exogeneous-regressors"><i class="fa fa-check"></i><b>15.5</b> Estimation of Dynamic Causal Effects with Strictly Exogeneous Regressors</a></li>
<li class="chapter" data-level="15.6" data-path="eodce.html"><a href="eodce.html#orange-juice-prices-and-cold-weather"><i class="fa fa-check"></i><b>15.6</b> Orange Juice Prices and Cold Weather</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="atitsr.html"><a href="atitsr.html"><i class="fa fa-check"></i><b>16</b> Additional Topics in Time Series Regression</a><ul>
<li class="chapter" data-level="16.1" data-path="atitsr.html"><a href="atitsr.html#vector-autoregressions"><i class="fa fa-check"></i><b>16.1</b> Vector Autoregressions</a></li>
<li class="chapter" data-level="16.2" data-path="atitsr.html"><a href="atitsr.html#ooiatdfglsurt"><i class="fa fa-check"></i><b>16.2</b> Orders of Integration and the DF-GLS Unit Root Test</a></li>
<li class="chapter" data-level="16.3" data-path="atitsr.html"><a href="atitsr.html#cointegration"><i class="fa fa-check"></i><b>16.3</b> Cointegration</a></li>
<li class="chapter" data-level="16.4" data-path="atitsr.html"><a href="atitsr.html#volatility-clustering-and-autoregressive-conditional-heteroskedasticity"><i class="fa fa-check"></i><b>16.4</b> Volatility Clustering and Autoregressive Conditional Heteroskedasticity</a><ul>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#arch-and-garch-models"><i class="fa fa-check"></i>ARCH and GARCH Models</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#application-to-stock-price-volatility"><i class="fa fa-check"></i>Application to Stock Price Volatility</a></li>
<li class="chapter" data-level="" data-path="atitsr.html"><a href="atitsr.html#summary-8"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Econometrics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="rwpd" class="section level1">
<h1><span class="header-section-number">10</span> Regression with Panel Data</h1>
<p>Regression using panel data may mitigate omitted variable bias when there is no information on variables that correlate with both the regressors of interest and the independent variable and if these variables are constant in the time dimension or across entities. Provided that panel data is available panel regression methods may improve upon multiple regression models which, as discussed in Chapter <a href="asbomr.html#asbomr">9</a>, produce results that are not internally valid in such a setting.</p>
<p>This chapter covers the following topics:</p>
<ul>
<li>notation for panel data</li>
<li>fixed effects regression using time and/or entity fixed effects</li>
<li>computation of standard errors in fixed effects regression models</li>
</ul>
<p>Following the book, for applications we make use of the data set <tt>Fatalities</tt> from the <tt>AER</tt> package <span class="citation">(Christian Kleiber &amp; Zeileis, <a href="#ref-R-AER">2017</a>)</span> which is a panel data set reporting annual state level observations on U.S. traffic fatalities for the period 1982 through 1988. The applications analyze if there are effects of alcohol taxes and drunk driving laws on road fatalities and, if present, <em>how strong</em> these effects are.</p>
<p>We introduce <tt>plm()</tt>, a convenient <tt>R</tt> function that enables us to estimate linear panel regression models which comes with the package <tt>plm</tt> <span class="citation">(Croissant, Millo, &amp; Tappe, <a href="#ref-R-plm">2017</a>)</span>. Usage of <tt>plm()</tt> is very similar as for the function <tt>lm()</tt> which we have used throughout the previous chapters for estimation of simple and multiple regression models.</p>
<p>The following packages and their dependencies are needed for reproduction of the code chunks presented throughout this chapter on your computer:</p>
<ul>
<li><tt>AER</tt></li>
<li><tt>plm</tt></li>
<li><tt>stargazer</tt></li>
</ul>
<p>Check whether the following code chunk runs without any errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(AER)
<span class="kw">library</span>(plm)
<span class="kw">library</span>(stargazer)</code></pre></div>
<div id="panel-data" class="section level2">
<h2><span class="header-section-number">10.1</span> Panel Data</h2>
<div class="keyconcept">
<h3 class="right">
Key Concept 10.1
</h3>
<h3 class="left">
Notation for Panel Data
</h3>
<p>In contrast to cross-section data where we have observations on <span class="math inline">\(n\)</span> subjects (entities), panel data has observations on <span class="math inline">\(n\)</span> entities at <span class="math inline">\(T\geq2\)</span> time periods. This is denoted</p>
<p><span class="math display">\[(X_{it},Y_{it}), \ i=1,\dots,n \ \ \ \text{and} \ \ \ t=1,\dots,T \]</span> where the index <span class="math inline">\(i\)</span> refers to the entity while <span class="math inline">\(t\)</span> refers to the time period.</p>
</div>
<p>Sometimes panel data is also called longitudinal data as it adds a temporal dimension to cross-sectional data. Let us have a look at the data set <tt>Fatalities</tt> by checking its structure and listing the first few observations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load the package and the dataset</span>
<span class="kw">library</span>(AER)
<span class="kw">data</span>(Fatalities)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># obtain the dimension and inspect the structure</span>
<span class="kw">is.data.frame</span>(Fatalities)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(Fatalities)</code></pre></div>
<pre><code>## [1] 336  34</code></pre>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(Fatalities)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    336 obs. of  34 variables:
##  $ state       : Factor w/ 48 levels &quot;al&quot;,&quot;az&quot;,&quot;ar&quot;,..: 1 1 1 1 1 1 1 2 2 2 ...
##  $ year        : Factor w/ 7 levels &quot;1982&quot;,&quot;1983&quot;,..: 1 2 3 4 5 6 7 1 2 3 ...
##  $ spirits     : num  1.37 1.36 1.32 1.28 1.23 ...
##  $ unemp       : num  14.4 13.7 11.1 8.9 9.8 ...
##  $ income      : num  10544 10733 11109 11333 11662 ...
##  $ emppop      : num  50.7 52.1 54.2 55.3 56.5 ...
##  $ beertax     : num  1.54 1.79 1.71 1.65 1.61 ...
##  $ baptist     : num  30.4 30.3 30.3 30.3 30.3 ...
##  $ mormon      : num  0.328 0.343 0.359 0.376 0.393 ...
##  $ drinkage    : num  19 19 19 19.7 21 ...
##  $ dry         : num  25 23 24 23.6 23.5 ...
##  $ youngdrivers: num  0.212 0.211 0.211 0.211 0.213 ...
##  $ miles       : num  7234 7836 8263 8727 8953 ...
##  $ breath      : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##  $ jail        : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 2 2 2 ...
##  $ service     : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 2 2 2 ...
##  $ fatal       : int  839 930 932 882 1081 1110 1023 724 675 869 ...
##  $ nfatal      : int  146 154 165 146 172 181 139 131 112 149 ...
##  $ sfatal      : int  99 98 94 98 119 114 89 76 60 81 ...
##  $ fatal1517   : int  53 71 49 66 82 94 66 40 40 51 ...
##  $ nfatal1517  : int  9 8 7 9 10 11 8 7 7 8 ...
##  $ fatal1820   : int  99 108 103 100 120 127 105 81 83 118 ...
##  $ nfatal1820  : int  34 26 25 23 23 31 24 16 19 34 ...
##  $ fatal2124   : int  120 124 118 114 119 138 123 96 80 123 ...
##  $ nfatal2124  : int  32 35 34 45 29 30 25 36 17 33 ...
##  $ afatal      : num  309 342 305 277 361 ...
##  $ pop         : num  3942002 3960008 3988992 4021008 4049994 ...
##  $ pop1517     : num  209000 202000 197000 195000 204000 ...
##  $ pop1820     : num  221553 219125 216724 214349 212000 ...
##  $ pop2124     : num  290000 290000 288000 284000 263000 ...
##  $ milestot    : num  28516 31032 32961 35091 36259 ...
##  $ unempus     : num  9.7 9.6 7.5 7.2 7 ...
##  $ emppopus    : num  57.8 57.9 59.5 60.1 60.7 ...
##  $ gsp         : num  -0.0221 0.0466 0.0628 0.0275 0.0321 ...</code></pre>
</div>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># list the first few observations</span>
<span class="kw">head</span>(Fatalities)</code></pre></div>
<pre><code>##   state year spirits unemp   income   emppop  beertax baptist  mormon
## 1    al 1982    1.37  14.4 10544.15 50.69204 1.539379 30.3557 0.32829
## 2    al 1983    1.36  13.7 10732.80 52.14703 1.788991 30.3336 0.34341
## 3    al 1984    1.32  11.1 11108.79 54.16809 1.714286 30.3115 0.35924
## 4    al 1985    1.28   8.9 11332.63 55.27114 1.652542 30.2895 0.37579
## 5    al 1986    1.23   9.8 11661.51 56.51450 1.609907 30.2674 0.39311
## 6    al 1987    1.18   7.8 11944.00 57.50988 1.560000 30.2453 0.41123
##   drinkage     dry youngdrivers    miles breath jail service fatal nfatal
## 1    19.00 25.0063     0.211572 7233.887     no   no      no   839    146
## 2    19.00 22.9942     0.210768 7836.348     no   no      no   930    154
## 3    19.00 24.0426     0.211484 8262.990     no   no      no   932    165
## 4    19.67 23.6339     0.211140 8726.917     no   no      no   882    146
## 5    21.00 23.4647     0.213400 8952.854     no   no      no  1081    172
## 6    21.00 23.7924     0.215527 9166.302     no   no      no  1110    181
##   sfatal fatal1517 nfatal1517 fatal1820 nfatal1820 fatal2124 nfatal2124
## 1     99        53          9        99         34       120         32
## 2     98        71          8       108         26       124         35
## 3     94        49          7       103         25       118         34
## 4     98        66          9       100         23       114         45
## 5    119        82         10       120         23       119         29
## 6    114        94         11       127         31       138         30
##    afatal     pop  pop1517  pop1820  pop2124 milestot unempus emppopus
## 1 309.438 3942002 208999.6 221553.4 290000.1    28516     9.7     57.8
## 2 341.834 3960008 202000.1 219125.5 290000.2    31032     9.6     57.9
## 3 304.872 3988992 197000.0 216724.1 288000.2    32961     7.5     59.5
## 4 276.742 4021008 194999.7 214349.0 284000.3    35091     7.2     60.1
## 5 360.716 4049994 203999.9 212000.0 263000.3    36259     7.0     60.7
## 6 368.421 4082999 204999.8 208998.5 258999.8    37426     6.2     61.5
##           gsp
## 1 -0.02212476
## 2  0.04655825
## 3  0.06279784
## 4  0.02748997
## 5  0.03214295
## 6  0.04897637</code></pre>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># summarize the variables &#39;state&#39; and &#39;year&#39;</span>
<span class="kw">summary</span>(Fatalities[, <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)])</code></pre></div>
<pre><code>##      state       year   
##  al     :  7   1982:48  
##  az     :  7   1983:48  
##  ar     :  7   1984:48  
##  ca     :  7   1985:48  
##  co     :  7   1986:48  
##  ct     :  7   1987:48  
##  (Other):294   1988:48</code></pre>
<p>We find that the data set consists of 336 observations on 34 variables. Notice that the variable <tt>state</tt> is a factor variable with 48 levels (one for each of the 48 contiguous federal states of the U.S.). The variable <tt>year</tt> is also a factor variable that has 7 levels identifying the time period when the observation was made. This gives us <span class="math inline">\(7\times48 = 336\)</span> observations in total. Since all variables are observed for all entities and over all time periods, the panel is <em>balanced</em>. If there were missing data for at least one entity in at least one time period we would call the panel <em>unbalanced</em>.</p>
<div id="example-traffic-deaths-and-alcohol-taxes" class="section level4 unnumbered">
<h4>Example: Traffic Deaths and Alcohol Taxes</h4>
<p>We start by reproducing Figure 10.1 of the book. To this end we estimate simple regressions using data for years 1982 and 1988 that model the relationship between beer tax (adjusted for 1988 dollars) and the traffic fatality rate, measured as the number of fatalities per 10000 inhabitants. Afterwards, we plot the data and add the corresponding estimated regression functions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define the fatality rate</span>
Fatalities<span class="op">$</span>fatal_rate &lt;-<span class="st"> </span>Fatalities<span class="op">$</span>fatal <span class="op">/</span><span class="st"> </span>Fatalities<span class="op">$</span>pop <span class="op">*</span><span class="st"> </span><span class="dv">10000</span>

<span class="co"># subset the data</span>
Fatalities1982 &lt;-<span class="st"> </span><span class="kw">subset</span>(Fatalities, year <span class="op">==</span><span class="st"> &quot;1982&quot;</span>)
Fatalities1988 &lt;-<span class="st"> </span><span class="kw">subset</span>(Fatalities, year <span class="op">==</span><span class="st"> &quot;1988&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate simple regression models using 1982 and 1988 data</span>
fatal1982_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax, <span class="dt">data =</span> Fatalities1982)
fatal1988_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax, <span class="dt">data =</span> Fatalities1988)

<span class="kw">coeftest</span>(fatal1982_mod, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.01038    0.14957 13.4408   &lt;2e-16 ***
## beertax      0.14846    0.13261  1.1196   0.2687    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coeftest</span>(fatal1988_mod, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##             Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept)  1.85907    0.11461 16.2205 &lt; 2.2e-16 ***
## beertax      0.43875    0.12786  3.4314  0.001279 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
The estimated regression functions are
<span class="math display">\[\begin{align*}
  \widehat{FatalityRate} =&amp; \, \underset{(0.15)}{2.01} + \underset{(0.13)}{0.15} \times BeerTax \quad (1982 \text{ data}), \\
  \widehat{FatalityRate} =&amp; \, \underset{(0.11)}{1.86} + \underset{(0.13)}{0.44} \times BeerTax \quad (1988 \text{ data}).
\end{align*}\]</span>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the observations and add the estimated regression line for 1982 data</span>
<span class="kw">plot</span>(<span class="dt">x =</span> Fatalities1982<span class="op">$</span>beertax, 
     <span class="dt">y =</span> Fatalities1982<span class="op">$</span>fatal_rate, 
     <span class="dt">xlab =</span> <span class="st">&quot;Beer tax (in 1988 dollars)&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Fatality rate (fatalities per 10000)&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Traffic Fatality Rates and Beer Taxes in 1982&quot;</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">4.5</span>),
     <span class="dt">pch =</span> <span class="dv">20</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>)

<span class="kw">abline</span>(fatal1982_mod, <span class="dt">lwd =</span> <span class="fl">1.5</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-420-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot observations and add estimated regression line for 1988 data</span>
<span class="kw">plot</span>(<span class="dt">x =</span> Fatalities1988<span class="op">$</span>beertax, 
     <span class="dt">y =</span> Fatalities1988<span class="op">$</span>fatal_rate, 
     <span class="dt">xlab =</span> <span class="st">&quot;Beer tax (in 1988 dollars)&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Fatality rate (fatalities per 10000)&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Traffic Fatality Rates and Beer Taxes in 1988&quot;</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">4.5</span>),
     <span class="dt">pch =</span> <span class="dv">20</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>)

<span class="kw">abline</span>(fatal1988_mod, <span class="dt">lwd =</span> <span class="fl">1.5</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-420-2.png" width="672" /></p>
</div>
<p>In both plots, each point represents observations of beer tax and fatality rate for a given state in the respective year. The regression results indicate a positive relationship between the beer tax and the fatality rate for both years. The estimated coefficient on beer tax for the 1988 data is almost three times as large as for the 1988 data set. This is contrary to our expectations: alcohol taxes are supposed to <em>lower</em> the rate of traffic fatalities. As we known from Chapter <a href="rmwmr.html#rmwmr">6</a>, this is possibly due to omitted variable bias, since both models do not include any covariates, e.g., economic conditions. This could be corrected for using a multiple regression approach. However, this cannot account for omitted <em>unobservable</em> factors that differ from state to state but can be assumed to be constant over the observation span, e.g., the populations’ attitude towards drunk driving. As shown in the next section, panel data allow us to hold such factors constant.</p>
</div>
</div>
<div id="PDWTTP" class="section level2">
<h2><span class="header-section-number">10.2</span> Panel Data with Two Time Periods: “Before and After” Comparisons</h2>
Suppose there are only <span class="math inline">\(T=2\)</span> time periods <span class="math inline">\(t=1982,1988\)</span>. This allows us to analyze differences in changes of the the fatality rate from year 1982 to 1988. We start by considering the population regression model <span class="math display">\[FatalityRate_{it} = \beta_0 + \beta_1 BeerTax_{it} + \beta_2 Z_{i} + u_{it}\]</span> where the <span class="math inline">\(Z_i\)</span> are state specific characteristics that differ between states but are <em>constant over time</em>. For <span class="math inline">\(t=1982\)</span> and <span class="math inline">\(t=1988\)</span> we have
<span class="math display">\[\begin{align*}
  FatalityRate_{i1982} =&amp;\, \beta_0 + \beta_1 BeerTax_{i1982} + \beta_2 Z_i + u_{i1982}, \\
  FatalityRate_{i1988} =&amp;\, \beta_0 + \beta_1 BeerTax_{i1988} + \beta_2 Z_i + u_{i1988}.
\end{align*}\]</span>
<p>We can eliminate the <span class="math inline">\(Z_i\)</span> by regressing the difference in the fatality rate between 1988 and 1982 on the difference in beer tax between those years: <span class="math display">\[FatalityRate_{i1988} - FatalityRate_{i1982} = \beta_1 (BeerTax_{i1988} - BeerTax_{i1982}) + u_{i1988} - u_{i1982}\]</span> This regression model yields an estimate for <span class="math inline">\(\beta_1\)</span> robust a possible bias due to omission of the <span class="math inline">\(Z_i\)</span>, since these influences are eliminated from the model. Next we use use <tt>R</tt> to estimate a regression based on the differenced data and plot the estimated regression function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute the differences </span>
diff_fatal_rate &lt;-<span class="st"> </span>Fatalities1988<span class="op">$</span>fatal_rate <span class="op">-</span><span class="st"> </span>Fatalities1982<span class="op">$</span>fatal_rate
diff_beertax &lt;-<span class="st"> </span>Fatalities1988<span class="op">$</span>beertax <span class="op">-</span><span class="st"> </span>Fatalities1982<span class="op">$</span>beertax

<span class="co"># estimate a regression using differenced data</span>
fatal_diff_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(diff_fatal_rate <span class="op">~</span><span class="st"> </span>diff_beertax)

<span class="kw">coeftest</span>(fatal_diff_mod, <span class="dt">vcov =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##               Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)  -0.072037   0.065355 -1.1022 0.276091   
## diff_beertax -1.040973   0.355006 -2.9323 0.005229 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Including the intercept allows for a change in the mean fatality rate in the time between 1982 and 1988 in the absence of a change in the beer tax.</p>
<p>We obtain the OLS estimated regression function <span class="math display">\[\widehat{FatalityRate_{i1988} - FatalityRate_{i1982}} = -\underset{(0.065)}{0.072} -\underset{(0.36)}{1.04} \times (BeerTax_{i1988}-BeerTax_{i1982}).\]</span></p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># plot the differenced data</span>
<span class="kw">plot</span>(<span class="dt">x =</span> diff_beertax, 
     <span class="dt">y =</span> diff_fatal_rate, 
     <span class="dt">xlab =</span> <span class="st">&quot;Change in beer tax (in 1988 dollars)&quot;</span>,
     <span class="dt">ylab =</span> <span class="st">&quot;Change in fatality rate (fatalities per 10000)&quot;</span>,
     <span class="dt">main =</span> <span class="st">&quot;Changes in Traffic Fatality Rates and Beer Taxes in 1982-1988&quot;</span>,
     <span class="dt">xlim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">0.6</span>, <span class="fl">0.6</span>),
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="op">-</span><span class="fl">1.5</span>, <span class="dv">1</span>),
     <span class="dt">pch =</span> <span class="dv">20</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>)

<span class="co"># add the regression line to plot</span>
<span class="kw">abline</span>(fatal_diff_mod, <span class="dt">lwd =</span> <span class="fl">1.5</span>)</code></pre></div>
<p><img src="ITER_files/figure-html/unnamed-chunk-422-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The estimated coefficient on beer tax is now negative and significantly different from zero at <span class="math inline">\(5\%\)</span>. Its interpretation is that raising the beer tax by <span class="math inline">\(\$1\)</span> causes traffic fatalities to decrease by <span class="math inline">\(1.04\)</span> per <span class="math inline">\(10000\)</span> people. This is rather large as the average fatality rate is approximately <span class="math inline">\(2\)</span> persons per <span class="math inline">\(10000\)</span> people.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># compute mean fatality rate over all states for all time periods</span>
<span class="kw">mean</span>(Fatalities<span class="op">$</span>fatal_rate)</code></pre></div>
<pre><code>## [1] 2.040444</code></pre>
<p>Once more this outcome is likely to be a consequence of omitting factors in the single-year regression that influence the fatality rate and are correlated with the beer tax <em>and</em> change over time. The message is that we need to be more careful and control for such factors before drawing conclusions about the effect of a raise in beer taxes.</p>
<p>The approach presented in this section discards information for years <span class="math inline">\(1983\)</span> to <span class="math inline">\(1987\)</span>. A method that allows to use data for more than <span class="math inline">\(T=2\)</span> time periods and enables us to add control variables is the fixed effects regression approach.</p>
</div>
<div id="fixed-effects-regression" class="section level2">
<h2><span class="header-section-number">10.3</span> Fixed Effects Regression</h2>
<p>Consider the panel regression model</p>
<span class="math display">\[Y_{it} = \beta_0 + \beta_1 X_{it} + \beta_2 Z_i +  u_{it}\]</span> where the <span class="math inline">\(Z_i\)</span> are unobserved time-invariant heterogeneities across the entities <span class="math inline">\(i=1,\dots,n\)</span>. We aim to estimate <span class="math inline">\(\beta_1\)</span>, the effect on <span class="math inline">\(Y_i\)</span> of a change in <span class="math inline">\(X_i\)</span> holding constant <span class="math inline">\(Z_i\)</span>. Letting <span class="math inline">\(\alpha_i = \beta_0 + \beta_2 Z_i\)</span> we obtain the model
<span class="math display" id="eq:femodel">\[\begin{align}
Y_{it} = \alpha_i + \beta_1 X_{it} + u_{it} \tag{10.1}.
\end{align}\]</span>
Having individual specific intercepts <span class="math inline">\(\alpha_i\)</span>, <span class="math inline">\(i=1,\dots,n\)</span>, where each of these can be understood as the fixed effect of entity <span class="math inline">\(i\)</span>, this model is called the <em>fixed effects model</em>. The variation in the <span class="math inline">\(\alpha_i\)</span>, <span class="math inline">\(i=1,\dots,n\)</span> comes from the <span class="math inline">\(Z_i\)</span>. <a href="rwpd.html#eq:femodel">(10.1)</a> can be rewritten as a regression model containing <span class="math inline">\(n-1\)</span> dummy regressors and a constant:
<span class="math display" id="eq:drmodel">\[\begin{align}
Y_{it} = \beta_0 + \beta_1 X_{it} + \gamma_2 D2_i + \gamma_3 D3_i + \cdots + \gamma_n Dn_i + u_{it} \tag{10.2}.
\end{align}\]</span>
<p>Model <a href="rwpd.html#eq:drmodel">(10.2)</a> has <span class="math inline">\(n\)</span> different intercepts — one for every entity. <a href="rwpd.html#eq:femodel">(10.1)</a> and <a href="rwpd.html#eq:drmodel">(10.2)</a> are equivalent representations of the fixed effects model.</p>
<p>The fixed effects model can be generalized to contain more than just one determinant of <span class="math inline">\(Y\)</span> that is correlated with <span class="math inline">\(X\)</span> and changes over time. Key Concept 10.2 presents the generalized fixed effects regression model.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 10.2
</h3>
<h3 class="left">
The Fixed Effects Regression Model
</h3>
<p>The fixed effects regression model is</p>
<span class="math display" id="eq:gfemodel">\[\begin{align}
Y_{it} = \beta_1 X_{1,it} + \cdots + \beta_k X_{k,it} + \alpha_i + u_{it} \tag{10.3}
\end{align}\]</span>
<p>with <span class="math inline">\(i=1,\dots,n\)</span> and <span class="math inline">\(t=1,\dots,T\)</span>. The <span class="math inline">\(\alpha_i\)</span> are entity-specific intercepts that capture heterogeneities across entities. An equivalent representation of this model is given by</p>
<span class="math display" id="eq:gdrmodel">\[\begin{align}
Y_{it} = \beta_0 + \beta_1 X_{1,it} + \cdots + \beta_k X_{k,it} + \gamma_2 D2_i + \gamma_3 D3_i + \cdots + \gamma_n Dn_i  + u_{it} \tag{10.4}
\end{align}\]</span>
<p>where the <span class="math inline">\(D2_i,D3_i,\dots,Dn_i\)</span> are dummy variables.</p>
</div>
<div id="estimation-and-inference" class="section level3 unnumbered">
<h3>Estimation and Inference</h3>
<p>Software packages use a so-called “entity-demeaned” OLS algorithm which is computationally more efficient than estimating regression models with <span class="math inline">\(k+n\)</span> regressors as needed for models <a href="rwpd.html#eq:gfemodel">(10.3)</a> and <a href="rwpd.html#eq:gdrmodel">(10.4)</a>.</p>
Taking averages on both sides of <a href="rwpd.html#eq:femodel">(10.1)</a> we obtain
<span class="math display">\[\begin{align*}
\frac{1}{n} \sum_{i=1}^n Y_{it} =&amp; \, \beta_1 \frac{1}{n} \sum_{i=1}^n X_{it} + \frac{1}{n} \sum_{i=1}^n a_i + \frac{1}{n} \sum_{i=1}^n u_{it} \\
\overline{Y} =&amp; \, \beta_1 \overline{X}_i + \alpha_i + \overline{u}_i. 
\end{align*}\]</span>
Subtraction from <a href="rwpd.html#eq:femodel">(10.1)</a> yields
<span class="math display" id="eq:edols">\[\begin{align}
\begin{split}
Y_{it} - \overline{Y}_i =&amp; \, \beta_1(X_{it}-\overline{X}_i) + (u_{it} - \overline{u}_i) \\
\overset{\sim}{Y}_{it} =&amp; \, \beta_1 \overset{\sim}{X}_{it} + \overset{\sim}{u}_{it}. 
\end{split} \tag{10.5}
\end{align}\]</span>
<p>In this model, the OLS estimate of the parameter of interest <span class="math inline">\(\beta_1\)</span> is equal to the estimate obtained using <a href="rwpd.html#eq:drmodel">(10.2)</a> — without the need to estimate <span class="math inline">\(n-1\)</span> dummies and an intercept.</p>
<p>We conclude that there are two ways of estimating <span class="math inline">\(\beta_1\)</span> in the fixed effects regression:</p>
<ol style="list-style-type: decimal">
<li><p>OLS of the dummy regression model as shown in <a href="rwpd.html#eq:drmodel">(10.2)</a></p></li>
<li><p>OLS using the entity demeaned data as in <a href="rwpd.html#eq:edols">(10.5)</a></p></li>
</ol>
<p>Provided the fixed effects regression assumptions stated in Key Concept 10.3 hold, the sampling distribution of the OLS estimator in the fixed effects regression model is normal in large samples. The variance of the estimates can be estimated and we can compute standard errors, <span class="math inline">\(t\)</span>-statistics and confidence intervals for coefficients. In the next section, we see how to estimate a fixed effects model using <tt>R</tt> and how to obtain a model summary that reports heteroskedasticity-robust standard errors. We leave aside complicated formulas of the estimators. See Chapter 10.5 and Appendix 10.2 of the book for a discussion of theoretical aspects.</p>
</div>
<div id="application-to-traffic-deaths" class="section level3 unnumbered">
<h3>Application to Traffic Deaths</h3>
Following Key Concept 10.2, the simple fixed effects model for estimation of the relation between traffic fatality rates and the beer taxes is
<span class="math display" id="eq:fatsemod">\[\begin{align}
FatalityRate_{it} = \beta_1 BeerTax_{it} + StateFixedEffects + u_{it}, \tag{10.6}
\end{align}\]</span>
<p>a regression of the traffic fatality rate on beer tax and 48 binary regressors — one for each federal state.</p>
<p>We can simply use the function <tt>lm()</tt> to obtain an estimate of <span class="math inline">\(\beta_1\)</span>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fatal_fe_lm_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> Fatalities)
fatal_fe_lm_mod</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fatal_rate ~ beertax + state - 1, data = Fatalities)
## 
## Coefficients:
## beertax  stateal  stateaz  statear  stateca  stateco  statect  statede  
## -0.6559   3.4776   2.9099   2.8227   1.9682   1.9933   1.6154   2.1700  
## statefl  statega  stateid  stateil  statein  stateia  stateks  stateky  
##  3.2095   4.0022   2.8086   1.5160   2.0161   1.9337   2.2544   2.2601  
## statela  stateme  statemd  statema  statemi  statemn  statems  statemo  
##  2.6305   2.3697   1.7712   1.3679   1.9931   1.5804   3.4486   2.1814  
## statemt  statene  statenv  statenh  statenj  statenm  stateny  statenc  
##  3.1172   1.9555   2.8769   2.2232   1.3719   3.9040   1.2910   3.1872  
## statend  stateoh  stateok  stateor  statepa  stateri  statesc  statesd  
##  1.8542   1.8032   2.9326   2.3096   1.7102   1.2126   4.0348   2.4739  
## statetn  statetx  stateut  statevt  stateva  statewa  statewv  statewi  
##  2.6020   2.5602   2.3137   2.5116   2.1874   1.8181   2.5809   1.7184  
## statewy  
##  3.2491</code></pre>
<p>As discussed in the previous section, it is also possible to estimate <span class="math inline">\(\beta_1\)</span> by applying OLS to the demeaned data, that is, to run the regression</p>
<p><span class="math display">\[\overset{\sim}{FatalityRate} = \beta_1 \overset{\sim}{BeerTax}_{it} + u_{it}. \]</span></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># obtain demeaned data</span>
Fatalities_demeaned &lt;-<span class="st"> </span><span class="kw">with</span>(Fatalities,
            <span class="kw">data.frame</span>(<span class="dt">fatal_rate =</span> fatal_rate <span class="op">-</span><span class="st"> </span><span class="kw">ave</span>(fatal_rate, state),
            <span class="dt">beertaxs =</span> beertax <span class="op">-</span><span class="st"> </span><span class="kw">ave</span>(beertax, state)))

<span class="co"># estimate the regression</span>
<span class="kw">summary</span>(<span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> Fatalities_demeaned))</code></pre></div>
<p>The function <tt>ave</tt> is convenient for computing group averages. We use it to obtain state specific averages of the fatality rate and the beer tax.</p>
<p>Alternatively one may use <tt>plm()</tt> from the package with the same name.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># install and load the &#39;plm&#39; package</span>
## install.packages(&quot;plm&quot;)
<span class="kw">library</span>(plm)</code></pre></div>
<p>As for <tt>lm()</tt> we have to specify the regression formula and the data to be used in our call of <tt>plm()</tt>. Additionally, it is required to pass a vector of names of entity and time ID variables to the argument <tt>index</tt>. For <tt>Fatalities</tt>, the ID variable for entities is named <tt>state</tt> and the time id variable is <tt>year</tt>. Since the fixed effects estimator is also called the <em>within estimator</em>, we set <tt>model = “within”</tt>. Finally, the function <tt>coeftest()</tt> allows to obtain inference based on robust standard errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate the fixed effects regression with plm()</span>
fatal_fe_mod &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax, 
                    <span class="dt">data =</span> Fatalities,
                    <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>), 
                    <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>)

<span class="co"># print summary using robust standard errors</span>
<span class="kw">coeftest</span>(fatal_fe_mod, <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##         Estimate Std. Error t value Pr(&gt;|t|)  
## beertax -0.65587    0.28880  -2.271  0.02388 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The estimated coefficient is again <span class="math inline">\(-0.6559\)</span>. Note that <tt>plm()</tt> uses the entity-demeaned OLS algorithm and thus does not report dummy coefficients. The estimated regression function is</p>
<span class="math display" id="eq:efemod">\[\begin{align}
\widehat{FatalityRate} = -\underset{(0.29)}{0.66} \times BeerTax + StateFixedEffects. \tag{10.7}
\end{align}\]</span>
<p>The coefficient on <span class="math inline">\(BeerTax\)</span> is negative and significant. The interpretation is that the estimated reduction in traffic fatalities due to an increase in the real beer tax by <span class="math inline">\(\$1\)</span> is <span class="math inline">\(0.66\)</span> per <span class="math inline">\(10000\)</span> people, which is still pretty high. Although including state fixed effects eliminates the risk of a bias due to omitted factors that vary across states but not over time, we suspect that there are other omitted variables that vary over time and thus cause a bias.</p>
</div>
</div>
<div id="regression-with-time-fixed-effects" class="section level2">
<h2><span class="header-section-number">10.4</span> Regression with Time Fixed Effects</h2>
<p>Controlling for variables that are constant across entities but vary over time can be done by including time fixed effects. If there are <em>only</em> time fixed effects, the fixed effects regression model becomes <span class="math display">\[Y_{it} = \beta_0 + \beta_1 X_{it} + \delta_2 B2_t + \cdots + \delta_T BT_t + u_{it},\]</span> where only <span class="math inline">\(T-1\)</span> dummies are included (<span class="math inline">\(B1\)</span> is omitted) since the model includes an intercept. This model eliminates omitted variable bias caused by excluding unobserved variables that evolve over time but are constant across entities.</p>
<p>In some applications it is meaningful to include both entity and time fixed effects. The <em>entity and time fixed effects model</em> is <span class="math display">\[Y_{it} = \beta_0 + \beta_1 X_{it} + \gamma_2 D2_i + \cdots + \gamma_n DT_i + \delta_2 B2_t + \cdots + \delta_T BT_t + u_{it} .\]</span> The combined model allows to eliminate bias from unobservables that change over time but are constant over entities and it controls for factors that differ across entities but are constant over time. Such models can be estimated using the OLS algorithm that is implemented in <tt>R</tt>.</p>
<p>The following code chunk shows how to estimate the combined entity and time fixed effects model of the relation between fatalities and beer tax, <span class="math display">\[FatalityRate_{it} = \beta_1 BeerTax_{it} + StateEffects + TimeFixedEffects + u_{it}\]</span> using both <tt>lm()</tt> and <tt>plm()</tt>. It is straightforward to estimate this regression with <tt>lm()</tt> since it is just an extension of <a href="rwpd.html#eq:fatsemod">(10.6)</a> so we only have to adjust the <tt>formula</tt> argument by adding the additional regressor <tt>year</tt> for time fixed effects. In our call of <tt>plm()</tt> we set another argument <tt>effect = “twoways”</tt> for inclusion of entity <em>and</em> time dummies.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate a combined time and entity fixed effects regression model</span>

<span class="co"># via lm()</span>
fatal_tefe_lm_mod &lt;-<span class="st"> </span><span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>year <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> Fatalities)
fatal_tefe_lm_mod</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = fatal_rate ~ beertax + state + year - 1, data = Fatalities)
## 
## Coefficients:
##  beertax   stateal   stateaz   statear   stateca   stateco   statect  
## -0.63998   3.51137   2.96451   2.87284   2.02618   2.04984   1.67125  
##  statede   statefl   statega   stateid   stateil   statein   stateia  
##  2.22711   3.25132   4.02300   2.86242   1.57287   2.07123   1.98709  
##  stateks   stateky   statela   stateme   statemd   statema   statemi  
##  2.30707   2.31659   2.67772   2.41713   1.82731   1.42335   2.04488  
##  statemn   statems   statemo   statemt   statene   statenv   statenh  
##  1.63488   3.49146   2.23598   3.17160   2.00846   2.93322   2.27245  
##  statenj   statenm   stateny   statenc   statend   stateoh   stateok  
##  1.43016   3.95748   1.34849   3.22630   1.90762   1.85664   2.97776  
##  stateor   statepa   stateri   statesc   statesd   statetn   statetx  
##  2.36597   1.76563   1.26964   4.06496   2.52317   2.65670   2.61282  
##  stateut   statevt   stateva   statewa   statewv   statewi   statewy  
##  2.36165   2.56100   2.23618   1.87424   2.63364   1.77545   3.30791  
## year1983  year1984  year1985  year1986  year1987  year1988  
## -0.07990  -0.07242  -0.12398  -0.03786  -0.05090  -0.05180</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># via plm()</span>
fatal_tefe_mod &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax, 
                      <span class="dt">data =</span> Fatalities,
                      <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>), 
                      <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>, 
                      <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>)

<span class="kw">coeftest</span>(fatal_tefe_mod, <span class="dt">vcov =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##         Estimate Std. Error t value Pr(&gt;|t|)  
## beertax -0.63998    0.35015 -1.8277  0.06865 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Before discussing the outcomes we convince ourselves that <tt>state</tt> and <tt>year</tt> are of the class <tt>factor</tt> .</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check the class of &#39;state&#39; and &#39;year&#39;</span>
<span class="kw">class</span>(Fatalities<span class="op">$</span>state)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(Fatalities<span class="op">$</span>year)</code></pre></div>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>The <tt>lm()</tt> functions converts factors into dummies automatically. Since we exclude the intercept by adding <tt>-1</tt> to the right-hand side of the regression formula, <tt>lm()</tt> estimates coefficients for <span class="math inline">\(n + (T-1) = 48 + 6 = 54\)</span> binary variables (6 year dummies and 48 state dummies). Again, <tt>plm()</tt> only reports the estimated coefficient on <span class="math inline">\(BeerTax\)</span>.</p>
The estimated regression function is
<span class="math display" id="eq:cbnfemod">\[\begin{align}
\widehat{FatalityRate} =  -\underset{(0.35)}{0.64} \times BeerTax + StateEffects + TimeFixedEffects. \tag{10.8}
\end{align}\]</span>
<p>The result <span class="math inline">\(-0.66\)</span> is close to the estimated coefficient for the regression model including only entity fixed effects. Unsurprisingly, the coefficient is less precisely estimated but significantly different from zero at <span class="math inline">\(10\%\)</span>.</p>
<p>In view of <a href="rwpd.html#eq:efemod">(10.7)</a> and <a href="rwpd.html#eq:cbnfemod">(10.8)</a> we conclude that the estimated relationship between traffic fatalities and the real beer tax is not affected by omitted variable bias due to factors that are constant over time.</p>
</div>
<div id="tferaaseffer" class="section level2">
<h2><span class="header-section-number">10.5</span> The Fixed Effects Regression Assumptions and Standard Errors for Fixed Effects Regression</h2>
<p>This section focuses on the entity fixed effects model and presents model assumptions that need to hold in order for OLS to produce unbiased estimates that are normally distributed in large samples. These assumptions are an extension of the assumptions made for the multiple regression model (see Key Concept 6.4) and are given in Key Concept 10.3. We also briefly discuss standard errors in fixed effects models which differ from standard errors in multiple regression as the regression error can exhibit serial correlation in panel models.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 10.3
</h3>
<h3 class="left">
The Fixed Effects Regression Assumptions
</h3>
<p>In the fixed effects model <span class="math display">\[ Y_{it} = \beta_1 X_{it} + \alpha_i + u_{it} \ \ , \ \ i=1,\dots,n, \ t=1,\dots,T, \]</span> we assume the following:</p>
<ol style="list-style-type: decimal">
<li><p>The error term <span class="math inline">\(u_{it}\)</span> has conditional mean zero, that is, <span class="math inline">\(E(u_{it}|X_{i1}, X_{i2},\dots, X_{iT})\)</span>.</p></li>
<li><p><span class="math inline">\((X_{i1}, X_{i2}, \dots, X_{i3}, u_{i1}, \dots, u_{iT})\)</span>, <span class="math inline">\(i=1,\dots,n\)</span> are i.i.d. draws from their joint distribution.</p></li>
<li><p>Large outliers are unlikely, i.e., <span class="math inline">\((X_{it}, u_{it})\)</span> have nonzero finite fourth moments.</p></li>
<li><p>There is no perfect multicollinearity.</p></li>
</ol>
<p>When there are multiple regressors, <span class="math inline">\(X_{it}\)</span> is replaced by <span class="math inline">\(X_{1,it}, X_{2,it}, \dots, X_{k,it}\)</span>.</p>
</div>
<p>The first assumption is that the error is uncorrelated with <em>all</em> observations of the variable <span class="math inline">\(X\)</span> for the entity <span class="math inline">\(i\)</span> over time. If this assumption is violated, we face omitted variables bias. The second assumption ensures that variables are i.i.d. <em>across</em> entities <span class="math inline">\(i=1,\dots,n\)</span>. This does not require the observations to be uncorrelated <em>within</em> an entity. The <span class="math inline">\(X_{it}\)</span> are allowed to be <em>autocorrelated</em> within entities. This is a common property of time series data. The same is allowed for errors <span class="math inline">\(u_{it}\)</span>. Consult Chapter <a href="rwpd.html#tferaaseffer">10.5</a> of the book for a detailed explanation for why autocorrelation is plausible in panel applications. The second assumption is justified if the entities are selected by simple random sampling. The third and fourth assumptions are analogous to the multiple regression assumptions made in Key Concept 6.4.</p>
<div id="standard-errors-for-fixed-effects-regression" class="section level4 unnumbered">
<h4>Standard Errors for Fixed Effects Regression</h4>
<p>Similar as for heteroskedasticity, autocorrelation invalidates the usual standard error formulas as well as heteroskedasticity-robust standard errors since these are derived under the assumption that there is no autocorrelation. When there is both heteroskedasticity <em>and</em> autocorrelation so-called <em>heteroskedasticity and autocorrelation-consistent (HAC) standard errors</em> need to be used. <em>Clustered standard errors</em> belong to these type of standard errors. They allow for heteroskedasticity and autocorrelated errors within an entity but <em>not</em> correlation across entities.</p>
<p>As shown in the examples throughout this chapter, it is fairly easy to specify usage of clustered standard errors in regression summaries produced by function like <tt>coeftest()</tt> in conjunction with <tt>vcovHC()</tt> from the package <tt>sandwich</tt>. Conveniently, <tt>vcovHC()</tt> recognizes panel model objects (objects of class <tt>plm</tt>) and computes clustered standard errors by default.</p>
<p>The regressions conducted in this chapter are a good examples for why usage of clustered standard errors is crucial in empirical applications of fixed effects models. For example, consider the entity and time fixed effects model for fatalities. Since <tt>fatal_tefe_lm_mod</tt> is an object of class <tt>lm</tt>, <tt>coeftest()</tt> does not compute clustered standard errors but uses robust standard errors that are only valid in the absence of autocorrelated errors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check class of the model object</span>
<span class="kw">class</span>(fatal_tefe_lm_mod)</code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># obtain a summary based on heteroskedasticity-robust standard errors </span>
<span class="co"># (no adjustment for heteroskedasticity only)</span>
<span class="kw">coeftest</span>(fatal_tefe_lm_mod, <span class="dt">vcov =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)[<span class="dv">1</span>, ]</code></pre></div>
<pre><code>##   Estimate Std. Error    t value   Pr(&gt;|t|) 
## -0.6399800  0.2547149 -2.5125346  0.0125470</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># check class of the (plm) model object</span>
<span class="kw">class</span>(fatal_tefe_mod)</code></pre></div>
<pre><code>## [1] &quot;plm&quot;        &quot;panelmodel&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># obtain a summary based on clusterd standard errors </span>
<span class="co"># (adjustment for autocorrelation + heteroskedasticity)</span>
<span class="kw">coeftest</span>(fatal_tefe_mod, <span class="dt">vcov =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##         Estimate Std. Error t value Pr(&gt;|t|)  
## beertax -0.63998    0.35015 -1.8277  0.06865 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The outcomes differ rather strongly: imposing no autocorrelation we obtain a standard error of <span class="math inline">\(0.25\)</span> which implies significance of <span class="math inline">\(\hat\beta_1\)</span>, the coefficient on <span class="math inline">\(BeerTax\)</span> at the level of <span class="math inline">\(5\%\)</span>. On the contrary, using the clustered standard error <span class="math inline">\(0.35\)</span> leads to acceptance of the hypothesis <span class="math inline">\(H_0: \beta_1 = 0\)</span> at the same level, see equation <a href="rwpd.html#eq:cbnfemod">(10.8)</a>. Consult Appendix 10.2 of the book for insights on the computation of clustered standard errors.</p>
</div>
</div>
<div id="drunk-driving-laws-and-traffic-deaths" class="section level2">
<h2><span class="header-section-number">10.6</span> Drunk Driving Laws and Traffic Deaths</h2>
<p>There are two major sources of omitted variable bias that are not accounted for by all of the models of the relation between traffic fatalities and beer taxes that we have considered so far: economic conditions and driving laws. Fortunately, <tt>Fatalities</tt> has data on state-specific legal drinking age (<tt>drinkage</tt>), punishment (<tt>jail</tt>, <tt>service</tt>) and various economic indicators like unemployment rate (<tt>unemp</tt>) and per capita income (<tt>income</tt>). We may use these covariates to extend the preceding analysis.</p>
<p>These covariates are defined as follows:</p>
<ul>
<li><tt>unemp</tt>: a numeric variable stating the state specific unemployment rate.</li>
<li><tt>log(income)</tt>: the logarithm of real per capita income (in prices of 1988).</li>
<li><tt>miles</tt>: the state average miles per driver.</li>
<li><tt>drinkage</tt>: the state specify minimum legal drinking age.</li>
<li><tt>drinkagc</tt>: a discretized version of <tt>drinkage</tt> that classifies states into four categories of minimal drinking age; <span class="math inline">\(18\)</span>, <span class="math inline">\(19\)</span>, <span class="math inline">\(20\)</span>, <span class="math inline">\(21\)</span> and older. <tt>R</tt> denotes this as <tt>[18,19)</tt>, <tt>[19,20)</tt>, <tt>[20,21)</tt> and <tt>[21,22]</tt>. These categories are included as dummy regressors where <tt>[21,22]</tt> is chosen as the reference category.</li>
<li><tt>punish</tt>: a dummy variable with levels <tt>yes</tt> and <tt>no</tt> that measures if drunk driving is severely punished by mandatory jail time or mandatory community service (first conviction).</li>
</ul>
<p>At first, we define the variables according to the regression results presented in Table 10.1 of the book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># discretize the minimum legal drinking age</span>
Fatalities<span class="op">$</span>drinkagec &lt;-<span class="st"> </span><span class="kw">cut</span>(Fatalities<span class="op">$</span>drinkage,
                            <span class="dt">breaks =</span> <span class="dv">18</span><span class="op">:</span><span class="dv">22</span>, 
                            <span class="dt">include.lowest =</span> <span class="ot">TRUE</span>, 
                            <span class="dt">right =</span> <span class="ot">FALSE</span>)

<span class="co"># set minimum drinking age [21, 22] to be the baseline level</span>
Fatalities<span class="op">$</span>drinkagec &lt;-<span class="st"> </span><span class="kw">relevel</span>(Fatalities<span class="op">$</span>drinkagec, <span class="st">&quot;[21,22]&quot;</span>)

<span class="co"># mandadory jail or community service?</span>
Fatalities<span class="op">$</span>punish &lt;-<span class="st"> </span><span class="kw">with</span>(Fatalities, <span class="kw">factor</span>(jail <span class="op">==</span><span class="st"> &quot;yes&quot;</span> <span class="op">|</span><span class="st"> </span>service <span class="op">==</span><span class="st"> &quot;yes&quot;</span>, 
                                             <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;no&quot;</span>, <span class="st">&quot;yes&quot;</span>)))

<span class="co"># the set of observations on all variables for 1982 and 1988</span>
Fatalities_1982_<span class="dv">1988</span> &lt;-<span class="st"> </span>Fatalities[<span class="kw">with</span>(Fatalities, year <span class="op">==</span><span class="st"> </span><span class="dv">1982</span> <span class="op">|</span><span class="st"> </span>year <span class="op">==</span><span class="st"> </span><span class="dv">1988</span>), ]</code></pre></div>
<p>Next, we estimate all seven models using <tt>plm()</tt>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># estimate all seven models</span>
fatalities_mod1 &lt;-<span class="st"> </span><span class="kw">lm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax, <span class="dt">data =</span> Fatalities)

fatalities_mod2 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state, <span class="dt">data =</span> Fatalities)

fatalities_mod3 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>year,
                       <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>,<span class="st">&quot;year&quot;</span>),
                       <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>,
                       <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>, 
                       <span class="dt">data =</span> Fatalities)

fatalities_mod4 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>drinkagec 
                       <span class="op">+</span><span class="st"> </span>punish <span class="op">+</span><span class="st"> </span>miles <span class="op">+</span><span class="st"> </span>unemp <span class="op">+</span><span class="st"> </span><span class="kw">log</span>(income), 
                       <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),
                       <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>,
                       <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>,
                       <span class="dt">data =</span> Fatalities)

fatalities_mod5 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>drinkagec 
                       <span class="op">+</span><span class="st"> </span>punish <span class="op">+</span><span class="st"> </span>miles,
                       <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),
                       <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>,
                       <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>,
                       <span class="dt">data =</span> Fatalities)

fatalities_mod6 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>drinkage 
                       <span class="op">+</span><span class="st"> </span>punish <span class="op">+</span><span class="st"> </span>miles <span class="op">+</span><span class="st"> </span>unemp <span class="op">+</span><span class="st"> </span><span class="kw">log</span>(income), 
                       <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),
                       <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>,
                       <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>,
                       <span class="dt">data =</span> Fatalities)

fatalities_mod7 &lt;-<span class="st"> </span><span class="kw">plm</span>(fatal_rate <span class="op">~</span><span class="st"> </span>beertax <span class="op">+</span><span class="st"> </span>state <span class="op">+</span><span class="st"> </span>year <span class="op">+</span><span class="st"> </span>drinkagec 
                       <span class="op">+</span><span class="st"> </span>punish <span class="op">+</span><span class="st"> </span>miles <span class="op">+</span><span class="st"> </span>unemp <span class="op">+</span><span class="st"> </span><span class="kw">log</span>(income), 
                       <span class="dt">index =</span> <span class="kw">c</span>(<span class="st">&quot;state&quot;</span>, <span class="st">&quot;year&quot;</span>),
                       <span class="dt">model =</span> <span class="st">&quot;within&quot;</span>,
                       <span class="dt">effect =</span> <span class="st">&quot;twoways&quot;</span>,
                       <span class="dt">data =</span> Fatalities_1982_<span class="dv">1988</span>)</code></pre></div>
<p>We again use <tt>stargazer()</tt> <span class="citation">(Hlavac, <a href="#ref-R-stargazer">2018</a>)</span> to generate a comprehensive tabular presentation of the results.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(stargazer)

<span class="co"># gather clustered standard errors in a list</span>
rob_se &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod1, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod2, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod3, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod4, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod5, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod6, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))),
               <span class="kw">sqrt</span>(<span class="kw">diag</span>(<span class="kw">vcovHC</span>(fatalities_mod7, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>))))

<span class="co"># generate the table</span>
<span class="kw">stargazer</span>(fatalities_mod1, fatalities_mod2, fatalities_mod3, 
          fatalities_mod4, fatalities_mod5, fatalities_mod6, fatalities_mod7, 
          <span class="dt">digits =</span> <span class="dv">3</span>,
          <span class="dt">header =</span> <span class="ot">FALSE</span>,
          <span class="dt">type =</span> <span class="st">&quot;latex&quot;</span>, 
          <span class="dt">se =</span> rob_se,
          <span class="dt">title =</span> <span class="st">&quot;Linear Panel Regression Models of Traffic Fatalities due to Drunk Driving&quot;</span>,
          <span class="dt">model.numbers =</span> <span class="ot">FALSE</span>,
          <span class="dt">column.labels =</span> <span class="kw">c</span>(<span class="st">&quot;(1)&quot;</span>, <span class="st">&quot;(2)&quot;</span>, <span class="st">&quot;(3)&quot;</span>, <span class="st">&quot;(4)&quot;</span>, <span class="st">&quot;(5)&quot;</span>, <span class="st">&quot;(6)&quot;</span>, <span class="st">&quot;(7)&quot;</span>))</code></pre></div>



<table style="text-align:center"><tr><td colspan="8" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"></td><td colspan="7">Dependent Variable: Fatality Rate</td></tr>
<tr><td></td><td colspan="7" style="border-bottom: 1px solid black"></td></tr>
<tr><td style="text-align:left"></td><td colspan="7">fatal_rate</td></tr>
<tr><td style="text-align:left"></td><td><em>OLS</em></td><td colspan="6"><em>panel</em></td></tr>
<tr><td style="text-align:left"></td><td><em></em></td><td colspan="6"><em>linear</em></td></tr>
<tr><td style="text-align:left"></td><td>(1)</td><td>(2)</td><td>(3)</td><td>(4)</td><td>(5)</td><td>(6)</td><td>(7)</td></tr>
<tr><td colspan="8" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">beertax</td><td>0.365<sup>***</sup></td><td>-0.656<sup>**</sup></td><td>-0.640<sup>*</sup></td><td>-0.445</td><td>-0.690<sup>**</sup></td><td>-0.456</td><td>-0.926<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td>(0.053)</td><td>(0.289)</td><td>(0.350)</td><td>(0.291)</td><td>(0.345)</td><td>(0.301)</td><td>(0.337)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">drinkagec[18,19)</td><td></td><td></td><td></td><td>0.028</td><td>-0.010</td><td></td><td>0.037</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.068)</td><td>(0.081)</td><td></td><td>(0.101)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">drinkagec[19,20)</td><td></td><td></td><td></td><td>-0.018</td><td>-0.076</td><td></td><td>-0.065</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.049)</td><td>(0.066)</td><td></td><td>(0.097)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">drinkagec[20,21)</td><td></td><td></td><td></td><td>0.032</td><td>-0.100<sup>*</sup></td><td></td><td>-0.113</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.050)</td><td>(0.055)</td><td></td><td>(0.123)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">drinkage</td><td></td><td></td><td></td><td></td><td></td><td>-0.002</td><td></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td>(0.021)</td><td></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">punishyes</td><td></td><td></td><td></td><td>0.038</td><td>0.085</td><td>0.039</td><td>0.089</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.101)</td><td>(0.109)</td><td>(0.101)</td><td>(0.161)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">miles</td><td></td><td></td><td></td><td>0.00001</td><td>0.00002<sup>*</sup></td><td>0.00001</td><td>0.0001<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.00001)</td><td>(0.00001)</td><td>(0.00001)</td><td>(0.00005)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">unemp</td><td></td><td></td><td></td><td>-0.063<sup>***</sup></td><td></td><td>-0.063<sup>***</sup></td><td>-0.091<sup>***</sup></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.013)</td><td></td><td>(0.013)</td><td>(0.021)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">log(income)</td><td></td><td></td><td></td><td>1.816<sup>***</sup></td><td></td><td>1.786<sup>***</sup></td><td>0.996</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td>(0.624)</td><td></td><td>(0.631)</td><td>(0.666)</td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">Constant</td><td>1.853<sup>***</sup></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left"></td><td>(0.047)</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left"></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td colspan="8" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left">Observations</td><td>336</td><td>336</td><td>336</td><td>335</td><td>335</td><td>335</td><td>95</td></tr>
<tr><td style="text-align:left">R<sup>2</sup></td><td>0.093</td><td>0.041</td><td>0.036</td><td>0.360</td><td>0.066</td><td>0.357</td><td>0.659</td></tr>
<tr><td style="text-align:left">Adjusted R<sup>2</sup></td><td>0.091</td><td>-0.120</td><td>-0.149</td><td>0.217</td><td>-0.134</td><td>0.219</td><td>0.157</td></tr>
<tr><td style="text-align:left">Residual Std. Error</td><td>0.544 (df = 334)</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td style="text-align:left">F Statistic</td><td>34.394<sup>***</sup> (df = 1; 334)</td><td>12.190<sup>***</sup> (df = 1; 287)</td><td>10.513<sup>***</sup> (df = 1; 281)</td><td>19.194<sup>***</sup> (df = 8; 273)</td><td>3.252<sup>***</sup> (df = 6; 275)</td><td>25.423<sup>***</sup> (df = 6; 275)</td><td>9.194<sup>***</sup> (df = 8; 38)</td></tr>
<tr><td colspan="8" style="border-bottom: 1px solid black"></td></tr><tr><td style="text-align:left"><em>Note:</em></td><td colspan="7" style="text-align:right"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>
</table>
<caption><p style='text-align:center'><span id="tab:lprmotfdtdd">Table 10.1: </span> Linear Panel Regression Models of Traffic Fatalities due to Drunk Driving</p></caption>


<p>While columns (2) and (3) recap the results <a href="rwpd.html#eq:efemod">(10.7)</a> and <a href="rwpd.html#eq:cbnfemod">(10.8)</a>, column (1) presents an estimate of the coefficient of interest in the naive OLS regression of the fatality rate on beer tax without any fixed effects. We obtain a <em>positive</em> estimate for the coefficient on beer tax that is likely to be upward biased. The model fit is rather bad, too (<span class="math inline">\(\bar{R}^2 = 0.091\)</span>). The sign of the estimate changes as we extend the model by both entity and time fixed effects in models (2) and (3). Furthermore <span class="math inline">\(\bar{R}^2\)</span> increases substantially as fixed effects are included in the model equation. Nonetheless, as discussed before, the magnitudes of both estimates may be too large.</p>
<p>The model specifications (4) to (7) include covariates that shall capture the effect of overall state economic conditions as well as the legal framework. Considering (4) as the baseline specification, we observe four interesting results:</p>
<ol style="list-style-type: decimal">
<li><p>Including the covariates does not lead to a major reduction of the estimated effect of the beer tax. The coefficient is not significantly different from zero at the level of <span class="math inline">\(5\%\)</span> as the estimate is rather imprecise.</p></li>
<li><p>The minimum legal drinking age <em>does not</em> have an effect on traffic fatalities: none of the three dummy variables are significantly different from zero at any common level of significance. Moreover, an <span class="math inline">\(F\)</span>-Test of the joint hypothesis that all three coefficients are zero does not reject. The next code chunk shows how to test this hypothesis.</p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if legal drinking age has no explanatory power</span>
<span class="kw">linearHypothesis</span>(fatalities_mod4,
                 <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>,
                 <span class="kw">c</span>(<span class="st">&quot;drinkagec[18,19)=0&quot;</span>, <span class="st">&quot;drinkagec[19,20)=0&quot;</span>, <span class="st">&quot;drinkagec[20,21)&quot;</span>), 
                 <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## drinkagec[18,19) = 0
## drinkagec[19,20) = 0
## drinkagec[20,21) = 0
## 
## Model 1: restricted model
## Model 2: fatal_rate ~ beertax + state + year + drinkagec + punish + miles + 
##     unemp + log(income)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F Pr(&gt;F)
## 1    276                 
## 2    273  3 0.3782 0.7688</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><p>There is no evidence that punishment for first offenders has a deterring effects on drunk driving: the corresponding coefficient is not significant at the <span class="math inline">\(10\%\)</span> level.</p></li>
<li><p>The economic variables significantly explain traffic fatalities. We can check that the employment rate and per capita income are jointly significant at the level of <span class="math inline">\(0.1\%\)</span>.</p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># test if economic indicators have no explanatory power</span>
<span class="kw">linearHypothesis</span>(fatalities_mod4, 
                 <span class="dt">test =</span> <span class="st">&quot;F&quot;</span>,
                 <span class="kw">c</span>(<span class="st">&quot;log(income)&quot;</span>, <span class="st">&quot;unemp&quot;</span>), 
                 <span class="dt">vcov. =</span> vcovHC, <span class="dt">type =</span> <span class="st">&quot;HC1&quot;</span>)</code></pre></div>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## log(income) = 0
## unemp = 0
## 
## Model 1: restricted model
## Model 2: fatal_rate ~ beertax + state + year + drinkagec + punish + miles + 
##     unemp + log(income)
## 
## Note: Coefficient covariance matrix supplied.
## 
##   Res.Df Df      F    Pr(&gt;F)    
## 1    275                        
## 2    273  2 31.577 4.609e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Model (5) omits the economic factors. The result supports the notion that economic indicators should remain in the model as the coefficient on beer tax is sensitive to the inclusion of the latter.</p>
<p>Results for model (6) demonstrate that the legal drinking age has little explanatory power and that the coefficient of interest is not sensitive to changes in the functional form of the relation between drinking age and traffic fatalities.</p>
<p>Specification (7) reveals that reducing the amount of available information (we only use 95 observations for the period 1982 to 1988 here) inflates standard errors but does not lead to drastic changes in coefficient estimates.</p>
<div id="summary-2" class="section level4 unnumbered">
<h4>Summary</h4>
<p>We have not found evidence that severe punishments and increasing the minimum drinking age reduce traffic fatalities due to drunk driving. Nonetheless, there seems to be a negative effect of alcohol taxes on traffic fatalities which, however, is estimated imprecisely and cannot be interpreted as the causal effect of interest as there still may be a bias. The issue is that there may be omitted variables that differ across states <em>and</em> change over time and this bias remains even though we use a panel approach that controls for entity specific and time invariant unobservables.</p>
<p>A powerful method that can be used if common panel regression approaches fail is instrumental variables regression. We will return to this concept in Chapter <a href="ivr.html#ivr">12</a>.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-R-AER">
<p>Kleiber, C., &amp; Zeileis, A. (2017). AER: Applied Econometrics with R (Version 1.2-5). Retrieved from <a href="https://CRAN.R-project.org/package=AER" class="uri">https://CRAN.R-project.org/package=AER</a></p>
</div>
<div id="ref-R-plm">
<p>Croissant, Y., Millo, G., &amp; Tappe, K. (2017). plm: Linear Models for Panel Data (Version 1.6-6). Retrieved from <a href="https://CRAN.R-project.org/package=plm" class="uri">https://CRAN.R-project.org/package=plm</a></p>
</div>
<div id="ref-R-stargazer">
<p>Hlavac, M. (2018). stargazer: Well-Formatted Regression and Summary Statistics Tables (Version 5.2.2). Retrieved from <a href="https://CRAN.R-project.org/package=stargazer" class="uri">https://CRAN.R-project.org/package=stargazer</a></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="asbomr.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="rwabdv.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": true,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
