<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Using R for Introduction to Econometrics</title>
  <meta name="description" content="Using <tt>R</tt> for Introduction to Econometrics">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Using R for Introduction to Econometrics" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="Emwikts1970/URFITE-Bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Using R for Introduction to Econometrics" />
  
  
  

<meta name="author" content="Christoph Hanck, Martin Arnold, Alexander Gerber and Martin Schmelzer">


<meta name="date" content="2018-07-27">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="htaciitslrm.html">
<link rel="next" href="cifrc.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="js/hideOutput.js"></script>
<script type="text/javascript" src="MathJax-2.7.2/MathJax.js?config=default"></script>

 <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["tex2jax.js", "TeX/AMSmath.js"],
        tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
        jax: ["input/TeX","output/CommonHTML"]
      });
      MathJax.Hub.processSectionDelay = 0;
  </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110299877-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110299877-1');
</script>

<!-- open review block -->

<script async defer src="https://hypothes.is/embed.js"></script>

<!-- datacamp-light-latest -->

<script src="https://cdn.datacamp.com/datacamp-light-latest.min.js"></script>


<!-- <script src="js/d3.v3.min.js"></script>
<script src="js/leastsquares.js"></script>
<script src="js/d3functions.js"></script>
<script src="d3.slider.js"></script>
<script src="slrm.js"></script> -->


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
<link rel="stylesheet" href="toc.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">URFITE</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="a-very-short-introduction-to-r-and-rstudio.html"><a href="a-very-short-introduction-to-r-and-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> A Very Short Introduction to <tt>R</tt> and <em>RStudio</em></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="htaciitslrm.html"><a href="htaciitslrm.html"><i class="fa fa-check"></i><b>2</b> Hypothesis Tests and Confidence Intervals in the Simple Linear Regression Model</a><ul>
<li class="chapter" data-level="2.1" data-path="testing-two-sided-hypotheses-concerning-the-slope-coefficient.html"><a href="testing-two-sided-hypotheses-concerning-the-slope-coefficient.html"><i class="fa fa-check"></i><b>2.1</b> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</a></li>
<li class="chapter" data-level="2.2" data-path="cifrc.html"><a href="cifrc.html"><i class="fa fa-check"></i><b>2.2</b> Confidence Intervals for Regression Coefficients</a><ul>
<li class="chapter" data-level="" data-path="cifrc.html"><a href="cifrc.html#simulation-study-confidence-intervals"><i class="fa fa-check"></i>Simulation Study: Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="rwxiabv.html"><a href="rwxiabv.html"><i class="fa fa-check"></i><b>2.3</b> Regression when X is a Binary Variable</a></li>
<li class="chapter" data-level="2.4" data-path="hah.html"><a href="hah.html"><i class="fa fa-check"></i><b>2.4</b> Heteroskedasticity and Homoskedasticity</a><ul>
<li class="chapter" data-level="" data-path="hah.html"><a href="hah.html#a-real-world-example-for-heteroskedasticity"><i class="fa fa-check"></i>A Real-World Example for Heteroskedasticity</a></li>
<li class="chapter" data-level="" data-path="hah.html"><a href="hah.html#should-we-care-about-heteroskedasticity"><i class="fa fa-check"></i>Should We Care About Heteroskedasticity?</a></li>
<li class="chapter" data-level="" data-path="hah.html"><a href="hah.html#computation-of-heteroskedasticity-robust-standard-errors"><i class="fa fa-check"></i>Computation of Heteroskedasticity-Robust Standard Errors</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="the-gauss-markov-theorem.html"><a href="the-gauss-markov-theorem.html"><i class="fa fa-check"></i><b>2.5</b> The Gauss-Markov Theorem</a><ul>
<li class="chapter" data-level="" data-path="the-gauss-markov-theorem.html"><a href="the-gauss-markov-theorem.html#simulation-study-blue-estimator"><i class="fa fa-check"></i>Simulation Study: BLUE Estimator</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="using-the-t-statistic-in-regression-when-the-sample-size-is-small.html"><a href="using-the-t-statistic-in-regression-when-the-sample-size-is-small.html"><i class="fa fa-check"></i><b>2.6</b> Using the t-Statistic in Regression When the Sample Size Is Small</a></li>
<li class="chapter" data-level="2.7" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>2.7</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Using <tt>R</tt> for Introduction to Econometrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div class = rmdreview>
This book is in <b>Open Review</b>. We want your feedback to make the book better for you and other students. You may annotate some text by <span style="background-color: #3297FD; color: white">selecting it with the cursor</span> and then click the <i class="h-icon-annotate"></i> on the pop-up menu. You can also see the annotations of others: click the <i class="h-icon-chevron-left"></i> in the upper right hand corner of the page <i class="fa fa-arrow-circle-right  fa-rotate-315" aria-hidden="true"></i>
</div>
<div id="testing-two-sided-hypotheses-concerning-the-slope-coefficient" class="section level2">
<h2><span class="header-section-number">2.1</span> Testing Two-Sided Hypotheses Concerning the Slope Coefficient</h2>
<p>Using the fact that <span class="math inline">\(\hat{\beta}_1\)</span> is approximately normally distributed in large samples (see <a href="#tsdotoe">Key Concept 4.4</a>), testing hypotheses about the true value <span class="math inline">\(\beta_1\)</span> can be done as in Chapter <a href="#potsm"><strong>??</strong></a>.</p>
<div class="keyconcept">
<h3 class="right">
Key Concept 5.1
</h3>
<h3 class="left">
General Form of the <span class="math inline">\(t\)</span>-Statistic
</h3>
<p>Remember from Chapter <a href="#arosur"><strong>??</strong></a> that a general <span class="math inline">\(t\)</span>-statistic has the form <span class="math display">\[ t = \frac{\text{estimated value} - \text{hypothesized value}}{\text{standard error of the estimator}}.\]</span></p>
</div>
<div class="keyconcept">
<h3 class="right">
Key Concept 5.2
</h3>
<h3 class="left">
Testing Hypotheses regarding <span class="math inline">\(\beta_1\)</span>
</h3>
<p>For testing the hypothesis <span class="math inline">\(H_0: \beta_1 = \beta_{1,0}\)</span>, we need to perform the following steps:</p>
<ol style="list-style-type: decimal">
<li>Compute the standard error of <span class="math inline">\(\hat{\beta}_1\)</span>, <span class="math inline">\(SE(\hat{\beta}_1)\)</span></li>
</ol>
<p><span class="math display">\[ SE(\hat{\beta}_1) = \sqrt{ \hat{\sigma}^2_{\hat{\beta}_1} } \ \ , \ \ 
  \hat{\sigma}^2_{\hat{\beta}_1} = \frac{1}{n} \times \frac{\frac{1}{n-2} \sum_{i=1}^n (X_i - \overline{X})^2 \hat{u_i}^2 }{ \left[ \frac{1}{n} \sum_{i=1}^n (X_i - \overline{X})^2 \right]^2}.
\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Compute the <span class="math inline">\(t\)</span>-statistic</li>
</ol>
<p><span class="math display">\[ t = \frac{\hat{\beta}_1 - \beta_{1,0}}{ SE(\hat{\beta}_1) }. \]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Given a two sided alternative (<span class="math inline">\(H_1:\beta_1 \neq \beta_{1,0}\)</span>) we reject at the <span class="math inline">\(5\%\)</span> level if <span class="math inline">\(|t^{act}| &gt; 1.96\)</span> or, equivalently, if the <span class="math inline">\(p\)</span>-value is less than <span class="math inline">\(0.05\)</span>.<br><br />
Recall the definition of the <span class="math inline">\(p\)</span>-value:</li>
</ol>
<span class="math display">\[\begin{align*}
    p \text{-value} =&amp; \, \text{Pr}_{H_0} \left[ \left| \frac{ \hat{\beta}_1 - \beta_{1,0} }{ SE(\hat{\beta}_1) } \right| &gt; \left|        \frac{ \hat{\beta}_1^{act} - \beta_{1,0} }{ SE(\hat{\beta}_1) } \right| \right] \\
    =&amp; \, \text{Pr}_{H_0} (|t| &gt; |t^{act}|) \\
    \approx&amp; \, 2 \cdot \Phi(-|t^{act}|)
  \end{align*}\]</span>
<p>       The last transformation is due to the normal approximation for large samples.</p>
</div>
<p>Consider again the OLS regression stored in <tt>linear_model</tt> from Chapter <a href="#lrwor"><strong>??</strong></a> that gave us the regression line</p>
<p><span class="math display">\[ \widehat{TestScore} \ = \underset{(9.47)}{698.9} - \underset{(0.49)}{2.28} \times STR \ , \ R^2=0.051 \ , \ SER=18.6. \]</span></p>
<p>For testing a hypothesis concerning the slope parameter (the coefficient on <span class="math inline">\(STR\)</span>), we need <span class="math inline">\(SE(\hat{\beta}_1)\)</span>, the standard error of the respective point estimator. As is common in the literature, standard errors are presented in parentheses below the point estimates.</p>
<p>Key Concept 5.1 reveals that it is rather cumbersome to compute the standard error and thereby the <span class="math inline">\(t\)</span>-statistic by hand. The question you should be asking yourself right now is: can we obtain these values with minimum effort using <tt>R</tt>? Yes, we can. Let us first use <tt>summary()</tt> to get a summary on the estimated coefficients in <tt>linear_model</tt>.</p>
<p><strong>Note</strong>: Throughout the book, robust standard errors are reported. We consider it instructive keep things simple at the beginning and thus start out with simple examples that do not allow for robust inference. Standard errors that are robust to heteroskedasticity are introduced in Chapter <a href="hah.html#hah">2.4</a> where we also demonstrate how they can be computed using <tt>R</tt>. A discussion of heteroskedasticity-autocorrelation robust standard errors takes place in Chapter <a href="#eodce"><strong>??</strong></a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># print the summary of the coefficients to the console</span></code></pre></div>
<pre><code>##               Estimate Std. Error   t value      Pr(&gt;|t|)
## (Intercept) 698.932949  9.4674911 73.824516 6.569846e-242
## STR          -2.279808  0.4798255 -4.751327  2.783308e-06</code></pre>
<p>The second column of the coefficients’ summary, reports <span class="math inline">\(SE(\hat\beta_0)\)</span> and <span class="math inline">\(SE(\hat\beta_1)\)</span>. Also, in the third column <tt>t value</tt>, we find <span class="math inline">\(t\)</span>-statistics <span class="math inline">\(t^{act}\)</span> suitable for tests of the separate hypotheses <span class="math inline">\(H_0: \beta_0=0\)</span> and <span class="math inline">\(H_0: \beta_1=0\)</span>. Furthermore, the output provides us with <span class="math inline">\(p\)</span>-values corresponding to both tests against the two-sided alternatives <span class="math inline">\(H_1:\beta_0\neq0\)</span> respectively <span class="math inline">\(H_1:\beta_1\neq0\)</span> in the fourth column of the table.</p>
<p>Let us have a closer look at the test of</p>
<p><span class="math display">\[H_0: \beta_1=0 \ \ \ vs. \ \ \ H_1: \beta_1 \neq 0.\]</span></p>
<p>We have <span class="math display">\[ t^{act} = \frac{-2.279808 - 0}{0.4798255} \approx - 4.75. \]</span></p>
<p>What does this tell us about the significance of the estimated coefficient? We reject the null hypothesis at the <span class="math inline">\(5\%\)</span> level of significance since <span class="math inline">\(|t^{act}| &gt; 1.96\)</span>. That is, the observed test statistic falls into the rejection region as <span class="math inline">\(p\text{-value} = 2.78\cdot 10^{-6} &lt; 0.05\)</span>. We conclude that the coefficient is significantly different from zero. In other words, we reject the hypothesis that the class size <em>has no influence</em> on the students test scores at the <span class="math inline">\(5\%\)</span> level.</p>
<p>Note that although the difference is negligible in the present case as we will see later, <tt>summary()</tt> does not perform the normal approximation but calculates <span class="math inline">\(p\)</span>-values using the <span class="math inline">\(t\)</span>-distribution instead. Generally, the degrees of freedom of the assumed <span class="math inline">\(t\)</span>-distribution are determined in the following manner:</p>
<p><span class="math display">\[ \text{DF} = n - k - 1 \]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of observations used to estimate the model and <span class="math inline">\(k\)</span> is the number of regressors, excluding the intercept. In our case, we have <span class="math inline">\(n=420\)</span> observations and the only regressor is <span class="math inline">\(STR\)</span> so <span class="math inline">\(k=1\)</span>. The simplest way to determine the model degrees of freedom is</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># determine residual degrees of freedom</span>
linear_model<span class="op">$</span>df.residual</code></pre></div>
<pre><code>## [1] 418</code></pre>
<p>Hence, for the assumed sampling distribution of <span class="math inline">\(\hat\beta_1\)</span> we have</p>
<p><span class="math display">\[\hat\beta_1 \sim t_{418}\]</span> such that the <span class="math inline">\(p\)</span>-value for a two-sided significance test can be obtained by executing the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">pt</span>(<span class="op">-</span><span class="fl">4.751327</span>, <span class="dt">df =</span> <span class="dv">418</span>)</code></pre></div>
<pre><code>## [1] 2.78331e-06</code></pre>
<p>The result is very close to the value provided by <tt>summary()</tt>. However since <span class="math inline">\(n\)</span> is sufficiently large one could just as well use the standard normal density to compute the <span class="math inline">\(p\)</span>-value:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span><span class="fl">4.751327</span>)</code></pre></div>
<pre><code>## [1] 2.02086e-06</code></pre>
<p>The difference is indeed negligible. These findings tell us that, if <span class="math inline">\(H_0: \beta_1 = 0\)</span> is true and we were to repeat the whole process of gathering observations and estimating the model, observing a <span class="math inline">\(\hat\beta_1 \geq |-2.28|\)</span> is very unlikely!</p>
<p>Using <tt>R</tt> we may visualize how such a statement is made when using the normal approximation. This reflects the principles depicted in figure 5.1 in the book. Do not let the following code chunk deter you: the code is somewhat longer than the usual examples and looks unappealing but there is <strong>a lot</strong> of repetition since color shadings and annotations are added on both tails of the normal distribution. We recommend to execute the code step by step in order to see how the graph is augmented with the annotations.</p>
<div class="unfolded">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Plot the standard normal on the support [-6,6]</span>
t &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">6</span>, <span class="dv">6</span>, <span class="fl">0.01</span>)

<span class="kw">plot</span>(<span class="dt">x =</span> t, 
     <span class="dt">y =</span> <span class="kw">dnorm</span>(t, <span class="dv">0</span>, <span class="dv">1</span>), 
     <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, 
     <span class="dt">col =</span> <span class="st">&quot;steelblue&quot;</span>, 
     <span class="dt">lwd =</span> <span class="dv">2</span>, 
     <span class="dt">yaxs =</span> <span class="st">&quot;i&quot;</span>, 
     <span class="dt">axes =</span> F, 
     <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>, 
     <span class="dt">main =</span> <span class="kw">expression</span>(<span class="st">&quot;Calculating the p-value of a Two-sided Test when&quot;</span> <span class="op">~</span><span class="st"> </span>t<span class="op">^</span>act <span class="op">~</span><span class="st"> &quot;=-0.47&quot;</span>), 
     <span class="dt">cex.lab =</span> <span class="fl">0.7</span>,
     <span class="dt">cex.main =</span> <span class="dv">1</span>)

tact &lt;-<span class="st"> </span><span class="op">-</span><span class="fl">4.75</span>

<span class="kw">axis</span>(<span class="dv">1</span>, <span class="dt">at =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="op">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>, <span class="op">-</span>tact, tact), <span class="dt">cex.axis =</span> <span class="fl">0.7</span>)

<span class="co"># Shade the critical regions using polygon():</span>

<span class="co"># critical region in left tail</span>
<span class="kw">polygon</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">6</span>, <span class="kw">seq</span>(<span class="op">-</span><span class="dv">6</span>, <span class="op">-</span><span class="fl">1.96</span>, <span class="fl">0.01</span>), <span class="op">-</span><span class="fl">1.96</span>),
        <span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">dnorm</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">6</span>, <span class="op">-</span><span class="fl">1.96</span>, <span class="fl">0.01</span>)), <span class="dv">0</span>), 
        <span class="dt">col =</span> <span class="st">&#39;orange&#39;</span>)

<span class="co"># critical region in right tail</span>

<span class="kw">polygon</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="fl">1.96</span>, <span class="kw">seq</span>(<span class="fl">1.96</span>, <span class="dv">6</span>, <span class="fl">0.01</span>), <span class="dv">6</span>),
        <span class="dt">y =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="kw">dnorm</span>(<span class="kw">seq</span>(<span class="fl">1.96</span>, <span class="dv">6</span>, <span class="fl">0.01</span>)), <span class="dv">0</span>), 
        <span class="dt">col =</span> <span class="st">&#39;orange&#39;</span>)

<span class="co"># Add arrows and texts indicating critical regions and the p-value</span>
<span class="kw">arrows</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">0.2</span>, <span class="op">-</span><span class="fl">2.5</span>, <span class="fl">0.02</span>, <span class="dt">length =</span> <span class="fl">0.1</span>)
<span class="kw">arrows</span>(<span class="fl">3.5</span>, <span class="fl">0.2</span>, <span class="fl">2.5</span>, <span class="fl">0.02</span>, <span class="dt">length =</span> <span class="fl">0.1</span>)

<span class="kw">arrows</span>(<span class="op">-</span><span class="dv">5</span>, <span class="fl">0.16</span>, <span class="op">-</span><span class="fl">4.75</span>, <span class="dv">0</span>, <span class="dt">length =</span> <span class="fl">0.1</span>)
<span class="kw">arrows</span>(<span class="dv">5</span>, <span class="fl">0.16</span>, <span class="fl">4.75</span>, <span class="dv">0</span>, <span class="dt">length =</span> <span class="fl">0.1</span>)

<span class="kw">text</span>(<span class="op">-</span><span class="fl">3.5</span>, <span class="fl">0.22</span>, 
     <span class="dt">labels =</span> <span class="kw">expression</span>(<span class="st">&quot;0.025&quot;</span><span class="op">~</span><span class="st">&quot;=&quot;</span><span class="op">~</span><span class="kw">over</span>(alpha, <span class="dv">2</span>)),
     <span class="dt">cex =</span> <span class="fl">0.7</span>)
<span class="kw">text</span>(<span class="fl">3.5</span>, <span class="fl">0.22</span>, 
     <span class="dt">labels =</span> <span class="kw">expression</span>(<span class="st">&quot;0.025&quot;</span><span class="op">~</span><span class="st">&quot;=&quot;</span><span class="op">~</span><span class="kw">over</span>(alpha, <span class="dv">2</span>)),
     <span class="dt">cex =</span> <span class="fl">0.7</span>)

<span class="kw">text</span>(<span class="op">-</span><span class="dv">5</span>, <span class="fl">0.18</span>, 
     <span class="dt">labels =</span> <span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;-|&quot;</span>,t[act],<span class="st">&quot;|&quot;</span>)), 
     <span class="dt">cex =</span> <span class="fl">0.7</span>)
<span class="kw">text</span>(<span class="dv">5</span>, <span class="fl">0.18</span>, 
     <span class="dt">labels =</span> <span class="kw">expression</span>(<span class="kw">paste</span>(<span class="st">&quot;|&quot;</span>,t[act],<span class="st">&quot;|&quot;</span>)), 
     <span class="dt">cex =</span> <span class="fl">0.7</span>)

<span class="co"># Add ticks indicating critical values at the 0.05-level, t^act and -t^act </span>
<span class="kw">rug</span>(<span class="kw">c</span>(<span class="op">-</span><span class="fl">1.96</span>, <span class="fl">1.96</span>), <span class="dt">ticksize  =</span> <span class="fl">0.145</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkred&quot;</span>)
<span class="kw">rug</span>(<span class="kw">c</span>(<span class="op">-</span>tact, tact), <span class="dt">ticksize  =</span> <span class="op">-</span><span class="fl">0.0451</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;darkgreen&quot;</span>)</code></pre></div>
<p><img src="URFITE_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<p>The <span class="math inline">\(p\)</span>-Value is the area under the curve to left of <span class="math inline">\(-4.75\)</span> plus the area under the curve to the right of <span class="math inline">\(4.75\)</span>. As we already know from the calculations above, this value is very small.</p>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="htaciitslrm.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cifrc.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 1
},
"edit": null,
"download": ["URFITE.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
